### ISSUE TITLE
Reporting error at start up as required

### ISSUE THREAD

**Issue by ylsxfk** [bisq-network/bisq#1252]
Hi,
I've just downloaded, installed and launched v0.6.4 and just before typing password, I was asked to send this message along with [bisq.log](https://github.com/bisq-network/exchange/files/1653115/bisq.log) because of a java.lang.NullPointerException (see log line 16658).
Hope that helps.

**Comment by blabno** [comment]
Seems that relevant part of the log is this:
```
Jan-22 19:09:49.783 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Uncaught Exception from thread JavaFX Application Thread
Jan-22 19:09:49.783 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableMessage= null
Jan-22 19:09:49.784 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableClass= class java.lang.NullPointerException
Jan-22 19:09:49.786 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Stack trace:
java.lang.NullPointerException
        at io.bisq.core.provider.price.PriceFeedService.lambda$request$3(PriceFeedService.java:138)
        at io.bisq.core.provider.price.PriceFeedService$1.lambda$onFailure$2(PriceFeedService.java:320)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by nuschpl** [comment]
The same for me. Relvant is before "SOCKS: Connection refused" on TOR hidden service with getAllMarketPrices provider.
@ManfredKarrer what you meant by:
`        //noinspection unchecked` in **core/src/main/java/io/bisq/core/provider/price/PriceProvider.java** ?

Maybe we have race condition in time slot before TOR connection is established and http connection itself either on client or server side ?
Jan-22 09:57:34.568 [PriceRequest-HttpClientProvider{
     httpClient=HttpClient{socks5ProxyProvider=io.bisq.network.Socks5ProxyProvider@532f34c9, baseUrl='http://rb2l2qale2pqzjyo.onion/', ignoreSocks5Proxy=false}
}] ERROR i.b.c.p.p.PriceFeedService: Could not load marketPrices. Error: java.io.IOException: Error at requestWithGETProxy with URL: http://rb2l2qale2pqzjyo.onion/getAllMarketPrices. Throwable=SOCKS: Connection refused
Jan-22 09:57:34.573 [JavaFX Application Thread] WARN  i.b.c.p.p.PriceFeedService: request from priceProvider failed: errorMessage=Could not load marketPrices
Jan-22 09:57:34.574 [JavaFX Application Thread] INFO  i.b.c.p.ProvidersRepository: Use new provider baseUrl: http://5bmpx76qllutpcyp.onion/
Jan-22 09:57:34.576 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Uncaught Exception from thread JavaFX Application Thread
Jan-22 09:57:34.580 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableMessage= null
Jan-22 09:57:34.580 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableClass= class java.lang.NullPointerException
Jan-22 09:57:34.604 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Stack trace:
java.lang.NullPointerException
        at io.bisq.core.provider.price.PriceFeedService.lambda$request$3(PriceFeedService.java:138)
        at io.bisq.core.provider.price.PriceFeedService$1.lambda$onFailure$2(PriceFeedService.java:320)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by pandysp** [comment]
I have the same error. Here is my log:

Jan-25 17:04:42.095 [PriceRequest-HttpClientProvider{
     httpClient=HttpClient{socks5ProxyProvider=io.bisq.network.Socks5ProxyProvider@350cdf2e, baseUrl='http://rb2l2qale2pqzjyo.onion/', ignoreSocks5Proxy=false}
}] ERROR i.b.c.p.p.PriceFeedService: Could not load marketPrices. Error: java.io.IOException: Error at requestWithGETProxy with URL: http://rb2l2qale2pqzjyo.onion/getAllMarketPrices. Throwable=SOCKS: Connection refused 
Jan-25 17:04:42.096 [JavaFX Application Thread] WARN  i.b.c.p.p.PriceFeedService: request from priceProvider failed: errorMessage=Could not load marketPrices 
Jan-25 17:04:42.096 [JavaFX Application Thread] INFO  i.b.c.p.ProvidersRepository: Use new provider baseUrl: http://ceaanhbvluug4we6.onion/ 
Jan-25 17:04:42.097 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Uncaught Exception from thread JavaFX Application Thread 
Jan-25 17:04:42.098 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableMessage= null 
Jan-25 17:04:42.098 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableClass= class java.lang.NullPointerException 
Jan-25 17:04:42.100 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Stack trace:
java.lang.NullPointerException
	at io.bisq.core.provider.price.PriceFeedService.lambda$request$3(PriceFeedService.java:138)
	at io.bisq.core.provider.price.PriceFeedService$1.lambda$onFailure$2(PriceFeedService.java:320)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by ManfredKarrer** [comment]
Nullpointer is fixed now (faultHandler was null if error got caused by very first request).
@ nuschpl @gunjx : The Tor connection issues are caused because the Tor network is under heavy load/attack since 2 months. I just added better support for handling errors and reconnect to other nodes. Will be released soon.

**Comment by cbeams** [comment]
> Nullpointer is fixed now (faultHandler was null if error got caused by very first request).

8075f9eef99456b50baea24ff9f8543675da03f9 is the commit that fixed this.
