### ISSUE TITLE
NullPointerException on PriceFeedService SOCKS Connection refused

### ISSUE THREAD

**Issue by rodasmith** [bisq-network/bisq#1293]
After updating to v0.6.4, I got this error on launch. Bisq application seems fine despite the error, price shown seems current.
```
Jan-28 19:46:44.848 [PriceRequest-HttpClientProvider{
     httpClient=HttpClient{socks5ProxyProvider=io.bisq.network.Socks5ProxyProvider@477635ba, baseUrl='http://rb2l2qale2pqzjyo.onion/', ignoreSocks5Proxy=false}
}] ERROR i.b.c.p.p.PriceFeedService: Could not load marketPrices. Error: java.io.IOException: Error at requestWithGETProxy with URL: http://rb2l2qale2pqzjyo.onion/getAllMarketPrices. Throwable=SOCKS: Connection refused 
Jan-28 19:46:44.848 [JavaFX Application Thread] WARN  i.b.c.p.p.PriceFeedService: request from priceProvider failed: errorMessage=Could not load marketPrices 
Jan-28 19:46:44.849 [JavaFX Application Thread] INFO  i.b.c.p.ProvidersRepository: Use new provider baseUrl: http://ceaanhbvluug4we6.onion/ 
Jan-28 19:46:44.849 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Uncaught Exception from thread JavaFX Application Thread 
Jan-28 19:46:44.849 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableMessage= null 
Jan-28 19:46:44.850 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableClass= class java.lang.NullPointerException 
Jan-28 19:46:44.851 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Stack trace:
java.lang.NullPointerException
	at io.bisq.core.provider.price.PriceFeedService.lambda$request$3(PriceFeedService.java:138)
	at io.bisq.core.provider.price.PriceFeedService$1.lambda$onFailure$2(PriceFeedService.java:320)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by ManfredKarrer** [comment]
Fixed in commit 8075f9eef99456b50baea24ff9f8543675da03f9
