### ISSUE TITLE
Error: script resulted in a non-true stack

### ISSUE THREAD

**Issue by yashbhutwala** [bisq-network/bisq#1573]
A trade recently failed due to transaction unable to broadcast.  Since then, I keep getting this error message in addition to it showing some of my funds are locked.

<img width="1211" alt="screen shot 2018-06-10 at 8 55 24 pm" src="https://user-images.githubusercontent.com/5788514/41208386-e0b48110-6cf0-11e8-861a-d5c55ba23021.png">

Jun-10 20:56:11.333 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.RuntimeException: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@5459edcd, [B@598b8672, [B@553ee4d7]
	at bisq.core.arbitration.DisputeManager.onDisputeResultMessage(DisputeManager.java:730)
	at bisq.core.arbitration.DisputeManager.dispatchMessage(DisputeManager.java:251)
	at bisq.core.arbitration.DisputeManager.lambda$applyMessages$8(DisputeManager.java:236)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404)
	at bisq.core.arbitration.DisputeManager.applyMessages(DisputeManager.java:232)
	at bisq.core.arbitration.DisputeManager.tryApplyMessages(DisputeManager.java:214)
	at bisq.core.arbitration.DisputeManager.lambda$onAllServicesInitialized$4(DisputeManager.java:179)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.IntegerPropertyBase.fireValueChangedEvent(IntegerPropertyBase.java:106)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:147)
	at bisq.core.btc.wallet.WalletsSetup$1.lambda$onSetupCompleted$0(WalletsSetup.java:211)
	at org.bitcoinj.core.PeerGroup$11.run(PeerGroup.java:1709)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by ghost** [comment]
Did you verify the implied addresses (departure address, deposit address) in a BTC explorer ?
What does it tell ?

**Comment by ManfredKarrer** [comment]
Can you post the arbitrator address, so the arbitrator can try another payout with the other user or do a manual payout?
Seems the internal wallet database got corrupted and the assigned signing key is wrong.

**Comment by yashbhutwala** [comment]
Issue is similar to [1508](https://github.com/bisq-network/bisq-desktop/issues/1508).  Fortunately, my funds were recovered.  I followed directions [here](https://bisq.community/t/switching-to-a-new-data-directory/1697) to start with a new data directory.  Thanks.
