### ISSUE TITLE
TomP2P: Null pointer exception in one of the relay handlers

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#161]
There is a bug in the TomP2P library causing error messages in the server logs. That happens onyl when using relay mode which is the case when I connect from ym machine to the serverside master seed node.
It seems that this is not the primary problem with the serverside master seed node.
We need to check also if that is already resolved in the latest version.

See: http://lists.tomp2p.net/pipermail/users/2014-August/000373.html

```
Error messages on the server:
05:44:04.799 [NETTY-TOMP2P - worker-client/server - -1-2] ERROR net.tomp2p.rpc.DispatchHandler - Exception in custom handler java.lang.NullPointerException: null
    at net.tomp2p.message.Encoder.loop(Encoder.java:219) ~[tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.message.Encoder.write(Encoder.java:54) ~[tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.relay.RelayUtils.encodeMessage(RelayUtils.java:30) ~[tomp2p-nat-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.relay.RelayForwarderRPC.handleRelay(RelayForwarderRPC.java:148) ~[tomp2p-nat-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.relay.RelayForwarderRPC.handleResponse(RelayForwarderRPC.java:139) ~[tomp2p-nat-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.rpc.DispatchHandler.forwardMessage(DispatchHandler.java:151) ~[tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.connection.Dispatcher.channelRead0(Dispatcher.java:153) [tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.connection.Dispatcher.channelRead0(Dispatcher.java:54) [tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at net.tomp2p.message.TomP2PCumulationTCP.decoding(TomP2PCumulationTCP.java:69) [tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.message.TomP2PCumulationTCP.channelRead(TomP2PCumulationTCP.java:47) [tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at net.tomp2p.connection.IdleStateHandlerTomP2P.channelRead(IdleStateHandlerTomP2P.java:112) [tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-common-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.21.Final.jar:4.0.21.Final]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]
```

**Comment by ManfredKarrer** [comment]
With latest master there are still problems: 
http://lists.tomp2p.net/pipermail/users/2014-October/000396.html

**Comment by ManfredKarrer** [comment]
That si fixed in the latest master.
