### ISSUE TITLE
Testing: Stack trace from trying to create order

### ISSUE THREAD

**Issue by sqrrm** [bisq-network/bisq#1632]
Trying to create sell btc with halcash, get stack trace when trying to enter the amount in btc. Not on first try, but after values resetting a few times

```Aug-16 23:02:48.782 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at org.bitcoinj.utils.ExchangeRate.<init>(ExchangeRate.java:39)
	at org.bitcoinj.utils.ExchangeRate.<init>(ExchangeRate.java:47)
	at bisq.core.monetary.Price.getAmountByVolume(Price.java:71)
	at bisq.core.offer.OfferUtil.getAdjustedAmount(OfferUtil.java:170)
	at bisq.core.offer.OfferUtil.getAdjustedAmountForHalCash(OfferUtil.java:164)
	at bisq.desktop.main.offer.MutableOfferViewModel.setMinAmountToModel(MutableOfferViewModel.java:1004)
	at bisq.desktop.main.offer.MutableOfferViewModel.lambda$createListeners$7(MutableOfferViewModel.java:312)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:57)
	at com.sun.javafx.binding.BidirectionalBinding$TypedGenericBidirectionalBinding.changed(BidirectionalBinding.java:599)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1389)
	at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1393)
	at javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(TextInputControl.java:1332)
	at javafx.scene.control.TextInputControl$TextProperty.access$1600(TextInputControl.java:1300)
	at javafx.scene.control.TextInputControl.lambda$new$62(TextInputControl.java:139)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.control.TextField$TextFieldContent.insert(TextField.java:87)
	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:1204)
	at javafx.scene.control.TextInputControl.updateContent(TextInputControl.java:556)
	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:548)
	at com.sun.javafx.scene.control.skin.TextFieldSkin.replaceText(TextFieldSkin.java:576)
	at com.sun.javafx.scene.control.behavior.TextFieldBehavior.replaceText(TextFieldBehavior.java:202)
	at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.defaultKeyTyped(TextInputControlBehavior.java:238)
	at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.callAction(TextInputControlBehavior.java:139)
	at com.sun.javafx.scene.control.behavior.BehaviorBase.callActionForEvent(BehaviorBase.java:218)
	at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.callActionForEvent(TextInputControlBehavior.java:127)
	at com.sun.javafx.scene.control.behavior.BehaviorBase.lambda$new$157(BehaviorBase.java:135)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:197)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:147)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$299(GlassViewEventHandler.java:228)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:227)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
	at com.sun.glass.ui.View.notifyKey(View.java:966)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by sqrrm** [comment]
The popup telling me about the rounding of values is really annoying. I could of course tell it to not reappear but if I don't it's almost impossible to create an order. Perhaps we could have a little note around the rounded number or something, faded out values or something that's not making it less usable.

**Comment by sqrrm** [comment]
Again after setting euro value and clicking btc amount
```java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at org.bitcoinj.utils.ExchangeRate.<init>(ExchangeRate.java:39)
	at org.bitcoinj.utils.ExchangeRate.<init>(ExchangeRate.java:47)
	at bisq.core.monetary.Price.getAmountByVolume(Price.java:71)
	at bisq.core.offer.OfferUtil.getAdjustedAmount(OfferUtil.java:170)
	at bisq.core.offer.OfferUtil.getAdjustedAmountForHalCash(OfferUtil.java:164)
	at bisq.desktop.main.offer.MutableOfferViewModel.setMinAmountToModel(MutableOfferViewModel.java:1004)
	at bisq.desktop.main.offer.MutableOfferViewModel.onFocusOutMinAmountTextField(MutableOfferViewModel.java:701)
	at bisq.desktop.main.offer.MutableOfferViewModel.lambda$onFocusOutAmountTextField$24(MutableOfferViewModel.java:690)
	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ripcurlx** [comment]
@sqrrm I'll de-annoy the popup and only show it on screen activation and I'll try to re-produce the other exception.

**Comment by ManfredKarrer** [comment]
Should be fixed with https://github.com/bisq-network/bisq-core/pull/158/commits/9bbe5a6ef58d64524d4f5d3edd7d17170384c440  at https://github.com/bisq-network/bisq-core/pull/158

**Comment by sqrrm** [comment]
@ripcurlx this is more usable. I feel it would be enough to just have the little eye hover text without the popup but I'm not an expert and I'm doing a lot of trades testing, not just one per day.

@ManfredKarrer That could well be it, haven't seen it reappear while testing today.
