### ISSUE TITLE
Arch AUR package install error

### ISSUE THREAD

**Issue by GarlandKey** [bisq-network/bisq#1677]
```
user@computer:~/.cache/pacaur |⇒ pacaur -S bisq-git
:: Package bisq-git not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (1) bisq-git-latest  

:: Proceed with installation? [Y/n] y
:: Retrieving package(s)...
Cloning into 'bisq-git'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 4 (delta 0)
Unpacking objects: 100% (5/5), done.
:: View bisq-git PKGBUILD? [Y/n] n
sudo: a password is required
[sudo] password for toorboi: 
:: Checking bisq-git integrity...
==> Making package: bisq-git 0.8.0.r41.g3d6260559-1 (Wed 12 Sep 2018 02:24:17 AM CDT)
==> Retrieving sources...
  -> Cloning bisq-git git repo...
Cloning into bare repository '~/.cache/pacaur/bisq-git/bisq-git'...
remote: Counting objects: 158063, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 158063 (delta 4), reused 20 (delta 0), pack-reused 158025
Receiving objects: 100% (158063/158063), 402.35 MiB | 3.17 MiB/s, done.
Resolving deltas: 100% (87250/87250), done.
  -> Found bisq.desktop
==> Validating source files with sha256sums...
    bisq-git ... Skipped
    bisq.desktop ... Passed
:: Preparing bisq-git...
==> Making package: bisq-git 0.8.0.r41.g3d6260559-1 (Wed 12 Sep 2018 02:26:27 AM CDT)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Updating bisq-git git repo...
Fetching origin
  -> Found bisq.desktop
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Creating working copy of bisq-git git repo...
Cloning into 'bisq-git'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Updated version: bisq-git 0.8.0.r45.g22dcd17ef-1
==> Sources are ready.
:: Building bisq-git package(s)...
==> Making package: bisq-git 0.8.0.r45.g22dcd17ef-1 (Wed 12 Sep 2018 02:26:29 AM CDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
  -> Building bisq...
> Task :assemble UP-TO-DATE
> Task :check UP-TO-DATE
> Task :build UP-TO-DATE
> Task :common:extractIncludeProto
> Task :common:extractProto
> Task :common:generateProto

> Task :common:compileJava FAILED
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:39: error: package javafx.scene.input does not exist
import javafx.scene.input.Clipboard;
                         ^
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:40: error: package javafx.scene.input does not exist
import javafx.scene.input.ClipboardContent;
                         ^
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:41: error: package javafx.scene.input does not exist
import javafx.scene.input.KeyCode;
                         ^
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:42: error: package javafx.scene.input does not exist
import javafx.scene.input.KeyCodeCombination;
                         ^
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:43: error: package javafx.scene.input does not exist
import javafx.scene.input.KeyCombination;
                         ^
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:44: error: package javafx.scene.input does not exist
import javafx.scene.input.KeyEvent;
                         ^
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:423: error: cannot find symbol
    public static boolean isAltOrCtrlPressed(KeyCode keyCode, KeyEvent keyEvent) {
                                             ^
  symbol:   class KeyCode
  location: class Utilities
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:423: error: cannot find symbol
    public static boolean isAltOrCtrlPressed(KeyCode keyCode, KeyEvent keyEvent) {
                                                              ^
  symbol:   class KeyEvent
  location: class Utilities
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:427: error: cannot find symbol
    public static boolean isCtrlPressed(KeyCode keyCode, KeyEvent keyEvent) {
                                        ^
  symbol:   class KeyCode
  location: class Utilities
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:427: error: cannot find symbol
    public static boolean isCtrlPressed(KeyCode keyCode, KeyEvent keyEvent) {
                                                         ^
  symbol:   class KeyEvent
  location: class Utilities
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:432: error: cannot find symbol
    public static boolean isAltPressed(KeyCode keyCode, KeyEvent keyEvent) {
                                       ^
  symbol:   class KeyCode
  location: class Utilities
~/.cache/pacaur/bisq-git/src/bisq-git/common/src/main/java/bisq/common/util/Utilities.java:432: error: cannot find symbol
    public static boolean isAltPressed(KeyCode keyCode, KeyEvent keyEvent) {
                                                        ^
  symbol:   class KeyEvent
  location: class Utilities
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:compileJava'.
> java.lang.ExceptionInInitializerError

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
4 actionable tasks: 4 executed
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build bisq-git package(s)
```

**Comment by ripcurlx** [comment]
Which Java version are you running? I do work on a [Java 10 port](https://github.com/bisq-network/bisq/pull/1660), but atm Bisq only supports Java 8.

**Comment by GarlandKey** [comment]
I guess that's it:

```
user@computer:~/.cache/pacaur |⇒  java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)
```

**Comment by GarlandKey** [comment]
**[FIXED]**

I installed jdk8 and it worked.

**Comment by ripcurlx** [comment]
Perfect 😄 - closing as complete.

**Comment by KodeToad** [comment]
I updated mine on Manjaro with just java 8 but there is a dependency on java 10 which it keeps bringing back.
Even when I edit the build file it fails the build

**Comment by KodeToad** [comment]
`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: bisq/desktop/app/BisqAppMain has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
`

**Comment by KodeToad** [comment]
Fixed like this:
[Manjaro ~]# archlinux-java status
Available Java environments:
  java-10-openjdk
  java-8-openjdk (default)
[Manjaro ~]# archlinux-java set java-10-openjdk
[Manjaro ~]# archlinux-java status
Available Java environments:
  java-10-openjdk (default)
  java-8-openjdk
[Manjaro ~]# java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)
