### ISSUE TITLE
Can't edit order

### ISSUE THREAD

**Issue by R3ktl355** [bisq-network/bisq#1732]
When I try to edit an order I get error: java.lang.Nullpointerexception

![bisqerror](https://user-images.githubusercontent.com/43645603/46199744-f5975080-c34e-11e8-890e-cb647bf53536.PNG)

Logfile attached.

[nullpointerexception.txt](https://github.com/bisq-network/bisq/files/2427572/nullpointerexception.txt)

**Comment by ManfredKarrer** [comment]
@R3ktl355 Did you change your payment account? Seems the app did not find the payment account with which the offer was created.

**Comment by ManfredKarrer** [comment]
@ripcurlx 

Nullpointer happened at the `PaymentAccount.fromProto` call:
```
PaymentAccount tmpPaymentAccount = user.getPaymentAccount(openOffer.getOffer().getMakerPaymentAccountId());
        TradeCurrency selectedTradeCurrency = CurrencyUtil.getTradeCurrency(openOffer.getOffer().getCurrencyCode()).get();

        this.paymentAccount = PaymentAccount.fromProto(tmpPaymentAccount.toProtoMessage(), corePersistenceProtoResolver);

        if (paymentAccount.getSingleTradeCurrency() != null)
            paymentAccount.setSingleTradeCurrency(selectedTradeCurrency);
        else
            paymentAccount.setSelectedTradeCurrency(selectedTradeCurrency);
```

To add a null check would be good but would likely lead to further issues if the paymentAccount is not set. Basically it should not be possible that the paymentAccount is not found as one cannot delete a paymentAccount if there are open offers. Maybe the check there does not cover deactivated offers?

**Comment by clearwater-trust** [comment]
I'm getting this error after moving Bisq to a new machine. I just realized that none of my payment accounts moved over. I have funds reserved in offers and locked in trades. I didn't export any of my accounts- only made a backup of the app data directory. How should I proceed? 

`Dec-02 21:25:46.581 [JavaFX Application Thread] ERROR b.c.s.FileManager: Exception at proto read: Not supported PaymentMethod: PaymentMethod(id=N/A, maxTradePeriod=0, maxTradeLimit=0) file:/home/alpha/.local/share/Bisq/btc_mainnet/db/UserPayload java.lang.RuntimeException: Not supported PaymentMethod: PaymentMethod(id=N/A, maxTradePeriod=0, maxTradeLimit=0)
	at bisq.core.payment.PaymentAccountFactory.getPaymentAccount(PaymentAccountFactory.java:76)
	at bisq.core.payment.PaymentAccount.fromProto(PaymentAccount.java:102)
	at bisq.core.user.UserPayload.lambda$fromProto$13(UserPayload.java:108)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at bisq.core.user.UserPayload.fromProto(UserPayload.java:109)
	at bisq.core.proto.persistable.CorePersistenceProtoResolver.fromProto(CorePersistenceProtoResolver.java:101)
	at bisq.common.storage.FileManager.read(FileManager.java:126)
	at bisq.common.storage.Storage.getPersisted(Storage.java:152)
	at bisq.common.storage.Storage.initAndGetPersistedWithFileName(Storage.java:84)
	at bisq.core.user.User.readPersisted(User.java:87)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at bisq.common.proto.persistable.PersistedDataHost.apply(PersistedDataHost.java:26)
	at bisq.core.app.BisqExecutable.setupPersistedDataHosts(BisqExecutable.java:213)
	at bisq.desktop.app.BisqAppMain.setupPersistedDataHosts(BisqAppMain.java:106)
	at bisq.core.app.BisqExecutable.applyInjector(BisqExecutable.java:204)
	at bisq.desktop.app.BisqAppMain.applyInjector(BisqAppMain.java:98)
	at bisq.core.app.BisqExecutable.setupGuice(BisqExecutable.java:190)
	at bisq.core.app.BisqExecutable.onApplicationLaunched(BisqExecutable.java:178)
	at bisq.desktop.app.BisqAppMain.onApplicationLaunched(BisqAppMain.java:83)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by ghost** [comment]
@clearwater-trust wrote:
> I'm getting this error after moving Bisq to a new machine. I just realized that none of my payment accounts moved over. I have funds reserved in offers and locked in trades. I didn't export any of my accounts- only made a backup of the app data directory. How should I proceed?

What do you call "moving Bisq to a new machine" ?

afaik, if you backup the whole app data directory, and copy it to the new machine, everything should work fine (the payment accounts data are stored in the Bisq data directory).

**Comment by clearwater-trust** [comment]
@HarryMacfinned  - After the .9 update and recopying the bisq backup files my install appears to be working and my payment accounts are back. Thanks for looking at the issue.

**Comment by ripcurlx** [comment]
Closing as complete.
