### ISSUE TITLE
app freeze when clicking on accounts for the first time

### ISSUE THREAD

**Issue by adrelanos** [bisq-network/bisq#1752]
```
java.lang.NullPointerException
        at com.sun.scenario.effect.impl.sw.sse.SSELinearConvolvePeer.filter(SSELinearConvolvePeer.java:83)
        at com.sun.scenario.effect.impl.sw.sse.SSELinearConvolvePeer.filter(SSELinearConvolvePeer.java:44)
        at com.sun.scenario.effect.LinearConvolveCoreEffect.filterImageDatas(LinearConvolveCoreEffect.java:85)
        at com.sun.scenario.effect.LinearConvolveCoreEffect.filterImageDatas(LinearConvolveCoreEffect.java:41)
        at com.sun.scenario.effect.FilterEffect.filter(FilterEffect.java:195)
        at com.sun.scenario.effect.impl.prism.PrEffectHelper.render(PrEffectHelper.java:166)
        at com.sun.javafx.sg.prism.EffectFilter.render(EffectFilter.java:61)
        at com.sun.javafx.sg.prism.NGNode.renderEffect(NGNode.java:2365)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2050)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
        at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
        at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:330)
        at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:134)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ManfredKarrer** [comment]
@adrelanos Can you send me more logs? Here I don't see where it is originated in Bisq. Either you post a longer part or you PM me on the Forum the log... Thanks!

**Comment by ManfredKarrer** [comment]
Which Bisq version and OS do u use?

**Comment by adrelanos** [comment]
Latest. Just downloaded the same day.

Whonix 14 / based on Debian stretch.

**Comment by ManfredKarrer** [comment]
Any special windows manager? from the log it looks like a graphic system error. such happened sometimes with some exotic linux distos/windows managers
