### ISSUE TITLE
0.9.0: Windows system tray icon is low resolution

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#1996]
The new Bisq icon shown in the Windows system tray is low resolution and looks bad.
![image](https://user-images.githubusercontent.com/603793/49204273-2cdea980-f360-11e8-8dd8-763cebc5292d.png)

**Comment by ripcurlx** [comment]
I'll add a high-res icon version and do the same retina check as we do for macOS. Hopefully that solves this problem.

**Comment by devinbileck** [comment]
@ripcurlx Now I am encountering the following
```
Nov-30 00:21:17.300 [JavaFX Application Thread] ERROR bisq.desktop.app.BisqApp: Error during app init java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1400)
	at bisq.desktop.app.SystemTray.init(SystemTray.java:107)
	at bisq.desktop.app.SystemTray.<init>(SystemTray.java:74)
	at bisq.desktop.app.SystemTray.create(SystemTray.java:68)
	at bisq.desktop.app.BisqApp.setupStage(BisqApp.java:231)
	at bisq.desktop.app.BisqApp.startApplication(BisqApp.java:137)
	at bisq.desktop.app.BisqAppMain.startApplication(BisqAppMain.java:126)
	at bisq.core.app.BisqExecutable.onApplicationLaunched(BisqExecutable.java:211)
	at bisq.desktop.app.BisqAppMain.onApplicationLaunched(BisqAppMain.java:94)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
`task_bar_icon_windows@2x.png` needs to be renamed to `system_tray_icon_windows@2x.png`

When I rename it, the icon is still shown low-res in the system tray. Might need to provide a different icon size or update the icon scaling (https://github.com/bisq-network/bisq/blob/master/desktop/src/main/java/bisq/desktop/app/SystemTray.java#L108)

**Comment by devinbileck** [comment]
I find that if I use `trayIcon.setImageAutoSize(true)` instead of `trayIconImage.getScaledInstance`, it does look a little better:
![image](https://user-images.githubusercontent.com/603793/49325438-4bc37400-f4f7-11e8-807a-394e9dd4dade.png)

However, I have only tried this change on my laptop (which uses the hi res image) and have not tried on my desktop (which uses the low res image). And I have also not tried it on Linux.

**Comment by ripcurlx** [comment]
Damn, I thought it will work the same as with macOS. I’ll try it in my Windows VM on Monday morning. Just is a little bit slow to work with.

**Comment by ripcurlx** [comment]
Worst case scenario I’ll roll it back as it was before and we add it in the next update, when we have time to properly test it.

**Comment by devinbileck** [comment]
@ripcurlx can you reopen this so we remember to address it.

**Comment by ripcurlx** [comment]
@devinbileck Do you want to take this issue yourself? I think it might be easier to test on a real Windows machine than within a VM. Let me know if you need any help with the setup.

**Comment by devinbileck** [comment]
@ripcurlx Sure, I will look into this one.
