### ISSUE TITLE
Could not delete AddressEntryList file

### ISSUE THREAD

**Issue by janfiedler** [bisq-network/bisq#2206]
Hi,
I upgraded to new bisq 9 from 7. For this I was forced to delete old version with all data. So now when I try recovery from seed I get this error.

![image](https://user-images.githubusercontent.com/13234075/50716715-2809c580-1083-11e9-9c37-aa9b2590398c.png)

Logs:
```
led-05 00:35:45.076 [NetworkNode-9999] INFO  b.n.p.n.NewTor: Starting tor 
led-05 00:35:45.082 [JavaFX Application Thread] INFO  b.c.a.WalletAppSetup: Initialize WalletAppSetup with BitcoinJ version 0.14.4.11 and LibDohJ version 0.14.4 with hash of BitcoinJ commit cd30ad5b 
led-05 00:35:45.101 [JavaFX Application Thread] INFO  b.c.b.s.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=null 
led-05 00:35:45.125 [JavaFX Application Thread] INFO  o.b.c.Context: Creating bitcoinj 0.14.4.11 context. 
led-05 00:35:45.160 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: walletInitialized=false, p2pNetWorkReady=false 
led-05 00:35:45.223 [ STARTING] INFO  b.c.b.s.WalletConfig: Wallet directory: C:\Users\******\AppData\Roaming\Bisq\btc_mainnet\wallet 
led-05 00:35:45.604 [ STARTING] INFO  o.b.c.AbstractBlockChain: chain head is at height 557058:
 block: 
   hash: 0000000000000000002a3beb73db2d7b2985edad0693f5261b030786ab18bf8a
   version: 536870912 (BIP34, BIP66, BIP65)
   previous block: 0000000000000000000f0a35aee1ce5f5f4df6789a20cc83da0171e1d1513009
   merkle root: b8ac0f61ffa24fdaf4790d4c851d00c1e6831393ca6471c9c61eac0116715c23
   time: 1546642876 (2019-01-04T23:01:16Z)
   difficulty target (nBits): 389159077
   nonce: 2470263210
 
led-05 00:35:45.949 [ STARTING] INFO  b.c.b.s.WalletConfig: We try to connect to 9 btc nodes 
led-05 00:35:45.986 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Saving wallet; last seen block is height -1, date unknown, hash null 
led-05 00:35:45.988 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Starting ... 
led-05 00:35:46.020 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Localhost peer detected, trying to use it instead of P2P discovery 
led-05 00:35:46.043 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [127.0.0.1]:8333     (0 connected, 1 pending, 0 max) 
led-05 00:35:46.051 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Save completed in 64.37 ms 
led-05 00:35:46.110 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: walletInitialized=true, p2pNetWorkReady=false 
led-05 00:35:46.176 [NioClientManager] INFO  o.b.n.NioClientManager: Connected to /127.0.0.1:8333 
led-05 00:35:46.177 [NioClientManager] INFO  o.b.core.Peer: Announcing to /127.0.0.1:8333 as: /bitcoinj:0.14.4.11/Bisq:0.9.1/ 
led-05 00:35:46.201 [NioClientManager] INFO  o.b.core.Peer: [127.0.0.1]:8333: Got version=70015, subVer='/Satoshi:0.17.1/', services=0x1037, time=2019-01-05 00:35:37, blocks=557058 
led-05 00:35:46.203 [NioClientManager] INFO  o.b.c.PeerGroup: [127.0.0.1]:8333: New peer      (1 connected, 0 pending, 1 max) 
led-05 00:35:46.218 [NioClientManager] INFO  o.b.c.PeerGroup: Setting download peer: [127.0.0.1]:8333 
led-05 00:35:49.308 [NetworkNode-9999] INFO  o.b.n.tor.Tor: Starting Tor 
led-05 00:35:55.927 [NetworkNode-9999] INFO  b.n.p.n.NewTor: 
################################################################
Tor started after 10851 ms. Start publishing hidden service.
################################################################ 
led-05 00:35:55.933 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://44mgyoe2b6oqiytt.onion/ 
led-05 00:35:55.996 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a PreliminaryGetDataRequest to peer rm7b56wbrcczpjvl.onion:8000.  
led-05 00:35:56.188 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a PreliminaryGetDataRequest to peer fl3mmribyxgrv63c.onion:8000.  
led-05 00:35:56.705 [NetworkNode-9999] INFO  b.n.p.n.TorNetworkNode: It will take some time for the HS to be reachable (~40 seconds). You will be notified about this 
led-05 00:36:03.673 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=CZK, price=86126.52, timestampSec=1546645024504, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 7.739 sec. 
led-05 00:36:08.749 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: 
#################################################################
Connected to node: fl3mmribyxgrv63c.onion:8000
Received 421 instances
Filter: 1
MailboxStoragePayload: 135
Alert: 1
Arbitrator: 2
OfferPayload: 282
################################################################# 
led-05 00:36:09.846 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Start processing 0 items. 
led-05 00:36:09.850 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: walletInitialized=true, p2pNetWorkReady=true 
led-05 00:36:09.851 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: initDomainServices 
led-05 00:36:09.887 [JavaFX Application Thread] INFO  b.c.a.ArbitratorManager: Available arbitrators: [s6yrrpezc3zp6biy.onion:9999, hvllnddukspprwt6.onion:9999] 
led-05 00:36:10.412 [JavaFX Application Thread] INFO  b.c.p.ProvidersRepository: Selected provider baseUrl=http://5bmpx76qllutpcyp.onion/, providerList=[http://44mgyoe2b6oqiytt.onion/, http://5bmpx76qllutpcyp.onion/, http://ceaanhbvluug4we6.onion/, http://xc3nh4juf2hshy7e.onion/, http://62nvujg5iou3vu3i.onion/] 
led-05 00:36:10.415 [JavaFX Application Thread] INFO  b.c.a.ArbitratorManager: Available arbitrators: [s6yrrpezc3zp6biy.onion:9999, hvllnddukspprwt6.onion:9999] 
led-05 00:36:10.444 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://5bmpx76qllutpcyp.onion/ 14.51 sec. after last request 
led-05 00:36:10.883 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: We have 2 connections open. Our limit is 12 
led-05 00:36:11.618 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerByte=10 
led-05 00:36:12.321 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=CZK, price=86126.52, timestampSec=1546645024504, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 1.876 sec. 
led-05 00:36:16.441 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: 
#################################################################
Connected to node: rm7b56wbrcczpjvl.onion:8000
Received 413 instances
Filter: 1
MailboxStoragePayload: 135
Alert: 1
Arbitrator: 2
OfferPayload: 274
################################################################# 
led-05 00:36:17.057 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Start processing 0 items. 
led-05 00:36:29.468 [Thread-11] INFO  o.b.n.tor.Tor: Hidden Service HiddenServiceSocket[addr=zf6bqwxdbync6ono.onion,port=9999] is ready 
led-05 00:36:29.468 [Thread-11] INFO  b.n.p.n.TorNetworkNode: 
################################################################
Tor hidden service published after 33539 ms. Socked=HiddenServiceSocket[addr=zf6bqwxdbync6ono.onion,port=9999]
################################################################ 
led-05 00:36:29.506 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer fl3mmribyxgrv63c.onion:8000.  
led-05 00:36:29.539 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a GetUpdatedDataRequest to peer 3f3cu2yw7u457ztq.onion:8000.  
led-05 00:36:33.198 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: Num of latestLivePeers=2 
led-05 00:36:39.009 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: 
#################################################################
Connected to node: fl3mmribyxgrv63c.onion:8000
Received 420 instances
Filter: 1
MailboxStoragePayload: 135
Alert: 1
Arbitrator: 2
OfferPayload: 281
################################################################# 
led-05 00:36:39.690 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Start processing 0 items. 
led-05 00:36:42.350 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: We have 13 connections open. Our limit is 12 
led-05 00:36:42.351 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: We have too many connections open. Lets try first to remove the inbound connections of type PEER. 
led-05 00:36:42.352 [JavaFX Application Thread] WARN  b.n.p.p.PeerManager: No candidates found to remove (That case should not be possible as we use in the last case all connections).
	allConnections=[Connection{peerAddress=Optional[23zk555epgocyjpf.onion:9999], peerType=PEER, uid='793b737f-4856-42d8-8a79-93e036ff7a6d'}, Connection{peerAddress=Optional[msfhjhmzw7qtt5vh.onion:9999], peerType=PEER, uid='78dc0984-9407-4a86-95c2-7135459c8029'}, Connection{peerAddress=Optional[wep5dncfp5qac5s5.onion:9999], peerType=PEER, uid='d704ec3f-36b7-4d7b-8486-f1b140807860'}, Connection{peerAddress=Optional[rm7b56wbrcczpjvl.onion:8000], peerType=SEED_NODE, uid='10d45cce-bcf7-455a-81bf-f8f384fa13df'}, Connection{peerAddress=Optional[3mfblm76oxe6yw7f.onion:9999], peerType=PEER, uid='181bd0c0-edad-49d7-9991-fc73676e4102'}, Connection{peerAddress=Optional[mj3ijiia3vobvrb3.onion:9999], peerType=PEER, uid='ba820d2c-0eea-46d8-987b-4d9954f31421'}, Connection{peerAddress=Optional[3f3cu2yw7u457ztq.onion:8000], peerType=SEED_NODE, uid='28081cc1-14e1-4c6d-8d76-39b6e4004409'}, Connection{peerAddress=Optional[fl3mmribyxgrv63c.onion:8000], peerType=SEED_NODE, uid='2c0eaf31-70c4-4358-882f-bbc0493eb190'}, Connection{peerAddress=Optional[bn6koqzrc5cxhkep.onion:9999], peerType=PEER, uid='b8b2513d-5484-4ed7-9109-fbf97a63fcfb'}, Connection{peerAddress=Optional[4cqqaah2kn5yeaei.onion:9999], peerType=PEER, uid='9179297b-21f1-42c5-8da0-58331fb3f0da'}, Connection{peerAddress=Optional[lnnzy3pe5y2a3z6v.onion:9999], peerType=PEER, uid='0bf9f33e-9656-4fa5-8614-9ca10dba83fb'}, Connection{peerAddress=Optional[3yanbr3hnjf2nlvz.onion:9999], peerType=PEER, uid='50a00442-9039-4d15-b2e9-9a44d62855a2'}, Connection{peerAddress=Optional[rb3qhwh4ilhhexvp.onion:9999], peerType=PEER, uid='236b37da-935e-476d-8486-41bb6095e106'}] 
led-05 00:36:42.353 [InputHandler-3f3cu2yw7u457ztq.onion:8000] INFO  b.n.p.n.Connection$SharedModel: SocketException (expected if connection lost). closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=false} RESET; connection=Connection{peerAddress=Optional[3f3cu2yw7u457ztq.onion:8000], peerType=SEED_NODE, uid='28081cc1-14e1-4c6d-8d76-39b6e4004409'} 
led-05 00:36:42.555 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: onDisconnect called: nodeAddress=Optional[3f3cu2yw7u457ztq.onion:8000], closeConnectionReason=CloseConnectionReason{sendCloseMessage=true, isIntended=true} TOO_MANY_SEED_NODES_CONNECTED 
led-05 00:36:42.556 [JavaFX Application Thread] INFO  b.n.p.p.p.PeerExchangeManager: onDisconnect closeConnectionReason=CloseConnectionReason{sendCloseMessage=true, isIntended=true} TOO_MANY_SEED_NODES_CONNECTED, nodeAddressOpt=Optional[3f3cu2yw7u457ztq.onion:8000] 
led-05 00:36:43.081 [NetworkNode:SendMessage-to-gcprwj6tdmddpcon.onion:9999] INFO  b.n.p.n.NetworkNode: onFailure at sendMessage: peersNodeAddress=gcprwj6tdmddpcon.onion:9999
	message=GetPeersRequest(senderNodeAddress=zf6bqwxdbync6ono.onion:9999, nonce=-625039558, reportedPeers=[Peer{     nodeAddress=4cqqaah2kn5yeaei.onion:9999,     supportedCapabilities=[0, 1, 2, 7],     fai... 
led-05 00:36:47.964 [InputHandler-3yanbr3hnjf2nlvz.onion:9999] INFO  b.n.p.n.Connection$InputHandler: CloseConnectionMessage received. Reason=TOO_MANY_CONNECTIONS_OPEN
	connection=Connection{peerAddress=Optional[3yanbr3hnjf2nlvz.onion:9999], peerType=PEER, uid='50a00442-9039-4d15-b2e9-9a44d62855a2'} 
led-05 00:36:47.966 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: onDisconnect called: nodeAddress=Optional[3yanbr3hnjf2nlvz.onion:9999], closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=true} CLOSE_REQUESTED_BY_PEER 
led-05 00:36:47.967 [JavaFX Application Thread] INFO  b.n.p.p.p.PeerExchangeManager: onDisconnect closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=true} CLOSE_REQUESTED_BY_PEER, nodeAddressOpt=Optional[3yanbr3hnjf2nlvz.onion:9999] 
led-05 00:36:51.139 [JavaFX Application Thread] INFO  o.b.c.MnemonicCode: PBKDF2 took 90.92 ms 
led-05 00:36:51.198 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Stopping ... 
led-05 00:36:51.205 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Stopped. 
led-05 00:36:51.210 [ STOPPING] INFO  o.b.c.PeerGroup: Awaiting PeerGroup shutdown ... 
led-05 00:36:51.257 [ STOPPING] INFO  o.b.s.SPVBlockStore: Windows mmap hack: Forcing buffer cleaning 
led-05 00:36:51.263 [RestoreBTCWallet-%d] INFO  b.c.b.s.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=null 
led-05 00:36:51.263 [RestoreBTCWallet-%d] INFO  o.b.c.Context: Creating bitcoinj 0.14.4.11 context. 
led-05 00:36:51.269 [ STARTING] INFO  b.c.b.s.WalletConfig: Wallet directory: C:\Users\***\AppData\Roaming\Bisq\btc_mainnet\wallet 
led-05 00:36:51.278 [ STARTING] INFO  b.c.b.s.WalletConfig: Renaming old wallet file C:\Users\***\AppData\Roaming\Bisq\btc_mainnet\wallet\bisq_BTC.wallet to C:\Users\***\AppData\Roaming\Bisq\btc_mainnet\wallet\Backup 3 for bisq_BTC.wallet 
led-05 00:36:51.281 [ STARTING] INFO  o.b.w.DeterministicKeyChain: 133 keys needed for M/44H/0H/0H/0 = 0 issued + 100 lookahead size + 33 lookahead threshold - 0 num children 
led-05 00:36:51.340 [ STARTING] INFO  o.b.w.DeterministicKeyChain: Took 57.19 ms 
led-05 00:36:51.341 [ STARTING] INFO  o.b.w.DeterministicKeyChain: 133 keys needed for M/44H/0H/0H/1 = 0 issued + 100 lookahead size + 33 lookahead threshold - 0 num children 
led-05 00:36:51.412 [ STARTING] INFO  o.b.w.DeterministicKeyChain: Took 70.33 ms 
led-05 00:36:51.443 [ STARTING] INFO  b.c.b.s.WalletConfig: Renaming old wallet file C:\Users\***\AppData\Roaming\Bisq\btc_mainnet\wallet\bisq_BSQ.wallet to C:\Users\***\AppData\Roaming\Bisq\btc_mainnet\wallet\Backup 3 for bisq_BSQ.wallet 
led-05 00:36:51.446 [ STARTING] INFO  o.b.w.DeterministicKeyChain: 133 keys needed for M/44H/142H/0H/0 = 0 issued + 100 lookahead size + 33 lookahead threshold - 0 num children 
led-05 00:36:51.488 [ STARTING] INFO  o.b.w.DeterministicKeyChain: Took 41.50 ms 
led-05 00:36:51.489 [ STARTING] INFO  o.b.w.DeterministicKeyChain: 133 keys needed for M/44H/142H/0H/1 = 0 issued + 100 lookahead size + 33 lookahead threshold - 0 num children 
led-05 00:36:51.523 [ STARTING] INFO  o.b.w.DeterministicKeyChain: Took 33.53 ms 
led-05 00:36:51.543 [JavaFX Application Thread] ERROR b.c.b.s.WalletsSetup: Service failure from state: STARTING; failure={} java.io.IOException: org.bitcoinj.store.BlockStoreException: java.nio.channels.OverlappingFileLockException
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:494)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.bitcoinj.store.BlockStoreException: java.nio.channels.OverlappingFileLockException
	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:133)
	at bisq.core.btc.setup.WalletConfig.provideBlockStore(WalletConfig.java:331)
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:406)
	... 3 common frames omitted
Caused by: java.nio.channels.OverlappingFileLockException: null
	at java.base/sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at java.base/sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1191)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1160)
	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:106)
	... 5 common frames omitted

led-05 00:36:51.545 [JavaFX Application Thread] ERROR b.d.u.GUIUtil: java.io.IOException: org.bitcoinj.store.BlockStoreException: java.nio.channels.OverlappingFileLockException 
led-05 00:37:01.875 [InputHandler-msfhjhmzw7qtt5vh.onion:9999] INFO  b.n.p.n.Connection$InputHandler: CloseConnectionMessage received. Reason=TOO_MANY_CONNECTIONS_OPEN
	connection=Connection{peerAddress=Optional[msfhjhmzw7qtt5vh.onion:9999], peerType=PEER, uid='78dc0984-9407-4a86-95c2-7135459c8029'} 
led-05 00:37:01.899 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: onDisconnect called: nodeAddress=Optional[msfhjhmzw7qtt5vh.onion:9999], closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=true} CLOSE_REQUESTED_BY_PEER 
led-05 00:37:01.900 [JavaFX Application Thread] INFO  b.n.p.p.p.PeerExchangeManager: onDisconnect closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=true} CLOSE_REQUESTED_BY_PEER, nodeAddressOpt=Optional[msfhjhmzw7qtt5vh.onion:9999] 
led-05 00:37:12.460 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://5bmpx76qllutpcyp.onion/ 62.015 sec. after last request 
led-05 00:37:14.125 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=CZK, price=86126.52, timestampSec=1546645114376, isExternallyProvidedPrice=true) from provider http://44mgyoe2b6oqiytt.onion/ after 1.665 sec. 
led-05 00:37:20.338 [JavaFX Application Thread] INFO  o.b.c.MnemonicCode: PBKDF2 took 22.19 ms 
led-05 00:37:20.350 [RestoreBTCWallet-%d] ERROR b.c.b.s.WalletsSetup: Executing task failed. null
```
Thanks for help

**Comment by ghost** [comment]
> For this I was forced to delete old version with all data. 

Hi, 
Sorry, I have no idea what to do with this error, but please note that you are **never** forced to delete anything in order to install a new version. And certainly not your data directory.
Do not delete.
Rename the directory (so it won't be overwritten) and then make the install.
So, in case of troubles you still have your old directory available if necessary.

I'm pretty sure that the install takes care about the important already existing files, but saving your data directory (from time to time) is a costless precaution.

**Comment by janfiedler** [comment]
Hi, thanks for answer.
I have backup of deleted folder. Without deleting old version new version never start. I found this bug here and this was solution how to solve it
