### ISSUE TITLE
Can not edit order: "No value present'

### ISSUE THREAD

**Issue by clashicly** [bisq-network/bisq#2210]
v0.9.1 win64
Steps to reproduce:
Portfolio (tab), My Open Offers (sub tab), click green pencil on right. Get a dialog "No Value Present"
Subsequent attempts at editing have no action/error.

Two Orders originated 3-4 months ago and Bisq was upgraded from v0.8 to v0.9.1 since.

**Comment by clashicly** [comment]
`Jan-06 18:56:45.250 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Jan-06 18:56:45.264 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= No value present 
Jan-06 18:56:45.270 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.util.NoSuchElementException 
Jan-06 18:56:45.272 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at bisq.desktop.main.portfolio.editoffer.EditOfferDataModel.applyOpenOffer(EditOfferDataModel.java:120)
	at bisq.desktop.main.portfolio.editoffer.EditOfferViewModel.applyOpenOffer(EditOfferViewModel.java:59)
	at bisq.desktop.main.portfolio.editoffer.EditOfferView.applyOpenOffer(EditOfferView.java:138)
	at bisq.desktop.main.portfolio.PortfolioView.loadView(PortfolioView.java:184)
	at bisq.desktop.main.portfolio.PortfolioView.lambda$initialize$0(PortfolioView.java:90)
	at bisq.desktop.Navigation.lambda$navigateTo$1(Navigation.java:127)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.desktop.Navigation.navigateTo(Navigation.java:127)
	at bisq.desktop.Navigation.navigateTo(Navigation.java:96)
	at bisq.desktop.main.portfolio.PortfolioView.lambda$selectOpenOffersView$5(PortfolioView.java:213)
	at bisq.desktop.main.portfolio.openoffer.OpenOffersView.onEditOpenOffer(OpenOffersView.java:212)
	at bisq.desktop.main.portfolio.openoffer.OpenOffersView.access$1700(OpenOffersView.java:67)
	at bisq.desktop.main.portfolio.openoffer.OpenOffersView$10$1.lambda$updateItem$0(OpenOffersView.java:503)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8865)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3876)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Scene.java:3604)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2613)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:844)`

**Comment by ripcurlx** [comment]
Just to verify my assumption: Could you please tell me the market/asset of your offer? I think it has something to do with an offer of an asset that was removed from the client because of trading inactivity.

**Comment by ripcurlx** [comment]
@clashicly Can you please update to the latest version v0.9.3 to see if your problem is fixed? I tried to simulate it in a test, but wasn't able to cause this exception within the lastest code on master.

**Comment by clashicly** [comment]
> Just to verify my assumption: Could you please tell me the market/asset of your offer? I think it has something to do with an offer of an asset that was removed from the client because of trading inactivity.

BCHC/BTC
BTCC/BTC

**Comment by clashicly** [comment]
> @clashicly Can you please update to the latest version v0.9.3 to see if your problem is fixed? I tried to simulate it in a test, but wasn't able to cause this exception within the lastest code on master.

Same issue with v0.9.3

**Comment by ghost** [comment]
BCHC (Bitcoin Clashic) has probably been delisted from Bisq due to too low activity.

And I don't find BTCC (Bitcoin Classic ?) anymore on Bisq v0.9.3

**Comment by clashicly** [comment]
> BCHC (Bitcoin Clashic) has probably been delisted from Bisq due to too low activity.
> 
> And I don't find BTCC (Bitcoin Classic ?) anymore on Bisq v0.9.3

Isn't everything low activity besides XMR?
Why isn't the order automatically cancelled on delist?
And Maker Fee?

**Comment by ghost** [comment]
> Isn't everything low activity besides XMR?

No

> Why isn't the order automatically cancelled on delist?

Bisq is open-source, is always lacking devs to implement so many things, and welcomes contributors.
If you have some nice code to submit to achieve that properly, please just submit it.

**Comment by ripcurlx** [comment]
@clashicly Could you please post the error log you get in version 0.9.3. I think it must be something else. Just so I'm able to simulate it in a test probably. The exception you posted shouldn't exist in v0.9.3.

**Comment by clashicly** [comment]
@ripcurlx I have since cancelled the orders that I was unable to modify. I am no longer able to reproduce error messages at this time. I can confirm that I received what appeared to be the same error after upgrading to 0.9.3, but did not save the log to compare vs 0.9.1 errors.

**Comment by ripcurlx** [comment]
@clashicly Thanks for the update. If it occurs again feel free to re-open this issue or create a new one.
