### ISSUE TITLE
Error on starting v0.9.2

### ISSUE THREAD

**Issue by meapistol** [bisq-network/bisq#2222]
java.lang.NullPointerException

**Comment by meapistol** [comment]
The market/trades screen is not working.

**Comment by ManfredKarrer** [comment]
Can you post or send me the log file?

**Comment by meapistol** [comment]
Can I send it by email? I got the error on my arbitration-instance.

-mep

**Comment by meapistol** [comment]
Fucking github, my cover is now blown.

**Comment by ghost** [comment]
v0.9.2/Debian 9.6
Bisq closes itself 15 sec after launch.

The concerned log:
<pre>
janv.-08 19:05:16.912 [main] INFO  b.c.s.CoreSetup: 


Log files under: /home/user1/.local/share/Bisq/bisq 
janv.-08 19:05:16.929 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=4.9.0-8-amd64; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
janv.-08 19:05:17.119 [main] INFO  b.c.app.Version: Version{VERSION=0.9.2, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
janv.-08 19:05:17.120 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-0.9.2-all.jar 
janv.-08 19:05:18.800 [JavaFX Application Thread] INFO  b.c.p.ProvidersRepository: Selected provider baseUrl=http://ceaanhbvluug4we6.onion/, providerList=[http://ceaanhbvluug4we6.onion/, http://44mgyoe2b6oqiytt.onion/, http://xc3nh4juf2hshy7e.onion/, http://62nvujg5iou3vu3i.onion/, http://5bmpx76qllutpcyp.onion/] 
janv.-08 19:05:19.111 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: peersWithNoCapabilitiesSet=48, persistedPeerList.size()=500 
janv.-08 19:05:19.302 [JavaFX Application Thread] INFO  b.c.d.n.f.RpcService: Version of btcd-cli4j library: 0.5.8.4 
janv.-08 19:05:20.838 [JavaFX Application Thread] INFO  b.c.a.AvoidStandbyModeService: AvoidStandbyModeService started 
janv.-08 19:05:21.879 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: TradeStatistics2StorageService: size of Storage: 4.814912 MB 
janv.-08 19:05:22.077 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: AccountAgeWitnessStorageService: size of Storage: 0.684174 MB 
janv.-08 19:05:22.082 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=DaoStateStore_BTC_MAINNET, destinationFile=/home/user1/.local/share/Bisq/btc_mainnet/db/DaoStateStore 
janv.-08 19:05:22.085 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: Could not find resourceFile DaoStateStore_BTC_MAINNET. That is expected if none is provided yet. 
janv.-08 19:05:22.154 [readFromResourcesThread] INFO  b.c.a.SetupUtils: readFromResources took 1173 ms 
janv.-08 19:05:22.185 [NetworkNode-9999] INFO  b.n.p.n.NewTor: Starting tor 
janv.-08 19:05:22.191 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: walletInitialized=false, p2pNetWorkReady=false 
janv.-08 19:05:26.657 [NetworkNode-9999] INFO  o.b.n.tor.Tor: Starting Tor 
janv.-08 19:05:30.336 [NetworkNode-9999] INFO  b.n.p.n.NewTor: 
################################################################
Tor started after 8151 ms. Start publishing hidden service.
################################################################ 
janv.-08 19:05:30.349 [JavaFX Application Thread] INFO  b.c.a.WalletAppSetup: Initialize WalletAppSetup with BitcoinJ version 0.14.4.11 and LibDohJ version 0.14.4 with hash of BitcoinJ commit cd30ad5b 
janv.-08 19:05:30.373 [JavaFX Application Thread] INFO  b.c.b.s.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=localhost:43867	Version 5 
janv.-08 19:05:30.397 [JavaFX Application Thread] INFO  o.b.c.Context: Creating bitcoinj 0.14.4.11 context. 
janv.-08 19:05:30.420 [JavaFX Application Thread] INFO  b.c.b.n.BtcNetworkConfig: You connect with peerAddresses: [[r3dsojfhwcm7x7p6.onion]:8333, [vlf5i3grro3wux24.onion]:8333, [fz6nsij6jiyuwlsc.onion]:8333, [c6ac4jdfyeiakex2.onion]:8333, [sjyzmwwu6diiit3r.onion]:8333, [3xucqntxp5ddoaz5.onion]:8333, [lgkvbvro67jomosw.onion]:8333, [4jyh6llqj264oggs.onion]:8333, [mxdtrjhe2yfsx3pg.onion]:8333, [3r44ddzjitznyahw.onion]:8333, [i3a5xtzfm4xwtybd.onion]:8333, [z33nukt7ngik3cpe.onion]:8333, [sslnjjhnmwllysv4.onion]:8333] 
janv.-08 19:05:30.437 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://ceaanhbvluug4we6.onion/ 
janv.-08 19:05:30.446 [ STARTING] INFO  b.c.b.s.WalletConfig: Wallet directory: /home/user1/.local/share/Bisq/btc_mainnet/wallet 
janv.-08 19:05:30.651 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a PreliminaryGetDataRequest to peer rm7b56wbrcczpjvl.onion:8000.  
janv.-08 19:05:30.679 [NetworkNode-9999] ERROR b.n.p.n.TorNetworkNode: Could not connect to running Tor: Unsupported private_key algorithm. Did Tor get a new key type for hidden services? 
janv.-08 19:05:30.780 [NetworkNode:SendMessage-to-rm7b56wbrcczpjvl.onion:8000] INFO  b.n.p.n.NetworkNode: onFailure at sendMessage: peersNodeAddress=rm7b56wbrcczpjvl.onion:8000
	message=PreliminaryGetDataRequest(supportedCapabilities=[0, 1, 2, 7]) 
</pre>

if I should better open a separate issue, just tell me.

**Comment by ManfredKarrer** [comment]
@HarryMacfinned Can you email me the full log?

**Comment by ManfredKarrer** [comment]
@HarryMacfinned weid....can u try to delete all tro files beside the hiddenservice folder? do u use any program argument for tor?

**Comment by ghost** [comment]
@ManfredKarrer , 
I started with an empty Bisq.log, so this is the full log copied above.

I started Bisq from CLI with just
> Bisq

no arguments etc.

The Bisq.log just before (with v0.9.1 running) seems to contain a lot of errors. I'll look a bit closely.

**Comment by ghost** [comment]
I delete all files inside the hiddenservice folder and now Bisq seems to work.

I however now have a java.lang.IllegalArgumentException

**Comment by ManfredKarrer** [comment]
Not inside the hiddenservice all except the hiddenservice folder. there is your priv key for the onion address!

**Comment by ManfredKarrer** [comment]
but if that fixed it, it seems your priv key was somehow corrupted.

**Comment by ghost** [comment]
Here's the log part concerning the java.lang.IllegalArgumentException 

<pre>
janv.-08 19:50:08.604 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
janv.-08 19:50:08.604 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= null 
janv.-08 19:50:08.605 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.IllegalArgumentException 
janv.-08 19:50:08.605 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at org.bitcoinj.utils.ExchangeRate.<init>(ExchangeRate.java:39)
	at org.bitcoinj.utils.ExchangeRate.<init>(ExchangeRate.java:47)
	at bisq.core.trade.statistics.TradeStatistics2.getTradeVolume(TradeStatistics2.java:261)
	at bisq.desktop.main.market.trades.TradesChartsViewModel.getCandleData(TradesChartsViewModel.java:318)
	at bisq.desktop.main.market.trades.TradesChartsViewModel.lambda$updateChartData$7(TradesChartsViewModel.java:283)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1751)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at bisq.desktop.main.market.trades.TradesChartsViewModel.updateChartData(TradesChartsViewModel.java:284)
	at bisq.desktop.main.market.trades.TradesChartsViewModel.lambda$new$0(TradesChartsViewModel.java:130)
	at javafx.base/com.sun.javafx.collections.SetListenerHelper$Generic.fireValueChangedEvent(SetListenerHelper.java:327)
	at javafx.base/com.sun.javafx.collections.SetListenerHelper.fireValueChangedEvent(SetListenerHelper.java:72)
	at javafx.base/com.sun.javafx.collections.ObservableSetWrapper.callObservers(ObservableSetWrapper.java:128)
	at javafx.base/com.sun.javafx.collections.ObservableSetWrapper.add(ObservableSetWrapper.java:269)
	at bisq.core.trade.statistics.TradeStatisticsManager.addToMap(TradeStatisticsManager.java:155)
	at bisq.core.trade.statistics.TradeStatisticsManager.lambda$onAllServicesInitialized$2(TradeStatisticsManager.java:100)
	at bisq.network.p2p.storage.P2PDataStorage.lambda$addPersistableNetworkPayload$7(P2PDataStorage.java:318)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.storage.P2PDataStorage.addPersistableNetworkPayload(P2PDataStorage.java:318)
	at bisq.network.p2p.storage.P2PDataStorage.lambda$onMessage$5(P2PDataStorage.java:234)
	at java.base/java.util.Optional.ifPresent(Optional.java:172)
	at bisq.network.p2p.storage.P2PDataStorage.onMessage(P2PDataStorage.java:224)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:342)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:342)
	at bisq.network.p2p.network.Connection.lambda$onMessage$3(Connection.java:397)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:397)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
 </pre>

maybe it's the same issue as meapistol ? or related ?

**Comment by ManfredKarrer** [comment]
yes thats fixed. we got a object with 0 price and amount which is invalid.

**Comment by ghost** [comment]
@ManfredKarrer wrote:
> but if that fixed it, it seems your priv key was somehow corrupted.

Just for information,
My <code>~/.local/share/Bisq/btc_mainnet/tor/hiddenservices/hostname</code> file had 23 bytes.
And it seems that 22 bytes is more legit (?)
So <code>hostname</code> was perhaps the corrupted file ?

23 bytes = hostname with LF at the end
22 bytes = hostname without LF at the end
