### ISSUE TITLE
Error java.lang.NullPointerException

### ISSUE THREAD

**Issue by 21isenough** [bisq-network/bisq#2225]
**Got this error, when switching between tabs.**  I update to the newest release about an hour ago (Settings > Version Details > 0.9.2). 
Yet it still says "Update available".

Jan-08 20:09:10.056 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException
	at bisq.desktop.main.market.trades.TradesChartsView.deactivate(TradesChartsView.java:269)
	at bisq.desktop.common.view.ActivatableViewAndModel.lambda$prepareInitialize$0(ActivatableViewAndModel.java:46)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.base/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.graphics/javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1054)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1114)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent$3.onProposedChange(Parent.java:609)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at bisq.desktop.main.MainView.lambda$initialize$7(MainView.java:317)
	at bisq.desktop.Navigation.lambda$navigateTo$1(Navigation.java:127)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.desktop.Navigation.navigateTo(Navigation.java:127)
	at bisq.desktop.Navigation.navigateTo(Navigation.java:96)
	at bisq.desktop.main.MainView$NavButton.lambda$new$1(MainView.java:737)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8865)
	at javafx.controls/javafx.scene.control.ToggleButton.fire(ToggleButton.java:257)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3876)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Scene.java:3604)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2613)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by 21isenough** [comment]
I recall, it happened the fist time, when I selected "Grin" in Market > Trades. 

Jan-08 20:19:29.831 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Market price for currency GRIN is not provided by the provider http://62nvujg5iou3vu3i.onion/. That is expected for currencies not listed at providers.

**Comment by ghost** [comment]
... there is a v0.9.3 just available (corrects a little bug).

**Comment by ripcurlx** [comment]
@21isenough This should be fixed with v0.9.3 (just had another release). We have out of sudden an empty trade object loitering around, that causes this issue.

**Comment by ripcurlx** [comment]
Closing as complete. @21isenough Please re-open if this is not fixed with v0.9.3.

**Comment by ghost** [comment]
just selected GRIN in v0.9.3 market/trades, and it seems indeed to work ok.
