### ISSUE TITLE
Funds stuck when canceling offer

### ISSUE THREAD

**Issue by aynik** [bisq-network/bisq#2230]
My funds got stuck when trying to cancel an offer. 

The offer id is:

192955-92605620-83f5-40fa-b6dc-81d996f66330-091

The error is this:

```
disputed payoutTx:
  fa4fa1c30c746d7f9e2d29c49bf109a274253309a1b4b7c474401b8065914c3c
     in   0[] PUSHDATA(72)[3045022100e53e1f2c90736b8b3c4ffe57e8bc340ffe15de4f32773297cc28bb2baf07274d02205d9fb4b7da25a57a8c0299a8e6daf3020606691452561cd51e1f9d65799517ab01] PUSHDATA(72)[3045022100d1bca394b160740bc19414275582b0300fff34fcdb0739e446fbfffd29156a1802200b1686b2cb07635510d5666d619e703baee4ce5102161b567525b3a28ce2521201] PUSHDATA1[522103c573088374ed872253a70565b36c6dc02ed889ca29d5a3e6546c67ccbc52ffd021038f11da3b85e86b76b81ed075fe4930a5b471c294613b8932c95ada8e3202409f210360fe2df0cfe1bdb54cf73f08a177a43e78c6bbb08a7a5b46040611f25645522853ae] 0.075532 BTC (7553200)
          outpoint:fc0f7be83bc6eb80fba1d9e9a27984da66c95d06bc6c92579ec73e85448f7b12:0 hash160:d9a4890cba021909902864434e9a05ad294b06e7
     out  DUP HASH160 PUSHDATA(20)[04c0203d31f5b8d40b194e404bb713c815644ded] EQUALVERIFY CHECKSIG 0.01 BTC (1000000) ScriptPubKey: 76a91404c0203d31f5b8d40b194e404bb713c815644ded88ac Address:1S7rurN6G9MsRUs5hNy2vPT63xAWeVxJs 
     out  DUP HASH160 PUSHDATA(20)[c35c2d1007c5f2dab0aba13a8dc4ee1a1b33be44] EQUALVERIFY CHECKSIG 0.0655 BTC (6550000) ScriptPubKey: 76a914c35c2d1007c5f2dab0aba13a8dc4ee1a1b33be4488ac Address:1JoyBukWkr3Gw9aJGxpmbPCUUroS7H2SP8 
     fee  0.000032 BTC for 375 bytes (8 Satoshi/Byte)
     prps UNKNOWN
 
Jan-09 18:32:19.321 [JavaFX Application Thread] ERROR b.c.b.w.WalletService: Script resulted in a non-true stack: [[B@3b3943cb, [B@745ed869, [B@22820b38] 
Jan-09 18:32:19.323 [JavaFX Application Thread] ERROR b.c.a.DisputeManager: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@3b3943cb, [B@745ed869, [B@22820b38] 
Jan-09 18:32:19.324 [JavaFX Application Thread] INFO  b.c.a.DisputeManager: Send AckMessage for DisputeCommunicationMessage to peer 3b7cft5k4ae6a236.onion:9999. tradeId=PnTtlSi-7a12ea0f-e691-465b-8260-f503206bc405-080, uid=34bd461c-42f2-470f-acfa-d7366b671149 
Jan-09 18:32:19.339 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Jan-09 18:32:19.339 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@3b3943cb, [B@745ed869, [B@22820b38] 
Jan-09 18:32:19.339 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.RuntimeException 
Jan-09 18:32:19.342 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.RuntimeException: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@3b3943cb, [B@745ed869, [B@22820b38]
	at bisq.core.arbitration.DisputeManager.onDisputeResultMessage(DisputeManager.java:1004)
	at bisq.core.arbitration.DisputeManager.dispatchMessage(DisputeManager.java:328)
	at bisq.core.arbitration.DisputeManager.lambda$applyMessages$14(DisputeManager.java:282)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.core.arbitration.DisputeManager.applyMessages(DisputeManager.java:278)
	at bisq.core.arbitration.DisputeManager.tryApplyMessages(DisputeManager.java:258)
	at bisq.core.arbitration.DisputeManager.lambda$new$1(DisputeManager.java:162)
	at bisq.network.p2p.P2PService.lambda$processMailboxEntry$9(P2PService.java:540)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.P2PService.processMailboxEntry(P2PService.java:539)
	at bisq.network.p2p.P2PService.lambda$maybeProcessAllMailboxEntries$13(P2PService.java:660)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4791)
	at bisq.network.p2p.P2PService.maybeProcessAllMailboxEntries(P2PService.java:658)
	at bisq.network.p2p.P2PService.onUpdatedDataReceived(P2PService.java:351)
	at bisq.network.p2p.peers.getdata.RequestDataManager$2.onComplete(RequestDataManager.java:353)
	at bisq.network.p2p.peers.getdata.RequestDataHandler.onMessage(RequestDataHandler.java:294)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:342)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:342)
	at bisq.network.p2p.network.Connection.lambda$onMessage$3(Connection.java:397)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:397)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

**Comment by ripcurlx** [comment]
At what point of the trade did you try to cancel the offer?
In this screen after you've transferred the funds?
<img width="1284" alt="bildschirmfoto 2019-01-09 um 12 00 36" src="https://user-images.githubusercontent.com/170962/50895370-3a2e8f80-1406-11e9-9880-965bba2ce1c0.png">

**Comment by ripcurlx** [comment]
Was it in the take offer or create offer process?

**Comment by aynik** [comment]
After the create offer process. The offer was published for some time (a day or so), then I tried to cancel it and I get that error.

**Comment by aynik** [comment]
I see this may be related to a previous offer that was disputed and resolved (by cancelation of the assigned arbitrator):

PnTtlSi-7a12ea0f-e691-465b-8260-f503206bc405-080

**Comment by aynik** [comment]
Arbitrator was:

3b7cft5k4ae6a236.onion:9999

Closing message for PnTtlSi dispute was:

> Ticket closed on Jan 3, 2019 3:29:16 AM
> 
> Summary:
> BTC seller/Taker delivered tamper proof evidence: No
> BTC seller/Taker did ID verification: No
> BTC seller/Taker did screencast or video: No
> Payout amount for BTC buyer: 0.01 BTC
> Payout amount for BTC seller: 0.0655 BTC
> 
> Summary notes:
> Not published deposit tx. Buyer used v.0.8 but will upgrade to v.0.9.1

**Comment by keo-bisq** [comment]
There was a problem with closing PnTtlSi, and I have now closed it again. I hope this solves your problem. If not please tell us.

**Comment by aynik** [comment]
I still get the same error:

> Jan-11 10:32:45.296 [JavaFX Application Thread] ERROR b.c.a.DisputeManager: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@74fe37b6, [B@667da6c0, [B@2c30174d]

**Comment by aynik** [comment]
I've withdrawn all funds now, will create a new bisq account. This one was constantly causing problems (maybe due being an old 2017 account?). You can close this ticket.
