### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by emphasisx** [bisq-network/bisq#2235]
Happens when I click on the open trades tab in portfolio.

[bisq.log](https://github.com/bisq-network/bisq/files/2742242/bisq.log)

**Comment by ManfredKarrer** [comment]
Do you have updated to v0.9.3? There was a silimar issue which was fixed with 0.9.3.

**Comment by ripcurlx** [comment]
I think it is something different. @emphasisx is running v0.9.3 and the exception gets thrown in the pending trades view:

```
Jan-09 14:03:13.833 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at org.bitcoinj.utils.ExchangeRate.<init>(ExchangeRate.java:39)
	at org.bitcoinj.utils.ExchangeRate.<init>(ExchangeRate.java:47)
	at bisq.core.monetary.Price.getVolumeByAmount(Price.java:85)
	at bisq.core.trade.Trade.getTradeVolume(Trade.java:723)
	at bisq.desktop.main.portfolio.pendingtrades.PendingTradesView$5$1.updateItem(PendingTradesView.java:404)
	at bisq.desktop.main.portfolio.pendingtrades.PendingTradesView$5$1.updateItem(PendingTradesView.java:399)
	at javafx.controls/javafx.scene.control.TableCell.updateItem(TableCell.java:665)
	at javafx.controls/javafx.scene.control.TableCell.indexChanged(TableCell.java:469)

```

**Comment by ripcurlx** [comment]
Or actually it is the same problem on a different screen as it fails here at `checkArgument(fiat.isPositive());` and I guess it is because the fiat value is 0.
@emphasisx As this is a pending trade, when you accepted the offer, did everything look fine on the offer? Or was the fiat volume zero?

**Comment by ManfredKarrer** [comment]
@emphasisx 
Do you use the normal Bisq desktop client or anything special (API)?

Please open a dispute with cmd+o. 

If you use the normal client maybe the peer use either the API or a buggy Bisq client. Please refer that GH link to the arbitrator so he has full context. The arbitrator should ask the peer then what Bisq version he uses and if he did anything special.

**Comment by emphasisx** [comment]
I'm using the desktop client 0.9.3. I created the offer and everything was fine. I opened a dispute to complete the trade.

**Comment by ripcurlx** [comment]
Closing as complete. @emphasisx feel free to reopen if there is still a problem.
