### ISSUE TITLE
user.getAcceptedArbitrators() must not be empty

### ISSUE THREAD

**Issue by tocog** [bisq-network/bisq#2254]
Just installed, sent some BTC to buy XMR and get this message when I go to accept any offers.
The BTC have 1 confirmation.
Tried several offers and this always happens.

Here's the log:

`Jan-11 20:10:41.534 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Jan-11 20:10:41.535 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= user.getAcceptedArbitrators() must not be empty 
Jan-11 20:10:41.535 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.IllegalArgumentException 
Jan-11 20:10:41.535 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.IllegalArgumentException: user.getAcceptedArbitrators() must not be empty
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at bisq.desktop.main.offer.takeoffer.TakeOfferDataModel.estimateTxSize(TakeOfferDataModel.java:345)
	at bisq.desktop.main.offer.takeoffer.TakeOfferDataModel.onShowPayFundsScreen(TakeOfferDataModel.java:265)
	at bisq.desktop.main.offer.takeoffer.TakeOfferViewModel.onShowPayFundsScreen(TakeOfferViewModel.java:253)
	at bisq.desktop.main.offer.takeoffer.TakeOfferView.onShowPayFundsScreen(TakeOfferView.java:485)
	at bisq.desktop.main.offer.takeoffer.TakeOfferView.showNextStepAfterAmountIsSet(TakeOfferView.java:933)
	at bisq.desktop.main.offer.takeoffer.TakeOfferView.lambda$addSubscriptions$18(TakeOfferView.java:707)
	at org.fxmisc.easybind.EasyBind.lambda$subscribe$12(EasyBind.java:263)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at bisq.desktop.main.offer.takeoffer.TakeOfferViewModel.applyOfferState(TakeOfferViewModel.java:397)
	at bisq.desktop.main.offer.takeoffer.TakeOfferViewModel.lambda$createListeners$10(TakeOfferViewModel.java:530)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at bisq.core.offer.Offer.setState(Offer.java:255)
	at bisq.core.offer.availability.tasks.ProcessOfferAvailabilityResponse.run(ProcessOfferAvailabilityResponse.java:63)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.run(TaskRunner.java:60)
	at bisq.core.offer.availability.OfferAvailabilityProtocol.handleOfferAvailabilityResponse(OfferAvailabilityProtocol.java:134)
	at bisq.core.offer.availability.OfferAvailabilityProtocol.lambda$new$0(OfferAvailabilityProtocol.java:75)
	at bisq.network.p2p.P2PService.lambda$onMessage$8(P2PService.java:422)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.P2PService.onMessage(P2PService.java:421)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:342)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:342)
	at bisq.network.p2p.network.Connection.lambda$onMessage$3(Connection.java:397)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:397)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)`

**Comment by donacid** [comment]
Same issue here. Tried to take 2 orders a couple minutes before which gave me a timeout error and made me lose the taker fee. After that I restarted the application and got the AcceptedArbitrators must not be empty error before I could fund a new trade.

Here's my log:
Jan.-12 02:28:22.222 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.IllegalArgumentException: user.getAcceptedArbitrators() must not be empty
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at bisq.desktop.main.offer.takeoffer.TakeOfferDataModel.estimateTxSize(TakeOfferDataModel.java:345)
	at bisq.desktop.main.offer.takeoffer.TakeOfferDataModel.onShowPayFundsScreen(TakeOfferDataModel.java:265)
	at bisq.desktop.main.offer.takeoffer.TakeOfferViewModel.onShowPayFundsScreen(TakeOfferViewModel.java:253)
	at bisq.desktop.main.offer.takeoffer.TakeOfferView.onShowPayFundsScreen(TakeOfferView.java:485)
	at bisq.desktop.main.offer.takeoffer.TakeOfferView.showNextStepAfterAmountIsSet(TakeOfferView.java:933)
	at bisq.desktop.main.offer.takeoffer.TakeOfferView.lambda$addSubscriptions$18(TakeOfferView.java:707)
	at org.fxmisc.easybind.EasyBind.lambda$subscribe$12(EasyBind.java:263)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at bisq.desktop.main.offer.takeoffer.TakeOfferViewModel.applyOfferState(TakeOfferViewModel.java:397)
	at bisq.desktop.main.offer.takeoffer.TakeOfferViewModel.lambda$createListeners$10(TakeOfferViewModel.java:530)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at bisq.core.offer.Offer.setState(Offer.java:255)
	at bisq.core.offer.availability.tasks.ProcessOfferAvailabilityResponse.run(ProcessOfferAvailabilityResponse.java:63)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.run(TaskRunner.java:60)
	at bisq.core.offer.availability.OfferAvailabilityProtocol.handleOfferAvailabilityResponse(OfferAvailabilityProtocol.java:134)
	at bisq.core.offer.availability.OfferAvailabilityProtocol.lambda$new$0(OfferAvailabilityProtocol.java:75)
	at bisq.network.p2p.P2PService.lambda$onMessage$8(P2PService.java:422)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.P2PService.onMessage(P2PService.java:421)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:342)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:342)
	at bisq.network.p2p.network.Connection.lambda$onMessage$3(Connection.java:397)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:397)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by tocog** [comment]
BTW, when I try to create a buy offer for XMR I get an error saying "Warning. There are not arbitrators available".
I deleted the SPV data, restarted computer, nothing.

**Comment by ManfredKarrer** [comment]
Can you please restart? There have been issues with the seed nodes. Fixed now.

**Comment by tocog** [comment]
> Can you please restart? There have been issues with the seed nodes. Fixed now.

Yep, it's fixed now, thanks

**Comment by ManfredKarrer** [comment]
See https://github.com/bisq-network/roles/issues/15#issuecomment-453749038
