### ISSUE TITLE
Investigate reason for Protobuffer errors

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#2302]
We get some error logs from protobuffer and it is not clear why they happen. Those are likely not critical and might be results of network disconnections during parsing the PB message as well they are known since long and seem to not cause issues. But it would be good to investigate and find out what exactly is the reason and if they are expected in valid cases like network disconnections during parsing we should not log them as errors but use debug log level.

**Comment by ManfredKarrer** [comment]
Here is an example log from a seed node:

bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope. ExecutionException java.util.concurrent.ExecutionException: bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope
	at bisq.network.p2p.network.SynchronizedProtoOutputStream.writeEnvelope(SynchronizedProtoOutputStream.java:59)
	at bisq.network.p2p.network.Connection.sendMessage(Connection.java:269)
	at bisq.network.p2p.network.NetworkNode.lambda$sendMessage$1(NetworkNode.java:265)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.util.concurrent.ExecutionException: bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at bisq.network.p2p.network.SynchronizedProtoOutputStream.writeEnvelope(SynchronizedProtoOutputStream.java:49)
	... 8 more
Caused by: bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelope(ProtoOutputStream.java:51)
	at bisq.network.p2p.network.SynchronizedProtoOutputStream.lambda$writeEnvelope$0(SynchronizedProtoOutputStream.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:2985)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.flush(CodedOutputStream.java:2896)
	at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:99)
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelopeOrThrow(ProtoOutputStream.java:65)
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelope(ProtoOutputStream.java:48)
	... 6 more
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:86)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawBytesSlowPathOneChunk(CodedInputStream.java:2944)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readBytesSlowPath(CodedInputStream.java:2991)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readBytes(CodedInputStream.java:2419)
	at io.bisq.generated.protobuffer.PB$GetUpdatedDataRequest.<init>(PB.java:10611)
	at io.bisq.generated.protobuffer.PB$GetUpdatedDataRequest.<init>(PB.java:10543)
	at io.bisq.generated.protobuffer.PB$GetUpdatedDataRequest$1.parsePartialFrom(PB.java:11290)
	at io.bisq.generated.protobuffer.PB$GetUpdatedDataRequest$1.parsePartialFrom(PB.java:11285)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2399)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope.<init>(PB.java:1341)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope.<init>(PB.java:1257)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope$1.parsePartialFrom(PB.java:8278)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope$1.parsePartialFrom(PB.java:8273)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
	at com.google.protobuf.AbstractParser.parsePartialDelimitedFrom(AbstractParser.java:262)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:275)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:280)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:49)
	at com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(GeneratedMessageV3.java:347)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope.parseDelimitedFrom(PB.java:3319)
	at bisq.network.p2p.network.Connection$InputHandler.run(Connection.java:802)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:86)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawBytesSlowPathOneChunk(CodedInputStream.java:2944)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readBytesSlowPath(CodedInputStream.java:2991)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readBytes(CodedInputStream.java:2419)
	at io.bisq.generated.protobuffer.PB$PreliminaryGetDataRequest.<init>(PB.java:8386)
	at io.bisq.generated.protobuffer.PB$PreliminaryGetDataRequest.<init>(PB.java:8335)
	at io.bisq.generated.protobuffer.PB$PreliminaryGetDataRequest$1.parsePartialFrom(PB.java:9060)
	at io.bisq.generated.protobuffer.PB$PreliminaryGetDataRequest$1.parsePartialFrom(PB.java:9055)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2399)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope.<init>(PB.java:1313)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope.<init>(PB.java:1257)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope$1.parsePartialFrom(PB.java:8278)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope$1.parsePartialFrom(PB.java:8273)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
	at com.google.protobuf.AbstractParser.parsePartialDelimitedFrom(AbstractParser.java:262)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:275)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:280)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:49)
	at com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(GeneratedMessageV3.java:347)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope.parseDelimitedFrom(PB.java:3319)
	at bisq.network.p2p.network.Connection$InputHandler.run(Connection.java:802)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:86)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readRawBytesSlowPathOneChunk(CodedInputStream.java:2944)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readBytesSlowPath(CodedInputStream.java:2991)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readBytes(CodedInputStream.java:2419)
	at io.bisq.generated.protobuffer.PB$PreliminaryGetDataRequest.<init>(PB.java:8386)
	at io.bisq.generated.protobuffer.PB$PreliminaryGetDataRequest.<init>(PB.java:8335)
	at io.bisq.generated.protobuffer.PB$PreliminaryGetDataRequest$1.parsePartialFrom(PB.java:9060)
	at io.bisq.generated.protobuffer.PB$PreliminaryGetDataRequest$1.parsePartialFrom(PB.java:9055)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2399)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope.<init>(PB.java:1313)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope.<init>(PB.java:1257)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope$1.parsePartialFrom(PB.java:8278)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope$1.parsePartialFrom(PB.java:8273)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
	at com.google.protobuf.AbstractParser.parsePartialDelimitedFrom(AbstractParser.java:262)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:275)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:280)
	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:49)
	at com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(GeneratedMessageV3.java:347)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope.parseDelimitedFrom(PB.java:3319)
	at bisq.network.p2p.network.Connection$InputHandler.run(Connection.java:802)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope. ExecutionException java.util.concurrent.ExecutionException: bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope
	at bisq.network.p2p.network.SynchronizedProtoOutputStream.writeEnvelope(SynchronizedProtoOutputStream.java:59)
	at bisq.network.p2p.network.Connection.sendMessage(Connection.java:269)
	at bisq.network.p2p.network.NetworkNode.lambda$sendMessage$1(NetworkNode.java:265)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.util.concurrent.ExecutionException: bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at bisq.network.p2p.network.SynchronizedProtoOutputStream.writeEnvelope(SynchronizedProtoOutputStream.java:49)
	... 8 more
Caused by: bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelope(ProtoOutputStream.java:51)
	at bisq.network.p2p.network.SynchronizedProtoOutputStream.lambda$writeEnvelope$0(SynchronizedProtoOutputStream.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:2985)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:2917)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:2936)
	at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1337)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2735)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2708)
	at io.bisq.generated.protobuffer.PB$ProtectedStorageEntry.writeTo(PB.java:48660)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2783)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2759)
	at io.bisq.generated.protobuffer.PB$StorageEntryWrapper.writeTo(PB.java:49517)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2783)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2759)
	at io.bisq.generated.protobuffer.PB$GetDataResponse.writeTo(PB.java:9419)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2783)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2759)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope.writeTo(PB.java:2737)
	at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:98)
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelopeOrThrow(ProtoOutputStream.java:65)
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelope(ProtoOutputStream.java:48)
	... 6 more
bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope. ExecutionException java.util.concurrent.ExecutionException: bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope
	at bisq.network.p2p.network.SynchronizedProtoOutputStream.writeEnvelope(SynchronizedProtoOutputStream.java:59)
	at bisq.network.p2p.network.Connection.sendMessage(Connection.java:269)
	at bisq.network.p2p.network.NetworkNode.lambda$sendMessage$1(NetworkNode.java:265)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.util.concurrent.ExecutionException: bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at bisq.network.p2p.network.SynchronizedProtoOutputStream.writeEnvelope(SynchronizedProtoOutputStream.java:49)
	... 8 more
Caused by: bisq.network.p2p.network.BisqRuntimeException: Failed to write envelope
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelope(ProtoOutputStream.java:51)
	at bisq.network.p2p.network.SynchronizedProtoOutputStream.lambda$writeEnvelope$0(SynchronizedProtoOutputStream.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:2985)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.flushIfNotAvailable(CodedOutputStream.java:2980)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeInt32(CodedOutputStream.java:2659)
	at io.bisq.generated.protobuffer.PB$NetworkEnvelope.writeTo(PB.java:2731)
	at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:98)
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelopeOrThrow(ProtoOutputStream.java:65)
	at bisq.network.p2p.network.ProtoOutputStream.writeEnvelope(ProtoOutputStream.java:48)
	... 6 more

**Comment by ManfredKarrer** [comment]
Still relevant

**Comment by ManfredKarrer** [comment]
Still relevant
