### ISSUE TITLE
Unable to restore wallet from seed phrase.

### ISSUE THREAD

**Issue by gordonbrice** [bisq-network/bisq#2323]
Tried to restore my wallet from the seed phrase and got the attached error.  Also attached the log file.
![bisq-scrnshot](https://user-images.githubusercontent.com/2254839/51805672-21174280-223e-11e9-85c5-8af1f3e6c10f.PNG)
[bisq.log](https://github.com/bisq-network/bisq/files/2800405/bisq.log)

**Comment by ManfredKarrer** [comment]
Do you have the lastest Bisq version?

**Comment by gordonbrice** [comment]
Yes, I have the latest version.  I was able to restore from backup and do
Alt+J to recover my private keys.  BTW, my wallet was password protected
and I was able to do this without entering a password.  This seems like a
security hole.

-Regards
Gordon

**Comment by ManfredKarrer** [comment]
When you restore from seed the pw protection is removed.

**Comment by Mycelial1** [comment]
I've also got the same error. 
![bisq error](https://user-images.githubusercontent.com/34950746/52514443-cbe51480-2bdf-11e9-983c-e2ed7e2a7e31.PNG)

I have the latest version.

**Comment by ghost** [comment]
@Mycelial1 
- what is your OS ?
- do you have an AntiVirus AV running ?

**Comment by Mycelial1** [comment]
I'm using windows and there's no antivirus software running that I know of.

I tried to restore a wallet from generated from a different wallet app
(copay).

Is that 'restore' function different than 'import' wallet?

**Comment by ghost** [comment]
@Mycelial1 wrote:
> Is that 'restore' function different than 'import' wallet?

My understanding is that it is the same _restore_ function.
But _restoring_ means restoring from a Bisq wallet (primary usage)
while _importing_ means restoring from a non-Bisq wallet.

This will only work with compatible wallets, ie BIP44 format wallet, which is the format used by Bisq.
(see https://bisq.community/t/import-bitcoin-qt-wallet-to-bisq-or-another/4709)

However, I think this is to use only carefully.
The warning says "only for emergency cases".

**Comment by psyantyst** [comment]
I got the same error on Bisq v0.9.3. My wallet was backed up around Bisq version v0.5.1. The log file says:

```
[JavaFX Application Thread] ERROR b.c.b.s.WalletsSetup: Service failure from state: STARTING; failure={} java.io.IOException: org.bitcoinj.store.BlockStoreException: java.nio.channels.OverlappingFileLockException
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:492)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.bitcoinj.store.BlockStoreException: java.nio.channels.OverlappingFileLockException
	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:133)
	at bisq.core.btc.setup.WalletConfig.provideBlockStore(WalletConfig.java:329)
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:404)
	... 3 common frames omitted
Caused by: java.nio.channels.OverlappingFileLockException: null
	at java.base/sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at java.base/sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1191)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1160)
	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:106)
	... 5 common frames omitted
```

**Comment by oscarguindzberg** [comment]
@psyantyst Your issue is described here #2402 and should be fixed once https://github.com/bisq-network/bisq/pull/2403 is merged.

@gordonbrice @Mycelial1 You seem to have a different problem, but I still suggest to double check if the problem is still there once https://github.com/bisq-network/bisq/pull/2403 is merged.
