### ISSUE TITLE
Open Log File / Directory buttons wont work Ubuntu18

### ISSUE THREAD

**Issue by aejontargaryen** [bisq-network/bisq#2400]
just a bug report. may even be something with my personal system.
I _think_ they also had no response on ubuntu 16 & bisq 0.9.1. 
I had updated both around the same time while troubleshooting a (solved) connection [issue](https://github.com/bisq-network/bisq/issues/2374) recently.

**Comment by aejontargaryen** [comment]
log output after clicking buttons

```
Feb-09 07:10:50.634 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Market price for currency DRGL is not provided by the provider http://62nvujg5iou3vu3i.onion/. That is expected for currencies not listed at providers. 
Feb-09 07:10:50.637 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=DRGL, price=8.0E-7, timestampSec=0, isExternallyProvidedPrice=false) from provider http://62nvujg5iou3vu3i.onion/ after 1.989 sec. 
Feb-09 07:10:52.381 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 142 LAUNCHED  
Feb-09 07:10:52.381 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 135 CLOSED $58332DDDA15415CB3D13F5ECA3D54BE961B8C458~kaitlin,$C7946D9A192BBE44C1C8A926A8B135AC495D6636~t0adwarri0r,$24F97F98C45E4754655BE66799049763DAEE99CE~cosimaniehaus 
Feb-09 07:10:52.592 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 142 EXTENDED $D8A2D0080B0C73E1DC0EC9F33B497F64E5FB3F52~porthill 
Feb-09 07:10:52.846 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 142 EXTENDED $D8A2D0080B0C73E1DC0EC9F33B497F64E5FB3F52~porthill,$0677DF0B05ECDA2EF45F26C3332731043BB89AB8~niftyflorescaverat 
Feb-09 07:10:53.116 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 142 EXTENDED $D8A2D0080B0C73E1DC0EC9F33B497F64E5FB3F52~porthill,$0677DF0B05ECDA2EF45F26C3332731043BB89AB8~niftyflorescaverat,$171B71C46314F9BBBDEF73A70F9535CBBF3AFF9A~suthernfriend 
Feb-09 07:10:53.117 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 142 BUILT $D8A2D0080B0C73E1DC0EC9F33B497F64E5FB3F52~porthill,$0677DF0B05ECDA2EF45F26C3332731043BB89AB8~niftyflorescaverat,$171B71C46314F9BBBDEF73A70F9535CBBF3AFF9A~suthernfriend 
Feb-09 07:11:23.378 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 143 LAUNCHED  
Feb-09 07:11:23.378 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 136 CLOSED $D8A2D0080B0C73E1DC0EC9F33B497F64E5FB3F52~porthill,$CBD0D1BD110EC52963082D839AC6A89D0AE243E7~UV74S7mjxRcYVrGsAMw,$FF0F3170FF1FE4772FE16D7DA445C64FF3AFCD18~K25PACKWEB1 
Feb-09 07:11:23.667 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 143 EXTENDED $D8A2D0080B0C73E1DC0EC9F33B497F64E5FB3F52~porthill 
Feb-09 07:11:23.975 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 143 EXTENDED $D8A2D0080B0C73E1DC0EC9F33B497F64E5FB3F52~porthill,$AFFD147DBCC065A5CEF7258BC1367CC35855A431~Yahta4ee 
Feb-09 07:11:24.463 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 143 EXTENDED $D8A2D0080B0C73E1DC0EC9F33B497F64E5FB3F52~porthill,$AFFD147DBCC065A5CEF7258BC1367CC35855A431~Yahta4ee,$615ABEA2DE76EB3760BC51E7306BAA59F15CD8F2~Cloud 
Feb-09 07:11:24.463 [TorControlParser] DEBUG o.b.n.tor.Tor: CircuitStatus: 143 BUILT $D8A2D0080B0C73E1DC0EC9F33B497F64E5FB3F52~porthill,$AFFD147DBCC065A5CEF7258BC1367CC35855A431~Yahta4ee,$615ABEA2DE76EB3760BC51E7306BAA59F15CD8F2~Cloud 
Feb-09 07:11:48.662 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://xc3nh4juf2hshy7e.onion/ 60.014 sec. after last request 
Feb-09 07:11:51.657 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Market price for currency DRGL is not provided by the provider http://62nvujg5iou3vu3i.onion/. That is expected for currencies not listed at providers. 
Feb-09 07:11:51.659 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: Received new MarketPrice(currencyCode=DRGL, price=8.0E-7, timestampSec=0, isExternallyProvidedPrice=false) from provider http://62nvujg5iou3vu3i.onion/ after 2.997 sec```

**Comment by ripcurlx** [comment]
@HarryMacfinned Does it work for you on your systems?

**Comment by ghost** [comment]
@ripcurlx yes, absolutely, both buttons work nicely
(Debian Stretch 9.7 - Gnome 3.22.2 - Bisq v0.9.3)

**Comment by ripcurlx** [comment]
@aejontargaryen All other buttons work normally? Do you get a roll over effect for these two buttons?
Unfortunately the log doesn't give me any hint why it won't work.

**Comment by ManfredKarrer** [comment]
I assume the OS side calls to open a directory or file might fail on some Linux systems. Can any dev working on Linux test that? And if you are able to reproduce research alternative methods to open a directory or file.

**Comment by devinbileck** [comment]
I confirmed that it worked for me on Ubuntu 18.04. However, I did notice some errors in the console:
```
Trying to exec:
   cmd = kde-open
   args = %s
   %s = /home/user/.local/share/Bisq
Error running command.
java.io.IOException: Cannot run program "kde-open": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:635)
	at java.base/java.lang.Runtime.exec(Runtime.java:494)
	at bisq.common.util.DesktopUtil.runCommand(DesktopUtil.java:152)
	at bisq.common.util.DesktopUtil.openSystemSpecific(DesktopUtil.java:55)
	at bisq.common.util.DesktopUtil.open(DesktopUtil.java:40)
	at bisq.common.util.Utilities.openFile(Utilities.java:254)
	at bisq.desktop.main.account.content.backup.BackupView.lambda$openFileOrShowWarning$3(BackupView.java:157)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8879)
	at javafx.scene.control.Button.fire(Button.java:200)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:339)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:270)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 58 more
Trying to exec:
   cmd = gnome-open
   args = %s
   %s = /home/user/.local/share/Bisq
Error running command.
java.io.IOException: Cannot run program "gnome-open": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:635)
	at java.base/java.lang.Runtime.exec(Runtime.java:494)
	at bisq.common.util.DesktopUtil.runCommand(DesktopUtil.java:152)
	at bisq.common.util.DesktopUtil.openSystemSpecific(DesktopUtil.java:56)
	at bisq.common.util.DesktopUtil.open(DesktopUtil.java:40)
	at bisq.common.util.Utilities.openFile(Utilities.java:254)
	at bisq.desktop.main.account.content.backup.BackupView.lambda$openFileOrShowWarning$3(BackupView.java:157)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8879)
	at javafx.scene.control.Button.fire(Button.java:200)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:339)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:270)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 58 more
Trying to exec:
   cmd = xdg-open
   args = %s
   %s = /home/user/.local/share/Bisq
Process is running.
```

**Comment by aejontargaryen** [comment]
@ripcurlx it does show hover & click actions for both buttons, but no action beyond that i can find. 
I dont know how to access the command log like @devinbileck shows... is there a shortcut for that? i installed w/ .deb pkg this time.

**Comment by ghost** [comment]
@aejontargaryen 
What is your graphic interface ?
(Mine is Gnome 3.22.2)

**Comment by aejontargaryen** [comment]
@HarryMacfinned 
Gnome 3.28.2

**Comment by devinbileck** [comment]
@aejontargaryen I was running from master and launched Bisq from command line, which those errors get output to (I dont think they get output to the bisq log file). I also just tried running release v0.9.3 and was able to open the log file and directory.

**Comment by aejontargaryen** [comment]
must be my system somehow. I'll try building from source and checking CLI when i can get a chance

**Comment by devinbileck** [comment]
@aejontargaryen can you manually run the command `xdg-open`?
See [here](https://github.com/bisq-network/bisq/blob/fce7f45a4131773764a57391aca608a1b3657599/common/src/main/java/bisq/common/util/DesktopUtil.java#L57) where it tries a series of commands to open a file.

**Comment by aejontargaryen** [comment]
i ended up doing a clean reinstall of OS. everything worked correctly afterwards. thanks guys
