### ISSUE TITLE
Generate native installer binaries

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq#243]
- [x] OS X
- [x] Linux
- [x] Windows

**Comment by cbeams** [comment]
Supersedes #100, #108, #66, #37, #18

**Comment by ManfredKarrer** [comment]
For Windows and Mac there are issues with the path to the javapackager. I cannot create binaries. Are the binaries containing the jre? On linux i build a binary but it does not contain the jre.

On linux I get:
14:11:47: Executing external task 'packageNative'...
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileJava
:processResources
:classes
:shadowJar
:packageNative
No base JDK. Package will use system JRE.
Bundler DEB Installer skipped because of a configuration problem: Main application jar is missing.  
Advice to fix: Make sure to use fx:jar task to create main application jar.

**Comment by ManfredKarrer** [comment]
I change in the mac.sh:
    -Bruntime="$JAVA_HOME/bin/javapackager" \
But failes as well.

On Mac I get: 

00:04:53: Executing external task 'packageNative'...
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileJava
:processResources
:classes
:shadowJar
/Users/mk/Documents/_intellij/bitsquare/package/mac.sh: line 10: javapackager: command not found
:packageNative FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':packageNative'.
  
  > Process 'command '/Users/mk/Documents/_intellij/bitsquare/package/mac.sh'' finished with non-zero exit value 127
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.673 secs
Process 'command '/Users/mk/Documents/_intellij/bitsquare/package/mac.sh'' finished with non-zero exit value 127
00:05:13: External task execution finished 'packageNative'.

**Comment by cbeams** [comment]
> -Bruntime="$JAVA_HOME/bin/javapackager" \

Hm.. that wouldn't work in any case. You'd want to change the path to `javapackager` itself, e.g. from:

```
javapackager \
    -deploy \
    [...]
```

to:

```
$JAVA_HOME/bin/javapackager \
    -deploy \
    [...]
```

Does that work? Could just add `$JAVA_HOME/bin` to your `$PATH` as well...

**Comment by ManfredKarrer** [comment]
The path problem is now gone but I still cannot get a binary (Main application jar is missing).

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources
:classes
:shadowJar
:packageNative
Using base JDK at: /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/../..
Bundler DMG Installer skipped because of a configuration problem: Main application jar is missing.  
Advice to fix: Make sure to use fx:jar task to create main application jar.

BUILD SUCCESSFUL

**Comment by cbeams** [comment]
I get the same error. Looking into it now.

**Comment by cbeams** [comment]
Fixed, see 356b76a. Sometimes the order in which things happen can cause tricky issues with Gradle.

**Comment by ManfredKarrer** [comment]
Thanks! On mac it works now!
Just tested on Ubuntu but get that error:

kaoli@kaoli-VirtualBox:~/IdeaProjects/bitsquare$ ./gradlew packageNative
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:shadowJar UP-TO-DATE
:packageNative
No base JDK. Package will use system JRE.
Debian packages should specify a license.  The absence of a license will cause some linux distributions to complain about the quality of the application.
java.io.IOException: Cannot run program "fakeroot" (in directory "/tmp/fxbundler280592458788729816/images/linux-deb.image"): error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:146)
    at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
    at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
    at com.oracle.tools.packager.linux.LinuxDebBundler.buildDeb(LinuxDebBundler.java:577)
    at com.oracle.tools.packager.linux.LinuxDebBundler.bundle(LinuxDebBundler.java:278)
    at com.oracle.tools.packager.linux.LinuxDebBundler.execute(LinuxDebBundler.java:629)
    at com.sun.javafx.tools.packager.PackagerLib.generateNativeBundles(PackagerLib.java:511)
    at com.sun.javafx.tools.packager.PackagerLib.generateDeploymentPackages(PackagerLib.java:476)
    at com.sun.javafx.tools.packager.Main.main(Main.java:460)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 9 more
Error: Bundler "DEB Installer" (deb) failed to produce a bundle.
:packageNative FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':packageNative'.
  
  > Process 'command '/home/kaoli/IdeaProjects/bitsquare/package/linux.sh'' finished with non-zero exit value 255
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by ManfredKarrer** [comment]
Tested it again. JAVA_HOME is set but same error...

**Comment by ManfredKarrer** [comment]
On Win 7 I get those errors. java path is set.

I adopted the windows.bat to that to fit my environment:
%JAVA_PATH%\bin\javapackager.exe -deploy -BappVersion=0.1.0 -native exe -name Bitsquare -title Bitsquare -vendor Bitsquare -outdir build -appclass io.bitsquare.app.gui.Main -srcfiles .\build\libs\bitsquare-0.1.0-SNAPSHOT-all.jar -outfile Bitsquare -Bruntime="%JAVA_PATH%..\jre1.8.0_25"

C:\Users\mk\dev\bitsquare>gradlew packageNative --stacktrace
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:shadowJar UP-TO-DATE
:packageNative
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

'Bitsquare' is not recognized as an internal or external command,
C:\Users\mk\dev\bitsquare>C:\Program Files\Java\jdk1.8.0_25\bin\javapackager.exe
 -deploy -BappVersion=0.1.0 -native exe -name Bitsquare -title Bitsquare -vendor

operable program or batch file.
'-outfile' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\mk\dev\bitsquare>Bitsquare -outdir build -appclass io.bitsquare.app.gui
.Main -srcfiles .\build\libs\bitsquare-0.1.0-SNAPSHOT-all.jar

C:\Users\mk\dev\bitsquare>-outfile Bitsquare -Bruntime="c:\Program Files\Java\jr
e1.8.0_25"
:packageNative FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':packageNative'.
  
  > Process 'command 'C:\Users\mk\dev\bitsquare/package/windows.bat'' finished wit
  > h non-zero exit value 1
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':package
  Native'.
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecuteActions(ExecuteActionsTaskExecuter.java:69)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecute(ExecuteActionsTaskExecuter.java:46)
      at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
  uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
      at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
  ute(SkipUpToDateTaskExecuter.java:64)
      at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
  e(ValidatingTaskExecuter.java:58)
      at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
  ter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
      at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
  .execute(SkipTaskWithNoActionsExecuter.java:52)
      at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
  e(SkipOnlyIfTaskExecuter.java:53)
      at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
  .execute(ExecuteAtMostOnceTaskExecuter.java:43)
      at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailur
  e(AbstractTask.java:305)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
  orker.executeTask(AbstractTaskPlanExecutor.java:79)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
  orker.processTask(AbstractTaskPlanExecutor.java:63)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
  orker.run(AbstractTaskPlanExecutor.java:51)
      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
  tTaskPlanExecutor.java:23)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
  ltTaskGraphExecuter.java:88)
      at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
  ExecutionAction.java:29)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
  r.java:62)
      at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExec
  uter.java:23)
      at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecu
  ter.java:68)
      at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
  ecutionAction.java:32)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
  r.java:62)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
  r.java:55)
      at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
  GradleLauncher.java:149)
      at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
  Launcher.java:106)
      at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
  cher.java:86)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
  troller.run(InProcessBuildActionExecuter.java:80)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
  a:33)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
  a:24)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
  ssBuildActionExecuter.java:36)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
  ssBuildActionExecuter.java:26)
      at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
      at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
  a:171)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
  execute(CommandLineActionFactory.java:237)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
  execute(CommandLineActionFactory.java:210)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
  meValidationAction.java:35)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
  meValidationAction.java:24)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
  CommandLineActionFactory.java:206)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
  CommandLineActionFactory.java:169)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
  ortingAction.java:33)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
  ortingAction.java:22)
      at org.gradle.launcher.Main.doAction(Main.java:33)
      at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
  trap.java:54)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
  ava:35)
      at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
      at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja
  va:30)
      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
  Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Users
  \mk\dev\bitsquare/package/windows.bat'' finished with non-zero exit value 1
      at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNo
  rmalExitValue(DefaultExecHandle.java:365)
      at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecActi
  on.java:31)
      at org.gradle.api.tasks.AbstractExecTask.exec(AbstractExecTask.java:54)
      at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
  actory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
  actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
  actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
      at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
  ctTask.java:579)
      at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
  ctTask.java:562)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecuteAction(ExecuteActionsTaskExecuter.java:80)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecuteActions(ExecuteActionsTaskExecuter.java:61)
      ... 47 more

BUILD FAILED

**Comment by cbeams** [comment]
Thx

**Comment by cbeams** [comment]
Closing this issue, as it is basically complete. Native installer binaries for all three platforms can be created using `gradle packageNative`. We just need to fix the missing dll issue on Windows, and I've created #297 to address that. Also relates to #108.

**Comment by ghost** [comment]
As far as I know, javapackager doesn't allow to build Windows binaries under GNU Linux. Maybe you could give a try to my own tool, JNDT.

**Comment by ManfredKarrer** [comment]
We have native installers for all major OS including windoze
