### ISSUE TITLE
Two external screens on Ubuntu 18.xx result in blank window - JavaFX IllegalArgumentException: Window must not be zero

### ISSUE THREAD

**Issue by tomekit** [bisq-network/bisq#2452]
Tried to run Bisq on my Ubuntu 18.10, but have failed miserably.

Downloaded `deb` package from here: https://bisq.network/downloads/
Installed on my machine, then ran using the Search tool. Blank window has appeared, so I've ran the Bisq from command line, the blank window appears and here is the output:
```
/opt/Bisq 
15:42 $ ./Bisq
Feb-21 15:43:47.371 [main] INFO  bisq.core.setup.CoreSetup: 


Log files under: /home/user/.local/share/Bisq/bisq 
Feb-21 15:43:47.383 [main] INFO  bisq.common.util.Utilities: System info: os.name=Linux; os.version=4.18.0-15-generic; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
Feb-21 15:43:47.539 [main] INFO  bisq.common.app.Version: Version{VERSION=0.9.3, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Feb-21 15:43:47.540 [main] INFO  bisq.core.setup.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-0.9.3-all.jar 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/opt/Bisq/app/desktop-0.9.3-all.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Feb-21 15:43:48.756 [JavaFX Application Thread] INFO  b.c.p.ProvidersRepository: Selected provider baseUrl=http://44mgyoe2b6oqiytt.onion/, providerList=[http://44mgyoe2b6oqiytt.onion/, http://5bmpx76qllutpcyp.onion/, http://ceaanhbvluug4we6.onion/, http://xc3nh4juf2hshy7e.onion/, http://62nvujg5iou3vu3i.onion/] 
Feb-21 15:43:49.000 [JavaFX Application Thread] INFO  b.c.dao.node.full.RpcService: Version of btcd-cli4j library: 0.5.8.4 
Feb-21 15:43:49.782 [JavaFX Application Thread] ERROR bisq.desktop.app.BisqApp: Error during app init java.lang.IllegalArgumentException: Window must not be zero
	at java.desktop/sun.awt.X11.XAtom.checkWindow(XAtom.java:774)
	at java.desktop/sun.awt.X11.XAtom.getAtomData(XAtom.java:465)
	at java.desktop/sun.awt.X11.XToolkit.getWorkArea(XToolkit.java:805)
	at java.desktop/sun.awt.X11.XToolkit.getInsets(XToolkit.java:881)
	at java.desktop/sun.awt.X11.XToolkit.getScreenInsets(XToolkit.java:869)
	at java.desktop/sun.java2d.SunGraphicsEnvironment.getUsableBounds(SunGraphicsEnvironment.java:274)
	at java.desktop/sun.awt.X11GraphicsEnvironment.getXineramaWindowBounds(X11GraphicsEnvironment.java:390)
	at java.desktop/sun.awt.X11GraphicsEnvironment.getMaximumWindowBounds(X11GraphicsEnvironment.java:314)
	at bisq.desktop.app.BisqApp.createAndConfigScene(BisqApp.java:213)
	at bisq.desktop.app.BisqApp.startApplication(BisqApp.java:136)
	at bisq.desktop.app.BisqAppMain.startApplication(BisqAppMain.java:131)
	at bisq.core.app.BisqExecutable.onApplicationLaunched(BisqExecutable.java:213)
	at bisq.desktop.app.BisqAppMain.onApplicationLaunched(BisqAppMain.java:99)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)

java.lang.IllegalArgumentException: Window must not be zero
	at java.desktop/sun.awt.X11.XAtom.checkWindow(XAtom.java:774)
	at java.desktop/sun.awt.X11.XAtom.getAtomData(XAtom.java:465)
	at java.desktop/sun.awt.X11.XToolkit.getWorkArea(XToolkit.java:805)
	at java.desktop/sun.awt.X11.XToolkit.getInsets(XToolkit.java:881)
	at java.desktop/sun.awt.X11.XToolkit.getScreenInsets(XToolkit.java:869)
	at java.desktop/sun.java2d.SunGraphicsEnvironment.getUsableBounds(SunGraphicsEnvironment.java:274)
	at java.desktop/sun.awt.X11GraphicsEnvironment.getXineramaWindowBounds(X11GraphicsEnvironment.java:390)
	at java.desktop/sun.awt.X11GraphicsEnvironment.getMaximumWindowBounds(X11GraphicsEnvironment.java:314)
	at bisq.desktop.app.BisqApp.createAndConfigScene(BisqApp.java:213)
	at bisq.desktop.app.BisqApp.startApplication(BisqApp.java:136)
	at bisq.desktop.app.BisqAppMain.startApplication(BisqAppMain.java:131)
	at bisq.core.app.BisqExecutable.onApplicationLaunched(BisqExecutable.java:213)
	at bisq.desktop.app.BisqAppMain.onApplicationLaunched(BisqAppMain.java:99)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
Feb-21 15:43:49.784 [JavaFX Application Thread] WARN  bisq.desktop.app.BisqApp: Scene not available yet, we create a new scene. The bug might be caused by an exception in a constructor or by a circular dependency in Guice. throwable=java.lang.IllegalArgumentException: Window must not be zero 
```

**Comment by ripcurlx** [comment]
@tomekit Are you using a dual-window setup? There was a known bug which should be fixed already in the Java version we are using (10.0.2), but maybe that's not the case.

https://bugs.openjdk.java.net/browse/JDK-8020443

**Comment by ripcurlx** [comment]
@HarryMacfinned Any chance that you are running Ubuntu 18 as well for testing? Just to see if it is a problem for everyone who is running Ubuntu 18.

**Comment by ghost** [comment]
@ripcurlx ,
Sorry but I have only Debian Stretch 9.8 machines (+last gnome), and Bisq v0.9.3 works fine on it.

**Comment by ghost** [comment]
@tomekit 
Bisq next version (v0.9.4) will be out quite soon,
please retry when this new version is out and tell us how it works.

**Comment by tomekit** [comment]
Indeed that's related to multi-screen setup. On one display it does start OK. 
Thanks for help and if you want me to test this on dual / triple window setup on Ubuntu 18.10 once this get fixed let me know I am happy to check it for you.

**Comment by tomekit** [comment]
@HarryMacfinned Got v.0.9.4. No luck.
Still getting
`Feb-23 19:21:25.289 [JavaFX Application Thread] WARN  bisq.desktop.app.BisqApp: Scene not available yet, we create a new scene. The bug might be caused by an exception in a constructor or by a circular dependency in Guice. throwable=java.lang.IllegalArgumentException: Window must not be zero `

EDIT: Ubuntu 18.04 LTS is affected as well.

**Comment by ghost** [comment]
@tomekit , thanks for the return.
Was it with one screen, or with multi-screen ?

**Comment by tomekit** [comment]
@HarryMacfinned This does seem to happen when I've got 2 external screens connected to my laptop. It actually does seem to work OK on 1 external screen (whether VGA or HDMI) + 1 laptop built-in.
This applies to Ubuntu 18.04. Haven't tested if Ubuntu 18.10 works with just 1 external screen.

**Comment by m52go** [comment]
Sounds like a 2-external-screen thing...I tested earlier with 1 external + 1 built-in on 18.04 and everything worked fine.

**Comment by devinbileck** [comment]
I know where this is coming from, just not sure why. I guess Java still has some issues with multi-screen environments. I can add some exception handling to hopefully avoid this issue.

**Comment by devinbileck** [comment]
@tomekit just curious, are your external screens configured as a single display, like https://en.wikipedia.org/wiki/Xinerama?

**Comment by tomekit** [comment]
@devinbileck 
Screens are configured as a separate displays with standard Ubuntu `Displays` settings. 
They are not mirrors nor single merged display like `Xinerama`. Nothing fancy, just standard usage.
