### ISSUE TITLE
Trade testing results

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#261]
Trade testing results

Setup:
OS: OSX
Mode: Port forwarding.
Extra info: 2 clients connected wiht different internet access 

Repeated trades seem to work.
After placing 2 open offers and 1 was taken, the other offer was also removed from the DHT.
Also a new created offer is not displayed in the DHT. 
Many repeated warnings on the server and client logs (same):

16:43:13.341 [NETTY-TOMP2P - worker-client/server - -1-2] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
    at io.netty.buffer.AbstractReferenceCountedByteBuf.retain(AbstractReferenceCountedByteBuf.java:63) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
    at io.netty.buffer.AbstractDerivedByteBuf.retain(AbstractDerivedByteBuf.java:38) ~[netty-buffer-4.0.24.Final.jar:4.0.24.Final]
    at net.tomp2p.storage.DataBuffer.<init>(DataBuffer.java:53) ~[tomp2p-core-5.0-Alpha.542a1a8-SNAPSHOT.jar:na]

On windows we (me and Richard) cannot get port forwarding mode.

**Comment by ManfredKarrer** [comment]
@remyers @stevemyers 
The port forwarding problmes on windows are probably related to interface selection of localhost.
See: https://github.com/tomp2p/TomP2P/issues/61
ON mac i have first eth then localhost, on windows locashost is the first, and it seems that this is taken and cause a binding exception.
