### ISSUE TITLE
Voting on proposal threw a NullPointerException

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#2627]
I wasn't able to reproduce it again, but somehow the selected Item was reset (maybe through an update in the background).
```
java.lang.NullPointerException
	at bisq.desktop.main.dao.governance.proposals.ProposalsView.onAccept(ProposalsView.java:432)
	at bisq.desktop.main.dao.governance.proposals.ProposalsView.lambda$showVoteOnProposalWindow$9(ProposalsView.java:343)
	at java.base/java.util.Optional.ifPresent(Optional.java:172)
	at bisq.desktop.main.overlays.windows.SelectProposalWindow.lambda$addContent$2(SelectProposalWindow.java:192)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
´´´

**Comment by ManfredKarrer** [comment]
I assume getBallotListItem() is null. Not sure how that can happen and how to deal with it. We shoudl set selectedItem @Nullable and use it directly instead of getBallotListItem().

**Comment by devinbileck** [comment]
I just ran into this issue as well. Was voting in the proposal popup window. Had to close and reopen the popup to set my vote.

**Comment by ManfredKarrer** [comment]
Do you know how to reproduce it?

**Comment by devinbileck** [comment]
No. Just stumbled upon it once so far.
