### ISSUE TITLE
Error is encountered when taking offer using BSQ as fees with insufficient balance 

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#2678]
When attempting to take an offer using BSQ as trading fees but insufficient BSQ balance, the following error is encountered. In my case I had 2 BSQ available.
![image](https://user-images.githubusercontent.com/603793/55778047-a8f7a500-5a56-11e9-888d-e3bf1284fc0c.png)

This is a confusing error message as it states to restart the application and check the network connection, as well as reporting a bug.

Perhaps the UI should prevent the user from selecting BSQ as trading fees in the first place if there is insufficient balance.

**Comment by ManfredKarrer** [comment]
Can you post the logs where the error happens, so its easier to see which popup causes it. The error popups automatically shows that generice info. We should show a warn popup then.

I assum the BSQ fee was 0.38 BSQ.
Better would be to check if available BSQ does not resul tin dust output (e.g. > 5.46+fee)

**Comment by devinbileck** [comment]
```
java.lang.IllegalArgumentException: The change output of 1.85 BSQ is below the min. dust value of 5.46. At least 5.61 BSQ is needed for this transaction
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at bisq.core.btc.wallet.BsqWalletService.addInputsAndChangeOutputForTx(BsqWalletService.java:565)
	at bisq.core.btc.wallet.BsqWalletService.getPreparedBurnFeeTx(BsqWalletService.java:538)
	at bisq.core.btc.wallet.BsqWalletService.getPreparedBurnFeeTx(BsqWalletService.java:532)
	at bisq.core.trade.protocol.tasks.taker.CreateTakerFeeTx.run(CreateTakerFeeTx.java:84)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.handleComplete(TaskRunner.java:86)
	at bisq.common.taskrunner.Task.complete(Task.java:58)
	at bisq.core.trade.protocol.tasks.taker.TakerSelectMediator.run(TakerSelectMediator.java:60)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.handleComplete(TaskRunner.java:86)
	at bisq.common.taskrunner.Task.complete(Task.java:58)
	at bisq.core.trade.protocol.tasks.taker.TakerVerifyMakerFeePayment.run(TakerVerifyMakerFeePayment.java:43)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.handleComplete(TaskRunner.java:86)
	at bisq.common.taskrunner.Task.complete(Task.java:58)
	at bisq.core.trade.protocol.tasks.taker.TakerVerifyMakerAccount.run(TakerVerifyMakerAccount.java:44)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.run(TaskRunner.java:60)
	at bisq.core.trade.protocol.SellerAsTakerProtocol.takeAvailableOffer(SellerAsTakerProtocol.java:119)
	at bisq.core.trade.SellerAsTakerTrade.takeAvailableOffer(SellerAsTakerTrade.java:107)
	at bisq.core.trade.TradeManager.createTrade(TradeManager.java:471)
	at bisq.core.trade.TradeManager.lambda$onTakeOffer$13(TradeManager.java:416)
	at bisq.core.offer.Offer.lambda$checkOfferAvailability$0(Offer.java:145)
	at bisq.core.offer.availability.OfferAvailabilityProtocol.lambda$handleOfferAvailabilityResponse$3(OfferAvailabilityProtocol.java:129)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:75)
	at bisq.common.taskrunner.TaskRunner.handleComplete(TaskRunner.java:86)
	at bisq.common.taskrunner.Task.complete(Task.java:58)
	at bisq.core.offer.availability.tasks.ProcessOfferAvailabilityResponse.run(ProcessOfferAvailabilityResponse.java:69)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.run(TaskRunner.java:60)
	at bisq.core.offer.availability.OfferAvailabilityProtocol.handleOfferAvailabilityResponse(OfferAvailabilityProtocol.java:133)
	at bisq.core.offer.availability.OfferAvailabilityProtocol.lambda$new$0(OfferAvailabilityProtocol.java:74)
	at bisq.network.p2p.P2PService.lambda$onMessage$8(P2PService.java:410)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.P2PService.onMessage(P2PService.java:409)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:344)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:344)
	at bisq.network.p2p.network.Connection.lambda$onMessage$3(Connection.java:383)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:383)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:844)
Apr-09 22:53:15.527 [JavaFX Application Thread] ERROR bisq.common.taskrunner.Task: An error occurred at task: CreateTakerFeeTx
Exception message: The change output of 1.85 BSQ is below the min. dust value of 5.46. At least 5.61 BSQ is needed for this transaction 
```
