### ISSUE TITLE
Not sure, software asked to report.

### ISSUE THREAD

**Issue by inpharmaticist** [bisq-network/bisq#2754]
[Uploading bisq error.txt…]()

**Comment by ghost** [comment]
The link leads to no logfile.

**Comment by inpharmaticist** [comment]
[bisq error.txt](https://github.com/bisq-network/bisq/files/3100191/bisq.error.txt)

**Comment by ManfredKarrer** [comment]
@oscarguindzberg Could you have a look to the log file, there are many connection failed logs. We got another similar report recently. Any idea what can cause that?

**Comment by oscarguindzberg** [comment]
I had a look at the logs.
I see all the "[BlockingClient network thread for xxxxx.onion:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: xxxxx.onion:8333".
I see these error lines on my Bisq node too.
I tried to figure out what could be wrong, but could not find anything.
So,
- tor network instability could be the reason, #2773 was fixed by trying again after an OS restart.
- "Use bitcoinj with connection handling audit fixes" PR (https://github.com/bisq-network/bisq/pull/2618) was not merged. Although there is no direct fix for this problem, I would like to see whether we keep seeing this problem when that PR is merged.

**Comment by ghost** [comment]
BlockingClient
is that not the banned clients because of the running scam ?

**Comment by oscarguindzberg** [comment]
@HarryMacfinned BlockingClient is a bitcoinj class unrelated to the scam.

**Comment by oscarguindzberg** [comment]
@inpharmaticist were you able to get your funds back?

**Comment by inpharmaticist** [comment]
I don't think I lost any funds on the transaction. Everything worked after I saw the error to submit the bug (I'm not a programmer and new to github so I'm out of my element here).  I just submitted because I got the alert. I believe I am still whole though.

**Comment by oscarguindzberg** [comment]
I will post what I could find out:

This is the relevant part of the logs 
```
Apr-19 21:22:11.782 [JavaFX Application Thread] INFO  b.c.a.DisputeManager: Received DisputeResultMessage with tradeId PVByYn-15ccdcc8-436f-42a7-a638-ea093047ba61-097 and uid bb4145dc-e013-4553-bbb0-55be3613dbb0 
Apr-19 21:22:11.788 [JavaFX Application Thread] ERROR b.c.b.w.BtcWalletService: multiSigAddressEntry not found for trade ID=PVByYn-15ccdcc8-436f-42a7-a638-ea093047ba61-097.
We try to find the keypair in the wallet with the pubKey we found in the trade data. 
Apr-19 21:22:11.794 [JavaFX Application Thread] INFO  b.c.b.w.TradeWalletService: buyerPubKey ECKey{pub HEX=0324daeba5d98333b613f7da0d8da590ffa5924d5757d63e20e47d3abf87c00d92, isEncrypted=false, isPubKeyOnly=true} 
Apr-19 21:22:11.794 [JavaFX Application Thread] INFO  b.c.b.w.TradeWalletService: sellerPubKey ECKey{pub HEX=02b82184ea78e699fbffc9eb06627c5199a858294d2e1d44460a722bfdf03f7c15, isEncrypted=false, isPubKeyOnly=true} 
Apr-19 21:22:11.799 [JavaFX Application Thread] INFO  b.c.b.w.TradeWalletService: arbitratorPubKey ECKey{pub HEX=028bb8f79b59d6e359a4ee179db6c68a67502639e6061f5e04b913ccc09e4d7b4f, isEncrypted=false, isPubKeyOnly=true} 
Apr-19 21:22:11.821 [JavaFX Application Thread] INFO  b.c.b.w.WalletService: 
disputed payoutTx:
  9e747c4b20afae1ef5bfcc722d719b8e467edce8480eac6bb200f0f18fdd6960
     in   0[] PUSHDATA(72)[3045022100e8bd6c69db498c6382a1d602557d633fbe1e10e186b9484cdb002d53574fb33502204137d23956bc5270bbba4b9503a2730c1428a2a0c5990c0a2492872c4b6163b501] PUSHDATA(71)[304402203673ddae8dc5030588b1af61a20186674bcda6784c1603f9d8b0c65c33781b17022052a3b0be5fa095bc3cb2e562d31bffb87ae24c059f03581ed328fbae1d72a47f01] PUSHDATA1[5221028bb8f79b59d6e359a4ee179db6c68a67502639e6061f5e04b913ccc09e4d7b4f2102b82184ea78e699fbffc9eb06627c5199a858294d2e1d44460a722bfdf03f7c15210324daeba5d98333b613f7da0d8da590ffa5924d5757d63e20e47d3abf87c00d9253ae] 0.1275256 BTC (12752560)
          outpoint:9000408466e711723bf127838f190e86360e364c49de7452d05752fbc3d24a12:0 hash160:d24f40fc8829ed612537d2b74ad5ab166e598a28
     out  DUP HASH160 PUSHDATA(20)[fc47d87a9c2a98207fdd2d90aef802ea7685d416] EQUALVERIFY CHECKSIG 0.003725 BTC (372500) ScriptPubKey: 76a914fc47d87a9c2a98207fdd2d90aef802ea7685d41688ac Address:1PzwMGE7ZmfigyU6SfuYfyGdV35oTYqhTi 
     out  DUP HASH160 PUSHDATA(20)[e5e31b91fd345a9ae6da7f333e8a4e214862adb5] EQUALVERIFY CHECKSIG 0.0751 BTC (7510000) ScriptPubKey: 76a914e5e31b91fd345a9ae6da7f333e8a4e214862adb588ac Address:1MxXoeciFFU6iJ3Ft1khPdERo3accb49Ai 
     fee  0.0487006 BTC for 374 bytes (13021 Satoshi/Byte)
     prps UNKNOWN
 
Apr-19 21:22:11.824 [JavaFX Application Thread] ERROR b.c.b.w.WalletService: Script resulted in a non-true stack: [[B@1e725ffe, [B@1508522, [B@7f0254bf] 
Apr-19 21:22:11.827 [JavaFX Application Thread] ERROR b.c.a.DisputeManager: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@1e725ffe, [B@1508522, [B@7f0254bf] 
Apr-19 21:22:11.833 [JavaFX Application Thread] INFO  b.c.a.DisputeManager: Send AckMessage for DisputeCommunicationMessage to peer my4t3kedin7k63a6.onion:9999. tradeId=PVByYn-15ccdcc8-436f-42a7-a638-ea093047ba61-097, uid=a185ee8f-8763-4618-b901-882a319ea544 
Apr-19 21:22:11.833 [JavaFX Application Thread] ERROR b.c.a.DisputeManager: AckMessage for DisputeCommunicationMessage failed. Peer my4t3kedin7k63a6.onion:9999. tradeId=PVByYn-15ccdcc8-436f-42a7-a638-ea093047ba61-097, uid=a185ee8f-8763-4618-b901-882a319ea544, errorMessage=We did not send the EncryptedMailboxMessage because the peer does not support the capability. 
Apr-19 21:22:11.834 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Apr-19 21:22:11.834 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@1e725ffe, [B@1508522, [B@7f0254bf] 
Apr-19 21:22:11.834 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.RuntimeException 
Apr-19 21:22:11.836 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.RuntimeException: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@1e725ffe, [B@1508522, [B@7f0254bf]
	at bisq.core.arbitration.DisputeManager.onDisputeResultMessage(DisputeManager.java:1005)
	at bisq.core.arbitration.DisputeManager.dispatchMessage(DisputeManager.java:329)
	at bisq.core.arbitration.DisputeManager.lambda$applyMessages$13(DisputeManager.java:272)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.core.arbitration.DisputeManager.applyMessages(DisputeManager.java:269)
	at bisq.core.arbitration.DisputeManager.tryApplyMessages(DisputeManager.java:259)
	at bisq.core.arbitration.DisputeManager.lambda$new$0(DisputeManager.java:159)
	at bisq.network.p2p.P2PService.lambda$onMessage$8(P2PService.java:410)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.P2PService.onMessage(P2PService.java:409)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:344)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:344)
	at bisq.network.p2p.network.Connection.lambda$onMessage$3(Connection.java:383)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:383)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:844)
 ````


- `multiSigAddressEntry not found for trade` means the AddressEntry the code is looking for could not be found on the db and the private key will be taken from the bitcoinj wallet.
- The utxo trying to be spent is 9000408466e711723bf127838f190e86360e364c49de7452d05752fbc3d24a12 which was mined on March 21st (1 month before the github issue was created) and is a P2SH-P2WPKH (bitcoinj/bisq does not know how to spend this type of script yet). It was spent on March 21st a couple of minutes later to a segwit bech32 address (not available to send to bech32 addresses from bisq yet).
- The tx that is being built has a miner fee of 13021 Satoshi/Byte, while a super high fee during peak days is 300 satoshis/byte.
- I guess 9000408466e711723bf127838f190e86360e364c49de7452d05752fbc3d24a12 is a tx totally unrelated to bisq. 
- `input.verify(input.getConnectedOutput())` is probably the cause for `ScriptException: Script resulted in a non-true stack`.
