### ISSUE TITLE
Error at traderSignAndFinalizeDisputedPayoutTx 

### ISSUE THREAD

**Issue by Ghostx74** [bisq-network/bisq#2808]
Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: OP_EQUALVERIFY: non-equal data
[bisq.log](https://github.com/bisq-network/bisq/files/3145693/bisq.log)

**Comment by nacknacknock** [comment]
I'm periodically experiencing the same error (at startup and when running bisq).

Context:
Using the previous bisq version 1.0.1 I originally experienced the problems described in https://github.com/bisq-network/bisq/issues/2788 and https://github.com/bisq-network/bisq/issues/2795.

I've updated to version 1.1.0 and now was able to open two support tickets for the two non-initialized/broken trades. The error occured the first time when I started bisq again after having filed the support tickets (one of which is closed).

![bisq_error](https://user-images.githubusercontent.com/50173778/57200133-2d1a4b00-6f77-11e9-8a9b-9fd8bf94bef3.png)

> #################################################################
Connected to node: ***REDACTED***.onion:8000
Received 450 instances
Filter: 1
MailboxStoragePayload: 194
Alert: 1
Arbitrator: 2
OfferPayload: 252
################################################################# 
May-04 23:10:11.911 [NetworkNode:SendMessage-to-***REDACTED***.onion:9999] INFO  b.n.p.n.NetworkNode: onFailure at sendMessage: peersNodeAddress=***REDACTED***.onion:9999
	message=GetPeersRequest
	throwable=java.io.IOException: Cannot connect to hidden service 
May-04 23:10:12.743 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: Start processing 0 items. 
May-04 23:10:12.759 [JavaFX Application Thread] INFO  b.n.p.P2PService: Received a DisputeResultMessage mailbox message with messageUid ***REDACTED*** and senderAddress ***REDACTED***:9999 
May-04 23:10:12.845 [JavaFX Application Thread] INFO  b.c.a.DisputeManager: Received DisputeCommunicationMessage with tradeId ***REDACTED*** and uid ***REDACTED*** 
May-04 23:10:12.850 [JavaFX Application Thread] INFO  b.c.a.DisputeManager: Send AckMessage for DisputeCommunicationMessage to peer ***REDACTED***:9999. tradeId=***REDACTED***, uid=***REDACTED***
May-04 23:10:12.853 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: Num of latestLivePeers=8 
May-04 23:10:12.856 [JavaFX Application Thread] WARN  b.n.p.P2PService: We don't have the peer in our persisted peers so we don't know his capabilities. We decide to not sent the msg. peersNodeAddress=***REDACTED***.onion:9999 
May-04 23:10:12.856 [JavaFX Application Thread] ERROR b.c.a.DisputeManager: AckMessage for DisputeCommunicationMessage failed. Peer ***REDACTED***.onion:9999. tradeId=***REDACTED***, uid=***REDACTED***, errorMessage=We did not send the EncryptedMailboxMessage because the peer does not support the capability. 
May-04 23:10:13.008 [JavaFX Application Thread] INFO  b.c.a.DisputeManager: Received DisputeResultMessage with tradeId ***REDACTED*** and uid ***REDACTED***
May-04 23:10:13.012 [JavaFX Application Thread] ERROR b.c.b.w.BtcWalletService: multiSigAddressEntry not found for trade ID=***REDACTED***.
We try to find the keypair in the wallet with the pubKey we found in the trade data. 
May-04 23:10:13.016 [JavaFX Application Thread] INFO  b.c.b.w.TradeWalletService: buyerPubKey ECKey{pub HEX=***REDACTED***, isEncrypted=false, isPubKeyOnly=true} 
May-04 23:10:13.017 [JavaFX Application Thread] INFO  b.c.b.w.TradeWalletService: sellerPubKey ECKey{pub HEX=***REDACTED***, isEncrypted=false, isPubKeyOnly=true} 
May-04 23:10:13.017 [JavaFX Application Thread] INFO  b.c.b.w.TradeWalletService: arbitratorPubKey ECKey{pub HEX=***REDACTED***, isEncrypted=false, isPubKeyOnly=true} 
May-04 23:10:13.333 [JavaFX Application Thread] INFO  b.c.b.w.WalletService: 
disputed payoutTx:
  ***REDACTED***
     in   0[] PUSHDATA(71)[***REDACTED***] PUSHDATA(71)[***REDACTED***] PUSHDATA1[***REDACTED***] ***REDACTED*** BTC (***REDACTED***)
          outpoint:***REDACTED***:0 hash160:***REDACTED***
     out  DUP HASH160 PUSHDATA(20)[***REDACTED***] EQUALVERIFY CHECKSIG ***REDACTED*** BTC (***REDACTED***) ScriptPubKey: ***REDACTED*** Address:***REDACTED*** 
     out  DUP HASH160 PUSHDATA(20)[***REDACTED***] EQUALVERIFY CHECKSIG ***REDACTED*** BTC (***REDACTED***) ScriptPubKey: ***REDACTED*** Address:***REDACTED*** 
     fee  -0.0***REDACTED*** BTC for ***REDACTED*** bytes (-***REDACTED*** Satoshi/Byte)
     prps UNKNOWN
 
>May-04 23:10:13.337 [JavaFX Application Thread] ERROR b.c.b.w.WalletService: OP_EQUALVERIFY: non-equal data 
May-04 23:10:13.340 [JavaFX Application Thread] ERROR b.c.a.DisputeManager: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: OP_EQUALVERIFY: non-equal data 
May-04 23:10:13.612 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade ***REDACTED***
May-04 23:10:13.615 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade ***REDACTED***
May-04 23:10:13.615 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade ***REDACTED*** 
May-04 23:10:13.615 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade ***REDACTED*** 
May-04 23:10:13.616 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: swap addressEntry with address ***REDACTED*** and offerId ***REDACTED*** from context TRADE_PAYOUT to available 
May-04 23:10:13.619 [JavaFX Application Thread] INFO  b.c.a.DisputeManager: Send AckMessage for DisputeCommunicationMessage to peer ***REDACTED***.onion:9999. tradeId=***REDACTED***, uid=***REDACTED***
May-04 23:10:13.623 [JavaFX Application Thread] WARN  b.n.p.P2PService: We don't have the peer in our persisted peers so we don't know his capabilities. We decide to not sent the msg. peersNodeAddress=***REDACTED***.onion:9999 
May-04 23:10:13.624 [JavaFX Application Thread] ERROR b.c.a.DisputeManager: AckMessage for DisputeCommunicationMessage failed. Peer ***REDACTED***.onion:9999. tradeId=***REDACTED***, uid=***REDACTED***, errorMessage=We did not send the EncryptedMailboxMessage because the peer does not support the capability. 
May-04 23:10:13.625 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
May-04 23:10:13.626 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: OP_EQUALVERIFY: non-equal data 
May-04 23:10:13.626 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.RuntimeException 
May-04 23:10:13.671 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.RuntimeException: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: OP_EQUALVERIFY: non-equal data
	at bisq.core.arbitration.DisputeManager.onDisputeResultMessage(DisputeManager.java:1015)
	at bisq.core.arbitration.DisputeManager.dispatchMessage(DisputeManager.java:329)
	at bisq.core.arbitration.DisputeManager.lambda$applyMessages$14(DisputeManager.java:283)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.core.arbitration.DisputeManager.applyMessages(DisputeManager.java:279)
	at bisq.core.arbitration.DisputeManager.tryApplyMessages(DisputeManager.java:259)
	at bisq.core.arbitration.DisputeManager.lambda$new$1(DisputeManager.java:163)
	at bisq.network.p2p.P2PService.lambda$processMailboxEntry$9(P2PService.java:527)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.P2PService.processMailboxEntry(P2PService.java:526)
	at bisq.network.p2p.P2PService.lambda$maybeProcessAllMailboxEntries$12(P2PService.java:644)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4791)
	at bisq.network.p2p.P2PService.maybeProcessAllMailboxEntries(P2PService.java:642)
	at bisq.network.p2p.P2PService.onUpdatedDataReceived(P2PService.java:341)
	at bisq.network.p2p.peers.getdata.RequestDataManager$2.onComplete(RequestDataManager.java:343)
	at bisq.network.p2p.peers.getdata.RequestDataHandler.onMessage(RequestDataHandler.java:291)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:344)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:344)
	at bisq.network.p2p.network.Connection.lambda$onMessage$3(Connection.java:390)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:390)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by viciousvex** [comment]
Try renaming DisputeList in the db folder and restarting your app.

**Comment by ManfredKarrer** [comment]
Only rename DisputeList if you dont have other open disputes beside the failed one.
