### ISSUE TITLE
NullPointerException buying BSQ

### ISSUE THREAD

**Issue by billytaylor** [bisq-network/bisq#2885]
...while in the trade funding screen. Last msgs in log file:

```
Jun-14 20:45:44.614 [JavaFX Application Thread] INFO  b.c.b.TxFeeEstimationService: Fee estimation resulted in a tx size of 260 bytes.
We use an average between the taker fee tx and the deposit tx (320 bytes) which results in 290 bytes.
The payout tx has 380 bytes, we use that as our min value. Size for fee calculation is 380 bytes.
The tx fee of 24320 Sat 
Jun-14 20:45:44.693 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Jun-14 20:45:44.702 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= null 
Jun-14 20:45:44.702 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.NullPointerException 
Jun-14 20:45:44.770 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException
	at bisq.desktop.util.Transitions.lambda$fadeOutAndRemove$0(Transitions.java:94)
	at javafx.graphics/javafx.animation.Animation.finished(Animation.java:1131)
	at javafx.graphics/javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)
	at javafx.graphics/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.graphics/javafx.animation.Animation.doTimePulse(Animation.java:1101)
	at javafx.graphics/javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:186)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/javafx.animation.Animation$1.timePulse(Animation.java:185)
	at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:514)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:844)
 
Jun-14 20:45:44.772 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Jun-14 20:45:44.780 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= null 
Jun-14 20:45:44.781 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.NullPointerException 
Jun-14 20:45:44.781 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException
	at bisq.desktop.util.Transitions.lambda$fadeOutAndRemove$0(Transitions.java:94)
	at javafx.graphics/javafx.animation.Animation.finished(Animation.java:1131)
	at javafx.graphics/javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)
	at javafx.graphics/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.graphics/javafx.animation.Animation.doTimePulse(Animation.java:1101)
	at javafx.graphics/javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:186)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/javafx.animation.Animation$1.timePulse(Animation.java:185)
	at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:514)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:844)
 
Jun-14 20:46:37.882 [JavaFX Application Thread] INFO  b.c.p.p.PriceFeedService: request from provider http://62nvujg5iou3vu3i.onion/ 64.007 sec. after last request
```
I did manage to take the offer and the deposit txn was published ok. If you need any more of the log, pls just let me know what's safe to upload on here (e.g. lines with my onion address, etc)
Thanks
Billy

**Comment by ghost** [comment]
Thanks for the log,
but what was the effect in the appli itself ?

**Comment by billytaylor** [comment]
The only effect I could see was the unhandled exception popup with the instruction to open this issue and provide the log, hence this issue. Cheers

**Comment by sqrrm** [comment]
@billytaylor What platform are you on? What did you do just before this happened?

**Comment by billytaylor** [comment]
Windows 10. I was in the process of taking the offer. Let me know if you need more log context.

**Comment by sqrrm** [comment]
This might be related to something windows specific, that would make it harder to fix for me. Do you remember exactly what you clicked just before this happened?

**Comment by billytaylor** [comment]
Sorry, no, it was pretty late after a long day.

**Comment by devinbileck** [comment]
I am not sure what would cause this, but seems it occurred when it tried to fadeOutAndRemove the advancedOptionsGroup and advancedOptionsBox.
