### ISSUE TITLE
OS X installation (upgrade) problem

### ISSUE THREAD

**Issue by meapistol** [bisq-network/bisq#307]
After trying to clean and reinstall I get the following error report after starting bitsquare from the console and try to save an account:

```
java.lang.NullPointerException
    at io.bitsquare.btc.AddressEntry.getAddress(AddressEntry.java:74)
    at io.bitsquare.gui.main.account.content.registration.RegistrationDataModel.<init>(RegistrationDataModel.java:73)
    at io.bitsquare.gui.main.account.content.registration.RegistrationDataModel$$FastClassByGuice$$53967d9d.newInstance(<generated>)
    at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
    at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
    at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
    at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
    at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
    at viewfx.view.support.guice.InjectorViewFactory.call(InjectorViewFactory.java:37)
    at viewfx.view.support.guice.InjectorViewFactory.call(InjectorViewFactory.java:26)
    at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:925)
    at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:967)
    at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:216)
    at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:740)
    at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2701)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2521)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2435)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2403)
    at viewfx.view.support.fxml.FxmlViewLoader.loadFromFxml(FxmlViewLoader.java:100)
    at viewfx.view.support.fxml.FxmlViewLoader.load(FxmlViewLoader.java:89)
    at viewfx.view.support.CachingViewLoader.load(CachingViewLoader.java:42)
    at io.bitsquare.gui.main.account.setup.AccountSetupWizard.loadView(AccountSetupWizard.java:156)
    at io.bitsquare.gui.main.account.setup.AccountSetupWizard$WizardItem.show(AccountSetupWizard.java:208)
    at io.bitsquare.gui.main.account.setup.AccountSetupWizard.nextStep(AccountSetupWizard.java:143)
    at io.bitsquare.gui.main.account.content.irc.IrcAccountView.onSave(IrcAccountView.java:157)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
    at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1759)
    at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1645)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Node.fireEvent(Node.java:8216)
    at javafx.scene.control.Button.fire(Button.java:185)
    at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3724)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3452)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1728)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2461)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:348)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:273)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:382)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:553)
    at com.sun.glass.ui.View.notifyMouse(View.java:925)
```

**Comment by ManfredKarrer** [comment]
@cbeams I tested it with the latest mac binary and I get a error that the binary is damaged. Could you check on your side? 

Mats-Erik posted that in the g+:
" I deleted the entire directory Bitsquare from /Application Support/ assuming I was cleaning it. I then reinstalled Bitsquare from github (.dmg). Now OS X complains that Bitsquare is damaged when I try to open by clicking the icon and that I should move it to Trash. I can however start Bitsquare from the command line."

**Comment by cbeams** [comment]
I just re-downloaded and ran https://github.com/bitsquare/bitsquare/releases/download/v0.1.0-SNAPSHOT.1/Bitsquare-0.1.0-SNAPSHOT.dmg. Everything worked as expected for me.

**Comment by ManfredKarrer** [comment]
Its strange, I could open it earlier. Now i only can open it if i change the security settings. 
can it be that it conflicts with something from an earlier installation? we had also the installer?
I will try it with self build app and installers.

![bildschirmfoto 2014-12-03 um 12 20 21](https://cloud.githubusercontent.com/assets/1449498/5279588/d5d5a846-7ae6-11e4-878f-b483dcbad9cb.png)
![bildschirmfoto 2014-12-03 um 12 20 25](https://cloud.githubusercontent.com/assets/1449498/5279589/d8afae86-7ae6-11e4-80a9-093994c435f1.png)

**Comment by ManfredKarrer** [comment]
I build with packageNative a own binary and changed back security settings to standard (middle radio button) and did nto get the error. Can u test my binary to check if you can run it? and can u check your security settings? Uploaded it here: https://drive.google.com/file/d/0B4bdqF8QV-tDbTYtbmgwVERkb28/view?usp=sharing

**Comment by meapistol** [comment]
I still can only run from the console and get the following error after a short time: http://pastebin.com/x9MqyCtd
Security settings? I have at least: 
mats-eriks-MacBook-Pro:MacOS mepistol$ ls -al
total 40
drwxr-xr-x@ 3 mepistol  admin    102 Dec  3 18:25 .
drwxr-xr-x@ 9 mepistol  admin    306 Dec  3 18:25 ..
-r-xr-xr-x@ 1 mepistol  admin  19124 Dec  3 18:25 Bitsquare
mats-eriks-MacBook-Pro:MacOS mepistol$

**Comment by cbeams** [comment]
Are you sure you've completely removed the '~/Library/Application Support/Bitsquare' directory prior to starting the app? Perhaps try 'rm -rf' there once again.

**Comment by ManfredKarrer** [comment]
@meapistol 
There are 2 problems:
1. That you cannot open the app normallsy
2. That Error

Re 1:
Can you check which security settings are used under: System preferences/security/general and then "Allow app download": There are 3 radiobuttons and if not selected the last one (no restrictions) you cannot open an app which si not form App store or signed with an apple developer ID. As we don't support (like many others) Apples monopolistic approach you need to go to that last option ot be able to open the app normally. 
I will investigate in a few days more.

Re 2:
I assume, like @cbeams  that it is caused by an old incompatible bitsquare preferences files. If you delete the data directory for Bitsquare it should not popup anymore. I will investigate in a few days also more. We also plan soon to avoid that problems by handling incompabilities from different versions internally...

**Comment by meapistol** [comment]
Thx and sorry for the trouble. Changing the security settings allows me to open by clicking now. It does not connect to P2P network, but this I should check from home where UPnP works (it might not here).
I think the '~/Library/Application Support/Bitsquare' directory has been removed: http://pastebin.com/NtRF0LzB

**Comment by ManfredKarrer** [comment]
@meapistol Thanks YOU! And sorry for the bugs!
Yes seems there is no data dir. 
Hopefully soon there will also be support for other network environments so you can run it (nearly) from everywhere.

**Comment by ManfredKarrer** [comment]
I tested with a locally created binary and could it open also with the security settings for verified developers. I uploaded that binary to the Github releases and then downloaded it, then i could not open it anymore and got the error message that it is damaged. When downloaded qTox and opened it I also got a error message but with a clear information that the binary is not signed by a verified dev. Not sure how that is handled by OSX, but seems that the java packager we use now creates a binary where some data is missing to get at least the correct error message.

We will not apply for Apple developer license as we don't support their monopolistic politics.
But we should get better error message so people know what they have to do to run the app.
I will add for now in the user guide a comment for that.

@cbeams Maybe the old version you used solves the issue?

The Nullpointer exception I assume is caused by some problems with a not removed data directory. 

@meapistol: I uploaded a new OSX binary. Can you download that and clean the Bitsquare data dir and see if you get again the problems? Thanks!

![bildschirmfoto 2014-12-08 um 18 21 06](https://cloud.githubusercontent.com/assets/1449498/5343524/21ab2114-7f07-11e4-973a-467674d74c5c.png)
![bildschirmfoto 2014-12-08 um 18 21 55](https://cloud.githubusercontent.com/assets/1449498/5343525/21b1b18c-7f07-11e4-9ecd-924b9687cd45.png)

**Comment by meapistol** [comment]
I cleaned the Bitsquare data dir, downloaded the new .dmg and have so far no problems. I allow general downloads in the security settings. The bank account button is dimmed so I cannot try so much. I did install a Bitcoin core client and have some test-btc to spend now.
Best,
-mep

**Comment by ManfredKarrer** [comment]
@meapistol 
Thanks! I have removed the registration part so you can just create offers and take offers without registration. Atm I think there is nobody online to trade, if you like to test it ping me on IRC bitsquare and i can serve as trading peer (today I cant but tomorrow or maybe someone else in the IRC). Otherwise on saturday we will have a new session probably, will be announced soon.
