### ISSUE TITLE
Error at traderSignAndFinalizeDisputedPayoutTx

### ISSUE THREAD

**Issue by dcod3d** [bisq-network/bisq#3084]
I'm getting this error at startup and I am pretty much unable to do anything. I cannot confirm transactions. My offers do not show up in the market and I am unable to disable or edit offers. Also, my DAO balance is stuck at 0 even though it shows transactions. I would start over with a fresh install, but I just have too many open offers/trades/disputes in progress.

I get this error every time I start up.

The offer I think is causing all this is for a trade dispute that was closed last week. I opened the case because the taker's transaction was never published. The trade was accepted 8/2 by the buyer and I opened the dispute 8/9 and the arbitrator (g72ouph23eznvpuz) closed it a few hours later. I have tried to contact the arbitrator via slack and other open disputes (with the same arbitrator) about this issue, but have not received a response.

Here is an excerpt from the log.
```
Aug-13 22:02:42.921 [JavaFX Application Thread] ERROR b.c.b.w.BtcWalletService: multiSigAddressEntry not found for trade ID=oPH1Qe-725ad736-2381-4542-ae90-28fb5df11b6f-113.
We try to find the keypair in the wallet with the pubKey we found in the trade data. 
Aug-13 22:02:42.925 [JavaFX Application Thread] INFO  b.c.b.w.TradeWalletService: buyerPubKey ECKey{pub HEX=021cf83e4d0d67becf34f6d2f5b2c13662d9deacc62aa125d68a791055e8364d8c, isEncrypted=false, isPubKeyOnly=true} 
Aug-13 22:02:42.925 [JavaFX Application Thread] INFO  b.c.b.w.TradeWalletService: sellerPubKey ECKey{pub HEX=03141bf5db0a7f77025804f24e1d6acbaf1e06a274abdd20ed5ffe299095065ee5, isEncrypted=false, isPubKeyOnly=true} 
Aug-13 22:02:42.926 [JavaFX Application Thread] INFO  b.c.b.w.TradeWalletService: arbitratorPubKey ECKey{pub HEX=03036957627036bb8d9ca0f1eae67bedd0d4f6b173a2070666a5b5117b6d0a6624, isEncrypted=false, isPubKeyOnly=true} 
Aug-13 22:02:42.943 [JavaFX Application Thread] INFO  b.c.b.w.WalletService: 
disputed payoutTx:
  72627b61c389df1172ad3ee5e680cceeaf3d8fa807206d0e48d6d3b488b3956c
     in   0[] PUSHDATA(71)[30440220676bf7de822d70588879e647cf57d79493b849e1a159f8bcc8e8b70a31fade8f02201007c9dbc19f9805e1363dd73f58d5ddd7a020ab5f695be961bd534d089f861501] PUSHDATA(72)[3045022100806a648ceae1272a8f9dcd0e1f79ebdab09ac51b355c72c7583751aa10663daf02207f71925404cd5d53680c4d9cd7110a5edff762b972fcaf0f666ae2baca465b4b01] PUSHDATA1[522103036957627036bb8d9ca0f1eae67bedd0d4f6b173a2070666a5b5117b6d0a66242103141bf5db0a7f77025804f24e1d6acbaf1e06a274abdd20ed5ffe299095065ee521021cf83e4d0d67becf34f6d2f5b2c13662d9deacc62aa125d68a791055e8364d8c53ae] 0.0160456 BTC (1604560)
          outpoint:b6a570e4fc42a1f4dbe1b43163ca4a738b1f1781e035217a23a239a799300df7:0 hash160:16874808eb59d04ee05bc0a9aef5f23f3f903243
     out  DUP HASH160 PUSHDATA(20)[1fb8b45a337d3461c44c558ff6695204aede98e5] EQUALVERIFY CHECKSIG 0.001 BTC (100000) ScriptPubKey: 76a9141fb8b45a337d3461c44c558ff6695204aede98e588ac Address:13tjDSYnfiEdvWMBPKKdWZcgtH11nmBSwr 
     out  DUP HASH160 PUSHDATA(20)[3bda7127b08b2af16bfa44b09deb9489cf66e101] EQUALVERIFY CHECKSIG 0.015 BTC (1500000) ScriptPubKey: 76a9143bda7127b08b2af16bfa44b09deb9489cf66e10188ac Address:16TUYwEYZTMDcKbLZpsMg31zzMbPAiNvww 
     fee  0.0000456 BTC for 374 bytes (12 Satoshi/Byte)
     prps UNKNOWN
 
Aug-13 22:02:42.948 [JavaFX Application Thread] ERROR b.c.b.w.WalletService: Script resulted in a non-true stack: [[B@768b50e7, [B@280ef117, [B@587d11c1] 
Aug-13 22:02:42.950 [JavaFX Application Thread] ERROR b.c.a.DisputeManager: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@768b50e7, [B@280ef117, [B@587d11c1] bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@768b50e7, [B@280ef117, [B@587d11c1]
	at bisq.core.btc.wallet.WalletService.checkScriptSig(WalletService.java:233)
	at bisq.core.btc.wallet.TradeWalletService.traderSignAndFinalizeDisputedPayoutTx(TradeWalletService.java:935)
	at bisq.core.arbitration.DisputeManager.onDisputeResultMessage(DisputeManager.java:943)
	at bisq.core.arbitration.DisputeManager.dispatchMessage(DisputeManager.java:335)
	at bisq.core.arbitration.DisputeManager.lambda$applyMessages$14(DisputeManager.java:289)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.core.arbitration.DisputeManager.applyMessages(DisputeManager.java:285)
	at bisq.core.arbitration.DisputeManager.tryApplyMessages(DisputeManager.java:261)
	at bisq.core.arbitration.DisputeManager.lambda$new$1(DisputeManager.java:164)
	at bisq.network.p2p.P2PService.lambda$processMailboxEntry$9(P2PService.java:527)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.P2PService.processMailboxEntry(P2PService.java:526)
	at bisq.network.p2p.P2PService.lambda$maybeProcessAllMailboxEntries$12(P2PService.java:644)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4791)
	at bisq.network.p2p.P2PService.maybeProcessAllMailboxEntries(P2PService.java:642)
	at bisq.network.p2p.P2PService.onUpdatedDataReceived(P2PService.java:341)
	at bisq.network.p2p.peers.getdata.RequestDataManager$2.onComplete(RequestDataManager.java:339)
	at bisq.network.p2p.peers.getdata.RequestDataHandler.onMessage(RequestDataHandler.java:291)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:344)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:344)
	at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:428)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.network.Connection.lambda$onMessage$5(Connection.java:428)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@768b50e7, [B@280ef117, [B@587d11c1]
	at org.bitcoinj.script.Script.correctlySpends(Script.java:1606)
	at bisq.core.btc.wallet.WalletService.checkScriptSig(WalletService.java:229)
	... 31 common frames omitted

Aug-13 22:02:42.953 [JavaFX Application Thread] INFO  b.c.a.DisputeManager: Send AckMessage for DisputeCommunicationMessage to peer g72ouph23eznvpuz.onion:9999. tradeId=oPH1Qe-725ad736-2381-4542-ae90-28fb5df11b6f-113, uid=f5b6ef42-039d-469f-a29c-b2bea4898fdb 
Aug-13 22:02:42.973 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Aug-13 22:02:42.974 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@768b50e7, [B@280ef117, [B@587d11c1] 
Aug-13 22:02:42.974 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.RuntimeException 
Aug-13 22:02:42.976 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.RuntimeException: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@768b50e7, [B@280ef117, [B@587d11c1]
	at bisq.core.arbitration.DisputeManager.onDisputeResultMessage(DisputeManager.java:1020)
	at bisq.core.arbitration.DisputeManager.dispatchMessage(DisputeManager.java:335)
	at bisq.core.arbitration.DisputeManager.lambda$applyMessages$14(DisputeManager.java:289)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.core.arbitration.DisputeManager.applyMessages(DisputeManager.java:285)
	at bisq.core.arbitration.DisputeManager.tryApplyMessages(DisputeManager.java:261)
	at bisq.core.arbitration.DisputeManager.lambda$new$1(DisputeManager.java:164)
	at bisq.network.p2p.P2PService.lambda$processMailboxEntry$9(P2PService.java:527)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.P2PService.processMailboxEntry(P2PService.java:526)
	at bisq.network.p2p.P2PService.lambda$maybeProcessAllMailboxEntries$12(P2PService.java:644)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4791)
	at bisq.network.p2p.P2PService.maybeProcessAllMailboxEntries(P2PService.java:642)
	at bisq.network.p2p.P2PService.onUpdatedDataReceived(P2PService.java:341)
	at bisq.network.p2p.peers.getdata.RequestDataManager$2.onComplete(RequestDataManager.java:339)
	at bisq.network.p2p.peers.getdata.RequestDataHandler.onMessage(RequestDataHandler.java:291)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:344)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:344)
	at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:428)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.network.Connection.lambda$onMessage$5(Connection.java:428)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

**Comment by huey735** [comment]
That onion address is for @leomcy (@Arbitrator2)
The payout for the trade mentioned seems to have gone through though.

**Comment by dcod3d** [comment]
I was able to contact the arbitrator to re-close the trade. But that did not solve the issue. The payout tx 72627b61c389df1172ad3ee5e680cceeaf3d8fa807206d0e48d6d3b488b3956c is not found. However, I don't think there should be a payout tx since the buyer/taker's tx was never published. I've had several trades with the tx not being published, and the dispute closure just released the funds back to me in bisq.

**Comment by huey735** [comment]
@ncstdc I think this is the correct payout tx: a5b5b688efd4bb44dff517abfad942b09e8f5c8b6f24624c63672cb5048da7ca

**Comment by dcod3d** [comment]
@huey735 that tx is payout for trade 79532, which was completed successfully. 


![Screen Shot 2019-08-17 at 2 09 18 PM](https://user-images.githubusercontent.com/2712736/63216295-f2d55380-c0f8-11e9-98cb-d323eba23cf8.png)

**Comment by Perlover** [comment]
Hello!

Same problem under the same conditions
Bisq 1.1.5

After trade dispute resolving (my linux desktop version was not runned) i started Bisq and got window with stack trace. In log files i found like this stack trace:

```
сент.-04 18:12:07.551 [JavaFX Application Thread] INFO  b.c.b.w.TradeWalletService: arbitratorPubKey ECKey{pub HEX=03036957627036bb8d9ca0f1eae67bedd0d4f6b173a2070666a5b5117b6d0a6624, isEncrypted=false, isPubKeyOnly=true} 
сент.-04 18:12:07.563 [JavaFX Application Thread] INFO  b.c.b.w.WalletService: 
disputed payoutTx:
  e28fddd1643a929a012a1b5db7170e1862fb33e4c2da900deb7b80f24441738e
     in   0[] PUSHDATA(71)[304402207a9286d2cb5696a6b435d549a543d12eb2a7a845f51533bc21c9daee2482f2f902205abbeb0c31a4cdff368447b0ae3db20e89792bb6c9ae2837820464460aafb79701] PUSHDATA(71)[30440220323c5ad71a3b088c553c8564b65ba434b68b4c5d412ff2889ae63c620c67cafc022077a5904214cfd25c403f1c65c132b55a70ed566c62dbd30f1dbb8987d3
          outpoint:7be27cb563f477c48cd693ceed3d1db12278a0d58f4f8f639536fb7b04737206:0 hash160:9afcc9e34ceae1216cc0f5f85e5baa8d6ab7534e
     out  DUP HASH160 PUSHDATA(20)[ec880d4850ae0b3dc433060c5025c699abc347ac] EQUALVERIFY CHECKSIG 0.001 BTC (100000) ScriptPubKey: 76a914ec880d4850ae0b3dc433060c5025c699abc347ac88ac Address:1NZfTKiPzNMgEifbKL5sgeUtz79BGA4pAM 
     out  DUP HASH160 PUSHDATA(20)[c50a784bae9b6c8ff7fb2c266606b4362724c20e] EQUALVERIFY CHECKSIG 0.0149 BTC (1490000) ScriptPubKey: 76a914c50a784bae9b6c8ff7fb2c266606b4362724c20e88ac Address:1JxrfFdr7gscaydzygbitPvF79KSMfR47L 
     fee  0.0000456 BTC for 371 bytes (12 Satoshi/Byte)
     prps UNKNOWN
 
сент.-04 18:12:07.565 [JavaFX Application Thread] ERROR b.c.b.w.WalletService: Script resulted in a non-true stack: [[B@2e742a5a, [B@3e124cbf, [B@3eda0600] 
сент.-04 18:12:07.567 [JavaFX Application Thread] ERROR b.c.a.DisputeManager: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@2e742a5a, [B@3e124cbf, [B@3eda0600] bisq.core.btc.exceptio
        at bisq.core.btc.wallet.WalletService.checkScriptSig(WalletService.java:233)
        at bisq.core.btc.wallet.TradeWalletService.traderSignAndFinalizeDisputedPayoutTx(TradeWalletService.java:935)
        at bisq.core.arbitration.DisputeManager.onDisputeResultMessage(DisputeManager.java:943)
        at bisq.core.arbitration.DisputeManager.dispatchMessage(DisputeManager.java:335)
        at bisq.core.arbitration.DisputeManager.lambda$applyMessages$14(DisputeManager.java:289)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at bisq.core.arbitration.DisputeManager.applyMessages(DisputeManager.java:285)
        at bisq.core.arbitration.DisputeManager.tryApplyMessages(DisputeManager.java:261)
        at bisq.core.arbitration.DisputeManager.lambda$new$1(DisputeManager.java:164)
        at bisq.network.p2p.P2PService.lambda$processMailboxEntry$9(P2PService.java:527)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at bisq.network.p2p.P2PService.processMailboxEntry(P2PService.java:526)
        at bisq.network.p2p.P2PService.lambda$maybeProcessAllMailboxEntries$12(P2PService.java:644)
        at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4791)
        at bisq.network.p2p.P2PService.maybeProcessAllMailboxEntries(P2PService.java:642)
        at bisq.network.p2p.P2PService.onUpdatedDataReceived(P2PService.java:341)
        at bisq.network.p2p.peers.getdata.RequestDataManager$2.onComplete(RequestDataManager.java:339)
        at bisq.network.p2p.peers.getdata.RequestDataHandler.onMessage(RequestDataHandler.java:291)
        at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:344)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:344)
        at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:428)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at bisq.network.p2p.network.Connection.lambda$onMessage$5(Connection.java:428)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@2e742a5a, [B@3e124cbf, [B@3eda0600]
        at org.bitcoinj.script.Script.correctlySpends(Script.java:1606)
        at bisq.core.btc.wallet.WalletService.checkScriptSig(WalletService.java:229)
        ... 34 common frames omitted

сент.-04 18:12:07.589 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade VfxfJ-9a5e9286-ad76-4fd3-bc38-7c33845ae85f-112 
сент.-04 18:12:07.590 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade VfxfJ-9a5e9286-ad76-4fd3-bc38-7c33845ae85f-112 
сент.-04 18:12:07.590 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade VfxfJ-9a5e9286-ad76-4fd3-bc38-7c33845ae85f-112 
сент.-04 18:12:07.590 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade VfxfJ-9a5e9286-ad76-4fd3-bc38-7c33845ae85f-112 
сент.-04 18:12:07.590 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade vnqw78lz-bcc50b77-3336-4859-975a-78d1274c44f5-115 
сент.-04 18:12:07.590 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: swap addressEntry with address 1CtQb19R1n8p7RdbBofDyS29QfQMTj5CKP and offerId vnqw78lz-bcc50b77-3336-4859-975a-78d1274c44f5-115 from context MULTI_SIG to available 
сент.-04 18:12:07.590 [JavaFX Application Thread] WARN  b.c.t.TradeManager: We found an outdated addressEntry for trade vnqw78lz-bcc50b77-3336-4859-975a-78d1274c44f5-115 
сент.-04 18:12:07.590 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: swap addressEntry with address 1JxrfFdr7gscaydzygbitPvF79KSMfR47L and offerId vnqw78lz-bcc50b77-3336-4859-975a-78d1274c44f5-115 from context TRADE_PAYOUT to available 
сент.-04 18:12:07.590 [JavaFX Application Thread] INFO  b.c.a.DisputeManager: Send AckMessage for DisputeCommunicationMessage to peer g72ouph23eznvpuz.onion:9999. tradeId=vnqw78lz-bcc50b77-3336-4859-975a-78d1274c44f5-115, uid=e76f9a02-6f0d-4193-a30c-17e70c8b8b93 
сент.-04 18:12:07.591 [JavaFX Application Thread] WARN  b.n.p.P2PService: We don't have the peer in our persisted peers so we don't know his capabilities. We decide to not sent the msg. peersNodeAddress=g72ouph23eznvpuz.onion:9999 
сент.-04 18:12:07.591 [JavaFX Application Thread] ERROR b.c.a.DisputeManager: AckMessage for DisputeCommunicationMessage failed. Peer g72ouph23eznvpuz.onion:9999. tradeId=vnqw78lz-bcc50b77-3336-4859-975a-78d1274c44f5-115, uid=e76f9a02-6f0d-4193-a30c-17e70c8b8b93, errorMessage=We did not send the EncryptedMailboxMessa
сент.-04 18:12:07.591 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
сент.-04 18:12:07.591 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@2e742a5a, [B@3e124cbf, [B@3eda0600] 
сент.-04 18:12:07.591 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.RuntimeException 
сент.-04 18:12:07.592 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.RuntimeException: Error at traderSignAndFinalizeDisputedPayoutTx bisq.core.btc.exceptions.TransactionVerificationException: org.bitcoinj.core.ScriptException: Script resulted in a non-true stack: [[B@2e742a5a, [B@3e124cbf, [B@3eda0600]
        at bisq.core.arbitration.DisputeManager.onDisputeResultMessage(DisputeManager.java:1020)
        at bisq.core.arbitration.DisputeManager.dispatchMessage(DisputeManager.java:335)
        at bisq.core.arbitration.DisputeManager.lambda$applyMessages$14(DisputeManager.java:289)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at bisq.core.arbitration.DisputeManager.applyMessages(DisputeManager.java:285)
        at bisq.core.arbitration.DisputeManager.tryApplyMessages(DisputeManager.java:261)
        at bisq.core.arbitration.DisputeManager.lambda$new$1(DisputeManager.java:164)
        at bisq.network.p2p.P2PService.lambda$processMailboxEntry$9(P2PService.java:527)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at bisq.network.p2p.P2PService.processMailboxEntry(P2PService.java:526)
        at bisq.network.p2p.P2PService.lambda$maybeProcessAllMailboxEntries$12(P2PService.java:644)
        at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4791)
        at bisq.network.p2p.P2PService.maybeProcessAllMailboxEntries(P2PService.java:642)
        at bisq.network.p2p.P2PService.onUpdatedDataReceived(P2PService.java:341)
        at bisq.network.p2p.peers.getdata.RequestDataManager$2.onComplete(RequestDataManager.java:339)
        at bisq.network.p2p.peers.getdata.RequestDataHandler.onMessage(RequestDataHandler.java:291)
        at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:344)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:344)
        at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:428)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at bisq.network.p2p.network.Connection.lambda$onMessage$5(Connection.java:428)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:844)
```
After i didn't have problem with dispute funds and i was able to send them to another address
