### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by yourwpguy** [bisq-network/bisq#3117]
Getting "java.lang.IllegalStateException" error and Bisq endlessly tries to synchronize DAO. Bisq wallet balance is not synchronized, it is showing 0.00 BSQ, but there should be some BSQ in it.

Deleted SPV file and resynched, but it's still the same error.

(Windows 7, Bisq 1.1.5)

[bisq.zip](https://github.com/bisq-network/bisq/files/3524023/bisq.zip)

**Comment by ripcurlx** [comment]
A transaction (I think in connection with a dispute) is not published properly
```
aug.-21 10:01:08.831 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: Num of latestLivePeers=7 
aug.-21 10:01:08.843 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
aug.-21 10:01:08.844 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= null 
aug.-21 10:01:08.844 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.IllegalStateException 
aug.-21 10:01:08.847 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at org.bitcoinj.wallet.Wallet.addWalletTransaction(Wallet.java:2879)
	at org.bitcoinj.wallet.Wallet.maybeCommitTx(Wallet.java:2430)
	at bisq.core.btc.wallet.TxBroadcaster.broadcastTx(TxBroadcaster.java:110)
	at bisq.core.btc.wallet.TradeWalletService.broadcastTx(TradeWalletService.java:1050)
	at bisq.core.arbitration.DisputeManager.onDisputeResultMessage(DisputeManager.java:956)
	at bisq.core.arbitration.DisputeManager.dispatchMessage(DisputeManager.java:335)
	at bisq.core.arbitration.DisputeManager.lambda$applyMessages$14(DisputeManager.java:289)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.core.arbitration.DisputeManager.applyMessages(DisputeManager.java:285)
	at bisq.core.arbitration.DisputeManager.tryApplyMessages(DisputeManager.java:261)
	at bisq.core.arbitration.DisputeManager.lambda$new$1(DisputeManager.java:164)
	at bisq.network.p2p.P2PService.lambda$processMailboxEntry$9(P2PService.java:527)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.P2PService.processMailboxEntry(P2PService.java:526)
	at bisq.network.p2p.P2PService.lambda$maybeProcessAllMailboxEntries$12(P2PService.java:644)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4791)
	at bisq.network.p2p.P2PService.maybeProcessAllMailboxEntries(P2PService.java:642)
	at bisq.network.p2p.P2PService.onUpdatedDataReceived(P2PService.java:341)
	at bisq.network.p2p.peers.getdata.RequestDataManager$2.onComplete(RequestDataManager.java:339)
	at bisq.network.p2p.peers.getdata.RequestDataHandler.onMessage(RequestDataHandler.java:291)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:344)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:344)
	at bisq.network.p2p.network.Connection.lambda$onMessage$4(Connection.java:428)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.network.Connection.lambda$onMessage$5(Connection.java:428)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:844)
 
aug.-21 10:01:11.569 [JavaFX Application Thread] INFO  b.c.a.DisputeManager: AckMessage for DisputeCommunicationMessage arrived at peer s6yrrpezc3zp6biy.onion:9999. tradeId=TUKIMKD-a10aa9e0-f381-425e-b275-021cb57a51a2-115, uid=ec654aeb-48a4-40f0-ac9b-5b6e936b38d3 
aug.-21 10:01:15.301 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: We have 11 connections open. Our limit is 12 
aug.-21 10:01:19.751 [sendMobileNotification-42697...] INFO  b.c.n.MobileNotificationService: sendMobileNotification result: success 
aug.-21 10:01:23.844 [JavaFX Application Thread] WARN  b.c.b.w.TxBroadcaster: Broadcast of tx d160496524f9577dab06470da1a3fa0a3a33793095079019e3f86cb2231962ab not completed after 15 sec. 
aug.-21 10:01:23.861 [JavaFX Application Thread] WARN  b.c.b.w.TxBroadcaster: TxBroadcaster.onTimeout called: TxBroadcastTimeoutException{
     localTx=  d160496524f9577dab06470da1a3fa0a3a33793095079019e3f86cb2231962ab
  updated: 2019-08-21T07:01:08Z
     in   0[] PUSHDATA(71)[304402204800a889da68d70cd61932409c3c854cbf63484feae43fc5a12bd83a8f1f6cd9022036ef141ab2855734f99156f591e8ce0dcf839be952cfa9d2aab81c106dbad10d01] PUSHDATA(72)[3045022100edde5ae54f5c040cf236fbc9f4d52bc08acd4c2e443b0befc28ccd1c396aef3f022003ff931769445972d17f17cc750039077efb09c8004bb69bad64f9c60d60076b01] PUSHDATA1[5221020991c42278a4502693d6cb15d9cd585239a5b633687d3cf2b24fcd200234024a2102f5c8878f22841814640a7b69df30f3cfd1542b9c2026b863ddee30f9396cbd7f21021bd97b08cb2c6c3553866254357957f615daeec280236ef91074342594a2bed253ae]
          outpoint:e2fd708091c88036a492ad0278429f6c59f6414833d9f8a81691cad6c8b23003:0 hash160:ee4bd3438052fa35bf3898bb3edf1e6a1e547f53
     out  DUP HASH160 PUSHDATA(20)[c1507e9d1ed2d1000c895f7541286cf9494bcfd1] EQUALVERIFY CHECKSIG 0.0075 BTC (750000) ScriptPubKey: 76a914c1507e9d1ed2d1000c895f7541286cf9494bcfd188ac Address:1Jd9qtLRW5DaCTPySyQvGcZUSnjhwx9kzy 
     out  DUP HASH160 PUSHDATA(20)[aa4b846682bfaf3a021707ac986a87cf86d54185] EQUALVERIFY CHECKSIG 0.0045 BTC (450000) ScriptPubKey: 76a914aa4b846682bfaf3a021707ac986a87cf86d5418588ac Address:1GXSLdyRe7MKn86E8EWDvhkUstc4T4KSDr 
     prps UNKNOWN
,
     delay=15
} TxBroadcastException{
     txId='null'
} bisq.core.btc.exceptions.TxBroadcastTimeoutException: The transaction was not broadcasted in 15 seconds. txId=d160496524f9577dab06470da1a3fa0a3a33793095079019e3f86cb2231962ab 
```
@sqrrm @ManfredKarrer I think we had this kind of issues in the past every now and then, but I don't remember the workaround for it anymore.

**Comment by yourwpguy** [comment]
Both running trades ended successful. **Error still exists.** Bisq endlessly tries to synchronize DAO and BSQ amount is still 0.00

**Comment by ghost** [comment]
Generally, restarting the Bisq appli does the job.

**Comment by yourwpguy** [comment]
Restarted appli several times, but the error didn't disappear, and Bisq endlessly tries to synchronize DAO and BSQ amount is still 0.00

**Comment by yourwpguy** [comment]
I resolved the problem – **reinstalled** the appli.

1) First, made sure I don’t have any open offers, trades, or disputes. Then, sent any funds from Bisq wallet to an external wallet.

2) Replaced the bisq_BSQ.wallet wallet file in btc_mainnet/wallet with a backup wallet file and renamed it to bisq_BSQ.wallet, (since DAO was synching endlessly). Deleted bisq.spvchain.

3) restored payment accounts and Tor keys.
