### ISSUE TITLE
Connecting to Bisq P2P network is broken on master with NPE exception

### ISSUE THREAD

**Issue by battleofwizards** [bisq-network/bisq#3161]
It got broken by this merge:

```
commit 4e7cb0404 (HEAD -> master, upstream/master)
gpg: Signature made Thu 29 Aug 2019 04:15:18 PM CEST
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: No public key
Merge: edc1e6983 55092edb6
Author: Florian Reimair <office@florianreimair.at>
Date:   Thu Aug 29 16:15:18 2019 +0200

    Merge pull request #3154 from chimp1984/Fix-small-P2P-network-issues
    
    Fix small p2p network issues
```

The exception:

```
Aug-29 17:13:23.677 [Connection:SendCloseConnectionMessage-481de813-2ed1-4b22-8ff9-43ee8f713288] ERROR b.n.p2p.network.Connection: null 
java.lang.NullPointerException
	at bisq.network.p2p.network.Connection.lambda$shutDown$7(Connection.java:495)
	at java.base/java.lang.Thread.run(Thread.java:844)
Aug-29 17:13:23.682 [JavaFX Application Thread] INFO  b.n.p2p.peers.PeerManager: onDisconnect called: nodeAddress=Optional[rm7b56wbrcczpjvl.onion:8000], closeConnectionReason=CloseConnectionReason{sendCloseMessage=true, isIntended=false} RULE_VIOLATION 
Aug-29 17:13:23.685 [JavaFX Application Thread] INFO  b.n.p.p.p.PeerExchangeManager: onDisconnect closeConnectionReason=CloseConnectionReason{sendCloseMessage=true, isIntended=false} RULE_VIOLATION, nodeAddressOpt=Optional[rm7b56wbrcczpjvl.onion:8000] 
Aug-29 17:13:23.687 [JavaFX Application Thread] WARN  bisq.core.app.P2PNetworkSetup: RULE_VIOLATION onDisconnect closeConnectionReason=CloseConnectionReason{sendCloseMessage=true, isIntended=false} RULE_VIOLATION, connection=Connection{peerAddress=Optional[rm7b56wbrcczpjvl.onion:8000], peerType=SEED_NODE, connectionType=OutboundConnection, uid='481de813-2ed1-4b22-8ff9-43ee8f713288'} 
Aug-29 17:13:35.184 [TorControlParser] INFO  o.b.netlayer.tor.Tor: Hidden Service nkw5uvczpk66mnsd.onion.onion is ready 
Aug-29 17:13:38.019 [Connection:SendCloseConnectionMessage-bb1e5de4-1158-420c-9314-b427acdc3bbb] ERROR b.n.p2p.network.Connection: null 
java.lang.NullPointerException
	at bisq.network.p2p.network.Connection.lambda$shutDown$7(Connection.java:495)
	at java.base/java.lang.Thread.run(Thread.java:844)
Aug-29 17:13:38.020 [JavaFX Application Thread] INFO  b.n.p2p.peers.PeerManager: onDisconnect called: nodeAddress=Optional[s67qglwhkgkyvr74.onion:8000], closeConnectionReason=CloseConnectionReason{sendCloseMessage=true, isIntended=false} RULE_VIOLATION 
Aug-29 17:13:38.020 [JavaFX Application Thread] WARN  b.n.p2p.peers.PeerManager: 
------------------------------------------------------------
All connections lost
------------------------------------------------------------ 
```

Please revert the broken merge to make the master green again.

**Comment by wiz** [comment]
I haven't seen this particular stack trace but I can confirm I am having hard times starting the app using master branch builds today

**Comment by positiveblue** [comment]
![Screenshot from 2019-08-29 17-48-40](https://user-images.githubusercontent.com/3369356/63955699-7130de80-ca85-11e9-8b6c-1ae2ce40c4f7.png)


The CI did not complain about anything broken. Do you have any process for this cases? (Revert, add test so it does not happen again, fix test, merge again)?

**Comment by wiz** [comment]
Well the reviewer is supposed to test before approving - was this not done? In any case, easy to revert this commit.
