### ISSUE TITLE
shadowJar built on non-Linux OS does not run on Linux due to java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by wiz** [bisq-network/bisq#3201]
Apparently you need all the runtime libs installed in /opt/Bisq/runtime/lib/ to run Bisq on Linux, and cannot simply `java bisq.jar` like on other OS:

```
% java -Djavafx.verbose=true -Dprism.verbose=true -classpath ~/Downloads/desktop-1.1.6-ec633f0c3771893b47956b8d05b17c6f3f1919c1-all.jar bisq.desktop.app.BisqAppMain
Sep-05 01:16:21.408 [main] INFO  bisq.core.setup.CoreSetup: 


Log files under: /home/wiz/.local/share/Bisq/bisq 
Sep-05 01:16:21.421 [main] INFO  bisq.common.util.Utilities: System info: os.name=Linux; os.version=4.15.0-58-generic; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (OpenJDK 64-Bit Server VM) 
Sep-05 01:16:21.562 [main] INFO  bisq.common.app.Version: Version{VERSION=1.1.6, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Sep-05 01:16:21.563 [main] INFO  bisq.core.setup.CoreSetup: Path to Bisq jar file: /home/wiz/Downloads/desktop-1.1.6-ec633f0c3771893b47956b8d05b17c6f3f1919c1-all.jar 
Prism pipeline init order: es2 sw 
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: /home/wiz/Downloads/libprism_es2.so
GraphicsPipeline.createPipeline failed for com.sun.prism.es2.ES2Pipeline
java.lang.UnsatisfiedLinkError: no prism_es2 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2654)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:876)
	at java.base/java.lang.System.loadLibrary(System.java:1875)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:150)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:68)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:50)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:291)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:844)
*** Fallback to Prism SW pipeline
Prism pipeline name = com.sun.prism.sw.SWPipeline
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: /home/wiz/Downloads/libprism_sw.so
GraphicsPipeline.createPipeline failed for com.sun.prism.sw.SWPipeline
java.lang.UnsatisfiedLinkError: no prism_sw in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2654)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:876)
	at java.base/java.lang.System.loadLibrary(System.java:1875)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:150)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:42)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:291)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:844)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by wiz** [comment]
If we were using a supported version of Java, we could simply require set our .deb package to install javafx package as a dependency, but as we are stuck with OpenJDK 10 for now, the package installer to populate /opt/Bisq/runtime/lib/ seems necessary.

**Comment by wiz** [comment]
For reference, the reason why this works using the ./bisq-desktop launcher script is because gradlew puts the libraries here:
```
% ls -la ~/.openjfx/cache/11
total 660K
drwxrwxr-x 2 wiz wiz 4.0K Sep  5 01:18 .
drwxrwxr-x 3 wiz wiz 4.0K Sep  3 03:36 ..
-rw-rw-r-- 1 wiz wiz  74K Sep  3 03:36 libdecora_sse.so
-rw-rw-r-- 1 wiz wiz  13K Sep  3 03:36 libglass.so
-rw-rw-r-- 1 wiz wiz 347K Sep  3 03:36 libglassgtk3.so
-rw-rw-r-- 1 wiz wiz  17K Sep  3 03:36 libjavafx_font.so
-rw-rw-r-- 1 wiz wiz  27K Sep  3 03:36 libjavafx_font_freetype.so
-rw-rw-r-- 1 wiz wiz  25K Sep  3 03:36 libjavafx_font_pango.so
-rw-rw-r-- 1 wiz wiz  63K Sep  5 01:18 libprism_es2.so
-rw-rw-r-- 1 wiz wiz  70K Sep  5 01:18 libprism_sw.so
```
