### ISSUE TITLE
Errors while testing the DAO section 1.1.6

### ISSUE THREAD

**Issue by acrual** [bisq-network/bisq#3227]
I have encountered errors while testing the DAO. The first happened after Bob downvoting a compensation request by Alice and the log is in testpad (bisq_log).
The second happened while trying to reproduce the first. After booting the arbitrator, Alice and Bob, I mined one block and right after I clicked on Alice's DAO section and encountered this second error. The log is in testpad too => bisq_log2

**Comment by devinbileck** [comment]
I believe this is the error you are referring to?
```
sept.-08 18:32:49.400 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
sept.-08 18:32:49.402 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= -1 
sept.-08 18:32:49.405 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.ArrayIndexOutOfBoundsException 
sept.-08 18:32:49.409 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.ArrayIndexOutOfBoundsException: -1
	at bisq.common.util.MathUtils.getMedian(MathUtils.java:102)
	at bisq.desktop.main.dao.economy.dashboard.BsqDashboardView.getAverageAndMedian(BsqDashboardView.java:369)
	at bisq.desktop.main.dao.economy.dashboard.BsqDashboardView.updateAverageAndMedianPrice(BsqDashboardView.java:338)
	at bisq.desktop.main.dao.economy.dashboard.BsqDashboardView.activate(BsqDashboardView.java:174)
	at bisq.desktop.common.view.ActivatableView.lambda$prepareInitialize$0(ActivatableView.java:37)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.base/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.graphics/javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1054)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1114)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent$2.onChanged(Parent.java:376)
	at javafx.base/com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.base/javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:102)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:237)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:103)
	at javafx.controls/javafx.scene.control.skin.ScrollPaneSkin.initialize(ScrollPaneSkin.java:705)
	at javafx.controls/javafx.scene.control.skin.ScrollPaneSkin.<init>(ScrollPaneSkin.java:266)
	at javafx.controls/javafx.scene.control.ScrollPane.createDefaultSkin(ScrollPane.java:634)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9515)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:583)
	at javafx.graphics/javafx.scene.Scene.access$3500(Scene.java:173)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2502)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:410)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:409)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by acrual** [comment]
> I believe this is the error you are referring to?
> 
> ```
> sept.-08 18:32:49.400 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
> sept.-08 18:32:49.402 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= -1 
> sept.-08 18:32:49.405 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.ArrayIndexOutOfBoundsException 
> sept.-08 18:32:49.409 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
> java.lang.ArrayIndexOutOfBoundsException: -1
> 	at bisq.common.util.MathUtils.getMedian(MathUtils.java:102)
> 	at bisq.desktop.main.dao.economy.dashboard.BsqDashboardView.getAverageAndMedian(BsqDashboardView.java:369)
> 	at bisq.desktop.main.dao.economy.dashboard.BsqDashboardView.updateAverageAndMedianPrice(BsqDashboardView.java:338)
> 	at bisq.desktop.main.dao.economy.dashboard.BsqDashboardView.activate(BsqDashboardView.java:174)
> 	at bisq.desktop.common.view.ActivatableView.lambda$prepareInitialize$0(ActivatableView.java:37)
> 	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
> 	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
> 	at javafx.base/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
> 	at javafx.base/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
> 	at javafx.graphics/javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1054)
> 	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1114)
> 	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
> 	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
> 	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
> 	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
> 	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
> 	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
> 	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
> 	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:776)
> 	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
> 	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
> 	at javafx.graphics/javafx.scene.Parent$2.onChanged(Parent.java:376)
> 	at javafx.base/com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
> 	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
> 	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
> 	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
> 	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
> 	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
> 	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
> 	at javafx.base/javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:102)
> 	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:237)
> 	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:103)
> 	at javafx.controls/javafx.scene.control.skin.ScrollPaneSkin.initialize(ScrollPaneSkin.java:705)
> 	at javafx.controls/javafx.scene.control.skin.ScrollPaneSkin.<init>(ScrollPaneSkin.java:266)
> 	at javafx.controls/javafx.scene.control.ScrollPane.createDefaultSkin(ScrollPane.java:634)
> 	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
> 	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
> 	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
> 	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
> 	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
> 	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
> 	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
> 	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
> 	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
> 	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
> 	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
> 	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
> 	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
> 	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
> 	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
> 	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
> 	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
> 	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
> 	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
> 	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
> 	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1404)
> 	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:81)
> 	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:127)
> 	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:100)
> 	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
> 	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
> 	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
> 	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
> 	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
> 	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
> 	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
> 	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9515)
> 	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
> 	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
> 	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
> 	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9508)
> 	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:583)
> 	at javafx.graphics/javafx.scene.Scene.access$3500(Scene.java:173)
> 	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2502)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:410)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:409)
> 	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
> 	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
> 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
> 	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
> 	at java.base/java.lang.Thread.run(Thread.java:844)
> ```

Apologies, I'm afraid I am not able to interpret the log file yet, but I attach both here, in case you can. Please let me know what is your conclusion. Also, if you can please let me know how can I interpret it? :)

Many thanks

[bisq_log.txt](https://github.com/bisq-network/bisq/files/3628127/bisq_log.txt)
[bisq_log2.txt](https://github.com/bisq-network/bisq/files/3628128/bisq_log2.txt)

**Comment by devinbileck** [comment]
It seems the ArrayIndexOutOfBoundsException was caused by getting the median value of an empty list and was fixed on Sept 9 with this commit: https://github.com/bisq-network/bisq/commit/d55114e019fda469266dab50f63916289b2e71cb

**Comment by acrual** [comment]
> 
> 
> It seems the ArrayIndexOutOfBoundsException was caused by getting the median value of an empty list and was fixed on Sept 9 with this commit: [d55114e](https://github.com/bisq-network/bisq/commit/d55114e019fda469266dab50f63916289b2e71cb)

Understood many thanks,

**Comment by devinbileck** [comment]
Feel free to try the scenario on the latest release or master just to confirm the issue is resolved.

**Comment by acrual** [comment]
Sure!
