### ISSUE TITLE
Rejected role is shows in bonded roles

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#3271]
A rejected bonded role request (lio cycle 5) is displeyed in the bonded roles table. By clicking the role it throws an exception.
Expected: Rejected requests are filtered out.

```
java.lang.IllegalArgumentException: bondedRoleType must be present
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at bisq.core.dao.DaoFacade.getRequiredBond(DaoFacade.java:721)
	at bisq.desktop.main.dao.bonding.roles.RoleDetailsWindow.addContent(RoleDetailsWindow.java:88)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at bisq.desktop.main.dao.bonding.roles.RoleDetailsWindow.show(RoleDetailsWindow.java:66)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at bisq.desktop.main.dao.bonding.roles.RolesView$3$1.lambda$updateItem$0(RolesView.java:214)
```

**Comment by ben-kaufman** [comment]
Can confirm the issue. If no one is on it yet I'll try to fix it.
