### ISSUE TITLE
Critical error when posting trade

### ISSUE THREAD

**Issue by btcll** [bisq-network/bisq#328]
When I went to post a trade, funded the trade and then click the button I got the following error. The Bitsquare application also crashed.

```
java.lang.NullPointerException
    at io.bitsquare.gui.main.portfolio.pending.PendingTradesViewModel.getPaymentMethod(PendingTradesViewModel.java:173)
    at io.bitsquare.gui.main.portfolio.pending.PendingTradesView.applyOffererState(PendingTradesView.java:298)
    at io.bitsquare.gui.main.portfolio.pending.PendingTradesView.lambda$initialize$193(PendingTradesView.java:131)
    at io.bitsquare.gui.main.portfolio.pending.PendingTradesView$$Lambda$304/1963700273.changed(Unknown Source)
    at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145)
    at io.bitsquare.gui.main.portfolio.pending.PendingTradesViewModel.updateState(PendingTradesViewModel.java:230)
    at io.bitsquare.gui.main.portfolio.pending.PendingTradesViewModel.doActivate(PendingTradesViewModel.java:89)
    at viewfx.model.support.ActivatableWithDelegate.activate(ActivatableWithDelegate.java:31)
    at viewfx.view.support.ActivatableViewAndModel.activate(ActivatableViewAndModel.java:38)
    at viewfx.view.support.ActivatableView.lambda$prepareInitialize$105(ActivatableView.java:37)
    at viewfx.view.support.ActivatableView$$Lambda$248/519960516.changed(Unknown Source)
    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
    at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
    at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:806)
    at javafx.scene.Node.invalidatedScenes(Node.java:856)
    at javafx.scene.Node.setScenes(Node.java:894)
    at javafx.scene.Parent$1.onChanged(Parent.java:271)
    at com.sun.javafx.collections.TrackableObservableList.lambda$new$20(TrackableObservableList.java:45)
    at com.sun.javafx.collections.TrackableObservableList$$Lambda$54/652768898.onChanged(Unknown Source)
    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
    at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
    at com.sun.javafx.scene.control.skin.TabPaneSkin$TabContentRegion.updateContent(TabPaneSkin.java:1538)
    at com.sun.javafx.scene.control.skin.TabPaneSkin$TabContentRegion.lambda$new$469(TabPaneSkin.java:1505)
    at com.sun.javafx.scene.control.skin.TabPaneSkin$TabContentRegion$$Lambda$372/1641430868.invalidated(Unknown Source)
    at javafx.beans.WeakInvalidationListener.invalidated(WeakInvalidationListener.java:83)
    at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145)
    at javafx.scene.control.Tab.setContent(Tab.java:330)
    at io.bitsquare.gui.main.portfolio.PortfolioView.loadView(PortfolioView.java:106)
    at io.bitsquare.gui.main.portfolio.PortfolioView.lambda$initialize$158(PortfolioView.java:64)
    at io.bitsquare.gui.main.portfolio.PortfolioView$$Lambda$249/104786552.onNavigationRequested(Unknown Source)
    at io.bitsquare.gui.Navigation.lambda$navigateTo$19(Navigation.java:89)
    at io.bitsquare.gui.Navigation$$Lambda$244/78191090.accept(Unknown Source)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at io.bitsquare.gui.Navigation.navigateTo(Navigation.java:89)
    at io.bitsquare.gui.Navigation.navigateTo(Navigation.java:60)
    at io.bitsquare.gui.main.portfolio.PortfolioView.doActivate(PortfolioView.java:85)
    at viewfx.view.support.ActivatableViewAndModel.activate(ActivatableViewAndModel.java:39)
    at viewfx.view.support.ActivatableView.lambda$prepareInitialize$105(ActivatableView.java:37)
    at viewfx.view.support.ActivatableView$$Lambda$248/519960516.changed(Unknown Source)
    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
    at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
    at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:806)
    at javafx.scene.Node.invalidatedScenes(Node.java:856)
    at javafx.scene.Node.setScenes(Node.java:894)
    at javafx.scene.Parent$1.onChanged(Parent.java:271)
    at com.sun.javafx.collections.TrackableObservableList.lambda$new$20(TrackableObservableList.java:45)
    at com.sun.javafx.collections.TrackableObservableList$$Lambda$54/652768898.onChanged(Unknown Source)
    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
    at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
    at io.bitsquare.gui.main.MainView.lambda$initialize$59(MainView.java:139)
    at io.bitsquare.gui.main.MainView$$Lambda$89/701518138.onNavigationRequested(Unknown Source)
    at io.bitsquare.gui.Navigation.lambda$navigateTo$19(Navigation.java:89)
    at io.bitsquare.gui.Navigation$$Lambda$244/78191090.accept(Unknown Source)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at io.bitsquare.gui.Navigation.navigateTo(Navigation.java:89)
    at io.bitsquare.gui.Navigation.navigateTo(Navigation.java:80)
    at io.bitsquare.gui.Navigation.navigateTo(Navigation.java:60)
    at io.bitsquare.gui.main.trade.createoffer.CreateOfferView.close(CreateOfferView.java:240)
    at io.bitsquare.gui.main.trade.createoffer.CreateOfferView.access$000(CreateOfferView.java:77)
    at io.bitsquare.gui.main.trade.createoffer.CreateOfferView$2.handle(CreateOfferView.java:321)
    at io.bitsquare.gui.main.trade.createoffer.CreateOfferView$2.handle(CreateOfferView.java:316)
    at org.controlsfx.dialog.Dialog$7.handle(Dialog.java:1095)
    at org.controlsfx.dialog.Dialog$7.handle(Dialog.java:1093)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Node.fireEvent(Node.java:8216)
    at javafx.scene.control.Button.fire(Button.java:185)
    at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3724)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3452)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1728)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2461)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:348)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:273)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:382)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:553)
    at com.sun.glass.ui.View.notifyMouse(View.java:925)
    at com.sun.glass.ui.mac.MacApplication._enterNestedEventLoopImpl(Native Method)
    at com.sun.glass.ui.mac.MacApplication._enterNestedEventLoop(MacApplication.java:114)
    at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:513)
    at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
    at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:519)
    at javafx.stage.Stage.showAndWait(Stage.java:462)
    at org.controlsfx.dialog.HeavyweightDialog$1.showAndWait(HeavyweightDialog.java:135)
    at org.controlsfx.dialog.HeavyweightDialog.show(HeavyweightDialog.java:278)
    at org.controlsfx.dialog.Dialog.show(Dialog.java:321)
    at org.controlsfx.dialog.Dialogs.showSimpleContentDialog(Dialogs.java:1106)
    at org.controlsfx.dialog.Dialogs.showInformation(Dialogs.java:531)
    at io.bitsquare.gui.components.Popups.openInfoPopup(Popups.java:82)
    at io.bitsquare.gui.main.trade.createoffer.CreateOfferView.lambda$setupListeners$245(CreateOfferView.java:329)
    at io.bitsquare.gui.main.trade.createoffer.CreateOfferView$$Lambda$587/983758695.changed(Unknown Source)
    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
    at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
    at javafx.beans.property.BooleanPropertyBase.access$000(BooleanPropertyBase.java:49)
    at javafx.beans.property.BooleanPropertyBase$Listener.invalidated(BooleanPropertyBase.java:244)
    at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
    at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
    at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:143)
    at io.bitsquare.gui.main.trade.createoffer.CreateOfferDataModel.lambda$placeOffer$275(CreateOfferDataModel.java:182)
    at io.bitsquare.gui.main.trade.createoffer.CreateOfferDataModel$$Lambda$613/1897768203.onResult(Unknown Source)
    at io.bitsquare.trade.TradeManager.lambda$requestPlaceOffer$103(TradeManager.java:182)
    at io.bitsquare.trade.TradeManager$$Lambda$615/1594032319.onResult(Unknown Source)
    at io.bitsquare.trade.protocol.createoffer.CreateOfferCoordinator$1.lambda$onSuccess$335(CreateOfferCoordinator.java:88)
    at io.bitsquare.trade.protocol.createoffer.CreateOfferCoordinator$1$$Lambda$618/745036095.handleResult(Unknown Source)
    at io.bitsquare.offer.tomp2p.TomP2POfferRepository$1.lambda$operationComplete$325(TomP2POfferRepository.java:82)
    at io.bitsquare.offer.tomp2p.TomP2POfferRepository$1$$Lambda$619/1452421672.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
    at com.sun.javafx.application.PlatformImpl$$Lambda$49/969226313.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
    at com.sun.javafx.application.PlatformImpl$$Lambda$48/545970252.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by cbeams** [comment]
Closing this for now, as it has no clear path to reproduction.

**Comment by ManfredKarrer** [comment]
The NP happened here:   BSResources.get(delegate.getTrade().getContract().getTakerBankAccount().getBankAccountType().toString());
It seems that the trade was failing and error handling is missing. Might be related to #327

**Comment by ManfredKarrer** [comment]
Close for now as it is from missing error handling which will be impl. when working on the trade process.
