### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by onlymarcus** [bisq-network/bisq#3394]
Deu esse erro agora e pediu para eu reportar. Isso aconteceu quando eu fiz um anuncio de compra de bitcoins em real brasileiro.

**Comment by freimair** [comment]
possible translation with the help of google:
"Bisq asked me to report this error. This happened when I tried to take an offer to buy bitcoins in Brazilian Real."

Can you provide us with the log file? The information as is not sufficient to do anything about that. Thanks!

**Comment by PicaroonEsp** [comment]
same error attach my log
[bisq.log](https://github.com/bisq-network/bisq/files/3798331/bisq.log)

Only happend first time open after update from version 2.1

**Comment by freimair** [comment]
thanks, seems like an issue with the tooltip implementation somehow. Tagging this as GUI related.

for the devs out there:

```
Nov-01 15:25:57.712 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Nov-01 15:25:57.712 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= null 
Nov-01 15:25:57.712 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.NullPointerException 
Nov-01 15:25:57.715 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException
	at javafx.controls/javafx.scene.control.Tooltip$TooltipBehavior.lambda$new$0(Tooltip.java:932)
	at javafx.graphics/javafx.animation.Animation.finished(Animation.java:1131)
	at javafx.graphics/javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)
	at javafx.graphics/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.graphics/javafx.animation.Animation.doTimePulse(Animation.java:1101)
	at javafx.graphics/javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:186)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/javafx.animation.Animation$1.timePulse(Animation.java:185)
	at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:514)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by ripcurlx** [comment]
@onlymarcus Do you still have this problem? Please re-open this issue if that is the case.
