### ISSUE TITLE
javax.imageio.IIOException

### ISSUE THREAD

**Issue by githubacc32** [bisq-network/bisq#3397]
Hello,

I'm getting this exception on startup (v1.1.7): javax.imageio.IIOException
The bisq process is running, the password prompt is shown but after unlocking, the main window never shows up.

Log file:
```
Okt.-13 02:17:32.653 [main] INFO  b.c.s.CoreSetup: 
Log files under: C:\Users\Administrator\AppData\Roaming\Bisq\bisq 
Okt.-13 02:17:32.668 [main] INFO  b.c.u.Utilities: System info: os.name=Windows Server 2016; os.version=10.0; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
Okt.-13 02:17:32.715 [main] INFO  b.c.s.CoreNetworkCapabilities: Set Capability.RECEIVE_BSQ_BLOCK 
Okt.-13 02:17:32.778 [main] INFO  b.c.app.Version: Version{VERSION=1.1.7, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Okt.-13 02:17:32.778 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: C:\Users\Administrator\AppData\Local\Bisq\app\desktop-1.1.7-all.jar 
Okt.-13 02:17:33.713 [JavaFX Application Thread] INFO  b.n.p.n.ConnectionConfig: ConnectionConfig{
     msgThrottlePerSec=200,
     msgThrottlePer10Sec=1000,
     sendMsgThrottleTrigger=20,
     sendMsgThrottleSleep=50
} 
Okt.-13 02:17:33.778 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [723ljisnynbtdohi.onion:8000, fl3mmribyxgrv63c.onion:8000, s67qglwhkgkyvr74.onion:8000, 3f3cu2yw7u457ztq.onion:8000, rm7b56wbrcczpjvl.onion:8000, jhgcy2won7xnslrb.onion:8000, 5quyxpxheyvzmb2d.onion:8000, ef5qnzx6znifo3df.onion:8000] 
Okt.-13 02:17:33.791 [JavaFX Application Thread] WARN  b.c.p.ProvidersRepository: We have banned provider nodes: bannedNodes=[5bmpx76qllutpcyp], selected provider baseUrl=http://44mgyoe2b6oqiytt.onion/, providerList=[http://44mgyoe2b6oqiytt.onion/, http://ceaanhbvluug4we6.onion/, http://62nvujg5iou3vu3i.onion/, http://xc3nh4juf2hshy7e.onion/] 
Okt.-13 02:17:33.921 [JavaFX Application Thread] INFO  b.c.s.CoreNetworkCapabilities: Set Capability.RECEIVE_BSQ_BLOCK 
Okt.-13 02:17:34.005 [JavaFX Application Thread] INFO  b.c.trade.Trade: Set new state at SellerAsMakerTrade (id=AAKCGDS): SELLER_SAW_ARRIVED_PAYOUT_TX_PUBLISHED_MSG 
Okt.-13 02:17:34.019 [JavaFX Application Thread] ERROR b.c.p.ProtoUtil: Invalid value for enum MediationResultState: PB_ERROR_MEDIATION_RESULT 
Okt.-13 02:17:34.019 [JavaFX Application Thread] ERROR b.c.p.ProtoUtil: We try to lookup for an enum entry with name 'UNDEFINED' and use that if available, otherwise the enum is null. enum=null 
Okt.-13 02:17:34.030 [JavaFX Application Thread] INFO  b.c.trade.Trade: Set new state at SellerAsMakerTrade (id=0199981): DEPOSIT_CONFIRMED_IN_BLOCK_CHAIN 
Okt.-13 02:17:34.031 [JavaFX Application Thread] ERROR b.c.p.ProtoUtil: Invalid value for enum MediationResultState: PB_ERROR_MEDIATION_RESULT 
Okt.-13 02:17:34.031 [JavaFX Application Thread] ERROR b.c.p.ProtoUtil: We try to lookup for an enum entry with name 'UNDEFINED' and use that if available, otherwise the enum is null. enum=null 
Okt.-13 02:17:34.032 [JavaFX Application Thread] INFO  b.c.trade.Trade: Set new state at SellerAsMakerTrade (id=486144): SELLER_SAW_ARRIVED_PAYOUT_TX_PUBLISHED_MSG 
Okt.-13 02:17:34.033 [JavaFX Application Thread] ERROR b.c.p.ProtoUtil: Invalid value for enum MediationResultState: PB_ERROR_MEDIATION_RESULT 
Okt.-13 02:17:34.034 [JavaFX Application Thread] ERROR b.c.p.ProtoUtil: We try to lookup for an enum entry with name 'UNDEFINED' and use that if available, otherwise the enum is null. enum=null 
Okt.-13 02:17:34.084 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: peersWithNoCapabilitiesSet=8, persistedPeerList.size()=87 
Okt.-13 02:17:34.609 [JavaFX Application Thread] ERROR b.d.app.BisqApp: Error during app init bisq.core.exceptions.BisqException: **javax.imageio.IIOException**: Can't create cache file!
	at bisq.desktop.app.SystemTray.init(SystemTray.java:134)
	at bisq.desktop.app.SystemTray.<init>(SystemTray.java:76)
	at bisq.desktop.app.SystemTray.create(SystemTray.java:70)
	at bisq.desktop.app.BisqApp.setupStage(BisqApp.java:243)
	at bisq.desktop.app.BisqApp.startApplication(BisqApp.java:140)
	at bisq.desktop.app.BisqAppMain.startApplication(BisqAppMain.java:131)
	at bisq.core.app.BisqExecutable.onApplicationLaunched(BisqExecutable.java:210)
	at bisq.desktop.app.BisqAppMain.onApplicationLaunched(BisqAppMain.java:99)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: javax.imageio.IIOException: Can't create cache file!
	at java.desktop/javax.imageio.ImageIO.createImageInputStream(ImageIO.java:361)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1409)
	at bisq.desktop.app.SystemTray.init(SystemTray.java:113)
	... 14 common frames omitted
Caused by: java.nio.file.NoSuchFileException: C:\Users\ADMINI~1\AppData\Local\Temp\2\imageio3639684228941507101.tmp
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:231)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:369)
	at java.base/java.nio.file.Files.createFile(Files.java:640)
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
	at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
	at java.base/java.nio.file.Files.createTempFile(Files.java:905)
	at java.desktop/javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:102)
	at java.desktop/com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(InputStreamImageInputStreamSpi.java:69)
	at java.desktop/javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
	... 16 common frames omitted

Okt.-13 02:17:34.903 [JavaFX Application Thread] ERROR b.d.app.BisqApp: Error at displaying Throwable. 
Okt.-13 02:17:36.507 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: TradeStatistics2StorageService: size of Storage: 11.605063 MB 
Okt.-13 02:17:36.577 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: AccountAgeWitnessStorageService: size of Storage: 1.151034 MB 
Okt.-13 02:17:36.592 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: ProposalStorageService: size of Storage: 0.025304 MB 
Okt.-13 02:17:36.602 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: BlindVoteStorageService: size of Storage: 0.180937 MB 
Okt.-13 02:17:36.602 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: We copy resource to file: resourceFileName=SignedWitnessStore_BTC_MAINNET, destinationFile=C:\Users\Administrator\AppData\Roaming\Bisq\btc_mainnet\db\SignedWitnessStore 
Okt.-13 02:17:36.603 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: Could not find resourceFile SignedWitnessStore_BTC_MAINNET. That is expected if none is provided yet. 
Okt.-13 02:17:36.632 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: TempProposalStorageService: size of Storage: 0.066896 MB 
Okt.-13 02:17:37.621 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: DaoStateStorageService: size of Storage: 25.98484 MB 
Okt.-13 02:17:37.623 [readFromResourcesThread] INFO  b.c.a.SetupUtils: readFromResources took 1657 ms 
Okt.-13 02:17:37.639 [NetworkNode-9999] INFO  b.n.p.n.NewTor: Starting tor 
Okt.-13 02:17:37.642 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: walletInitialized=false, p2pNetWorkReady=false 
Okt.-13 02:17:39.865 [NetworkNode-9999] INFO  o.b.n.tor.Tor: Starting Tor 
Okt.-13 02:17:46.638 [NetworkNode-9999] INFO  b.n.p.n.NewTor: 
################################################################
Tor started after 8999 ms. Start publishing hidden service.
################################################################ 
```

**Comment by freimair** [comment]
`ERROR b.d.app.BisqApp: Error during app init bisq.core.exceptions.BisqException: **javax.imageio.IIOException**: Can't create cache file!` in the context of the system tray seems to be the issue here.

@githubacc32 what OS are you using?

**Comment by ripcurlx** [comment]
@githubacc32 Does it work for you in the meantime? Please re-open this issue if you still can't launch Bisq with the latest version.
