### ISSUE TITLE
Linux version cannot connect to BTC network

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#340]
That problem is only on Linux with testnet. Mainnet is fine and all other OS versions are with testnet fine as well.

I get those errors logged:
The "Peer does not have a copy of the block chain" sounds like there are new sybil nodes out?

Logs:
 [NioClientManager] WARN  org.bitcoinj.core.PeerSocketHandler - [195.154.81.170]:8333 -  org.bitcoinj.core.ProtocolException: Peer does not have a copy of the block chain.
    at org.bitcoinj.core.Peer.processVersionMessage(Peer.java:452) ~[1.jar:na]
    at org.bitcoinj.core.Peer.processMessage(Peer.java:378) ~[1.jar:na]
    at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:178) ~[1.jar:na]
    at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:217) [1.jar:na]
    at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [1.jar:na]
    at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) [1.jar:na]
    at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) [1.jar:na]
    at com.google.common.util.concurrent.Callables$3.run(Callables.java:93) [1.jar:na]
    at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:27) [1.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

18:01:40.990 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery - Seed testnet-seed.bitcoin.schildbach.de: timed out 
18:01:40.990 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery - Seed testnet-seed.bitcoin.petertodd.org: timed out 
18:01:40.991 [PeerGroup Thread] ERROR org.bitcoinj.core.PeerGroup - Peer discovery failure org.bitcoinj.net.discovery.PeerDiscoveryException: No peer discovery returned any results: check internet connection?
    at org.bitcoinj.net.discovery.MultiplexingDiscovery.getPeers(MultiplexingDiscovery.java:85) ~[1.jar:na]
    at org.bitcoinj.core.PeerGroup.discoverPeers(PeerGroup.java:742) ~[1.jar:na]
    at org.bitcoinj.core.PeerGroup$5.go(PeerGroup.java:448) [1.jar:na]
    at org.bitcoinj.core.PeerGroup$5.run(PeerGroup.java:414) [1.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:27) [1.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

18:01:53.244 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery - Seed testnet-seed.bitcoin.schildbach.de: timed out 
18:01:53.244 [PeerGroup Thread] WARN  o.b.n.d.MultiplexingDiscovery - Seed testnet-seed.bitcoin.petertodd.org: timed out 
18:01:53.245 [PeerGroup Thread] ERROR org.bitcoinj.core.PeerGroup - Peer discovery failure org.bitcoinj.net.discovery.PeerDiscoveryException: No peer discovery returned any results: check internet connection?
    at org.bitcoinj.net.discovery.MultiplexingDiscovery.getPeers(MultiplexingDiscovery.java:85) ~[1.jar:na]
    at org.bitcoinj.core.PeerGroup.discoverPeers(PeerGroup.java:742) ~[1.jar:na]
    at org.bitcoinj.core.PeerGroup$5.go(PeerGroup.java:448) [1.jar:na]
    at org.bitcoinj.core.PeerGroup$5.run(PeerGroup.java:414) [1.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:27) [1.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by ManfredKarrer** [comment]
If I run a local Bictoin core testnet client (which is 9 weeks behind in syncing) the Bitsquare app connects to that local node and all works. So seems that the network connection to the outside testnet nodes has some issues, whats strange as only the port is different between mainnet and testnet as far as I know.

**Comment by ManfredKarrer** [comment]
I just tested with BitcoinJ wallet template and get the same problem when using testnet. I reported an issue on the mailinglist:
https://groups.google.com/forum/#!topic/bitcoinj/1dRPpvH0VsQ

**Comment by dworznik** [comment]
I found the testnet DNS seed nodes unreliable at times. I ended up configuring my own node (https://github.com/sipa/bitcoin-seeder) and [modifying TestNet3Params](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/params/TestNet3Params.java#L61).

**Comment by ManfredKarrer** [comment]
Ah thats great, we have had many problems in the past and I was also thinking to run my own seed node. Can we use your node, or is it just a temporary setup?

**Comment by dworznik** [comment]
You can try testnet-seed.runter.net. If it solves your problem, feel free to add it to your seed list. I'm not planning on shutting it down anytime soon.

**Comment by ManfredKarrer** [comment]
Cool! will test and add it for th next release!
