### ISSUE TITLE
"Check if offer is available" waits indefinitely

### ISSUE THREAD

**Issue by rkfg** [bisq-network/bisq#341]
Wanted to buy testcoins via the exchange and got that message on the "Take offer" tab. There's a spinner which spins forever without any visible progress. There are two offers available, one is mine (I can only remove it) and another one is someone else's (I can buy it which I actually did).

Log says:

```
23:02:11.803 [JavaFX Application Thread] DEBUG i.b.t.p.a.OfferAvailabilityProtocol - sequence at onCheckOfferAvailability completed 
SLF4J: Failed toString() invocation on an object of type [net.tomp2p.message.Message]
java.lang.ArrayIndexOutOfBoundsException: 105
    at net.tomp2p.rpc.RPC$Commands.find(RPC.java:39)
    at net.tomp2p.message.Message.toString(Message.java:964)
    at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:305)
    at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:277)
    at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:231)
    at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:298)
    at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:208)
    at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:212)
    at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:103)
    at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:88)
    at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
    at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:273)
    at ch.qos.logback.classic.Logger.callAppenders(Logger.java:260)
    at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:442)
    at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
    at ch.qos.logback.classic.Logger.error(Logger.java:555)
    at net.tomp2p.connection.Dispatcher.channelRead0(Dispatcher.java:158)
    at net.tomp2p.connection.Dispatcher.channelRead0(Dispatcher.java:62)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32)
    at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299)
    at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
23:02:12.351 [defaultEventExecutorGroup-2-7] ERROR net.tomp2p.connection.Dispatcher - Wrong version. We are looking for 11 but we got 181325824, received: [FAILED toString()] 
```

**Comment by ManfredKarrer** [comment]
Thats unfortunately a known issue with relay mode (you have relay mode right?). If you can enable UPnP and try again it should work. I hope to get that bug fixed soon.

**Comment by rkfg** [comment]
Yes, I'm in the relay mode. Now it says "The offerer is offline" which may be true as well. I'm now connected with UPnP forwarding, could you place an order for me to test?

**Comment by rkfg** [comment]
Hmm, there's even a double error now:
![2015-05-25-232251_726x676_scrot](https://cloud.githubusercontent.com/assets/184066/7801899/f9dae202-0334-11e5-9fa2-d052ee6138b6.png)

**Comment by ManfredKarrer** [comment]
Yes there are some UI glitches....
I just placed an offer with 0.01 BTC. You can take it, I will take yours.  (Check if you have the filter values set to 0, in the version built from code there might be presets for dev mode).

**Comment by ManfredKarrer** [comment]
I took that sell offer with 240 EUR and a buy with 230. Both are in progress state now. We need to wait for 1 blockchain confirmation.

**Comment by rkfg** [comment]
I see the offers but both buy and sell result in "offer is offline". I have "Connected with port forwarding" on the bottom right.

**Comment by rkfg** [comment]
Hmm, actually only "buy" fails. Selling seems to be working. I wonder what's the difference...

**Comment by ManfredKarrer** [comment]
I restarted a min. ago, maybe you just caught me there. Can you try again the 200 EUR buy offer?

**Comment by ManfredKarrer** [comment]
On trade is complete, the other 2 need your confim.

**Comment by rkfg** [comment]
Still says the offerer is offline. I may be mistaking something, there's an open order on Buy tab, amount is 0.10 (0.08 min), price is 200€. If it's not yours then it explains the error.

All trades now complete. Seems to be working!

**Comment by ManfredKarrer** [comment]
I just created a new one 222 EUR, 0.01. The other one was not from me...

**Comment by ManfredKarrer** [comment]
Yes sorry was confusing buy/sell offers before... (when you create a buy offer it ends up in the sell table)

**Comment by ManfredKarrer** [comment]
Yes now its taken.

**Comment by rkfg** [comment]
Yep, this one works. Anonymity may be confusing sometimes.

**Comment by ManfredKarrer** [comment]
Btw: Whats your background, seems you are good with networking stuff? I could need some help in that area if you have time/are interested. The TomP2P is quite a big complex library and I still had no time to dive deeper into it.

**Comment by ManfredKarrer** [comment]
Cool completed. So with port forwarding it seems to work more or less stable. I wanted to do a larger testing session with many nodes connected but need to get first the relay problem fixed.

**Comment by ManfredKarrer** [comment]
We can move over to IRC if you like...

**Comment by rkfg** [comment]
It's pretty late here and tomorrow is another working day so just a few words before going to bed. I mostly write webapps in Java/GWT, one of the latest projects was a helpdesk for my company with nearly realtime events everywhere. Like, you don't need to refresh the page at all and you see any task changes in a matter of 100s of milliseconds + pluggable notifications via mail/XMPP/SMS. Pretty handy thing I can say.

Also I've developed a system for citizen alerts via TV and buzzers, I used protobuffs there on Netty to implement a protocol for chunked file uploading, starting and stopping videos and audio, receiving the remote system status (whether it's our interception or the regular TV) etc. The system is built on RPi + custom hardware to wire it altogether (by my colleagues). It also switches network channels between the regular ADSL ISP and 3G in case of a connection failure.

My other programs include accounting of different things, everything is web-based so it's pretty useful I guess. I'm not so good at P2P though, tried to develop a distributed social network but it wasn't designed well enough and also I choose wrong tools. Thinking about trying once again some time later...

**Comment by ManfredKarrer** [comment]
Thanks! If you feel some day to dive in ping me :-)
TomP2P is cool but it need quite a bit of time. I am a bit worried about that part because its the biggest risk in the project and there are not many alternatives for a mature P2P network implementation. 
Another interesting project is Subspace (https://github.com/cpacia/Subspace/) from Chris Pacia.

**Comment by ManfredKarrer** [comment]
Closed as related to TomP2P which is not used anymore.
