### ISSUE TITLE
possiblePaymentAccounts.isEmpty()

### ISSUE THREAD

**Issue by bryanlivingston** [bisq-network/bisq#3537]
Got the error in the title when trying to take order to sell btc.
Log is attached.
[bisq.log](https://github.com/bisq-network/bisq/files/3795727/bisq.log)

**Comment by Criatura83** [comment]
I got the same error when trying to take an order to buy btc.
Log attached.

[bisq.log](https://github.com/bisq-network/bisq/files/3796453/bisq.log)

**Comment by fflo** [comment]
ditto

**Comment by Manew-des** [comment]
I have the same problem, any words guys ?

**Comment by mattmill30** [comment]
Is the issue related to the new "signed accounts" feature for bank accounts?

The issue doesn't occur when purchasing against my Faster Payments (GB) account, but that account doesn't require signing.

I'm wondering whether the situation is along the lines of:
TakeOfferDataModel.java (line 194): ObservableList<PaymentAccount> possiblePaymentAccounts = getPossiblePaymentAccounts();

v1.1.7 - Lists all offers for National Bank Account and the possiblePaymentAccounts variable is populated, but if Account isn't mature, will error when making a purchase with "account created after 1st March 2019".

v1.2.2 - Lists all offers for National Bank Account and the possiblePaymentAccounts variable is populated with _only signed_ accounts which may enumerate to 0. Then when attempting to make a purchase using the TAKE OFFER TO BUY BTC button, the TakeOfferDataModel.java (line 195) exception is thrown.

Just my two Satoshis.

[bisq - possiblePaymentAccounts.isEmpty.log](https://github.com/bisq-network/bisq/files/3814878/bisq.-.possiblePaymentAccounts.isEmpty.log)

**Comment by Perlover** [comment]
Same error, Bisq 1.2.3, Linux (official deb package)
My accoung is signed but not aged

I clicked by offer (The Tab "Sell bitcoin" - i wanted to sell bitcoin, filter BTC/EUR Revolut)
The destination offer was in range sum (0.05-0.1 BTC). Destination account is signed too (i see now 19 days ago). My account has 0.02 BTC (but a button of order was actived and i clicked). I got `isEmpty()`

Here is logs:

```
нояб.-15 15:24:35.407 [JavaFX Application Thread] INFO  b.d.app.BisqApp: System load: Memory (MB): 819 / No. of threads: 142 
нояб.-15 15:24:59.808 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
нояб.-15 15:24:59.808 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= possiblePaymentAccounts.isEmpty() 
нояб.-15 15:24:59.808 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.IllegalArgumentException 
нояб.-15 15:24:59.816 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.IllegalArgumentException: possiblePaymentAccounts.isEmpty()
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at bisq.desktop.main.offer.takeoffer.TakeOfferDataModel.initWithData(TakeOfferDataModel.java:195)
	at bisq.desktop.main.offer.takeoffer.TakeOfferViewModel.initWithData(TakeOfferViewModel.java:207)
	at bisq.desktop.main.offer.takeoffer.TakeOfferView.initWithData(TakeOfferView.java:339)
	at bisq.desktop.main.offer.OfferView.loadView(OfferView.java:222)
	at bisq.desktop.main.offer.OfferView.lambda$initialize$0(OfferView.java:100)
	at bisq.desktop.Navigation.lambda$navigateTo$1(Navigation.java:140)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.desktop.Navigation.navigateTo(Navigation.java:140)
	at bisq.desktop.Navigation.navigateTo(Navigation.java:104)
	at bisq.desktop.main.offer.OfferView.openTakeOffer(OfferView.java:259)
	at bisq.desktop.main.offer.OfferView.access$400(OfferView.java:58)
	at bisq.desktop.main.offer.OfferView$1.onTakeOffer(OfferView.java:194)
	at bisq.desktop.main.offer.offerbook.OfferBookView.onTakeOffer(OfferBookView.java:602)
	at bisq.desktop.main.offer.offerbook.OfferBookView.access$3600(OfferBookView.java:119)
	at bisq.desktop.main.offer.offerbook.OfferBookView$11$1.lambda$updateItem$2(OfferBookView.java:1022)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8865)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3876)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Scene.java:3604)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2613)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by ripcurlx** [comment]
> Same error, Bisq 1.2.3, Linux (official deb package)
> My accoung is signed but not aged
> 
> I clicked by offer (The Tab "Sell bitcoin" - i wanted to sell bitcoin, filter BTC/EUR Revolut)
> The destination offer was in range sum (0.05-0.1 BTC). Destination account is signed too (i see now 19 days ago). My account has 0.02 BTC (but a button of order was actived and i clicked). I got `isEmpty()`

In the account settings for your EUR Revolut account, what does your limits field say for sell BTC? 

I think the check for activating the "take offer" offer might not be correct.

**Comment by Perlover** [comment]
> In the account settings for your EUR Revolut account, what does your limits field say for sell BTC?

I have there two Revolut accounts.

1st account has:

```
Max. trade duration: 1 день / Max. buy: 0.01 BTC / Max. sell: 0.0625 BTC / Account age: 23 дн.
Signed by a peer, waiting for limits to be lifted / 15 дн. since signing
```

2nd (created as for my email not phone, only for testing):

```
Max. trade duration: 1 день / Max. buy: 0.01 BTC / Max. sell: 0.0625 BTC / Account age: 15 дн.
Not signed yet
```

So by limits i could take offer (Max sell 0.0625 BTC), right?

**Comment by Perlover** [comment]
> So by limits i could take offer (Max sell 0.0625 BTC), right?

But please notice that i didn't have enough bitcoins in Bisq's wallet for selling (0.02 vs 0.05) but i think it's not problem to take offer: Bisq could ask me to send bitcoins to Bisq for taking of offer.

**Comment by rafaelpac** [comment]
It only happens in offers that have min-max amounts.
Pull request #3625
