### ISSUE TITLE
windows must not be zero

### ISSUE THREAD

**Issue by dikdust** [bisq-network/bisq#3825]
### Description

when launching Bisq for the first time a white window apper with error
 in attachment. Nothing happens, only logs but the application never starts ..

#### Version

1.2.4

### Steps to reproduce

just launch in a terminal and watch logs

### Expected behaviour

application gives some type of output

### Actual behaviour

the application never starts

### Screenshots

![Selezione_044](https://user-images.githubusercontent.com/25555288/71320789-b2278580-24b0-11ea-920e-2428c62ea9d7.png)

#### Device or machine

ubuntu 18.04 on a Intel(R) Xeon(R) CPU           E5504  @ 2.00GHz with 10Gb Ram (sata disk) and rx 550 with kde plasma  but it seems it has very low performance

#### Additional info
dic-22 11:38:42.851 [JavaFX Application Thread] ERROR bisq.desktop.app.BisqApp: Error during app init java.lang.IllegalArgumentException: Window must not be zero
        at java.desktop/sun.awt.X11.XAtom.checkWindow(XAtom.java:774)
        at java.desktop/sun.awt.X11.XAtom.getAtomData(XAtom.java:465)
        at java.desktop/sun.awt.X11.XToolkit.getWorkArea(XToolkit.java:805)
        at java.desktop/sun.awt.X11.XToolkit.getInsets(XToolkit.java:881)
        at java.desktop/sun.awt.X11.XToolkit.getScreenInsets(XToolkit.java:869)
        at java.desktop/java.awt.Window.init(Window.java:518)
        at java.desktop/java.awt.Window.<init>(Window.java:448)
        at java.desktop/java.awt.Window.<init>(Window.java:573)
        at java.desktop/sun.awt.X11.InfoWindow.<init>(InfoWindow.java:66)
        at java.desktop/sun.awt.X11.InfoWindow$Balloon.<init>(InfoWindow.java:303)
        at java.desktop/sun.awt.X11.XTrayIconPeer.<init>(XTrayIconPeer.java:271)
        at java.desktop/sun.awt.X11.XToolkit.createTrayIcon(XToolkit.java:1304)
        at java.desktop/java.awt.TrayIcon.addNotify(TrayIcon.java:692)
        at java.desktop/java.awt.SystemTray.add(SystemTray.java:280)
        at bisq.desktop.app.SystemTray.init(SystemTray.java:130)
        at bisq.desktop.app.SystemTray.<init>(SystemTray.java:76)
        at bisq.desktop.app.SystemTray.create(SystemTray.java:70)
        at bisq.desktop.app.BisqApp.setupStage(BisqApp.java:237)
        at bisq.desktop.app.BisqApp.startApplication(BisqApp.java:135)
        at bisq.desktop.app.BisqAppMain.startApplication(BisqAppMain.java:131)
        at bisq.core.app.BisqExecutable.onApplicationLaunched(BisqExecutable.java:210)
        at bisq.desktop.app.BisqAppMain.onApplicationLaunched(BisqAppMain.java:99)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:844)

java.lang.IllegalArgumentException: Window must not be zero
        at java.desktop/sun.awt.X11.XAtom.checkWindow(XAtom.java:774)
        at java.desktop/sun.awt.X11.XAtom.getAtomData(XAtom.java:465)
        at java.desktop/sun.awt.X11.XToolkit.getWorkArea(XToolkit.java:805)
        at java.desktop/sun.awt.X11.XToolkit.getInsets(XToolkit.java:881)
        at java.desktop/sun.awt.X11.XToolkit.getScreenInsets(XToolkit.java:869)
        at java.desktop/java.awt.Window.init(Window.java:518)
        at java.desktop/java.awt.Window.<init>(Window.java:448)
        at java.desktop/java.awt.Window.<init>(Window.java:573)
        at java.desktop/sun.awt.X11.InfoWindow.<init>(InfoWindow.java:66)
        at java.desktop/sun.awt.X11.InfoWindow$Balloon.<init>(InfoWindow.java:303)
        at java.desktop/sun.awt.X11.XTrayIconPeer.<init>(XTrayIconPeer.java:271)
        at java.desktop/sun.awt.X11.XToolkit.createTrayIcon(XToolkit.java:1304)
        at java.desktop/java.awt.TrayIcon.addNotify(TrayIcon.java:692)
        at java.desktop/java.awt.SystemTray.add(SystemTray.java:280)
        at bisq.desktop.app.SystemTray.init(SystemTray.java:130)
        at bisq.desktop.app.SystemTray.<init>(SystemTray.java:76)
        at bisq.desktop.app.SystemTray.create(SystemTray.java:70)
        at bisq.desktop.app.BisqApp.setupStage(BisqApp.java:237)
        at bisq.desktop.app.BisqApp.startApplication(BisqApp.java:135)
        at bisq.desktop.app.BisqAppMain.startApplication(BisqAppMain.java:131)
        at bisq.core.app.BisqExecutable.onApplicationLaunched(BisqExecutable.java:210)
        at bisq.desktop.app.BisqAppMain.onApplicationLaunched(BisqAppMain.java:99)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by wiz** [comment]
Thanks for reporting - I assume you are using a non-default window manager (kde plasma?) - can you include instructions how to install / configure your window manager?

**Comment by dikdust** [comment]
sorry my fault .. is a 
dikdust@ml150:/opt/Bisq$ lsb_release -a
No LSB modules are available.
Distributor ID: neon
Description:    KDE neon User Edition 5.17
Release:        18.04
Codename:       bionic

installed with this repo
deb http://archive.neon.kde.org/user bionic main
if you want I can test with a more standard desktop manager shipped with 18.04

**Comment by dikdust** [comment]
problem persist on 1.2.5 with non standard 18.04 ubuntu (kde neon as explained above) after I have #3846 then the app ask for the password but stay in background forever without starting and throws out only "cannot connect to hidden services" in the logs. No issue with gnome anyway, if you want close it ;)

**Comment by drujd** [comment]
This is still a problem... KDE Plasma / Manjaro

**Comment by dikdust** [comment]
> This is still a problem... KDE Plasma / Manjaro

Solved with a clean install of kubuntu 20.04 bisq 1.3.4 perhaps we need to find the difference ... (plasma 5.18.x  on *ubuntu)
