### ISSUE TITLE
java.lang.NullPointerException while Bisq starts up

### ISSUE THREAD

**Issue by alan8325** [bisq-network/bisq#3908]
Getting the exception java.lang.NullPointerException during startup on Arch Linux. 

Below is the output of archlinux-java-status:

~]$ archlinux-java status
Available Java environments:
  java-10-openjdk
  java-13-openjdk (default)
  java-7-openjdk
  java-8-openjdk

Below is the section of the log with the error:

Jan-18 20:15:56.703 [ STARTING] INFO  b.c.b.s.WalletConfig: We try to connect to 9 btc nodes 
Jan-18 20:15:56.713 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Starting ... 
Jan-18 20:15:56.719 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [fz6nsij6jiyuwlsc.onion]:8333     (0 connected, 1 pending, 9 max) 
Jan-18 20:15:56.720 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [sslnjjhnmwllysv4.onion]:8333     (0 connected, 2 pending, 9 max) 
Jan-18 20:15:56.721 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [jiuuuislm7ooesic.onion]:8333     (0 connected, 3 pending, 9 max) 
Jan-18 20:15:56.721 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [22tg6ufbwz6o3l2u.onion]:8333     (0 connected, 4 pending, 9 max) 
Jan-18 20:15:56.722 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [4nnuyxm5k5tlyjq3.onion]:8333     (0 connected, 5 pending, 9 max) 
Jan-18 20:15:56.722 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [lva54pnbq2nsmjyr.onion]:8333     (0 connected, 6 pending, 9 max) 
Jan-18 20:15:56.724 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [mbm6ffx6j5ygi2ck.onion]:8333     (0 connected, 7 pending, 9 max) 
Jan-18 20:15:56.731 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [i3a5xtzfm4xwtybd.onion]:8333     (0 connected, 8 pending, 9 max) 
Jan-18 20:15:56.732 [PeerGroup Thread] INFO  o.b.c.PeerGroup: Attempting connection to [3r44ddzjitznyahw.onion]:8333     (0 connected, 9 pending, 9 max) 
Jan-18 20:15:56.785 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a PreliminaryGetDataRequest to peer s67qglwhkgkyvr74.onion:8000.  
Jan-18 20:15:56.819 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: Wallet password required 
Jan-18 20:15:56.820 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: onRequestWalletPassword 
Jan-18 20:15:56.820 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: onRequestWalletPassword 
Jan-18 20:15:56.905 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Jan-18 20:15:56.905 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= null 
Jan-18 20:15:56.905 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.NullPointerException 
Jan-18 20:15:56.906 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException
	at bisq.desktop.components.JFXTextFieldSkinBisqStyle.updateTextPos(JFXTextFieldSkinBisqStyle.java:95)
	at bisq.desktop.components.JFXTextFieldSkinBisqStyle.layoutChildren(JFXTextFieldSkinBisqStyle.java:79)
	at javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.scene.Parent.layout(Parent.java:1204)
	at javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.scene.Scene.preferredSize(Scene.java:1748)
	at javafx.scene.Scene$2.preferredSize(Scene.java:393)
	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.stage.Window$12.invalidated(Window.java:1086)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.stage.Window.show(Window.java:1189)
	at javafx.stage.Stage.show(Stage.java:273)
	at bisq.desktop.main.overlays.Overlay.display(Overlay.java:540)
	at bisq.desktop.main.overlays.windows.WalletPasswordWindow.show(WalletPasswordWindow.java:145)
	at bisq.desktop.main.MainViewModel.lambda$setupHandlers$14(MainViewModel.java:319)
	at bisq.core.app.BisqSetup.lambda$initWallet$11(BisqSetup.java:603)
	at bisq.core.app.WalletAppSetup.lambda$init$2(WalletAppSetup.java:164)
	at bisq.common.reactfx.FxTimer.lambda$restart$0(FxTimer.java:93)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.animation.Timeline.doPlayTo(Timeline.java:177)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:99)
	at javafx.animation.Animation.doTimePulse(Animation.java:1101)
	at javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:186)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:515)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by alan8325** [comment]
Resolved by setting Java environment to java-10-openjdk.

~]$ archlinux-java set java-10-openjdk
~]$ archlinux-java status
Available Java environments:
  java-10-openjdk (default)
  java-13-openjdk
  java-7-openjdk
  java-8-openjdk
