### ISSUE TITLE
Bisq tries to shutdown a nonexistent tor instance

### ISSUE THREAD

**Issue by leshik** [bisq-network/bisq#4181]
### Description

Seems that `bisq` tries to shut down the `tor` instance even if it wasn't started.

#### Version

`1.3.1`

### Steps to reproduce

```
/Applications/Bisq.app/Contents/MacOS/Bisq \
  --torControlUseSafeCookieAuth \
  --torControlPort=9051 \
  --torControlCookieFile=$PWD/tor/control_auth_cookie
```

### Expected behaviour

Bisq shouldn't try stopping the bundled `tor` if it was instructed to use an external instance.

### Actual behaviour

`Bisq` always tries to stop `tor` on shutdown.

#### Device or machine

macOS 10.15.4

#### Additional info

```
Apr-18 19:38:53.265 [torNetworkNodeShutDown-2113] ERROR b.n.p2p.network.TorNetworkNode: Shutdown torNetworkNode failed with exception: Error reply: Unknown Onion Service id
net.freehaven.tor.control.TorControlError: Error reply: Unknown Onion Service id
        at net.freehaven.tor.control.TorControlConnection.sendAndWaitForResponse(TorControlConnection.java:195)
        at net.freehaven.tor.control.TorControlConnection.destroyHiddenService(TorControlConnection.java:968)
        at org.berndpruenster.netlayer.tor.Tor.unpublishHiddenService(Tor.kt:299)
        at org.berndpruenster.netlayer.tor.ExternalTor.shutdown(ExternalTor.kt:174)
        at bisq.network.p2p.network.TorNetworkNode.lambda$torNetworkNodeShutDown$3(TorNetworkNode.java:189)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by freimair** [comment]
hi there and thanks for the stacktrace.

the stacktrace says that Bisq wants to shutdown the onion service it has used not tor. Do you see your external tor to be shutdown by Bisq?

we have seen that message for a long time now and it should be gone with the upcoming 1.3.2. Would you maybe check again once 1.3.2 is out?

Thanks!

**Comment by leshik** [comment]
Oh, I didn’t realize that. No, my external tor continues working. I will try 1.3.2, thanks!

**Comment by leshik** [comment]
1.3.2 doesn't suffer from this issue.
