### ISSUE TITLE
NullPointerException in AccountAgeWitnessService

### ISSUE THREAD

**Issue by eigentsmis** [bisq-network/bisq#4190]
Cannot tell exactly the timing of the issue or what triggered it but a NullPointerException pop-up was displayed. I've pasted below the relevant log info
This is on **v1.3.2**

Apr 21 [JavaFX Application Thread] INFO  b.c.a.w.AccountAgeWitnessService: AccountSigning:
tradeId: 123
is buyer: false
buyer account age witness info: UNSIGNED Not signed yet
Optional[AccountAgeWitness{
     hash=123,
     date=2020-04
}]
seller account age witness info: UNSIGNED Not signed yet
Optional[AccountAgeWitness{
     hash=123
     date=2020-01
}]
checking for sign trade: true
is myWitness signer: false
peer has signed witness: false
trade amount: 1000000
trade amount is sufficient: true
isSignWitnessTrade: false
Apr-22 22:58:19.484 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread
Apr-22 22:58:19.485 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= null
Apr-22 22:58:19.485 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.NullPointerException
Apr-22 22:58:19.487 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException
	at com.jfoenix.skins.JFXTextFieldSkin.updateTextPos(JFXTextFieldSkin.java:109)
	at com.jfoenix.skins.JFXTextFieldSkin.layoutChildren(JFXTextFieldSkin.java:93)
	at javafx.controls/javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:590)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2507)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:410)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:409)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Comment by ripcurlx** [comment]
@eigentsmis I fear this is something JFX library related. It might be worth to update to 9.0.10 from 9.0.6 at some point.

**Comment by ripcurlx** [comment]
This will be probably fixed with https://github.com/bisq-network/bisq/pull/4242.
