### ISSUE TITLE
Error during app init java.lang.IllegalArgumentException: Window must not be zero

### ISSUE THREAD

**Issue by drujd** [bisq-network/bisq#4286]
When starting the application on Manjaro + KDE Plasma (on X11) + 3 monitors:

Jun-08 12:11:03.216 [JavaFX Application Thread] ERROR b.d.app.BisqApp: Error during app init java.lang.IllegalArgumentException: Window must not be zero
	at java.desktop/sun.awt.X11.XAtom.checkWindow(XAtom.java:774)
	at java.desktop/sun.awt.X11.XAtom.getAtomData(XAtom.java:465)
	at java.desktop/sun.awt.X11.XToolkit.getWorkArea(XToolkit.java:805)
	at java.desktop/sun.awt.X11.XToolkit.getInsets(XToolkit.java:881)
	at java.desktop/sun.awt.X11.XToolkit.getScreenInsets(XToolkit.java:869)
	at java.desktop/java.awt.Window.init(Window.java:518)
	at java.desktop/java.awt.Window.<init>(Window.java:448)
	at java.desktop/java.awt.Window.<init>(Window.java:573)
	at java.desktop/sun.awt.X11.InfoWindow.<init>(InfoWindow.java:66)
	at java.desktop/sun.awt.X11.InfoWindow$Balloon.<init>(InfoWindow.java:303)
	at java.desktop/sun.awt.X11.XTrayIconPeer.<init>(XTrayIconPeer.java:271)
	at java.desktop/sun.awt.X11.XToolkit.createTrayIcon(XToolkit.java:1304)
	at java.desktop/java.awt.TrayIcon.addNotify(TrayIcon.java:692)
	at java.desktop/java.awt.SystemTray.add(SystemTray.java:280)
	at bisq.desktop.app.SystemTray.init(SystemTray.java:130)
	at bisq.desktop.app.SystemTray.<init>(SystemTray.java:76)
	at bisq.desktop.app.SystemTray.create(SystemTray.java:70)
	at bisq.desktop.app.BisqApp.setupStage(BisqApp.java:234)
	at bisq.desktop.app.BisqApp.startApplication(BisqApp.java:133)
	at bisq.desktop.app.BisqAppMain.startApplication(BisqAppMain.java:129)
	at bisq.core.app.BisqExecutable.onApplicationLaunched(BisqExecutable.java:139)
	at bisq.desktop.app.BisqAppMain.onApplicationLaunched(BisqAppMain.java:97)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)

Jun-08 12:11:03.347 [JavaFX Application Thread] ERROR b.d.app.BisqApp: Error at displaying Throwable.

The app itself seems to be running on first start, but there is no way to view the main window.
After the initial start and closing the application (by killing it, as there is no other way, the tray icon does nothing), the same exception causes Bisq to quit.

**Comment by HeroCC** [comment]
Same symptoms here -- don't suppose anyone has found a fix yet? Only difference is sometimes after waiting a bit another window opens telling me to about a NPE.

**Comment by cd2357** [comment]
Reopening, cause not sure if this was fixed.

@drujd @HeroCC what Bisq version were you running? Does this still happen with the latest release?

**Comment by HeroCC** [comment]
I'm not at the affected machine right now, but it was still happening as of the latest released version around late July / August. I was running Arch, also with KDE and 3 monitors of the same type. From what I remember, a window would open and close, the tray icon would stick around but be unresponsive, and I had to `killall Bisq` to get things to quit.

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which upgraded several UI components and libraries. Please try it out and let us know if it's still an issue for you.
