### ISSUE TITLE
crash of v.0.4.6 on debian 8

### ISSUE THREAD

**Issue by metabit** [bisq-network/bisq#458]
Additional info that might help: The app was running overnight. I am during a dispute now. Got message and sent message.
Is there any other info that I can add?

```
May-21 01:06:54.680 [JavaFX Application Thread] WARN  i.b.p.p.BroadcastHandler: stopped at sendToPeer: Message not broadcasted because we have stopped the handler already.
    message = RefreshTTLMessage{, hashOfDataAndSeqNr.hashCode()=1358352132, hashOfPayload.hashCode()=476620274,... 
May-21 01:06:54.886 [JavaFX Application Thread] WARN  i.b.p.p.BroadcastHandler: stopped at sendToPeer: Message not broadcasted because we have stopped the handler already.
    message = RefreshTTLMessage{, hashOfDataAndSeqNr.hashCode()=1358352132, hashOfPayload.hashCode()=476620274,... 
May-21 01:07:25.638 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-21 01:07:26.235 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
May-21 01:07:39.727 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
May-21 01:07:40.340 [InputHandler-port=9999] WARN  i.b.p.n.Connection$SharedModel: Unknown reason for exception at socket Proxy:localhost:56957 Version 5;addr:hrrytkr5kfjpsm24.onion,port:9999,localport:0
    connection=SharedSpace{, socket=Proxy:localhost:56957   Version 5;addr:hrrytkr5kfjpsm24.onion,port:9999,localport:0, ruleViolations={}}
    Exception= 
May-21 01:07:43.556 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= linkToTargetMethod=Lambda(a0:L,a1:L,a2:L)=>{
    t3:L=MethodHandle.invokeBasic(a2:L,a0:L,a1:L);t3:L} 
java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
    at io.bitsquare.p2p.network.Connection$InputHandler.run(Connection.java:777)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
java.lang.InternalError: linkToTargetMethod=Lambda(a0:L,a1:L,a2:L)=>{
    t3:L=MethodHandle.invokeBasic(a2:L,a0:L,a1:L);t3:L}
    at java.lang.invoke.MethodHandleStatics.newInternalError(MethodHandleStatics.java:127)
    at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:660)
    at java.lang.invoke.Invokers.callSiteForm(Invokers.java:381)
    at java.lang.invoke.Invokers.linkToTargetMethod(Invokers.java:347)
    at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:314)
    at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
    at io.bitsquare.app.BitsquareApp.lambda$start$1(BitsquareApp.java:122)
    at com.sun.glass.ui.Application.reportException(Application.java:453)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
May-21 01:07:54.850 [Thread-19] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread Thread-19 
May-21 01:07:56.235 [InputHandler-port=9999] WARN  i.b.p.n.Connection$SharedModel: Unknown reason for exception at socket Proxy:localhost:56957 Version 5;addr:fsrwzr2pfi4sxew5.onion,port:9999,localport:0
    connection=SharedSpace{, socket=Proxy:localhost:56957   Version 5;addr:fsrwzr2pfi4sxew5.onion,port:9999,localport:0, ruleViolations={}}
    Exception= 
java.lang.Exception: java.lang.OutOfMemoryError: Java heap spaceMay-21 01:07:56.428 [InputHandler-localPort=33794/port=50736] WARN  i.b.p.n.Connection$SharedModel: Unknown reason for exception at socket Socket[addr=/127.0.0.1,port=50736,localport=33794]
    connection=SharedSpace{, socket=Socket[addr=/127.0.0.1,port=50736,localport=33794], ruleViolations={}}
    Exception= 

    at io.bitsquare.p2p.network.Connection$InputHandler.run(Connection.java:777)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
May-21 01:07:56.817 [InputHandler-port=9999] WARN  i.b.p.n.Connection$SharedModel: Unknown reason for exception at socket Proxy:localhost:56957 Version 5;addr:fsuqrpggyuzjhqhe.onion,port:9999,localport:0
    connection=SharedSpace{, socket=Proxy:localhost:56957   Version 5;addr:fsuqrpggyuzjhqhe.onion,port:9999,localport:0, ruleViolations={}}
    Exception= 
May-21 01:07:57.014 [Thread-19] ERROR i.b.a.BitsquareApp: Uncaught Exception throwableMessage= Java heap space 
java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
    at io.bitsquare.p2p.network.Connection$InputHandler.run(Connection.java:783)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
    at io.bitsquare.p2p.network.Connection$InputHandler.run(Connection.java:777)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
May-21 01:08:05.967 [InputHandler-localPort=33794/port=50737] WARN  i.b.p.s.p.MailboxStoragePayload: Exception at readObject: Java heap space 
May-21 01:08:09.650 [Wallet autosave thread] WARN  o.b.core.Wallet: Temp file still exists after failed save. 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f8e85b235bf, pid=7634, tid=0x00007f8e22652700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x4685bf]*** Error in `/opt/Bitsquare/Bitsquare': malloc(): memory corruption: 0x00007f8df8002010 ***
Aborted
```

**Comment by ManfredKarrer** [comment]
Do u have a very restricted machine? I never got an out of memory error so far.

**Comment by metabit** [comment]
bitsquare runs in a debian 8 virtual machine on top of Qubes OS.
Except for default OS processes, it is the only process running.
The RAM settings for this vm is starting with 400MB and dynamically
growing towards 4000MB, and there is another 1GB swap which is hardly
used. It should be more than enough I guess.
Except for this it is 4 CPU and 2GB hard drive.
The crash has happened around 6 hours from starting (memory leak?)
I will report on other crashes when they happen.

a snapshot from top:

top - 07:44:23 up 4 days, 18:41,  2 users,  load average: 0.20, 0.24, 0.48
Tasks: 137 total,   2 running, 135 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.7 us,  1.8 sy,  0.0 ni, 95.1 id,  0.2 wa,  0.0 hi,  0.0 si, 0.3 st
KiB Mem:    885252 total,   665448 used,   219804 free,    19908 buffers
KiB Swap:  1048572 total,    42672 used,  1005900 free.   156292 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME COMMAND  
13863 user      20   0 3892388 342064  41728 S  11.3 38.6   2:19.96 Bitsquare

**Comment by ManfredKarrer** [comment]
342 mb should not cause a out of memory on such a vm.

**Comment by ManfredKarrer** [comment]
Related to https://github.com/bitsquare/bitsquare/issues/463
