### ISSUE TITLE
bitcoinj wallet serialization issue on shutdown

### ISSUE THREAD

**Issue by oscarguindzberg** [bisq-network/bisq#4580]
Sep.-30 09:39:31.805 [ STOPPING] ERROR org.bitcoinj.wallet.Wallet: Failed whilst saving wallet java.lang.NullPointerException: null
    at org.bitcoinj.wallet.WalletProtobufSerializer.writeConfidence(WalletProtobufSerializer.java:392)
    at org.bitcoinj.wallet.WalletProtobufSerializer.makeTxProto(WalletProtobufSerializer.java:320)
    at org.bitcoinj.wallet.WalletProtobufSerializer.walletToProto(WalletProtobufSerializer.java:183)
    at org.bitcoinj.wallet.WalletProtobufSerializer.writeWallet(WalletProtobufSerializer.java:153)
    at org.bitcoinj.wallet.Wallet.saveToFileStream(Wallet.java:1684)
    at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1498)
    at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1538)
    at bisq.core.btc.setup.WalletConfig.shutDown(WalletConfig.java:433)
    at com.google.common.util.concurrent.AbstractIdleService$DelegateService$2.run(AbstractIdleService.java:79)
    at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
    at java.base/java.lang.Thread.run(Thread.java:844)

java.lang.NullPointerException: null
    at org.bitcoinj.wallet.WalletProtobufSerializer.writeConfidence(WalletProtobufSerializer.java:392)
    at org.bitcoinj.wallet.WalletProtobufSerializer.makeTxProto(WalletProtobufSerializer.java:320)
    at org.bitcoinj.wallet.WalletProtobufSerializer.walletToProto(WalletProtobufSerializer.java:183)
    at org.bitcoinj.wallet.WalletProtobufSerializer.writeWallet(WalletProtobufSerializer.java:153)
    at org.bitcoinj.wallet.Wallet.saveToFileStream(Wallet.java:1684)
    at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1498)
    at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1538)
    at bisq.core.btc.setup.WalletConfig.shutDown(WalletConfig.java:433)
    at com.google.common.util.concurrent.AbstractIdleService$DelegateService$2.run(AbstractIdleService.java:79)
    at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
    at java.base/java.lang.Thread.run(Thread.java:844)
Sep.-30 09:39:31.806 [ STOPPING] WARN  org.bitcoinj.wallet.Wallet: Temp file still exists after failed save. 
Sep.-30 09:39:31.807 [JavaFX Application Thread] INFO  b.core.btc.setup.WalletsSetup: walletConfig shutDown interrupted by timeout 
Sep.-30 09:39:31.807 [JavaFX Application Thread] INFO  bisq.core.app.BisqExecutable: WalletsSetup shutdown completed 
Sep.-30 09:39:31.808 [JavaFX Application Thread] ERROR b.core.btc.setup.WalletsSetup: Service failure from state: STOPPING; failure={} java.lang.NullPointerException: null
    at org.bitcoinj.wallet.WalletProtobufSerializer.writeConfidence(WalletProtobufSerializer.java:392)
    at org.bitcoinj.wallet.WalletProtobufSerializer.makeTxProto(WalletProtobufSerializer.java:320)
    at org.bitcoinj.wallet.WalletProtobufSerializer.walletToProto(WalletProtobufSerializer.java:183)
    at org.bitcoinj.wallet.WalletProtobufSerializer.writeWallet(WalletProtobufSerializer.java:153)
    at org.bitcoinj.wallet.Wallet.saveToFileStream(Wallet.java:1684)
    at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1498)
    at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1538)
    at bisq.core.btc.setup.WalletConfig.shutDown(WalletConfig.java:433)
    at com.google.common.util.concurrent.AbstractIdleService$DelegateService$2.run(AbstractIdleService.java:79)
    at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
    at java.base/java.lang.Thread.run(Thread.java:844)

java.lang.NullPointerException: null
    at org.bitcoinj.wallet.WalletProtobufSerializer.writeConfidence(WalletProtobufSerializer.java:392)
    at org.bitcoinj.wallet.WalletProtobufSerializer.makeTxProto(WalletProtobufSerializer.java:320)
    at org.bitcoinj.wallet.WalletProtobufSerializer.walletToProto(WalletProtobufSerializer.java:183)
    at org.bitcoinj.wallet.WalletProtobufSerializer.writeWallet(WalletProtobufSerializer.java:153)
    at org.bitcoinj.wallet.Wallet.saveToFileStream(Wallet.java:1684)
    at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1498)
    at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1538)
    at bisq.core.btc.setup.WalletConfig.shutDown(WalletConfig.java:433)
    at com.google.common.util.concurrent.AbstractIdleService$DelegateService$2.run(AbstractIdleService.java:79)
    at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
    at java.base/java.lang.Thread.run(Thread.java:844)
Sep.-30 09:39:31.810 [JavaFX Application Thread] ERROR bisq.core.app.WalletAppSetup: java.lang.NullPointerException

**Comment by oscarguindzberg** [comment]
The cause seems to be bisq's custom bitcoinj PeerAddreas has a new hostname field. bitcoinj wallet protobuf serialization was not adapted to the new field.

**Comment by oscarguindzberg** [comment]
The field was added in 2017 with this commit https://github.com/bisq-network/bitcoinj/commit/5cfebe60de07d7b929cea34299ce062cfd3026c1#diff-3db99abded2a4bee7ff46117bcd87b23
