### ISSUE TITLE
Got no window, appear in taskbar and nothing more.

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#4591]
### Description

Got no window, appear in taskbar and nothing more.

#### Version

1.3.9

### Steps to reproduce

Update to 1.3.9 from 1.3.6

### Actual behaviour

Appear in taskbar and nothing more.

### Screenshots

![Screenshot from 2020-10-02 09-41-18](https://user-images.githubusercontent.com/52659208/94929749-09816a00-04b5-11eb-912c-d253e5f581d9.png)

#### Additional info

Oct-02 09:39:12.051 [main] INFO  b.c.u.Utilities: System info: os.name=Linux; os.version=5.4.0-48-generic; os.arch=amd64; sun.arch.data.model=64; JRE=10.0.2+13 (Oracle Corporation); JVM=10.0.2+13 (Java HotSpot(TM) 64-Bit Server VM) 
Oct-02 09:39:12.053 [main] INFO  b.c.s.CoreNetworkCapabilities: Set Capability.RECEIVE_BSQ_BLOCK 
Oct-02 09:39:12.151 [main] INFO  b.c.app.Version: Version{VERSION=1.3.9, P2P_NETWORK_VERSION=1, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=2, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=10} 
Oct-02 09:39:12.152 [main] INFO  b.c.s.CoreSetup: Path to Bisq jar file: /opt/Bisq/app/desktop-1.3.9-all.jar 
Oct-02 09:39:13.193 [JavaFX Application Thread] WARN  b.c.p.ProvidersRepository: We have banned provider nodes: bannedNodes=[5bmpx76qllutpcyp], selected provider baseUrl=http://aprcndeiwdrkbf4fq7iozxbd27dl72oeo76n7zmjwdi4z34agdrnheyd.onion/, providerList=[http://aprcndeiwdrkbf4fq7iozxbd27dl72oeo76n7zmjwdi4z34agdrnheyd.onion/, http://ro7nv73awqs3ga2qtqeqawrjpbxwarsazznszvr6whv7tes5ehffopid.onion/, http://wizpriceje6q5tdrxkyiazsgu7irquiqjy2dptezqhrtu7l2qelqktid.onion/, http://emzypricpidesmyqg2hc6dkwitqzaxrqnpkdg3ae2wef5znncu2ambqd.onion/, http://devinpndvdwll4wiqcyq5e7itezmarg7rzicrvf6brzkwxdm374kmmyd.onion/] 
Oct-02 09:39:13.221 [JavaFX Application Thread] INFO  b.c.n.p.s.DefaultSeedNodeRepository: Seed nodes: [723ljisnynbtdohi.onion:8000, devinv3rhon24gqf5v6ondoqgyrbzyqihzyouzv7ptltsewhfmox2zqd.onion:8000, s67qglwhkgkyvr74.onion:8000, sn2bisqad7ncazupgbd3dcedqh5ptirgwofw63djwpdtftwhddo75oid.onion:8000, rm7b56wbrcczpjvl.onion:8000, wizseedscybbttk4bmb2lzvbuk2jtect37lcpva4l3twktmkzemwbead.onion:8000, devinsn2teu33efff62bnvwbxmfgbfjlgqsu3ad4b4fudx3a725eqnyd.onion:8000, devinsn3xuzxhj6pmammrxpydhwwmwp75qkksedo5dn2tlmu7jggo7id.onion:8000, wizseed7ab2gi3x267xahrp2pkndyrovczezzb46jk6quvguciuyqrid.onion:8000, sn3emzy56u3mxzsr4geysc52feoq5qt7ja56km6gygwnszkshunn2sid.onion:8000, wizseed3d376esppbmbjxk2fhk2jg5fpucddrzj2kxtbxbx4vrnwclad.onion:8000, 5quyxpxheyvzmb2d.onion:8000] 
Oct-02 09:39:13.372 [JavaFX Application Thread] INFO  b.c.s.CoreNetworkCapabilities: Set Capability.RECEIVE_BSQ_BLOCK 
Oct-02 09:39:13.514 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: peersWithNoCapabilitiesSet=12, persistedPeerList.size()=333 
Oct-02 09:39:13.716 [JavaFX Application Thread] INFO  b.c.b.n.LocalBitcoinNode: No local Bitcoin node detected on port 8333. 
Oct-02 09:39:14.870 [JavaFX Application Thread] ERROR b.d.app.BisqApp: Error during app init java.lang.IllegalArgumentException: Window must not be zero
	at java.desktop/sun.awt.X11.XAtom.checkWindow(XAtom.java:774)
	at java.desktop/sun.awt.X11.XAtom.getAtomData(XAtom.java:465)
	at java.desktop/sun.awt.X11.XToolkit.getWorkArea(XToolkit.java:805)
	at java.desktop/sun.awt.X11.XToolkit.getInsets(XToolkit.java:881)
	at java.desktop/sun.awt.X11.XToolkit.getScreenInsets(XToolkit.java:869)
	at java.desktop/java.awt.Window.init(Window.java:518)
	at java.desktop/java.awt.Window.<init>(Window.java:448)
	at java.desktop/java.awt.Window.<init>(Window.java:573)
	at java.desktop/sun.awt.X11.InfoWindow.<init>(InfoWindow.java:66)
	at java.desktop/sun.awt.X11.InfoWindow$Balloon.<init>(InfoWindow.java:303)
	at java.desktop/sun.awt.X11.XTrayIconPeer.<init>(XTrayIconPeer.java:271)
	at java.desktop/sun.awt.X11.XToolkit.createTrayIcon(XToolkit.java:1304)
	at java.desktop/java.awt.TrayIcon.addNotify(TrayIcon.java:692)
	at java.desktop/java.awt.SystemTray.add(SystemTray.java:280)
	at bisq.desktop.app.SystemTray.init(SystemTray.java:130)
	at bisq.desktop.app.SystemTray.<init>(SystemTray.java:76)
	at bisq.desktop.app.SystemTray.create(SystemTray.java:70)
	at bisq.desktop.app.BisqApp.setupStage(BisqApp.java:235)
	at bisq.desktop.app.BisqApp.startApplication(BisqApp.java:133)
	at bisq.desktop.app.BisqAppMain.startApplication(BisqAppMain.java:126)
	at bisq.core.app.BisqExecutable.onApplicationLaunched(BisqExecutable.java:140)
	at bisq.desktop.app.BisqAppMain.onApplicationLaunched(BisqAppMain.java:95)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)

Oct-02 09:39:15.291 [JavaFX Application Thread] ERROR b.d.app.BisqApp: Error at displaying Throwable. 
Oct-02 09:39:15.695 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: SignedWitnessStorageService: size of Storage: 3.915346 MB 
Oct-02 09:39:15.887 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: AccountAgeWitnessStorageService: size of Storage: 1.959111 MB 
Oct-02 09:39:20.603 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: TradeStatistics2StorageService: size of Storage: 16.410721 MB 
Oct-02 09:39:20.629 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: ProposalStorageService: size of Storage: 0.103269 MB 
Oct-02 09:39:20.647 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: BlindVoteStorageService: size of Storage: 0.94042 MB 
Oct-02 09:39:20.675 [readFromResourcesThread] INFO  b.n.p.s.p.StoreService: TempProposalStorageService: size of Storage: 0.086402 MB

**Comment by cd2357** [comment]
Seems related to #2452, #3825 and #4286

**Comment by cd2357** [comment]
@cldtech so v1.3.6 worked fine, but as soon as you upgraded to v.1.3.9 you got this error?

Also, what version of Linux were you using?

**Comment by ghost** [comment]
Yes, for me it came when i installed the .deb for 1.3.9. Then no more window. Ubuntu 20.04 focal (x86-64).

**Comment by ripcurlx** [comment]
Maybe it is a JavaFX/Java issue that might get fixed by our attempt to upgrade JavaFX/Java 🤞  https://github.com/bisq-network/bisq/pull/4242

**Comment by cd2357** [comment]
Should be fixed in the most recent release (v1.6.4) which upgraded several UI components and libraries. Please try it out and let us know if it's still an issue for you.
