### ISSUE TITLE
Nullpointer at show private keys at wallet info popup at v1.4.0

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4621]
### Description

Nullpointer at show private keys at wallet info popup

#### Version

1.4.0

### Steps to reproduce

Set wallet password. click cmd+j to open wallet info window. Select show private keys checkbox. 

### Expected behaviour

No exception

### Actual behaviour

Exception is thrown.

#### Additional info

The reason is that we do not keep the AES key so when it is needed for showing the private keys it gets a nullpointer.
I tested with 1.3.9 and there it works.

Stacktrace:

```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
	at org.bitcoinj.crypto.KeyCrypterScrypt.decrypt(KeyCrypterScrypt.java:213)
	at org.bitcoinj.wallet.DeterministicSeed.decrypt(DeterministicSeed.java:209)
	at org.bitcoinj.wallet.DeterministicKeyChain.toString(DeterministicKeyChain.java:1392)
	at org.bitcoinj.wallet.KeyChainGroup.toString(KeyChainGroup.java:1071)
	at org.bitcoinj.wallet.Wallet.toString(Wallet.java:3424)
	at bisq.core.btc.wallet.BtcWalletService.getWalletAsString(BtcWalletService.java:144)
	at bisq.core.btc.wallet.WalletsManager.getWalletsAsString(WalletsManager.java:89)
	at bisq.desktop.main.overlays.windows.ShowWalletDataWindow.showWallet(ShowWalletDataWindow.java:109)
	at bisq.desktop.main.overlays.windows.ShowWalletDataWindow.lambda$addContent$1(ShowWalletDataWindow.java:99)
```

**Comment by oscarguindzberg** [comment]
In 1.3.9 there is also a bug: if wallet is encrypted and "Include private keys" is checked, priv key is not really included, only the public key.

**Comment by oscarguindzberg** [comment]
Fixed with https://github.com/bisq-network/bisq/pull/4627

**Comment by chimp1984** [comment]
Ah ok, have not checked more closely... thanks for the quick fix.

**Comment by ripcurlx** [comment]
Closing as complete. Merged into release branch.
