### ISSUE TITLE
Feature: Add "Don't show again flag" for systray warnings

### ISSUE THREAD

**Issue by NetworkJack2** [bisq-network/bisq#4691]
### Description

For desktops, such as GNOME that don't have a systray, bisq every couple of min has a pop up warning that it can't find one. Great. Please add another flag to suppress this

#### Device or machine
Arch linux

Linux BOXNAME 5.8.16.a-1-hardened #1 SMP PREEMPT Sat, 17 Oct 2020 13:04:20 +0000 x86_64 GNU/Linux
pacman -Q bisq
bisq 1.4.2-1

**Comment by ghost** [comment]
What OS distro & version are you running?  Could you paste here a screenshot of the popup?

**Comment by NetworkJack2** [comment]
![systray_error](https://user-images.githubusercontent.com/6799601/97115706-7eb81780-16ce-11eb-8141-0c810001ff97.png)

**Comment by ghost** [comment]
Thanks for the screenshot and for informing that OS is Arch linux.  Looks like a generic exception handler in Bisq popped up the error dialog.  The message `The system tray is not supported on the current platform` is coming from Java AWT.  It would also be helpful to see the exception callstack that gets written to the log file upon this error happening, so as to know which line of code is triggering it.  

Probably we have to find a dev with Arch linux willing to debug this.
It does not happen on Ubuntu 18.04 (GNOME).

**Comment by ghost** [comment]
I [installed](https://itsfoss.com/install-arch-linux/) Arch linux and Bisq 1.4.2; it runs fine and did not produce for me the error popups you experienced.  Perhaps a configuration issue.  I'm open to suggestions on how to reproduce this issue on Arch; otherwise its a one-off issue that cannot be reproduced.

**Comment by NetworkJack2** [comment]
Use GNOME, or another DE that doesn't have a native systray

**Comment by ghost** [comment]
Yes, using GNOME, details below.  Bisq runs fine and did not produce for me the error popups you experienced.

![image](https://user-images.githubusercontent.com/47253594/99760452-5ea32a80-2ab9-11eb-90c2-eadd6e2fd51b.png)

**Comment by premek** [comment]
I have the same warning showing up every time my laptop locks the screen after inactivity. 
I'm on Gnome 3.38.0

The exception in the log is as follows.
```
Dec-01 01:24:40.490 [AWT-EventQueue-0] ERROR b.c.s.CommonSetup: Uncaught Exception from thread AWT-EventQueue-0 
Dec-01 01:24:40.490 [AWT-EventQueue-0] ERROR b.c.s.CommonSetup: throwableMessage= The system tray is not supported on the current platform. 
Dec-01 01:24:40.490 [AWT-EventQueue-0] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.UnsupportedOperationException 
Dec-01 01:24:40.490 [AWT-EventQueue-0] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
	at java.desktop/java.awt.SystemTray.getSystemTray(SystemTray.java:188)
	at java.desktop/sun.awt.X11.XTrayIconPeer$4$1.run(XTrayIconPeer.java:222)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
Note the empty space in the top right corner where the icon should probably be, i can rightclick there but the icon is in the top left corner (not active).

![Screenshot from 2020-12-01 09-56-46](https://user-images.githubusercontent.com/1145361/100718720-f22f0200-33bb-11eb-8541-668777b5cb79.png)

**Comment by ghost** [comment]
@premek Thanks for the useful info!  It seems we are running the same OS but as you can see the bar at the top of the screen seems a little different.  On mine there is no systray icon, nor errors.  Hmm.  I built my Bisq from source, is yours from the AUR?  If so would you tell me steps to install Bisq from pacman/AUR, I tried but could not get it to work.

![Screenshot from 2020-12-02 15-13-26](https://user-images.githubusercontent.com/47253594/100891875-59fa5100-347f-11eb-9c60-28927b3ae56c.png)

Anyway, based on the stack trace you provided I can make a PR to prevent the popup.  It will be linked here shortly.

**Comment by premek** [comment]
I'm on debian and using the downloaded .deb file. I have some gnome extensions installed which moves things around in the top bar.
It would be nice not to have the popup every now and then but for me the icon is still displaced but that may be another issue.
