### ISSUE TITLE
[REGTEST] Exception in BSQ wallet transactions view

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#4775]
I'm getting an exception in regtest when opening the BSQ transactions view.  Not sure if it is a legitimate problem or if I have a screwed up wallet.  Last time I did any BSQ transactions in regtest was Oct 12 during testing of v1.4.0.  I was sending BSQ from Alice to Bob and vice-versa.  Have not noticed any issues until now.

The exception: `org.bitcoinj.core.SegwitAddress cannot be cast to org.bitcoinj.core.LegacyAddress `

At this line of code: https://github.com/bisq-network/bisq/blob/0345c795e2c227d827a1f239a323dda1250f4e69/desktop/src/main/java/bisq/desktop/main/dao/wallet/tx/BsqTxListItem.java#L106

The transaction that is causing the exception:
<details><summary>details</summary>

    -0.0001 BTC total value (sends 2.49997904 BTC and receives 2.49987904 BTC)
      confidence: Appeared in best chain at height 2671, depth 660. Source: NETWORK
      f54ac3658bcf92df563299007a7f326b096d9e5c3dcf2460aef251a768c40fde, wtxid ca2c67935fb8a549a5f54c312ea480f167c6f07e95f1f9a5040752cb513f0042
      updated: 2020-10-12T14:44:38Z
      included in best chain at: 2020-10-12T14:44:50Z
      purpose: USER_PAYMENT
         in   PUSHDATA(72)[304502210080767bdcb33a70be5a87ebbe5fab47084dd3c734e3380c43a103702afca2b7f6022061f836f490527103b2965d0cb85311e2f4af7c149ab575453c9ddd2c8fc28e8101] PUSHDATA(33)[02218b2da40151be2d3b3d9dd91e8a566f125b485386c4f747305ad899c1e0eb68]  2.49997904 BTC (249997904)
              P2PKH addr:miWJKUMVvcxe9a5ihQitwqkUwspYpEx9ix  outpoint:fb84433d6952db5e3ee650fae6c6eefcdf91e0c433229acc20fd527f1f58ce60:1
         in   <empty>  0.05760397 BTC (5760397)
              witness:3045022100f848605134cfa3321320e034fcfd3ac026afa8fb2ccd11974738564ca4496f9902202472c4ac56e47855f407992ad91fabf8660bf942c67dd8e4633c321235526a8c01 02fceff430c5b01ee6444519dd5866a3ff09adfb4dea900ce8166922ee4dc4733f
              unconnected  outpoint:f2b59d1c0d23b499d01cc6cd63efba560d8c16b80093f4eb93e4398c7130a1c9:2
         out  DUP HASH160 PUSHDATA(20)[8d17b1c34129de2a09e9e30bbc6592f0d58d71f0] EQUALVERIFY CHECKSIG (76a9148d17b1c34129de2a09e9e30bbc6592f0d58d71f088ac)  0.0001 BTC (10000)
              P2PKH addr:mtNyxR8ecLq9BkkpyUefYDmFCFFFmLWhnG  spent by:290c72085a4db06184d7d64058a2ec4a610853137fa3c30b1ab64256b7e26825:0
         out  DUP HASH160 PUSHDATA(20)[11c25915f5e24f8868672945519d58d1cf4ccff6] EQUALVERIFY CHECKSIG (76a91411c25915f5e24f8868672945519d58d1cf4ccff688ac)  2.49987904 BTC (249987904)
              P2PKH addr:mh8rbrGhDpn13npsxCZ2XznAdrhCTTZGa7
         out  0[] PUSHDATA(20)[34caaf93075fc6d1a404eb77d8e88431cf839d2d] (001434caaf93075fc6d1a404eb77d8e88431cf839d2d)  0.05734252 BTC (5734252)
              P2WPKH addr:bcrt1qxn92lyc8tlrdrfqyadma36yyx88c88fd9qp7ep
         fee  0.00063924 BTC/kB, 0.00026145 BTC for 409 bytes

</details>

Exception:
<details><summary>details</summary>

    Nov-09 17:23:13.493 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
    Nov-09 17:23:13.493 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= org.bitcoinj.core.SegwitAddress cannot be cast to org.bitcoinj.core.LegacyAddress 
    Nov-09 17:23:13.493 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.ClassCastException 
    Nov-09 17:23:13.533 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
    java.lang.ClassCastException: org.bitcoinj.core.SegwitAddress cannot be cast to org.bitcoinj.core.LegacyAddress
	    at bisq.desktop.main.dao.wallet.tx.BsqTxListItem.<init>(BsqTxListItem.java:106)
	    at bisq.desktop.main.dao.wallet.tx.BsqTxView.lambda$updateList$1(BsqTxView.java:317)
	    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	    at bisq.desktop.main.dao.wallet.tx.BsqTxView.updateList(BsqTxView.java:320)
	    at bisq.desktop.main.dao.wallet.tx.BsqTxView.activate(BsqTxView.java:193)
	    at bisq.desktop.common.view.ActivatableView.lambda$prepareInitialize$0(ActivatableView.java:37)
	    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	    at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	    at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	    at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1054)
	    at javafx.scene.Node.invalidatedScenes(Node.java:1114)
	    at javafx.scene.Node.setScenes(Node.java:1152)
	    at javafx.scene.Parent$2.onChanged(Parent.java:369)
	    at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	    at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
	    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	    at bisq.desktop.main.dao.wallet.BsqWalletView.loadView(BsqWalletView.java:130)
	    at bisq.desktop.main.dao.wallet.BsqWalletView.lambda$initialize$0(BsqWalletView.java:79)
	    at bisq.desktop.Navigation.lambda$navigateTo$2(Navigation.java:140)
	    at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	    at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	    at bisq.desktop.Navigation.navigateTo(Navigation.java:140)
	    at bisq.desktop.Navigation.navigateTo(Navigation.java:106)
	    at bisq.desktop.components.MenuItem.lambda$activate$1(MenuItem.java:123)
	    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	    at javafx.event.Event.fireEvent(Event.java:198)
	    at javafx.scene.Node.fireEvent(Node.java:8879)
	    at javafx.scene.control.Button.fire(Button.java:200)
	    at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	    at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	    at javafx.event.Event.fireEvent(Event.java:198)
	    at javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	    at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	    at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	    at java.base/java.security.AccessController.doPrivileged(Native Method)
	    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	    at com.sun.glass.ui.View.notifyMouse(View.java:942)
	    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	    at java.base/java.lang.Thread.run(Thread.java:844)
     
    java.lang.ClassCastException: org.bitcoinj.core.SegwitAddress cannot be cast to org.bitcoinj.core.LegacyAddress
	    at bisq.desktop.main.dao.wallet.tx.BsqTxListItem.<init>(BsqTxListItem.java:106)
	    at bisq.desktop.main.dao.wallet.tx.BsqTxView.lambda$updateList$1(BsqTxView.java:317)
	    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	    at bisq.desktop.main.dao.wallet.tx.BsqTxView.updateList(BsqTxView.java:320)
	    at bisq.desktop.main.dao.wallet.tx.BsqTxView.activate(BsqTxView.java:193)
	    at bisq.desktop.common.view.ActivatableView.lambda$prepareInitialize$0(ActivatableView.java:37)
	    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	    at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	    at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	    at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1054)
	    at javafx.scene.Node.invalidatedScenes(Node.java:1114)
	    at javafx.scene.Node.setScenes(Node.java:1152)
	    at javafx.scene.Parent$2.onChanged(Parent.java:369)
	    at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	    at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
	    at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	    at bisq.desktop.main.dao.wallet.BsqWalletView.loadView(BsqWalletView.java:130)
	    at bisq.desktop.main.dao.wallet.BsqWalletView.lambda$initialize$0(BsqWalletView.java:79)
	    at bisq.desktop.Navigation.lambda$navigateTo$2(Navigation.java:140)
	    at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	    at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	    at bisq.desktop.Navigation.navigateTo(Navigation.java:140)
	    at bisq.desktop.Navigation.navigateTo(Navigation.java:106)
	    at bisq.desktop.components.MenuItem.lambda$activate$1(MenuItem.java:123)
	    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	    at javafx.event.Event.fireEvent(Event.java:198)
	    at javafx.scene.Node.fireEvent(Node.java:8879)
	    at javafx.scene.control.Button.fire(Button.java:200)
	    at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	    at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	    at javafx.event.Event.fireEvent(Event.java:198)
	    at javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	    at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	    at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	    at java.base/java.security.AccessController.doPrivileged(Native Method)
	    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	    at com.sun.glass.ui.View.notifyMouse(View.java:942)
	    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	    at java.base/java.lang.Thread.run(Thread.java:844)
    Nov-09 17:23:29.648 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Serializing SequenceNumberMap took 0 msec 
    Nov-09 17:23:29.690 [Write-SequenceNumberMap_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized SequenceNumberMap completed in 42 msec 
    Nov-09 17:23:39.403 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Serializing PreferencesPayload took 0 msec 
    Nov-09 17:23:39.466 [Write-PreferencesPayload_to-disk] INFO  b.c.p.PersistenceManager: Writing the serialized PreferencesPayload completed in 63 msec 
    Nov-09 17:23:56.503 [JavaFX Application Thread] INFO  b.n.p2p.network.Statistic: Network statistics:

</details>

@oscarguindzberg

**Comment by oscarguindzberg** [comment]
I don't see any bug in the code at first sight and my first theory is your bisq datadir is corrupted somehow.
Please let me know if you find out the steps to reproduce the bug from scratch.

**Comment by ghost** [comment]
Closing, will reopen if it happens repeatably.

**Comment by ghost** [comment]
UPDATE: reproduced the problem using the following steps, with the latest master branch.

- From Bob, send 100 BSQ to Chris.  Generate a block.
- From Chris, send 100 BSQ to Bob.  Generate a block.
- Look at Bob's BSQ transaction view.  Crash as described in OP.

----

Also, to ensure starting from a clean wallet state I deleted Bob and Chris' wallets and reproduced the issue again.
It is consistently reproducible this way.

- Setup:  Have 3 users: Alice, Bob, and Chris.  Alice has funds in BTC and BSQ wallets.
- Setup: Delete Bob and Chris's wallets:
  `rm -rf ~/.local/share/bisq-BTC_REGTEST_Bob/btc_regtest/wallet`
  `rm -rf ~/.local/share/bisq-BTC_REGTEST_Chris/btc_regtest/wallet`
- Start Bisq (Alice, Bob, Chris)
- Alice sends some BTC and 100 BSQ to Bob.  Generate a block.
- Alice sends some BTC to Chris.  Generate a block.
- From Bob, send 100 BSQ to Chris.  Generate a block.
- From Chris, send 100 BSQ to Bob.  Generate a block.
- Look at Bob's BSQ transaction view.  Crash as described in OP.

**Comment by oscarguindzberg** [comment]
I could reproduce the bug.
I reproduced it on the v1.5.0 release branch

In fact, it is simpler to reproduce:
- Setup: Have 2 users: Alice, Bob. Alice has funds in BTC and BSQ wallets. Bob may or may not have funds
- Start Bisq (Alice, Bob)
- Alice sends all its BSQ to Bob. Generate a block.
- Look at Bob's BSQ transaction view. Crash as described in OP.

The reason is BsqTxListItem has a twisted way to find out the send/receive address.
The introduction of Segwit and forcing BSQ to use LegacyAddress exposed the problem.

I wrote a hack that solves the problem. It is not meant to be merged but to illustrate the problem:
https://github.com/oscarguindzberg/bisq/commit/6b720a4244e3fd8dbeff8d1b91cff159ceb5f97d

The ideal solution would be to rewrite the code in the BsqTxListItem constructor where it obtains the send/receive address. 
There are a number of BSQ transaction types/cases to consider.

@chimp1984 could you look into this?

**Comment by oscarguindzberg** [comment]
The bug was introduced by this PR: https://github.com/bisq-network/bisq/pull/4681

**Comment by oscarguindzberg** [comment]
@ripcurlx we need this fixed to release 1.5.0

**Comment by ripcurlx** [comment]
> @ripcurlx we need this fixed to release 1.5.0

Will wait for the fix by @chimp1984 and cherry-pick it afterwards.

**Comment by chimp1984** [comment]
Fixed with https://github.com/bisq-network/bisq/issues/4775
