### ISSUE TITLE
Error initializing QuantumRenderer: no suitable pipeline found

### ISSUE THREAD

**Issue by ligi** [bisq-network/bisq#480]
I installed Bitsquare on ubuntu 16.04. Trying to launch via launcher fails without any feedback. Trying to launch on the command-line fails like this:

```
⋊> ~ /opt/Bitsquare/Bitsquare                                           20:22:06
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
    at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
    at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
    at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:205)
    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
    at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
    ... 1 more
Bitsquare Error invoking method.
Bitsquare Failed to launch JVM
```

**Comment by ManfredKarrer** [comment]
Seems you have soem issues with the graphics system. Do you run in a VM? Do u have some special graphic card?

**Comment by ligi** [comment]
No - not running in a vm. It's a stock Lenovo T520 with optimus ( NVIDIA + INTEL )

**Comment by ivilata** [comment]
By looking at [this](https://stackoverflow.com/questions/21185156/javafx-on-linux-is-showing-a-graphics-device-initialization-failed-for-es2-s#21203726) and [this](https://askubuntu.com/questions/600657/graphics-device-initialization-failed-for-es2-sw) I suspect that maybe you're missing some graphics libs (like GTK) or you installed the 32-bit version in a 64-bit system (or the other way around). Is that possible?

**Comment by ligi** [comment]
Just came back to this and it works now so I am closing this issue. Unfortunately I cannot pin down the change that made it work - maybe a missing gfx-lib like GTK is now installed - but if this was the reason these libs should be part of the dependencies. When I find some time I might try to get this bug back by uninstalling mentioned libs and reopen this issue If I find a way to reproduce

**Comment by ManfredKarrer** [comment]
Thanks @ligi! Let us know if you find out anything.

**Comment by Macabre2077** [comment]
I'm having same issue. Solved by running `java -Xbootclasspath/a:jdkfix-0.4.9.2.jar:../runtime/lib/ext/jfxrt.jar -jar Bitsquare-0.4.9.2.jar` instead of `/opt/Bitsquare/Bitsquare`

Now I have
```
java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:101)
	at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:265)
	at io.bitsquare.common.crypto.Encryption.generateSecretKey(Encryption.java:252)
	at io.bitsquare.common.crypto.Encryption.encryptHybridWithSignature(Encryption.java:211)
	at io.bitsquare.gui.main.MainViewModel$4.run(MainViewModel.java:572)
Caused by: java.util.jar.JarException: file:/opt/Bitsquare/app/Bitsquare-0.4.9.2.jar has unsigned entries - fonts/Verdana.ttf
```

**Comment by phozzy** [comment]
@ligi so? have You found a solution? I've got the same issue.
