### ISSUE TITLE
Missing Taker fee tx and ghost deposit tx

### ISSUE THREAD

**Issue by Mycelial1** [bisq-network/bisq#4879]
### Description
I am reporting my specific issue with this new bug that other users have been experiencing. 

Upon startup, I get the java.lang.NullPointerException. 

Trade id lwujzg was taken once, and resulted in a "missing taker fee transaction". I thought it was my spotty internet connection not sending messages because upon further inspection it said "The trade protocol did not finish in 30 seconds"

![first fail](https://user-images.githubusercontent.com/34950746/100937297-d2353680-34c0-11eb-8a99-aac8799b0144.png)
![trade protocl did not finish in 30 secs](https://user-images.githubusercontent.com/34950746/100939113-c4cd7b80-34c3-11eb-9c68-0f4bcbebb12b.png)

The same offer was kept on the order book and taken by someone else and the deposit transaction was going in and out of the mempool. I checked today and turns out that it's confirmed with about 42 confirmations, but the trade prompt still says "waiting on blockchain confirmation". I do not have icons  for chat, or to move to failed trade but the UI says that there are coins "locked". Those locked coins are for this trade because I don't have any other open trades.
![noicons](https://user-images.githubusercontent.com/34950746/100938262-6358dd00-34c2-11eb-87ae-09da2690ea7a.png)

#### Version
1.5.0

### Steps to reproduce

I was BSQ maker as seller. 

#### Additional info

here is a snippet from my logs

################################################################# 
Dec-02 06:00:23.352 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: Processing 1262 protectedStorageEntries took 147 ms. 
Dec-02 06:00:24.639 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: Processing 79 persistableNetworkPayloads took 1286 ms. 
Dec-02 06:00:24.871 [JavaFX Application Thread] INFO  b.c.t.p.FluentProtocol$Condition: We received a STARTUP event at phase TAKER_FEE_PUBLISHED and state MAKER_SAW_ARRIVED_PUBLISH_DEPOSIT_TX_REQUEST, tradeId=lwujzg-558246d8-5c6c-4358-8ea4-be39e6db2081-139 
Dec-02 06:00:24.885 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: BuyerSetupDepositTxListener 
Dec-02 06:00:24.904 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: TaskRunner successfully completed. Triggered from STARTUP, tradeId=lwujzg-558246d8-5c6c-4358-8ea4-be39e6db2081-139 
Dec-02 06:00:24.919 [JavaFX Application Thread] INFO  b.c.t.p.FluentProtocol$Condition: We received a STARTUP event at phase TAKER_FEE_PUBLISHED and state MAKER_SAW_ARRIVED_PUBLISH_DEPOSIT_TX_REQUEST, tradeId=lwujzg-558246d8-5c6c-4358-8ea4-be39e6db2081-139 
Dec-02 06:00:24.919 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: BuyerSetupDepositTxListener 
Dec-02 06:00:24.923 [JavaFX Application Thread] INFO  b.c.t.p.TradeProtocol: TaskRunner successfully completed. Triggered from STARTUP, tradeId=lwujzg-558246d8-5c6c-4358-8ea4-be39e6db2081-139 
Dec-02 06:00:24.925 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Dec-02 06:00:24.926 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= null 
Dec-02 06:00:24.935 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.NullPointerException 
Dec-02 06:00:25.058 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException
	at bisq.core.trade.protocol.ProcessModel.getTradeWalletService(ProcessModel.java:342)
	at bisq.core.trade.Trade.updateDepositTxFromWallet(Trade.java:643)
	at bisq.core.trade.TradeManager.initPersistedTrade(TradeManager.java:344)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at bisq.common.proto.persistable.PersistableList.forEach(PersistableList.java:78)
	at bisq.core.trade.TradeManager.initPersistedTrades(TradeManager.java:331)
	at bisq.core.trade.TradeManager.access$000(TradeManager.java:109)
	at bisq.core.trade.TradeManager$1.onUpdatedDataReceived(TradeManager.java:299)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.P2PService.onUpdatedDataReceived(P2PService.java:376)
	at bisq.network.p2p.peers.getdata.RequestDataManager$2.onComplete(RequestDataManager.java:336)
	at bisq.network.p2p.peers.getdata.RequestDataHandler.onMessage(RequestDataHandler.java:206)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$6(NetworkNode.java:386)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:386)
	at bisq.network.p2p.network.Connection.lambda$onMessage$5(Connection.java:430)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.network.Connection.lambda$onMessage$6(Connection.java:430)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by chimp1984** [comment]
Which version did you use when the bug happened?

**Comment by chimp1984** [comment]
Fixed with https://github.com/bisq-network/bisq/pull/4889 (also description of the root of the probelm)

@Mycelial1 You can ignore for now that error popup and move the failed trade to failed trades (arror on the right side).

**Comment by Mycelial1** [comment]
@chimp1984 I will move to failed trades for the first one, but the second taker doesn't have the "move to failed trades" icon as depicted in my screenshot.

Also, even though it says I have "locked" coins, they do not show when I press "Ctrl e" but there is a corresponding transaction confirmed on the blockchain. Has my trading peer's coins moved?

**Comment by chimp1984** [comment]
The first trade in the list looks ok. Just go on with the trade with that. Only the one showing the error need to be moved to failed trades.

**Comment by Mycelial1** [comment]
I am unable to progress with the trade that has a confirmed  deposit transaction. I wasn't able to chat with them until I moved the other trade to "Failed Trades". I hope the other peer is receiving my messages.

I would like to know how we are supposed to progress with the trade because I do not have prompts for initiating payment.

**Comment by Mycelial1** [comment]
Turns out the prompts appeared and I can now start payment. However, I am going to wait until my peer has communicated with me because I don't know if he's having UI issues on his end.

**Comment by chimp1984** [comment]
Did your trade moved to step 2? If not open mediation with cmd+o. If you can get in touch with the peer, you can choose to continue with the trade (send the BSQ) and then tell the mediator to make a suggested payout to the BTC buyer. As soon both have accepted the trade should get completed.

**Comment by chimp1984** [comment]
@Mycelial1 any update?

**Comment by Mycelial1** [comment]
Finished trade smoothly.

**Comment by ripcurlx** [comment]
Closing as complete.
