### ISSUE TITLE
NullPointerException at ChainDownloadSpeedCalculator.calculate

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq#4928]
### Description
NullPointerException at ChainDownloadSpeedCalculator.calculate
Happened with a very slow connection.

Also many log like those:

Dec-09 19:47:28.194 [PeerGroup Thread] INFO  o.b.c.PeerGroup$ChainDownloadSpeedCalculator: 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 660243/0, stall disabled (threshold <0.78 KB/sec for 10 seconds) 
Dec-09 19:47:29.192 [PeerGroup Thread] INFO  o.b.c.PeerGroup$ChainDownloadSpeedCalculator: 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 660243/0, stall disabled (threshold <0.78 KB/sec for 10 seconds) 

#### Additional info
Dec-09 19:47:22.193 [PeerGroup Thread] WARN  o.b.c.PeerGroup$ChainDownloadSpeedCalculator: Chain download stalled: received 0.00 KB/sec for 10 seconds, require average of 0.78 KB/sec, disconnecting null, 3 stalls left 
Dec-09 19:47:22.193 [PeerGroup Thread] ERROR o.b.c.PeerGroup$ChainDownloadSpeedCalculator: Error in speed calculator java.lang.NullPointerException: null
	at org.bitcoinj.core.PeerGroup$ChainDownloadSpeedCalculator.calculate(PeerGroup.java:1959)
	at org.bitcoinj.core.PeerGroup$ChainDownloadSpeedCalculator.run(PeerGroup.java:1876)
	at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:679)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by forcryptos** [comment]
to reproduce:
trickle -d 1 -u 1 ./bisq-desktop

and wait
