### ISSUE TITLE
unable to start bisq: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING

### ISSUE THREAD

**Issue by fflo** [bisq-network/bisq#5050]
### Description

Unable to start Bisq v1.5.4 application due to the following error:

Warning
Connection to the Bitcoin network failed because of an error:
java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING

#### Version

v1.5.4

### Steps to reproduce

Start up the application Bisq v1.5.4

### Expected behaviour

Normal application startup after connecting to the Bitcoin network.

### Actual behaviour

Unable to start up the Bisq application.

### Screenshots

![Bildschirmfoto 2021-01-03 um 17 09 20](https://user-images.githubusercontent.com/6385715/103483549-56dce280-4de8-11eb-9751-b110592166a0.png)
![Bildschirmfoto 2021-01-03 um 17 09 30](https://user-images.githubusercontent.com/6385715/103483552-5ba19680-4de8-11eb-8e49-7ee8c0bc7583.png)
![Bildschirmfoto 2021-01-03 um 17 09 37](https://user-images.githubusercontent.com/6385715/103483555-5e9c8700-4de8-11eb-8c9f-bbc69b16c4bd.png)
![Bildschirmfoto 2021-01-03 um 17 09 42](https://user-images.githubusercontent.com/6385715/103483560-665c2b80-4de8-11eb-874e-c11d1241e309.png)
![Bildschirmfoto 2021-01-03 um 17 09 47](https://user-images.githubusercontent.com/6385715/103483562-6b20df80-4de8-11eb-96bb-730b30bfe94d.png)

#### Device or machine

Ubuntu 20.04.1 LTS running MATE.

#### Additional info

bisq.log:
```
Jan-03 16:04:20.759 [NetworkNode-9999] INFO  b.n.p.n.NewTor:
################################################################
Tor started after 8456 ms. Start publishing hidden service.
################################################################
Jan-03 16:04:20.989 [JavaFX Application Thread] INFO  b.c.a.BisqSetup: Init wallet
Jan-03 16:04:20.990 [JavaFX Application Thread] INFO  b.c.a.WalletAppSetup: Initialize WalletAppSetup with BitcoinJ version 0.15.8.bisq.13 and hash of BitcoinJ commit 2a80db4
Jan-03 16:04:21.015 [JavaFX Application Thread] INFO  b.c.b.s.WalletsSetup: Socks5Proxy for bitcoinj: socks5Proxy=localhost:41663	Version 5
Jan-03 16:04:21.018 [JavaFX Application Thread] INFO  o.b.c.Context: Creating bitcoinj 0.15.8.bisq.13 context.
Jan-03 16:04:21.033 [JavaFX Application Thread] INFO  b.c.b.n.BtcNetworkConfig: You connect with peerAddresses: [[fz6nsij6jiyuwlsc.onion]:8333, [c6ac4jdfyeiakex2.onion]:8333, [sjyzmwwu6diiit3r.onion]:8333, [3xucqntxp5ddoaz5.onion]:8333, [lgkvbvro67jomosw.onion]:8333, [4jyh6llqj264oggs.onion]:8333, [mxdtrjhe2yfsx3pg.onion]:8333, [3r44ddzjitznyahw.onion]:8333, [i3a5xtzfm4xwtybd.onion]:8333, [mbm6ffx6j5ygi2ck.onion]:8333, [lva54pnbq2nsmjyr.onion]:8333, [qxjrxmhyqp5vy5hj.onion]:8333, [4nnuyxm5k5tlyjq3.onion]:8333, [m3yqzythryowgedc.onion]:8333, [jiuuuislm7ooesic.onion]:8333, [orsy2v63ecrmdj55.onion]:8333, [z6mbqq7llxlrn4kq.onion]:8333, [2pj2o2mrawj7yotg.onion]:8333]
Jan-03 16:04:21.044 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 6011 entries from SignedWitnessStorageService to the excluded key set of our request
Jan-03 16:04:21.050 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 2377 entries from AccountAgeWitnessStorageService to the excluded key set of our request
Jan-03 16:04:21.050 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 0 entries from TradeStatistics2StorageService to the excluded key set of our request
Jan-03 16:04:21.051 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 2926 entries from TradeStatistics3StorageService to the excluded key set of our request
Jan-03 16:04:21.051 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 602 entries from ProposalStorageService to the excluded key set of our request
Jan-03 16:04:21.051 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 342 entries from BlindVoteStorageService to the excluded key set of our request
Jan-03 16:04:21.070 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a PreliminaryGetDataRequest to peer devinsn3xuzxhj6pmammrxpydhwwmwp75qkksedo5dn2tlmu7jggo7id.onion:8000.
Jan-03 16:04:21.194 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 6011 entries from SignedWitnessStorageService to the excluded key set of our request
Jan-03 16:04:21.195 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 2377 entries from AccountAgeWitnessStorageService to the excluded key set of our request
Jan-03 16:04:21.195 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 0 entries from TradeStatistics2StorageService to the excluded key set of our request
Jan-03 16:04:21.196 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 2926 entries from TradeStatistics3StorageService to the excluded key set of our request
Jan-03 16:04:21.196 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 602 entries from ProposalStorageService to the excluded key set of our request
Jan-03 16:04:21.196 [JavaFX Application Thread] INFO  b.n.p.s.P2PDataStorage: We added 342 entries from BlindVoteStorageService to the excluded key set of our request
Jan-03 16:04:21.202 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: We send a PreliminaryGetDataRequest to peer devinsn2teu33efff62bnvwbxmfgbfjlgqsu3ad4b4fudx3a725eqnyd.onion:8000.
Jan-03 16:04:21.447 [ STARTING] INFO  o.b.c.AbstractBlockChain: chain head is at height 661456:
 block:
   hash: 0000000000000000000bbd445583b32e8366607f2f3976fc520dec2cf4fd4696
   version: 536870912 (BIP34, BIP66, BIP65)
   previous block: 0000000000000000000689db9dec94e7acd15e505a46e967ea57e25ce76d7620
   time: 1608030062 (2020-12-15T11:01:02Z)
   difficulty target (nBits): 386863986
   nonce: 1332011661

Jan-03 16:04:21.618 [ STARTING] INFO  b.c.b.s.WalletConfig: We try to connect to 9 btc nodes
Jan-03 16:04:21.632 [JavaFX Application Thread] ERROR b.c.b.s.WalletsSetup: Service failure from state: STARTING; failure={} java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:589)
	at org.bitcoinj.wallet.Wallet.setTransactionBroadcaster(Wallet.java:5227)
	at org.bitcoinj.core.PeerGroup.addWallet(PeerGroup.java:1218)
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:333)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.base/java.lang.Thread.run(Thread.java:844)

Jan-03 16:04:21.635 [JavaFX Application Thread] ERROR b.c.a.WalletAppSetup: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
```

Resetting Tor does not resolve the issue. This is no connectivity issue to the Tor network.

**Comment by fflo** [comment]
Seems this issue is related to the bisq_BITCOIN and bisq_BSQ wallet(s).

Restoring an older version of these files from .../btc_mainnet/wallet/backup and removing the files .../btc_mainnet/wallet/bisq.spvchain and .../btc_mainnet/wallet/pre_segwit_bisq_BTC.wallet.backup does resolve the issue.

Not closing this issue request, because I think that _Bisq_ should start even if the blockchain and wallet(s) are not in sync.

**Comment by aphex3k** [comment]
I just received the same issue

**Comment by ghost** [comment]
The BitcoinJ wallet gets stuck that way sometimes.  To fix, you can do as [suggested](https://github.com/bisq-network/bisq/issues/5050#issuecomment-753709845) in the comment, or [SPV resync](https://bisq.wiki/Resyncing_SPV_file#From_the_file_system) the wallet.

**Comment by ljaa45** [comment]
Same issue. I have a backup from 1.5 yrs ago. If I’m getting this error message and can’t get in to Bisq then how can I create a new backup? I copied my previous backup into another location, and then deleted the spv file as instructed in the wiki. No result, just keep getting “Warning: Connection to the Bitcoin network failed because of an error: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.” Have trades pending as well, was working this morning.

**Comment by MwithM** [comment]
Repeated here: https://bisq.community/t/bitcoin-network-failed-because-of-an-error/11698/3

**Comment by Talkless** [comment]
> Restoring an older version of these files from...

@fflo Is it safe to restore these files and removing spvchain if I have trade open (in confirmed payment state)?

**Comment by Talkless** [comment]
Error occurs just after getting first block from my own node:

```
lapkr.-23 21:10:30.276 [JavaFX Application Thread] INFO  b.c.btc.nodes.BtcNetworkConfig: You connect with peerAddresses: [[xx.xx.xx.xx]:xxxx] 
lapkr.-23 21:10:30.281 [JavaFX Application Thread] INFO  bisq.core.app.BisqSetup: walletInitialized=false, p2pNetWorkReady=false 
lapkr.-23 21:10:30.591 [ STARTING] INFO  o.b.core.AbstractBlockChain: chain head is at height 817843:
 block: 
   hash: 00000000000000000001ce61d512de5dfd663d637be644978a31b8c55fcc0bf3
   version: 801480704 (BIP34, BIP66, BIP65)
   previous block: 000000000000000000031b5a4ff891b354b46fd9e4116322c0010bcf6282e349
   time: 1700597099 (2023-11-21T20:04:59Z)
   difficulty target (nBits): 386161170
   nonce: 2239917177
 
lapkr.-23 21:10:30.684 [ STARTING] INFO  b.core.btc.setup.WalletConfig: We try to connect to 1 btc nodes 
lapkr.-23 21:10:30.690 [JavaFX Application Thread] ERROR b.core.btc.setup.WalletsSetup: Service failure from state: STARTING; failure={} java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:591)
        at org.bitcoinj.wallet.Wallet.setTransactionBroadcaster(Wallet.java:5241)
        at org.bitcoinj.core.PeerGroup.addWallet(PeerGroup.java:1218)
        at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:338)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:61)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:117)
        at java.base/java.lang.Thread.run(Thread.java:829)

java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:591)
        at org.bitcoinj.wallet.Wallet.setTransactionBroadcaster(Wallet.java:5241)
        at org.bitcoinj.core.PeerGroup.addWallet(PeerGroup.java:1218)
        at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:338)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:61)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:117)
        at java.base/java.lang.Thread.run(Thread.java:829)
lapkr.-23 21:10:30.691 [JavaFX Application Thread] ERROR bisq.core.app.WalletAppSetup: java.lang.IllegalStateException: Expected PENDING or IN_CONFLICT, was BUILDING.
```

**Comment by pazza83** [comment]
> @fflo Is it safe to restore these files and removing spvchain if I have trade open (in confirmed payment state)?

I would not restore the files just do the SPV resync: https://bisq.wiki/Resyncing_SPV_file

**Comment by Talkless** [comment]
I've deleted only `spvchain` file, left it overnight to resync, and it works now, thanks.

**Comment by vurezo** [comment]
> I've deleted only `spvchain` file, left it overnight to resync, and it works now, thanks.

Thank you! That perfectly solved everything for me!

EDIT: %appdata%\Bisq\btc_mainnet\wallet
