### ISSUE TITLE
[v1.5.5] Export BSQ tx as CSV failed

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq#5100]
### Description

I tried to export my BSQ tx on Regtest and it failed with a NPE.

#### Version

v1.5.5

### Expected behaviour

CSV is exported

### Actual behaviour

NPE is thrown:
```
java.lang.NullPointerException
	at com.googlecode.jcsv.writer.internal.CSVColumnJoinerImpl.joinColumns(CSVColumnJoinerImpl.java:30)
	at com.googlecode.jcsv.writer.internal.CSVWriterImpl.write(CSVWriterImpl.java:38)
	at com.googlecode.jcsv.writer.internal.CSVWriterImpl.writeAll(CSVWriterImpl.java:29)
	at bisq.desktop.util.GUIUtil.exportCSV(GUIUtil.java:293)
	at bisq.desktop.main.dao.wallet.tx.BsqTxView.lambda$activate$3(BsqTxView.java:247)
```
It failed in my case as I had an item where the address was `null` instead of "". 
Maybe we shouldn't print the address at all as it is never populated. I think this might be a copy&paste issue 😉 

### Screenshots

<img width="1272" alt="Bildschirmfoto 2021-01-22 um 11 52 39" src="https://user-images.githubusercontent.com/170962/105487899-1ec31400-5cb1-11eb-8111-04d4b476c746.png">

**Comment by ripcurlx** [comment]
@chimp1984 I think we can remove the address from the export ☝️
