### ISSUE TITLE
java.security.NoSuchProviderException: JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by molecular** [bisq-network/bisq#538]
can't generate some keys (which are probably necessary for operation) because some bouncycastle signing issues:

```
java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
        at javax.crypto.JceSecurity.getInstance(JceSecurity.java:101)
        at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:265)
        at io.bitsquare.common.crypto.Encryption.generateSecretKey(Encryption.java:252)
        at io.bitsquare.common.crypto.Encryption.encryptHybridWithSignature(Encryption.java:211)
        at io.bitsquare.gui.main.MainViewModel$4.run(MainViewModel.java:560)
Caused by: java.util.jar.JarException: file:/home/user/bitcoin/bitsquare/gui/target/shaded.jar has unsigned entries - fonts/VerdanaBold.ttf
        at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)
        at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:322)
        at javax.crypto.JarVerifier.verify(JarVerifier.java:250)
        at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:160)
        at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:186)
        at javax.crypto.JceSecurity.getInstance(JceSecurity.java:98)
        ... 4 more
Jul-23 17:40:24.338 [Thread-10] ERROR i.b.c.c.Encryption: JCE cannot authenticate the provider BC
Jul-23 17:40:24.338 [Thread-10] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread Thread-10
Jul-23 17:40:24.338 [Thread-10] ERROR i.b.a.BitsquareApp: throwableMessage= Couldn't generate key
Jul-23 17:40:24.341 [Thread-10] ERROR i.b.a.BitsquareApp: throwableClass= class java.lang.RuntimeException
Jul-23 17:40:24.346 [Thread-10] ERROR i.b.a.BitsquareApp: Stack trace:
java.lang.RuntimeException: Couldn't generate key
        at io.bitsquare.common.crypto.Encryption.generateSecretKey(Encryption.java:258)
        at io.bitsquare.common.crypto.Encryption.encryptHybridWithSignature(Encryption.java:211)
        at io.bitsquare.gui.main.MainViewModel$4.run(MainViewModel.java:560)

java.lang.RuntimeException: Couldn't generate key
        at io.bitsquare.common.crypto.Encryption.generateSecretKey(Encryption.java:258)
        at io.bitsquare.common.crypto.Encryption.encryptHybridWithSignature(Encryption.java:211)
        at io.bitsquare.gui.main.MainViewModel$4.run(MainViewModel.java:560)
```

don't even know where bouncycastle stuff is (supposed to be) coming from. 

any help appreciated.

**Comment by ManfredKarrer** [comment]
Please follow the build instructions at the doc/build.md file.
https://github.com/bitsquare/bitsquare/blob/master/doc/build.md#prerequisites

**Comment by molecular** [comment]
Thanks!

I was following the "for the impatient" section. Maybe I shouldn't be so impatient...

So for anyone seeing this, solution was to install some bouncycastle libs as documentation clearly indicates:

```
3. Copy the BountyCastle provider jar file

Copy the BountyCastle provider jar file (bcprov-jdk15on-1.53.jar) from you local maven repository (/home/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.53/bcprov-jdk15on-1.53.jar) to $JavaHome/jre/lib/ext/. This prevent a "JCE cannot authenticate the provider BC" exception when starting the Bitsquare client.
```

**Comment by ManfredKarrer** [comment]
Yes should remove that "for the impatient" section :-)

**Comment by bilbma** [comment]
were is and how to copy in that dtrectory?.Could you explain to silly people like me?

 Copy the BountyCastle provider jar file

Copy the BountyCastle provider jar file (bcprov-jdk15on-1.53.jar) from you local maven repository (/home/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.53/bcprov-jdk15on-1.53.jar) to $JavaHome/jre/lib/ext/. This prevent a "JCE cannot authenticate the provider BC" exception when starting the Bitsquare client.

**Comment by ManfredKarrer** [comment]
In the current build process that is not needed anymore. Did you get an exception with missing bouncycastle?

**Comment by bilbma** [comment]
no, but I do not remember why I can not with bisq.Thank you

**Comment by ManfredKarrer** [comment]
Sorry I dont understand what you mean.

**Comment by ghost** [comment]
Hey guys, this works fine for me: [https://wp.huangshiyang.com/bcp-jce-cannot-authenticate-the-provider-bc](url)

**Comment by molecular** [comment]
> Hey guys, this works fine for me: [https://wp.huangshiyang.com/bcp-jce-cannot-authenticate-the-provider-bc](url)

that link seams dead
