### ISSUE TITLE
Attempt to open portfolio failed

### ISSUE THREAD

**Issue by richardalg** [bisq-network/bisq#5381]
Hi, 
I had created a new trade and a popup window appeared offering to open my portfolio window. 
When I clicked to say open the portfolio, an error message appeared. 
Among other things, and extract from the log was requested. 
These are the most recent and I believe, relevant parts: 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Mar-31 12:37:02.802 [MemPoolSpaceTxBroadcaster @ http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/tx] INFO  b.c.b.w.h.MemPoolSpaceTxBroadcaster: Broadcast of raw tx to http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/tx failed for transaction 2cb60319fc96289b93089275d0c18ce5deba99625ada2000fa49149acc213fcb. responseCode=400, error=sendrawtransaction RPC error: {"code":-22,"message":"TX decode failed. Make sure the tx has at least one input."} 
Mar-31 12:37:06.872 [JavaFX Application Thread] INFO  b.c.u.DesktopUtil: Trying to exec: cmd = kde-open args = %s file = /home/richard/.local/share/Bisq/bisq.log 
Mar-31 12:37:06.873 [JavaFX Application Thread] WARN  b.c.u.DesktopUtil: Error running command. java.io.IOException: Cannot run program "kde-open": error=2, No such file or directory 
Mar-31 12:37:06.873 [JavaFX Application Thread] INFO  b.c.u.DesktopUtil: Trying to exec: cmd = gnome-open args = %s file = /home/richard/.local/share/Bisq/bisq.log 
Mar-31 12:37:06.874 [JavaFX Application Thread] WARN  b.c.u.DesktopUtil: Error running command. java.io.IOException: Cannot run program "gnome-open": error=2, No such file or directory 
Mar-31 12:37:06.874 [JavaFX Application Thread] INFO  b.c.u.DesktopUtil: Trying to exec: cmd = xdg-open args = %s file = /home/richard/.local/share/Bisq/bisq.log 
Mar-31 12:37:06.875 [JavaFX Application Thread] INFO  b.c.u.DesktopUtil: Process is running.

**Comment by ghost** [comment]
> When I clicked to say open the portfolio, an error message appeared.

Can you provide information about the error message that appeared, wording or screenshot of it?

**Comment by richardalg** [comment]
On Wed, Mar 31, 2021 at 06:09:16AM -0700, jmacxx wrote:
> > When I clicked to say open the portfolio, an error message appeared.
> 
> Can you provide information about the error message that appeared, wording or screenshot of it?
> 
> -- 
I believe the error message appears anytime I atempt to open the 
portfolio. A screenshot should be attached with the message : 
"java.lang.NullPointerException"

richard

**Comment by ghost** [comment]
Please could you search your log for "NullPointerException", there will be a stack trace associated with it.  Pasting it here will enable us to know where in the code the problem was.  Also, which version of Bisq are you on?  Thanks!

**Comment by richardalg** [comment]
On Wed, Mar 31, 2021 at 10:24:18AM -0700, jmacxx wrote:
> Please could you search your log for "NullPointerException", there will be a stack trace associated with it.  Pasting it here will enable us to know where in the code the problem was.  Also, which version of Bisq are you on?  Thanks!
> 
> -- 
I expect this was the first error flagged. Log extract follows :

} TxBroadcastException{
     txId='null'
} bisq.core.btc.exceptions.TxBroadcastTimeoutException: The transaction was not broadcasted in 5 seconds. txId=2cb60319fc96289b93089275d0c18ce5deba99625ada2000fa49149acc213fcb 
Mar-31 12:36:35.520 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: swap addressEntry with address bc1q4wjqez2xvsdzgz0lw7hp8fjsc4dmft743n3dj7 and offerId mhxguegg-673c8b30-972a-4b9c-8854-4f4636e96fa1-161 from context OFFER_FUNDING to available 
Mar-31 12:36:35.520 [JavaFX Application Thread] INFO  b.c.b.m.AddressEntryList: swapToAvailable addressEntry to swap=AddressEntry{address=bc1q4wjqez2xvsdzgz0lw7hp8fjsc4dmft743n3dj7, context=OFFER_FUNDING, offerId='mhxguegg-673c8b30-972a-4b9c-8854-4f4636e96fa1-161', coinLockedInMultiSig=0, segwit=true} 
Mar-31 12:36:35.520 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: AddToOfferBook 
Mar-31 12:36:38.675 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: broadcastTransaction: SEEN_PEERS:  TX 2cb60319fc96289b93089275d0c18ce5deba99625ada2000fa49149acc213fcb seen by 1 peers 
Mar-31 12:36:41.388 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: broadcastTransaction: SEEN_PEERS:  TX 2cb60319fc96289b93089275d0c18ce5deba99625ada2000fa49149acc213fcb seen by 2 peers 
Mar-31 12:36:41.388 [JavaFX Application Thread] INFO  o.b.c.TransactionBroadcast: broadcastTransaction: 2cb60319fc96289b93089275d0c18ce5deba99625ada2000fa49149acc213fcb complete 
Mar-31 12:36:41.389 [JavaFX Application Thread] WARN  b.c.b.w.TxBroadcaster: We got an onSuccess callback for a broadcast which already triggered the timeout. txId=2cb60319fc96289b93089275d0c18ce5deba99625ada2000fa49149acc213fcb 
Mar-31 12:36:43.112 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Mar-31 12:36:43.112 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= null 
Mar-31 12:36:43.112 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.NullPointerException 
Mar-31 12:36:43.117 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException
	at bisq.core.offer.TriggerPriceService.wasTriggered(TriggerPriceService.java:124)
	at bisq.desktop.main.portfolio.openoffer.OpenOffersDataModel.wasTriggered(OpenOffersDataModel.java:103)
	at bisq.desktop.main.portfolio.openoffer.OpenOffersView$11$1.updateItem(OpenOffersView.java:685)
	at bisq.desktop.main.portfolio.openoffer.OpenOffersView$11$1.updateItem(OpenOffersView.java:666)
	at javafx.controls/javafx.scene.control.TableCell.updateItem(TableCell.java:665)
	at javafx.controls/javafx.scene.control.TableCell.indexChanged(TableCell.java:469)
	at javafx.controls/javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:539)
	at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.<init>(TableRowSkinBase.java:159)
	at javafx.controls/javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:89)
	at javafx.controls/javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:213)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9515)
	at javafx.graphics/javafx.scene.Node.applyCss(Node.java:9602)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1715)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1692)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.getCellLength(VirtualFlow.java:1801)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.computeViewportOffset(VirtualFlow.java:2638)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1245)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:590)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2507)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:410)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:409)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:844)
 
Mar-31 12:37:02.802 [MemPoolSpaceTxBroadcaster @ http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/tx] INFO  b.n.h.HttpClientImpl: Received errorMsg 'sendrawtransaction RPC error: {"code":-22,"message":"TX decode failed. Make sure the tx has at least one input."}' with statusCode 400 from http://mempoolhqx4isw62xs7abwphsq7ldayuidyx2v2oethdhhj6mlo2r6ad.onion/api/tx. Response took: 32275 ms. param: 010000000001013be7e08a72f8a6229d7fb16b2f508c7eee8ddcded1c728e5ece7d0b524c6ba3f010000006a473044022013ada8f549414d58838831508a05f4a97d8917a63477995792194b43cee5770a022036f7b9f92bce4d35c992237f189e5db3d876fd8933c1542696dfae8323de78f6012103d1a5ace67af70efef51aff3476fd50a1a4f834ab259bc9e3a127fcbd62ebc196ffffffff0388130000000000001976a9141f9342d9da1d15683076188c92f361ba2d6537ab88ac400d030000000000160014a410911dab650cb83f540d9801d19029711be4bf9ef10b0000000000160014acefb9f31561d7f731e12a507e4fd5cb7533b0090000000000

**Comment by richardalg** [comment]
On Wed, Mar 31, 2021 at 10:24:18AM -0700, jmacxx wrote:
> Please could you search your log for "NullPointerException", there will be a stack trace associated with it.  Pasting it here will enable us to know where in the code the problem was.  Also, which version of Bisq are you on?  Thanks!
> 
> -- 
The version installed was downloaded yesterday I believe: 

*Bisq-1.6.1.jar.txt  
*Bisq-64bit-1.6.1.deb  
*Bisq-64bit-1.6.1.deb.asc  
*Bisq-64bit-1.6.1.deb.asc.backup

HTH

**Comment by ghost** [comment]
Thanks for reporting @richardalg, fix is in the queue.

**Comment by richardalg** [comment]
On Wed, Mar 31, 2021 at 01:20:37PM -0700, jmacxx wrote:
> Thanks for reporting @richardalg, fix is in the queue.
> 
Good to hear that I didn't do something stupid :-)

And thanks for putting this together. 

richard
