### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by claudineyns** [bisq-network/bisq#542]
jul-25 10:47:07.221 [JavaFX Application Thread] WARN  i.b.p.p.BroadcastHandler: Timeout: Broadcast did not complete after 150 sec. 
jul-25 10:47:18.051 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: We have been in standby mode for 5 sec 
jul-25 10:47:36.080 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: We have been in standby mode for 5 sec 
jul-25 10:47:36.081 [JavaFX Application Thread] WARN  i.b.p.p.p.PeerExchangeManager: retryTimer already started 
jul-25 10:47:54.546 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: We have been in standby mode for 7 sec 
jul-25 10:48:14.926 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: We have been in standby mode for 7 sec 
jul-25 10:48:25.931 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
jul-25 10:48:25.932 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableMessage= null 
jul-25 10:48:25.932 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableClass= class java.lang.NullPointerException 
jul-25 10:48:25.959 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Stack trace:
java.lang.NullPointerException
    at io.bitsquare.gui.main.offer.offerbook.OfferBookViewModel.isPaymentAccountValidForOffer(OfferBookViewModel.java:414)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookViewModel.isAnyPaymentAccountValidForOffer(OfferBookViewModel.java:366)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookViewModel.isAnyPaymentAccountValidForOffer(OfferBookViewModel.java:361)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookView$12$1.updateItem(OfferBookView.java:631)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookView$12$1.updateItem(OfferBookView.java:609)
    at javafx.scene.control.TableCell.updateItem(TableCell.java:663)
    at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
    at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
    at com.sun.javafx.scene.control.skin.TableRowSkinBase.requestCellUpdate(TableRowSkinBase.java:659)
    at com.sun.javafx.scene.control.skin.TableRowSkinBase.handleControlPropertyChanged(TableRowSkinBase.java:234)
    at com.sun.javafx.scene.control.skin.TableRowSkin.handleControlPropertyChanged(TableRowSkin.java:70)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$61(BehaviorSkinBase.java:197)
    at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55)
    at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ReadOnlyIntegerWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:176)
    at javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:142)
    at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
    at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:147)
    at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:115)
    at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
    at com.sun.javafx.scene.control.skin.VirtualFlow.addLeadingCells(VirtualFlow.java:1246)
    at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1194)
    at javafx.scene.Parent.layout(Parent.java:1079)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Scene.doLayoutPass(Scene.java:552)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
    at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
    at java.lang.Thread.run(Thread.java:745)

jul-25 10:48:35.045 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: We have been in standby mode for 6 sec 
jul-25 10:48:53.457 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: We have been in standby mode for 6 sec 
jul-25 10:49:12.217 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: We have been in standby mode for 6 sec 
jul-25 10:49:29.974 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: We have been in standby mode for 5 sec 
jul-25 10:49:47.619 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: We have been in standby mode for 6 sec 
jul-25 10:50:05.692 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: We have been in standby mode for 6 sec 
jul-25 10:50:23.759 [JavaFX Application Thread] WARN  i.b.p.p.PeerManager: We have been in standby mode for 6 sec

**Comment by ManfredKarrer** [comment]
That is from that offer which has not bank name set up. Is that offer still online? If so can you send me the offer ID and price?

**Comment by ManfredKarrer** [comment]
Found the issue and fixed it. Will be out with upcoming release.
