### ISSUE TITLE
java.io.UncheckedIOException on startup

### ISSUE THREAD

**Issue by blex97** [bisq-network/bisq#5518]
during startup of bisq my machine suddenly rebootet. now all i get is the following when trying to start bisq

bisq version 1.6.4

lenovo x230
ubuntu 21.04

/opt/bisq/bin/Bisq
fault: An unexpected error occurred. Please file a report at https://bisq.network/issues
java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1
        at bisq.common.config.ConfigFileReader.getLines(ConfigFileReader.java:33)
        at bisq.common.config.ConfigFileReader.getOptionLines(ConfigFileReader.java:38)
        at bisq.common.config.Config.parseOptionsFrom(Config.java:822)
        at bisq.common.config.Config.<init>(Config.java:720)
        at bisq.core.app.BisqExecutable.execute(BisqExecutable.java:84)
        at bisq.desktop.app.BisqAppMain.main(BisqAppMain.java:54)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(Unknown Source)
        at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.base/java.io.InputStreamReader.read(Unknown Source)
        at java.base/java.io.BufferedReader.fill(Unknown Source)
        at java.base/java.io.BufferedReader.readLine(Unknown Source)
        at java.base/java.io.BufferedReader.readLine(Unknown Source)
        at java.base/java.nio.file.Files.readAllLines(Unknown Source)
        at java.base/java.nio.file.Files.readAllLines(Unknown Source)
        at bisq.common.config.ConfigFileReader.getLines(ConfigFileReader.java:29)
        ... 5 more

**Comment by ripcurlx** [comment]
@blex97 Please have a look at your bisq.properties file in your data directory. It might be that the file got corrupted. If you haven't configured anything yourself, just delete the file and start Bisq again.

**Comment by blex97** [comment]
perfect advice, works :)
