### ISSUE TITLE
Cannot invoke "bisq.core.payment.payload.PaymentAccountPayload.getAgeWitnessInputData()" because "paymentAccountPayload is null"

### ISSUE THREAD

**Issue by bitsanity** [bisq-network/bisq#5612]
### Description

Was waiting on trade partner to confirm receipt of my payment and release BTC to me. Starting Bisq today and the UI is locked up with two modal dialogs: one telling me my partner has opened a support ticket and one with this error message.

I can close the support ticket advisory dialog, but whenever I click "Close" on this error dialog, it simply comes back. I can't get past it into the app. The window close button doesn't work either. I have to kill it from the shell, but same happens after restart.

This modal dialog behavior means I can't help the arbitrator or chat with my trading partner. Seems I can't do anything with the app until this is resolved.

#### Version

1.7.0 downloaded and installed on Jun 29 (11 days ago)

### Steps to reproduce

Trading partner was on a sketchy connection when the trade was taken so the trade had appeared and disappeared a few times before I was able to take it. Not sure if related to this bug.

### Expected behaviour

Trading partner should be able to release BTC to me and complete the trade.
The modal dialogs should be dismissable and I should be able to get into the app.

### Actual behaviour

As stated above, I am actually stuck and unable to use the app.

### Screenshots

![bisqerror](https://user-images.githubusercontent.com/15133466/125097498-0e4dfc80-e08b-11eb-8cab-52fdd805ff82.png)

#### Device or machine

Ubuntu x86_64

#### Additional info

ava.lang.NullPointerException: Cannot invoke "bisq.core.payment.payload.PaymentAccountPayload.getAgeWitnessInputData()" because "paymentAccountPayload" is null
  at bisq.core.account.witness.AccountAgeWitnessService.getAccountInputDataWithSalt(AccountAgeWitnessService.java:274)
  at bisq.core.account.witness.AccountAgeWitnessService.findWitness(AccountAgeWitnessService.java:288)
  at bisq.core.account.witness.AccountAgeWitnessService.getAccountAge(AccountAgeWitnessService.java:346)
  at bisq.desktop.main.support.dispute.DisputeView.getBuyerOnionAddressColumnLabel(DisputeView.java:1267)
  at bisq.desktop.main.support.dispute.DisputeView.access$800(DisputeView.java:128)
  at bisq.desktop.main.support.dispute.DisputeView$12$1.updateItem(DisputeView.java:1216)
  at bisq.desktop.main.support.dispute.DisputeView$12$1.updateItem(DisputeView.java:1211)
  at javafx.scene.control.TableCell.updateItem(TableCell.java:665)
  at javafx.scene.control.TableCell.indexChanged(TableCell.java:469)
  at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
  at javafx.scene.control.skin.TableRowSkinBase.requestCellUpdate(TableRowSkinBase.java:701)
  at javafx.scene.control.skin.TableRowSkinBase.lambda$new$1(TableRowSkinBase.java:178)
  at com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:49)
  at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
  at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
  at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
  at javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(ReadOnlyIntegerPropertyBase.java:78)
  at javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:102)
  at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:114)
  at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
  at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:119)
  at javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1736)
  at javafx.scene.control.skin.VirtualFlow.addLeadingCells(VirtualFlow.java:2023)
  at javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1244)
  at javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:837)
  at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
  at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
  at javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:849)
  at javafx.scene.control.skin.TableViewSkinBase.updateItemCount(TableViewSkinBase.java:554)
  at javafx.scene.control.skin.VirtualContainerBase.checkState(VirtualContainerBase.java:184)
  at javafx.scene.control.skin.VirtualContainerBase.layoutChildren(VirtualContainerBase.java:159)
  at javafx.scene.control.skin.TableViewSkinBase.layoutChildren(TableViewSkinBase.java:406)
  at javafx.scene.control.Control.layoutChildren(Control.java:601)
  at javafx.scene.Parent.layout(Parent.java:1207)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Scene.doLayoutPass(Scene.java:576)
  at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2476)
  at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:413)
  at java.base/java.security.AccessController.doPrivileged(Unknown Source)
  at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:412)
  at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:439)
  at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:563)
  at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543)
  at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536)
  at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342)
  at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
  at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
  at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
  at java.base/java.lang.Thread.run(Unknown Source)

**Comment by bitsanity** [comment]
Did a NPV file delete and resync, plus deleted outdated torrent files and resynced. I'm able to get past the opening screen into the app. If I try to click on my "Open Trades" I get stuck with the same modal dialog problem.

**Comment by bitsanity** [comment]
This could be a result of the bug, or the root cause of the bug, not sure. The "Delayed payout transaction ID" transaction ID link takes to a page that says the transaction can't be found.

![brokentrade](https://user-images.githubusercontent.com/15133466/125169192-e67b9900-e15d-11eb-9b57-05a0183eacbe.png)

**Comment by bitsanity** [comment]
Possible symptom, or maybe root cause not sure. The "Delayed payout transaction ID" does not exist.

![brokentrade](https://user-images.githubusercontent.com/15133466/125169279-45411280-e15e-11eb-8dae-78d72dc03d8f.png)

**Comment by ghost** [comment]
@ripcurlx has a fix in progress for this issue @bitsanity.  Could you DM him on keybase about it?

**Comment by bitsanity** [comment]
Great news! Will do.

**Comment by bitsanity** [comment]
Looks like the patch provided by ripcurlx fixes this issue. The dispute is not resolved but am able to chat with the mediator and use the app normally.

**Comment by buddhalore** [comment]
Bisq1.7.0 upgraded in the client 6 Jul

Problem:

![bisq fail message](https://user-images.githubusercontent.com/85696011/125201989-dd7bec00-e271-11eb-97c6-c16354ce1c23.png)

Similar problem. Unresponsive app. Have to click through failed trade window a few times. Have a failed trade w btc locked up and showing me this:
![failed trade](https://user-images.githubusercontent.com/85696011/125202050-36e41b00-e272-11eb-9f81-ce8d87566e81.png)

When I ctl+o it doesn't open a moderation ticket I can see in the moderation window, but says it's already open and that i can summit it again in 24 hrs
![moderation request](https://user-images.githubusercontent.com/85696011/125202151-917d7700-e272-11eb-9b05-2879d80bb98d.png)

**Comment by cromav** [comment]
Hello, same issue here. @bitsanity could you post here the patch, please?

**Comment by ripcurlx** [comment]
> Hello, same issue here. @bitsanity could you post here the patch, please?

I'll publish a pre-release today, so there is a place to download and verify the patch for everyone until the next release is published.

**Comment by ManoloSFC** [comment]
Having the same issue here.

Looking forward to that patch.

Thanks.

**Comment by ripcurlx** [comment]
Please give https://github.com/bisq-network/bisq/releases/tag/v1.7.1 a shot. Hopefully this should fix the issues you are seeing 🤞

**Comment by pazza83** [comment]
Just had this error and upgraded to v1.7.1 and it has resolved it.
