### ISSUE TITLE
Pricenode encounters exception refreshing Bitfinex due to duplicate key DOGE/USD

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq#5669]
### Description

My pricenode is encountering the following exception:
```
Jul 31 06:27:21 localhost bisq-pricenode[276520]: Jul-31 06:27:21.815 [Timer-18] WARN  b.p.s.p.Bitfinex: refresh failed java.lang.IllegalStateException: Duplicate key DOGE/USD (attempted merging values 0.079138 and 0.20511)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at org.knowm.xchange.bitfinex.BitfinexExchange.remoteInit(BitfinexExchange.java:73)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:107)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:78)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:36)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.spot.ExchangeRateProvider.doGet(ExchangeRateProvider.java:107)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.spot.providers.Bitfinex.doGet(Bitfinex.java:42)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.spot.providers.Bitfinex.doGet(Bitfinex.java:31)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.PriceProvider.refresh(PriceProvider.java:83)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.PriceProvider.access$000(PriceProvider.java:34)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.PriceProvider$1.run(PriceProvider.java:69)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.TimerThread.run(Timer.java:506)
Jul 31 06:27:21 localhost bisq-pricenode[276520]: java.lang.IllegalStateException: Duplicate key DOGE/USD (attempted merging values 0.079138 and 0.20511)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at org.knowm.xchange.bitfinex.BitfinexExchange.remoteInit(BitfinexExchange.java:73)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:107)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:78)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:36)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.spot.ExchangeRateProvider.doGet(ExchangeRateProvider.java:107)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.spot.providers.Bitfinex.doGet(Bitfinex.java:42)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.spot.providers.Bitfinex.doGet(Bitfinex.java:31)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.PriceProvider.refresh(PriceProvider.java:83)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.PriceProvider.access$000(PriceProvider.java:34)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at bisq.price.PriceProvider$1.run(PriceProvider.java:69)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
Jul 31 06:27:21 localhost bisq-pricenode[276520]:         at java.base/java.util.TimerThread.run(Timer.java:506)
```

#### Version

master (commit 15093720b9e7fd77a0602cb9abf91705c1b2001f)

### Steps to reproduce

Monitor the pricenode log:
`journalctl -u bisq-pricenode.service -f`

**Comment by ghost** [comment]
There was an issue in the XChange library.  The issue was raised via: https://github.com/knowm/XChange/issues/4021 and fixed in release 5.0.8.  

We are currently using release 4.4.2.

However, 5.0.8 thru 5.0.10 have issues thrown from Huobi and Binance so upgrading to fix one issue would create two more.  It seems we'll have to wait for a stable release.  https://github.com/knowm/XChange/releases
