### ISSUE TITLE
version 0.4.9.3 - NullPointer Exception

### ISSUE THREAD

**Issue by dougbebber** [bisq-network/bisq#573]
<img width="1180" alt="screen shot 2016-08-08 at 1 20 16 pm" src="https://cloud.githubusercontent.com/assets/2474050/17490964/1993e634-5d6b-11e6-82fe-9963e322635b.png">

Received this error when Looking to "Sell bitcoin" USD

**Comment by dougbebber** [comment]
Looks like it is repeatable when looking for offers involving USD.
Here is a recent log dump:

Aug-08 13:01:13.012 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.9.3, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=1, BTC_NETWORK_ID=0, getP2PNetworkId()=0} 
Aug-08 13:01:13.012 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Linux 
Aug-08 13:01:13.013 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 3.19.0-43-generic 
Aug-08 13:01:13.013 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: amd64 
Aug-08 13:01:13.013 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64 
Aug-08 13:01:13.013 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_66-b17 (Oracle Corporation) 
Aug-08 13:01:13.013 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.66-b17 (Java HotSpot(TM) 64-Bit Server VM) 
Aug-08 13:01:30.918 [BlockingClient network thread for /164.132.172.106:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: /164.132.172.106:8333: SOCKS: Connection refused 
Aug-08 13:01:31.009 [BlockingClient network thread for /77.234.49.196:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: /77.234.49.196:8333: SOCKS: Connection refused 
Aug-08 13:01:49.208 [InputHandler] INFO  i.b.p.n.Connection$InputHandler: size=496255; object=GetDataResponse{messageVersion=40, dataSet.size()=315, requestNonce=-1977330792, supportedCapabil... 
Aug-08 13:01:49.213 [JavaFX Application Thread] INFO  i.b.p.p.g.RequestDataHandler: Received data size: 315, data items: 118 items of TradeStatistics; 167 items of Offer; 27 items of MailboxStoragePayload; 1 items of Alert; 2 items of Arbitrator;  
Aug-08 13:01:54.671 [Thread-8] INFO  c.m.t.t.OnionProxyManagerEventHandler: Hidden service jb5cktwkmhdkafzu.onion:9999 published. 
Aug-08 13:01:56.383 [InputHandler-wgthuiqn3aoiovbm.onion:8000] INFO  i.b.p.n.Connection$InputHandler: size=364618; object=GetDataResponse{messageVersion=40, dataSet.size()=207, requestNonce=-743603211, supportedCapabili... 
Aug-08 13:01:56.395 [JavaFX Application Thread] INFO  i.b.p.p.g.RequestDataHandler: Received data size: 207, data items: 10 items of TradeStatistics; 167 items of Offer; 27 items of MailboxStoragePayload; 1 items of Alert; 2 items of Arbitrator;  
Aug-08 13:02:01.255 [InputHandler-uadzuib66jupaept.onion:8000] INFO  i.b.p.n.Connection$InputHandler: size=519162; object=GetDataResponse{messageVersion=40, dataSet.size()=317, requestNonce=-1740524725, supportedCapabil... 
Aug-08 13:02:11.774 [BlockingClient network thread for /80.150.198.176:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: /80.150.198.176:8333: SOCKS: Host unreachable 
Aug-08 13:02:13.409 [BlockingClient network thread for /185.17.156.23:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: /185.17.156.23:8333: SOCKS: Connection refused 
Aug-08 13:02:25.414 [BlockingClient network thread for /67.244.10.85:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: /67.244.10.85:8333: SOCKS: Host unreachable 
Aug-08 13:11:15.638 [JavaFX Application Thread] INFO  i.b.a.BitsquareApp: System load: Memory (MB)): 89 / Nr. of threads: 50 
Aug-08 13:21:15.640 [JavaFX Application Thread] INFO  i.b.a.BitsquareApp: System load: Memory (MB)): 129 / Nr. of threads: 50 
Aug-08 13:27:20.931 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
Aug-08 13:27:20.932 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableMessage= null 
Aug-08 13:27:20.932 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableClass= class java.lang.NullPointerException 
Aug-08 13:27:20.933 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Stack trace:
java.lang.NullPointerException
    at io.bitsquare.payment.PaymentAccountUtil.isPaymentAccountValidForOffer(PaymentAccountUtil.java:78)
    at io.bitsquare.payment.PaymentAccountUtil.isAnyPaymentAccountValidForOffer(PaymentAccountUtil.java:21)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookViewModel.isAnyPaymentAccountValidForOffer(OfferBookViewModel.java:364)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:610)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:588)
    at javafx.scene.control.TableCell.updateItem(TableCell.java:663)
    at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
    at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
    at com.sun.javafx.scene.control.skin.TableRowSkinBase.requestCellUpdate(TableRowSkinBase.java:659)
    at com.sun.javafx.scene.control.skin.TableRowSkinBase.lambda$init$497(TableRowSkinBase.java:159)
    at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
    at javafx.scene.control.Cell.setItem(Cell.java:403)
    at javafx.scene.control.Cell.updateItem(Cell.java:670)
    at javafx.scene.control.TableRow.updateItem(TableRow.java:259)
    at javafx.scene.control.TableRow.indexChanged(TableRow.java:225)
    at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
    at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1957)
    at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1344)
    at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
    at com.sun.javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:231)
    at com.sun.javafx.scene.control.skin.TableViewSkinBase.updateRowCount(TableViewSkinBase.java:567)
    at com.sun.javafx.scene.control.skin.VirtualContainerBase.checkState(VirtualContainerBase.java:113)
    at com.sun.javafx.scene.control.skin.VirtualContainerBase.layoutChildren(VirtualContainerBase.java:108)
    at com.sun.javafx.scene.control.skin.TableViewSkinBase.layoutChildren(TableViewSkinBase.java:696)
    at javafx.scene.control.Control.layoutChildren(Control.java:576)
    at javafx.scene.Parent.layout(Parent.java:1079)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Scene.doLayoutPass(Scene.java:552)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
    at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
    at java.lang.Thread.run(Thread.java:745)

Aug-08 13:27:20.937 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
Aug-08 13:27:20.937 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableMessage= null 
Aug-08 13:27:20.937 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableClass= class java.lang.NullPointerException 
Aug-08 13:27:20.938 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Stack trace:
java.lang.NullPointerException
    at io.bitsquare.payment.PaymentAccountUtil.isPaymentAccountValidForOffer(PaymentAccountUtil.java:78)
    at io.bitsquare.payment.PaymentAccountUtil.isAnyPaymentAccountValidForOffer(PaymentAccountUtil.java:21)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookViewModel.isAnyPaymentAccountValidForOffer(OfferBookViewModel.java:364)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:610)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:588)
    at javafx.scene.control.TableCell.updateItem(TableCell.java:663)
    at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
    at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
    at com.sun.javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:533)
    at com.sun.javafx.scene.control.skin.TableRowSkinBase.checkState(TableRowSkinBase.java:634)
    at com.sun.javafx.scene.control.skin.TableRowSkinBase.computePrefHeight(TableRowSkinBase.java:571)
    at javafx.scene.control.Control.computePrefHeight(Control.java:545)
    at javafx.scene.Parent.prefHeight(Parent.java:927)
    at javafx.scene.layout.Region.prefHeight(Region.java:1435)
    at com.sun.javafx.scene.control.skin.VirtualFlow.resizeCellSize(VirtualFlow.java:1947)
    at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1345)
    at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
    at com.sun.javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:231)
    at com.sun.javafx.scene.control.skin.TableViewSkinBase.updateRowCount(TableViewSkinBase.java:567)
    at com.sun.javafx.scene.control.skin.VirtualContainerBase.checkState(VirtualContainerBase.java:113)
    at com.sun.javafx.scene.control.skin.VirtualContainerBase.layoutChildren(VirtualContainerBase.java:108)
    at com.sun.javafx.scene.control.skin.TableViewSkinBase.layoutChildren(TableViewSkinBase.java:696)
    at javafx.scene.control.Control.layoutChildren(Control.java:576)
    at javafx.scene.Parent.layout(Parent.java:1079)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Scene.doLayoutPass(Scene.java:552)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
    at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
    at java.lang.Thread.run(Thread.java:745)

Aug-08 13:28:47.657 [BlockingClient network thread for /199.58.178.159:8333] ERROR o.b.n.BlockingClient: Error writing message to connection, closing connection java.net.SocketException: Socket is closed
    at java.net.Socket.getOutputStream(Socket.java:943) ~[na:1.8.0_66]
    at org.bitcoinj.net.BlockingClient.writeBytes(BlockingClient.java:141) ~[Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.PeerSocketHandler.sendMessage(PeerSocketHandler.java:88) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.Peer.blockChainDownloadLocked(Peer.java:1328) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.Peer.startBlockChainDownload(Peer.java:1357) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.PeerGroup.startBlockChainDownloadFromPeer(PeerGroup.java:1678) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.PeerGroup.handlePeerDeath(PeerGroup.java:1480) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.PeerGroup$PeerStartupListener.onPeerDisconnected(PeerGroup.java:234) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.Peer$1.run(Peer.java:296) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.utils.Threading$2.execute(Threading.java:141) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.Peer.connectionClosed(Peer.java:293) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.net.BlockingClient$1.run(BlockingClient.java:114) [Bitsquare-0.4.9.3.jar:na]

Aug-08 13:28:47.665 [BlockingClient network thread for /192.237.202.64:8333] ERROR o.b.n.BlockingClient: Error writing message to connection, closing connection java.net.SocketException: Socket is closed
    at java.net.Socket.getOutputStream(Socket.java:943) ~[na:1.8.0_66]
    at org.bitcoinj.net.BlockingClient.writeBytes(BlockingClient.java:141) ~[Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.PeerSocketHandler.sendMessage(PeerSocketHandler.java:88) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.Peer.blockChainDownloadLocked(Peer.java:1328) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.Peer.startBlockChainDownload(Peer.java:1357) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.PeerGroup.startBlockChainDownloadFromPeer(PeerGroup.java:1678) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.PeerGroup.handlePeerDeath(PeerGroup.java:1480) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.PeerGroup$PeerStartupListener.onPeerDisconnected(PeerGroup.java:234) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.Peer$1.run(Peer.java:296) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.utils.Threading$2.execute(Threading.java:141) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.core.Peer.connectionClosed(Peer.java:293) [Bitsquare-0.4.9.3.jar:na]
    at org.bitcoinj.net.BlockingClient$1.run(BlockingClient.java:114) [Bitsquare-0.4.9.3.jar:na]

Aug-08 13:28:57.017 [JavaFX Application Thread] INFO  i.b.a.BitsquareApp: Log files under: /home/user/.local/share/Bitsquare/bitsquare 
Aug-08 13:28:57.021 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.9.3, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=1, BTC_NETWORK_ID=0, getP2PNetworkId()=0} 
Aug-08 13:28:57.021 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Linux 
Aug-08 13:28:57.021 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 3.19.0-43-generic 
Aug-08 13:28:57.021 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: amd64 
Aug-08 13:28:57.022 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64 
Aug-08 13:28:57.022 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_66-b17 (Oracle Corporation) 
Aug-08 13:28:57.022 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.66-b17 (Java HotSpot(TM) 64-Bit Server VM) 
Aug-08 13:29:05.073 [BlockingClient network thread for /164.132.172.106:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: /164.132.172.106:8333: SOCKS: Connection refused 
Aug-08 13:29:05.402 [BlockingClient network thread for /77.234.49.196:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: /77.234.49.196:8333: SOCKS: Connection refused 
Aug-08 13:29:13.557 [InputHandler] INFO  i.b.p.n.Connection$InputHandler: size=383116; object=GetDataResponse{messageVersion=40, dataSet.size()=204, requestNonce=-2019269469, supportedCapabil... 
Aug-08 13:29:13.565 [JavaFX Application Thread] INFO  i.b.p.p.g.RequestDataHandler: Received data size: 204, data items: 174 items of Offer; 27 items of MailboxStoragePayload; 1 items of Alert; 2 items of Arbitrator;  
Aug-08 13:29:15.589 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
Aug-08 13:29:15.589 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableMessage= null 
Aug-08 13:29:15.589 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableClass= class java.lang.NullPointerException 
Aug-08 13:29:15.591 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Stack trace:
java.lang.NullPointerException
    at io.bitsquare.payment.PaymentAccountUtil.isPaymentAccountValidForOffer(PaymentAccountUtil.java:78)
    at io.bitsquare.payment.PaymentAccountUtil.isAnyPaymentAccountValidForOffer(PaymentAccountUtil.java:21)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookViewModel.isAnyPaymentAccountValidForOffer(OfferBookViewModel.java:364)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:610)
    at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:588)
    at javafx.scene.control.TableCell.updateItem(TableCell.java:663)
    at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
    at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
    at com.sun.javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:533)
    at com.sun.javafx.scene.control.skin.TableRowSkinBase.init(TableRowSkinBase.java:147)
    at com.sun.javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:64)
    at javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:212)
    at javafx.scene.control.Control.impl_processCSS(Control.java:859)
    at javafx.scene.Node.processCSS(Node.java:9056)
    at javafx.scene.Node.applyCss(Node.java:9153)
    at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1964)
    at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1344)
    at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
    at javafx.scene.Parent.layout(Parent.java:1079)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Parent.layout(Parent.java:1085)
    at javafx.scene.Scene.doLayoutPass(Scene.java:552)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
    at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
    at java.lang.Thread.run(Thread.java:745)

Aug-08 13:29:38.654 [Thread-8] INFO  c.m.t.t.OnionProxyManagerEventHandler: Hidden service jb5cktwkmhdkafzu.onion:9999 published. 
Aug-08 13:29:39.874 [InputHandler-wgthuiqn3aoiovbm.onion:8000] INFO  i.b.p.n.Connection$InputHandler: size=381448; object=GetDataResponse{messageVersion=40, dataSet.size()=203, requestNonce=-1668267533, supportedCapabil... 
Aug-08 13:29:39.888 [JavaFX Application Thread] INFO  i.b.p.p.g.RequestDataHandler: Received data size: 203, data items: 173 items of Offer; 27 items of MailboxStoragePayload; 1 items of Alert; 2 items of Arbitrator;  
Aug-08 13:29:41.283 [BlockingClient network thread for /80.150.198.176:8333] ERROR o.b.n.BlockingClient: Error trying to open/read from connection: /80.150.198.176:8333: SOCKS: Host unreachable

**Comment by ManfredKarrer** [comment]
Thanks for reporting! Got that reported from another users as well. I cannot reproduce it but i added some null check in the code for the next version.

**Comment by dougbebber** [comment]
Manfred,

Once the error results (and I can reproduce it by selecting USD in the
"Filter by currency" selection), on the "Available offers" screen, I'm
stuck on USD. I can't change to any other currency (I select another
currency in the list but it has no effect. USD stays the value in the
"Filter by currency" field.

If I shutdown Bitsquare and restart, I can get back to other currencies in
the "Filter by currency" field.

**Comment by ManfredKarrer** [comment]
Hm, I just tried again to select USD and dont get the exception, but I don't see a offer with payment method "Same bank account", those are causing the exception.
When it happens you need to restart.
Will be fixed in next release....
