### ISSUE TITLE
Bisq doesn't operate on remote NAS devices over SMBFS

### ISSUE THREAD

**Issue by gregturn** [bisq-network/bisq#5761]
### Description

Bisq works great on my local Mac. But when I move my wallet to a remote RAID-based NAS (over SMBFS), it can't launch properly and thus fails to get started.

#### Version

1.7.4

### Steps to reproduce

1. Install latest version of Bisq.
2. Set up an alternative location for the wallet.
```
$ mount 

//zzz@remote-nas-storage-unit._smb._tcp.local/Bisq on /Volumes/Bisq (smbfs, nodev, nosuid, quarantine, mounted by zzz)
```
3. Launch Bisq but with an alternative command.
```
/Volumes/Bisq/Bisq.app/Contents/MacOS/Bisq --appDataDir=/Volumes/Bisq/BisqData
```

### Expected behaviour

I expected Bisq to come up just fine. In fact, it does if I let Bisq use the default path of `~/Library/Application Support/Bisq`.

### Actual behaviour

Bisq fails to launch. It complains about a potentially corrupted SPV file. But in truth, it appears to need to do some form of low level locking on the SPV file, which for some reason, the NAS in it's configuration is unable to do. 

And so it throws this stack trace:

```
Oct-16 21:08:29.682 [JavaFX Application Thread] ERROR b.core.btc.setup.WalletsSetup: Service failure from state: STARTING; failure={} java.io.IOException: org.bitcoinj.store.BlockStoreException: java.io.IOException: Operation not supported
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:352)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.bitcoinj.store.BlockStoreException: java.io.IOException: Operation not supported
	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:159)
	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:91)
	at bisq.core.btc.setup.WalletConfig.startUp(WalletConfig.java:289)
	... 3 common frames omitted
Caused by: java.io.IOException: Operation not supported
	at java.base/sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.lock(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(Unknown Source)
	at java.base/java.nio.channels.FileChannel.tryLock(Unknown Source)
	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:133)
	... 5 common frames omitted
```

#### Device or machine

I'm doing this on MacOS Big Sur. The NAS runs ext4, which is standard Linux. But the partition is `smbfs, nodev, nosuid, quarantine`.

#### Additional info

I need this because running Bisq (Tor-based tech) directly on my machine violates security policy. By running everything off of my NAS, I can continue using Bisq. Hopefully, there is some easy adjustment to the code that may make it operational.

**Comment by rex4539** [comment]
Perhaps using a symlink pointing to your NAS but keeping the symlink in the default path.

Something like `ln -s ~/Library/Application Support/Bisq /Volumes/Bisq/BisqData`
