### ISSUE TITLE
Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by tomguim** [bisq-network/bisq#585]
This occurred when I tried to click on the Buy BTC Tab

**Comment by ManfredKarrer** [comment]
Can you send me the log files?

**Comment by dmp1ce** [comment]
I get the same error when I go to "Sell BTC" page after creating an account. I'm using version `v.0.4.9.2`. Here is my log:

```
Aug-23 01:06:30.875 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread 
Aug-23 01:06:30.875 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableMessage= null 
Aug-23 01:06:30.875 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableClass= class java.lang.NullPointerException 
Aug-23 01:06:30.875 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Stack trace:
java.lang.NullPointerException
        at io.bitsquare.payment.PaymentAccountUtil.isPaymentAccountValidForOffer(PaymentAccountUtil.java:78)
        at io.bitsquare.payment.PaymentAccountUtil.isAnyPaymentAccountValidForOffer(PaymentAccountUtil.java:21)
        at io.bitsquare.gui.main.offer.offerbook.OfferBookViewModel.isAnyPaymentAccountValidForOffer(OfferBookViewModel.java:355)
        at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:610)
        at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:588)
        at javafx.scene.control.TableCell.updateItem(TableCell.java:663)
        at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
        at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
        at com.sun.javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:533)
        at com.sun.javafx.scene.control.skin.TableRowSkinBase.checkState(TableRowSkinBase.java:634)
        at com.sun.javafx.scene.control.skin.TableRowSkinBase.computePrefHeight(TableRowSkinBase.java:571)
        at javafx.scene.control.Control.computePrefHeight(Control.java:545)
        at javafx.scene.Parent.prefHeight(Parent.java:935)
        at javafx.scene.layout.Region.prefHeight(Region.java:1435)
        at com.sun.javafx.scene.control.skin.VirtualFlow.resizeCellSize(VirtualFlow.java:1947)
        at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1345)
        at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
        at javafx.scene.Parent.layout(Parent.java:1087)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$3(Toolkit.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ManfredKarrer** [comment]
It is fixed for the next release...

**Comment by dmp1ce** [comment]
I'm getting more NullExceptions just from staring bitsquare right now. Should I post those too in another issue?

**Comment by ManfredKarrer** [comment]
Yes, can you post the logs?

**Comment by ManfredKarrer** [comment]
And the screen where it happens

**Comment by dmp1ce** [comment]
This was cleared up when I ran the code from the Development branch.

**Comment by ManfredKarrer** [comment]
Ah goo dthen it is resolved :-)
