### ISSUE TITLE
Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by dmp1ce** [bisq-network/bisq#587]
I'm running on the latest commit in the master branch and I'm getting the following error from the log.

I created a bank account and then I went to the "Sell BTC" page. If I restart the application and go to the "Sell BTC" page again I still get the error "java.lang.NullPointerException".

```
Aug-23 14:18:26.421 [JavaFX Application Thread] INFO  i.b.a.BitsquareApp: Log files under: /home/david/.local/share/Bitsquare/bitsquare
Aug-23 14:18:26.428 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.9.3, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=1, BTC_NETWORK_ID=0, getP2PNetworkId()=0}
Aug-23 14:18:26.431 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Linux
Aug-23 14:18:26.432 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 4.4.17-1-MANJARO
Aug-23 14:18:26.432 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: amd64
Aug-23 14:18:26.432 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64
Aug-23 14:18:26.432 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_102-b14 (Oracle Corporation)
Aug-23 14:18:26.432 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.102-b14 (OpenJDK 64-Bit Server VM)
INFO: uname -m call results in:x86_64
Aug-23 14:18:45.173 [InputHandler] INFO  i.b.p.n.Connection$InputHandler: size=338628; object=GetDataResponse{messageVersion=40, dataSet.size()=214, requestNonce=1435801693, supportedCapabili...
Aug-23 14:18:45.186 [JavaFX Application Thread] INFO  i.b.p.p.g.RequestDataHandler: Received data size: 214, data items: 1 items of TradeStatistics; 198 items of Offer; 12 items of MailboxStoragePayload; 1 items of Alert; 2 items of Arbitrator;
Aug-23 14:19:13.426 [Thread-9] INFO  c.m.t.t.OnionProxyManagerEventHandler: Hidden service wt2t33b37puxcirm.onion:9999 published.
Aug-23 14:19:14.141 [InputHandler-2zxtnprnx5wqr7a3.onion:8000] INFO  i.b.p.n.Connection$InputHandler: size=336866; object=GetDataResponse{messageVersion=40, dataSet.size()=213, requestNonce=702312855, supportedCapabilit...
Aug-23 14:19:14.244 [JavaFX Application Thread] INFO  i.b.p.p.g.RequestDataHandler: Received data size: 213, data items: 198 items of Offer; 12 items of MailboxStoragePayload; 1 items of Alert; 2 items of Arbitrator;
Aug-23 14:19:20.452 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Uncaught Exception from thread JavaFX Application Thread
Aug-23 14:19:20.452 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableMessage= null
Aug-23 14:19:20.453 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: throwableClass= class java.lang.NullPointerException
Aug-23 14:19:20.455 [JavaFX Application Thread] ERROR i.b.a.BitsquareApp: Stack trace:
java.lang.NullPointerException
        at io.bitsquare.payment.PaymentAccountUtil.isPaymentAccountValidForOffer(PaymentAccountUtil.java:78)
        at io.bitsquare.payment.PaymentAccountUtil.isAnyPaymentAccountValidForOffer(PaymentAccountUtil.java:21)
        at io.bitsquare.gui.main.offer.offerbook.OfferBookViewModel.isAnyPaymentAccountValidForOffer(OfferBookViewModel.java:364)
        at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:610)
        at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:588)
        at javafx.scene.control.TableCell.updateItem(TableCell.java:663)
        at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
        at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
        at com.sun.javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:533)
        at com.sun.javafx.scene.control.skin.TableRowSkinBase.init(TableRowSkinBase.java:147)
        at com.sun.javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:64)
        at javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:212)
        at javafx.scene.control.Control.impl_processCSS(Control.java:859)
        at javafx.scene.Node.processCSS(Node.java:9056)
        at javafx.scene.Node.applyCss(Node.java:9153)
        at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1964)
        at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1344)
        at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
        at javafx.scene.Parent.layout(Parent.java:1087)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$3(Toolkit.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
        at java.lang.Thread.run(Thread.java:745)

java.lang.NullPointerException
        at io.bitsquare.payment.PaymentAccountUtil.isPaymentAccountValidForOffer(PaymentAccountUtil.java:78)
        at io.bitsquare.payment.PaymentAccountUtil.isAnyPaymentAccountValidForOffer(PaymentAccountUtil.java:21)
        at io.bitsquare.gui.main.offer.offerbook.OfferBookViewModel.isAnyPaymentAccountValidForOffer(OfferBookViewModel.java:364)
        at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:610)
        at io.bitsquare.gui.main.offer.offerbook.OfferBookView$11$1.updateItem(OfferBookView.java:588)
        at javafx.scene.control.TableCell.updateItem(TableCell.java:663)
        at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
        at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
        at com.sun.javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:533)
        at com.sun.javafx.scene.control.skin.TableRowSkinBase.init(TableRowSkinBase.java:147)
        at com.sun.javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:64)
        at javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:212)
        at javafx.scene.control.Control.impl_processCSS(Control.java:859)
        at javafx.scene.Node.processCSS(Node.java:9056)
        at javafx.scene.Node.applyCss(Node.java:9153)
        at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1964)
        at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1344)
        at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1197)
        at javafx.scene.Parent.layout(Parent.java:1087)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Parent.layout(Parent.java:1093)
        at javafx.scene.Scene.doLayoutPass(Scene.java:552)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$3(Toolkit.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by devildemon77** [comment]
I am having the same problem. 

Error message: 
java.lang.NullPointerException

**Comment by ManfredKarrer** [comment]
That is fixed for the upcoming version (prob. in a few days it will be released).

**Comment by dmp1ce** [comment]
Sorry, I didn't see that the commits were going into the development branch.

**Comment by ManfredKarrer** [comment]
No worry, thanks for reporting!
