### ISSUE TITLE
NPE accountName must not be null

### ISSUE THREAD

**Issue by salokiam** [bisq-network/bisq#6035]
I am using Win64, when I switched back to bisq, not clicking anywhere, It showed me a NPE, here is the log:
Iam using bisq v1.8.2

Feb.-08 10:21:19.336 [JavaFX Application Thread] INFO  b.c.u.Profiler: Total memory: 616 MB; Used memory: 556,954 MB; Free memory: 59,046 MB; Max memory: 2 GB; No. of threads: 75 
Feb.-08 10:22:24.835 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerVbyte=10 minFeePerVbyte=2 
Feb.-08 10:26:35.818 [JavaFX Application Thread] INFO  b.d.c.c.c.PopOver: hide:0.0 ms 
Feb.-08 10:26:35.818 [JavaFX Application Thread] INFO  b.d.c.c.c.PopOver: hide:0.0 ms 
Feb.-08 10:26:35.818 [JavaFX Application Thread] INFO  b.d.c.c.c.PopOver: hide:0.0 ms 
Feb.-08 10:26:35.818 [JavaFX Application Thread] INFO  b.d.c.c.c.PopOver: hide:0.0 ms 
Feb.-08 10:26:35.818 [JavaFX Application Thread] INFO  b.d.c.c.c.PopOver: hide:0.0 ms 
Feb.-08 10:26:35.819 [JavaFX Application Thread] INFO  b.d.c.c.c.PopOver: hide:0.0 ms 
Feb.-08 10:26:36.025 [JavaFX Application Thread] ERROR b.c.p.PersistenceManager: Error in saveToFile toProtoMessage: UserPayload, UserPayload 
Feb.-08 10:26:36.028 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Feb.-08 10:26:36.028 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= java.lang.NullPointerException: accountName must not be null 
Feb.-08 10:26:36.028 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.RuntimeException 
Feb.-08 10:26:36.031 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.RuntimeException: java.lang.NullPointerException: accountName must not be null
	at bisq.common.persistence.PersistenceManager.persistNow(PersistenceManager.java:432)
	at bisq.common.persistence.PersistenceManager.lambda$maybeStartTimerForPersistence$8(PersistenceManager.java:407)
	at bisq.common.reactfx.FxTimer.lambda$restart$0(FxTimer.java:93)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.animation.Timeline.doPlayTo(Timeline.java:172)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.animation.Animation.doTimePulse(Animation.java:1186)
	at javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:204)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.animation.Animation$1.timePulse(Animation.java:203)
	at com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:343)
	at com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:559)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: accountName must not be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:899)
	at bisq.core.payment.PaymentAccount.toProtoMessage(PaymentAccount.java:91)
	at bisq.core.payment.PaymentAccount.toProtoMessage(PaymentAccount.java:47)
	at bisq.common.proto.ProtoUtil.lambda$collectionToProto$0(ProtoUtil.java:88)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at bisq.common.proto.ProtoUtil.collectionToProto(ProtoUtil.java:97)
	at bisq.core.user.UserPayload.lambda$toProtoMessage$1(UserPayload.java:97)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at bisq.core.user.UserPayload.toProtoMessage(UserPayload.java:97)
	at bisq.core.user.UserPayload.toProtoMessage(UserPayload.java:47)
	at bisq.common.proto.persistable.PersistableEnvelope.toPersistableMessage(PersistableEnvelope.java:30)
	at bisq.common.persistence.PersistenceManager.persistNow(PersistenceManager.java:418)
	... 21 `more```

**Comment by ghost** [comment]
What you was doing when this bug occurred?

**Comment by salokiam** [comment]
I was just returning to that app. Earlier that day I made an offer, then left the compueter alone for some time (Computer no going into sleep mode). Then I returne to the computer and saw the NPE. Sorry, no steps t reproduce the error.

**Comment by ripcurlx** [comment]
> I was just returning to that app. Earlier that day I made an offer, then left the compueter alone for some time (Computer no going into sleep mode). Then I returne to the computer and saw the NPE. Sorry, no steps t reproduce the error.

Do you remember which view was open when you returned to the app?

**Comment by salokiam** [comment]
"Sell BTC"

**Comment by ghost** [comment]
This is happening quite frequently while testing release 1.8.3.  One way to reproduce, doing the following:

- Create a SEPA Instant account.  Save it.
- Click on the newly created account in the account list.
- ~~Click on toggle button "Use Custom Account Name".~~
- Click away to a different menu item, e.g. Buy BTC or Funds.
- Click on Account menu.
- The account name is blank.
- Click on the account, NPE happens, close down Bisq, NPE from OP happens.


[Edit] Step 3 above is not even necessary.

**Comment by ghost** [comment]
@jmacxx I noticed problem with this scenario and fixed it [here](https://github.com/bisq-network/bisq/pull/6014/commits/940f8dcd00902aa2d464ed2ed45402f02c788d81) - not yet merged. I'm wondering if case mentioned originally in this issue is same.

**Comment by ghost** [comment]
I'm convinced this is the same issue.  I just tested with https://github.com/bisq-network/bisq/pull/6014/commits/940f8dcd00902aa2d464ed2ed45402f02c788d81.  Please could you make a PR for the one line fix so @ripcurlx can cherry pick it into v1.8.3.

**Comment by ghost** [comment]
Sure

**Comment by salokiam** [comment]
Yes, I had 2 accounts renamed, shortly before I got the NPE.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------
