### ISSUE TITLE
Freeze / NPE when clicking on account age icon at offer entry

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#6059]
### Description

If you click on the account age icon in the account selection drop down at offer entry, the app freezes, a huge empty window is shown (with no contents) and an NPE is written to bisq.log.  The app cannot be closed, unless by `kill -9 [pid]`

#### Version

Current production release, v1.8.2
Most likely a problem with earlier releases too.  [Edit - has been reported previously #5383]

### Steps to reproduce

- You have at lease one account that features aging or signing, e.g. Zelle or SEPA.
- Click Buy BTC.
- Click Create New Offer To Buy BTC
- In the Create Offer screen, drop down the list of available accounts.
- See the icon next to the aged account, and click on it.
 

### Expected behaviour

Hovering over the icon shows a popover.
Clicking the icon should choose that payment account, or at least have no ill-effect.

### Actual behaviour

Crash

### Screenshots

![image](https://user-images.githubusercontent.com/47253594/154729809-e62c7e96-c95e-4713-a07c-78639c1b6308.png)

![image](https://user-images.githubusercontent.com/47253594/154728739-85857bc3-0c0c-40f8-b871-884406e57756.png)

#### Device or machine

Ubuntu Linux.

#### Additional info

    Feb-18 10:32:18.503 [JavaFX Application Thread] INFO  b.d.c.c.control.PopOver: hide:200.0 ms 
    Feb-18 10:32:18.504 [JavaFX Application Thread] INFO  b.d.c.c.control.PopOver: hide:200.0 ms 
    Feb-18 10:32:18.604 [JavaFX Application Thread] INFO  b.d.c.c.control.PopOver: hide:200.0 ms 
    Feb-18 10:32:18.606 [JavaFX Application Thread] INFO  b.d.c.c.control.PopOver: hide:200.0 ms 
    Feb-18 10:32:18.606 [JavaFX Application Thread] INFO  b.d.c.c.control.PopOver: hide:200.0 ms 
    Feb-18 10:32:18.615 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
    Feb-18 10:32:18.615 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= null 
    Feb-18 10:32:18.616 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.NullPointerException 
    Feb-18 10:32:18.633 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
    java.lang.NullPointerException
	    at com.sun.javafx.tk.quantum.GlassScene.getClearColor(GlassScene.java:334)
	    at com.sun.javafx.tk.quantum.SceneState.update(SceneState.java:100)
	    at com.sun.javafx.tk.quantum.GlassScene.updateSceneState(GlassScene.java:277)
	    at com.sun.javafx.tk.quantum.GlassScene.releaseSynchronization(GlassScene.java:138)
	    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2511)
	    at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:413)
	    at java.base/java.security.AccessController.doPrivileged(Native Method)
	    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:412)
	    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:439)
	    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:563)
	    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543)
	    at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536)
	    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342)
	    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	    at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ghost** [comment]
Is a bug in JavaFX: when a popover's parent window is closed before the popover itself has closed.
Selecting the list item closes the combo dropdown before the popover close.

Same error stack reported here: https://github.com/controlsfx/controlsfx/issues/448
And here: https://github.com/dlsc-software-consulting-gmbh/CalendarFX/issues/96

**Comment by abhinayagarwal** [comment]
Might be related to https://bugs.openjdk.java.net/browse/JDK-8265835

**Comment by ripcurlx** [comment]
> Is a bug in JavaFX: when a popover's parent window is closed before the popover itself has closed. Selecting the list item closes the combo dropdown before the popover close.
> 
> Same error stack reported here: [controlsfx/controlsfx#448](https://github.com/controlsfx/controlsfx/issues/448) And here: [dlsc-software-consulting-gmbh/CalendarFX#96](https://github.com/dlsc-software-consulting-gmbh/CalendarFX/issues/96)

Maybe we could just not enable the roll over popups in the combobox item renderers until this is fixed properly in JavaFX. WDYT?
