### ISSUE TITLE
NullPointerException at com.sun.scenario.effect...

### ISSUE THREAD

**Issue by stiell** [bisq-network/bisq#607]
Whenever a pop-up window appears, the UI sometimes freezes with a NullPointerException printed to the terminal, e.g.:

```
java.lang.NullPointerException
    at com.sun.scenario.effect.impl.sw.sse.SSELinearConvolvePeer.filter(SSELinearConvolvePeer.java:83)
    at com.sun.scenario.effect.impl.sw.sse.SSELinearConvolvePeer.filter(SSELinearConvolvePeer.java:44)
    at com.sun.scenario.effect.LinearConvolveCoreEffect.filterImageDatas(LinearConvolveCoreEffect.java:85)
    at com.sun.scenario.effect.LinearConvolveCoreEffect.filterImageDatas(LinearConvolveCoreEffect.java:41)
    at com.sun.scenario.effect.FilterEffect.filter(FilterEffect.java:195)
    at com.sun.scenario.effect.impl.prism.PrEffectHelper.render(PrEffectHelper.java:166)
    at com.sun.javafx.sg.prism.EffectFilter.render(EffectFilter.java:61)
    at com.sun.javafx.sg.prism.NGNode.renderEffect(NGNode.java:2365)
    at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2050)
    at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
    at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
    at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:330)
    at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:134)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
    at java.lang.Thread.run(Thread.java:745)
```

or:

```
java.lang.NullPointerException
    at com.sun.scenario.effect.impl.sw.sse.SSEColorAdjustPeer.filter(SSEColorAdjustPeer.java:117)
    at com.sun.scenario.effect.CoreEffect.filterImageDatas(CoreEffect.java:106)
    at com.sun.scenario.effect.ColorAdjust.filterImageDatas(ColorAdjust.java:36)
    at com.sun.scenario.effect.FilterEffect.filter(FilterEffect.java:195)
    at com.sun.scenario.effect.FilterEffect.filter(FilterEffect.java:185)
    at com.sun.scenario.effect.impl.prism.PrEffectHelper.render(PrEffectHelper.java:166)
    at com.sun.javafx.sg.prism.EffectFilter.render(EffectFilter.java:61)
    at com.sun.javafx.sg.prism.NGNode.renderEffect(NGNode.java:2365)
    at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2050)
    at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
    at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
    at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:330)
    at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:134)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
    at java.lang.Thread.run(Thread.java:745)
```

At that point I have to interrupt Bitsquare from the terminal and restart it.

I'm using Bitsquare v.0.4.9.6 on Debian 8 in a Qubes (Xen) VM, with i3 as the window manager.

**Comment by ManfredKarrer** [comment]
Never saw that bug, seems to be an issue with the graphic system and jdk. Can you post more logs to see where it start form the Bitsquare code?

**Comment by stiell** [comment]
The exceptions are only printed to the terminal, not to the log files in `~/.local/share/Bitsquare/`. I've attached partial terminal output with `--logLevel TRACE`, see [bitsquare-trace-npe.txt](https://github.com/bitsquare/bitsquare/files/491247/bitsquare-trace-npe.txt). With `-Dprism.verbose=true` it shows at initialisation that it uses software rendering:

```
Picked up JAVA_TOOL_OPTIONS: -Dprism.verbose=true
Prism pipeline init order: es2 sw 
Using java-based Pisces rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2
    succeeded.
GLFactory using com.sun.prism.es2.X11GLFactory
(X) Got class = class com.sun.prism.es2.ES2Pipeline
Failed Graphics Hardware Qualifier check.
System GPU doesn't meet the es2 pipe requirement
GraphicsPipeline.createPipeline: error initializing pipeline com.sun.prism.es2.ES2Pipeline
*** Fallback to Prism SW pipeline
Prism pipeline name = com.sun.prism.sw.SWPipeline
(X) Got class = class com.sun.prism.sw.SWPipeline
Initialized prism pipeline: com.sun.prism.sw.SWPipeline
 vsync: true vpipe: false
```

I tried the deprecated `-Dprism.order=j2d`, but that quickly ended up in an infinite loop of a different NullPointerException.

More system info:

```
Sep-24 18:24:17.153 [JavaFX Application Thread] INFO  i.b.app.Version: Version{VERSION=0.4.9.6, P2P_NETWORK_VERSION=4, LOCAL_DB_VERSION=4, TRADE_PROTOCOL_VERSION=1, BTC_NETWORK_ID=0, getP2PNetworkId()=0} 
Sep-24 18:24:17.153 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.name: Linux 
Sep-24 18:24:17.153 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.version: 4.4.12-9.pvops.qubes.x86_64 
Sep-24 18:24:17.153 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: os.arch: amd64 
Sep-24 18:24:17.153 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: sun.arch.data.model: 64 
Sep-24 18:24:17.153 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JRE: 1.8.0_66-b17 (Oracle Corporation) 
Sep-24 18:24:17.153 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: JVM: 25.66-b17 (Java HotSpot(TM) 64-Bit Server VM) 
INFO: uname -m call results in:x86_64
```

**Comment by ManfredKarrer** [comment]
Hm, seems a JDK issue... Unfortunaely it seems to not support very well several graphic systems on Linux. Maybe u can file a report on the JDK bug list?

**Comment by ManfredKarrer** [comment]
I think we cannot fix that as it seems like a JDK bug
