### ISSUE TITLE
NPE when duplicating offer if the account does not exist.

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq#6232]
### Description

Go to Portfolio -> History.  Click on the icon to duplicate one of your previous offers.  If the account of that offer is not available, a NPE error box will be displayed.

#### Version

1.9.1, probably earlier versions too.

### Expected behaviour

- If possible, clear the account selection which would make the user choose an account to enter the offer.

### Screenshots

![image](https://user-images.githubusercontent.com/47253594/171227303-25c136ed-4a24-44d0-bea8-49baccd72a5e.png)

    May-31 11:25:48.280 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.NullPointerException 
    May-31 11:25:48.293 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
    java.lang.NullPointerException
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferDataModel.isUsingHalCashAccount(MutableOfferDataModel.java:804)
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.setAmountToModel(MutableOfferViewModel.java:1176)
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.onFocusOutAmountTextField(MutableOfferViewModel.java:724)
	    at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.triggerFocusOutOnAmountFields(MutableOfferViewModel.java:861)
	    at bisq.desktop.main.portfolio.duplicateoffer.DuplicateOfferViewModel.activate(DuplicateOfferViewModel.java:89)
	    at bisq.desktop.common.model.ActivatableWithDataModel._activate(ActivatableWithDataModel.java:29)
	    at bisq.desktop.common.view.ActivatableViewAndModel.lambda$prepareInitialize$0(ActivatableViewAndModel.java:37)

**Comment by ripcurlx** [comment]
@xyzmaker123 Could you take this one? Thanks!
