### ISSUE TITLE
 org.bitcoinj.core.ECKey$KeyIsEncryptedException when trying to accept a BTC/fiat trade as a taker.

### ISSUE THREAD

**Issue by pajaco** [bisq-network/bisq#6305]
### Description

 org.bitcoinj.core.ECKey$KeyIsEncryptedException when trying to accept a BTC/fiat trade as a taker.

#### Version

1.9.4

### Steps to reproduce

1. Take a BTC for fiat, SEPA/EUR offer.
2. On Take offer screen: leave BTC as the fee currency and press NEXT STEP. 
3. Observe error popup and stack in the log.

### Expected behaviour

Be shown "Confirm trade" screen/modal.

### Actual behaviour

A modal with error gets shown that when dismissed shows the underlying "Accept offer" screen not displaying the bottom panes where "advanced settings" and NEXT STEP and CANCEL buttons reside.

### Screenshots

<img width="1021" alt="Screenshot 2022-07-31 at 15 11 47" src="https://user-images.githubusercontent.com/406310/182030804-97d59f51-c25a-430d-ad5d-b38d9cd2977a.png">

<img width="1090" alt="Screenshot 2022-07-31 at 15 27 42" src="https://user-images.githubusercontent.com/406310/182031327-97fe1759-3a7e-4570-ae3a-513257cf8eea.png">

#### Device or machine

Mac M1, OS 12.3.1

#### Additional info

```
Jul-31 15:11:31.693 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Jul-31 15:11:31.695 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= null 
Jul-31 15:11:31.695 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class org.bitcoinj.core.ECKey$KeyIsEncryptedException 
Jul-31 15:11:31.706 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
org.bitcoinj.core.ECKey$KeyIsEncryptedException
	at org.bitcoinj.wallet.DecryptingKeyBag.maybeDecrypt(DecryptingKeyBag.java:50)
	at org.bitcoinj.wallet.DecryptingKeyBag.findKeyFromPubKeyHash(DecryptingKeyBag.java:68)
	at org.bitcoinj.core.TransactionOutPoint.getConnectedRedeemData(TransactionOutPoint.java:175)
	at org.bitcoinj.core.TransactionInput.getConnectedRedeemData(TransactionInput.java:333)
	at org.bitcoinj.wallet.Wallet.signTransaction(Wallet.java:4298)
	at org.bitcoinj.wallet.Wallet.completeTx(Wallet.java:4226)
	at bisq.core.btc.wallet.BtcWalletService.getEstimatedFeeTxVsize(BtcWalletService.java:1143)
	at bisq.core.btc.TxFeeEstimationService.getEstimatedTxVsize(TxFeeEstimationService.java:188)
	at bisq.core.btc.TxFeeEstimationService.getEstimatedFeeAndTxVsize(TxFeeEstimationService.java:107)
	at bisq.core.btc.TxFeeEstimationService.getEstimatedFeeAndTxVsizeForTaker(TxFeeEstimationService.java:79)
	at bisq.desktop.main.offer.bisq_v1.takeoffer.TakeOfferDataModel.estimateTxVsize(TakeOfferDataModel.java:387)
	at bisq.desktop.main.offer.bisq_v1.takeoffer.TakeOfferDataModel.onShowPayFundsScreen(TakeOfferDataModel.java:286)
	at bisq.desktop.main.offer.bisq_v1.takeoffer.TakeOfferViewModel.onShowPayFundsScreen(TakeOfferViewModel.java:270)
	at bisq.desktop.main.offer.bisq_v1.takeoffer.TakeOfferView.onShowPayFundsScreen(TakeOfferView.java:497)
	at bisq.desktop.main.offer.bisq_v1.takeoffer.TakeOfferView.showFeeOption(TakeOfferView.java:969)
	at bisq.desktop.main.offer.bisq_v1.takeoffer.TakeOfferView.showNextStepAfterAmountIsSet(TakeOfferView.java:938)
	at bisq.desktop.main.offer.bisq_v1.takeoffer.TakeOfferView.nextStepCheckMakerTx(TakeOfferView.java:932)
	at bisq.desktop.main.offer.bisq_v1.takeoffer.TakeOfferView.lambda$addButtons$25(TakeOfferView.java:908)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8889)
	at javafx.scene.control.Button.fire(Button.java:203)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```

**Comment by pajaco** [comment]
FWIW I restored the wallet from the seed phrase and this went away.
