### ISSUE TITLE
Error creating sales offer [CreateMakerFeeTx]

### ISSUE THREAD

**Issue by thiagopaesm** [bisq-network/bisq#6400]
### Description

Error creating sales offer. The error happens when after the submit(confirmation). Offer sell BTC for BRL(fiat)

#### Version
1.9.6 (LAST)

### Screenshots

![Captura de tela de 2022-11-02 00-33-40](https://user-images.githubusercontent.com/8849975/199556351-d647bf5e-386f-4380-b143-394ef11d6b5c.png)

#### Device or machine

Linux Ubuntu 22.04 64bits

**Comment by ghost** [comment]
Please paste here some contextual information from your bisq.log file.  Search for `error occurred at task` and post several lines before and after it.  Hopefully will provide more information as to why it failed.

**Comment by thiagopaesm** [comment]
> Please paste here some contextual information from your bisq.log file. Search for `error occurred at task` and post several lines before and after it. Hopefully will provide more information as to why it failed.

Hi, thanks for support

nov.-02 13:03:13.349 [JavaFX Application Thread] ERROR b.c.b.w.TradeWalletService: completeBsqTradingFeeTx: preparedBsqTx=Transaction{
weight: 1332 wu, 333 bytes
purpose: USER_PAYMENT
   in   <empty>  0.00000562 BTC (562)
        P2WPKH addr:  outpoint::1
   in   <empty>  0.00005 BTC (5000)
        P2WPKH addr:  outpoint::0
   in   PUSHDATA(72)[3045022100e0102e87b00d85f48af4e55f9add6400c3b334e81f4cfc2be5a3dac709996a0702200529e2ce0b2bd063b2d0e82e5547af329bc650d56bad5d24bbc7eb7a49ab081601] PUSHDATA(33)[020ac335fff955073fbe958567862a1b89579d39630c0087f46b81acbdd5cb6ec0]  0.10 BTC (10000000)
        P2PKH addr:  outpoint:d1d486f9edca151b32f754d6a5f7271e8427d1496d850c271fc0203d84261f9a:0
   out  0[] PUSHDATA(20)[5e584bb540284e62d8a9ae04199a9d39b21d623e] (00145e584bb540284e62d8a9ae04199a9d39b21d623e)  0.00005526 BTC (5526)
        P2WPKH addr:
   out  0[] PUSHDATA(20)[5e9f978264cc186243b6b69eb944c699d87d8f6d] (00145e9f978264cc186243b6b69eb944c699d87d8f6d)  0.02875 BTC (2875000)
        P2WPKH addr:
   out  0[] PUSHDATA(20)[f0b9010c25cb215da5e8b2ce7356e58a3d581620] (0014f0b9010c25cb215da5e8b2ce7356e58a3d581620)  0.07118316 BTC (7118316)
        P2WPKH addr:
   fee  0.00005045 BTC/wu, 0.0002018 BTC/kB  0.0000672 BTC
} 
nov.-02 13:03:13.352 [JavaFX Application Thread] ERROR b.c.t.Task: An error occurred at task: CreateMakerFeeTx bisq.core.btc.exceptions.WalletException: java.lang.IllegalStateException
	at bisq.core.btc.wallet.WalletService.checkWalletConsistency(WalletService.java:244)
	at bisq.core.btc.wallet.TradeWalletService.completeBsqTradingFeeTx(TradeWalletService.java:286)
	at bisq.core.offer.placeoffer.bisq_v1.tasks.CreateMakerFeeTx.run(CreateMakerFeeTx.java:114)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.handleComplete(TaskRunner.java:85)
	at bisq.common.taskrunner.Task.complete(Task.java:58)
	at bisq.core.offer.placeoffer.bisq_v1.tasks.CheckNumberOfUnconfirmedTransactions.run(CheckNumberOfUnconfirmedTransactions.java:18)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.handleComplete(TaskRunner.java:85)
	at bisq.common.taskrunner.Task.complete(Task.java:58)
	at bisq.core.offer.placeoffer.bisq_v1.tasks.ValidateOffer.run(ValidateOffer.java:96)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.run(TaskRunner.java:60)
	at bisq.core.offer.placeoffer.bisq_v1.PlaceOfferProtocol.placeOffer(PlaceOfferProtocol.java:86)
	at bisq.core.offer.OpenOfferManager.placeOffer(OpenOfferManager.java:409)
	at bisq.desktop.main.offer.bisq_v1.MutableOfferDataModel.onPlaceOffer(MutableOfferDataModel.java:334)
	at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.onPlaceOffer(MutableOfferViewModel.java:656)
	at bisq.desktop.main.offer.bisq_v1.MutableOfferView.lambda$onPlaceOffer$1(MutableOfferView.java:385)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at bisq.desktop.main.overlays.windows.OfferDetailsWindow.lambda$addConfirmAndCancelButtons$3(OfferDetailsWindow.java:444)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8889)
	at javafx.scene.control.Button.fire(Button.java:203)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:494)
	at bisq.core.btc.wallet.WalletService.checkWalletConsistency(WalletService.java:240)
	... 64 common frames omitted

nov.-02 13:03:13.365 [JavaFX Application Thread] ERROR b.c.t.TaskRunner: Task failed: CreateMakerFeeTx / errorMessage: An error occurred at task: CreateMakerFeeTx 
nov.-02 13:03:13.365 [JavaFX Application Thread] ERROR b.c.o.p.b.PlaceOfferProtocol: An error occurred at task: CreateMakerFeeTx 
nov.-02 13:03:13.366 [JavaFX Application Thread] ERROR b.d.m.o.b.c.CreateOfferDataModel: An error occurred at task: CreateMakerFeeTx 
nov.-02 13:03:28.355 [InputHandler-t3ham5fd3yxi2gm2j3kgzq2que5p46rgjzabixcc3pbxcna67lmfcuad.onion:9999] INFO  b.n.p.n.Connection: Shut down caused by exception java.net.SocketTimeoutException: Read timed out on connection=Connection{peerAddress=Optional[t3ham5fd3yxi2gm2j3kgzq2que5p46rgjzabixcc3pbxcna67lmfcuad.onion:9999], connectionState=ConnectionState{,
     peerType=PEER,
     numInitialDataRequests=0,
     numInitialDataResponses=0,
     lastInitialDataMsgTimeStamp=0,
     isSeedNode=false,
     expectedRequests=5
}, connectionType=InboundConnection, uid='4ee0dc9c-b97d-43fa-9da5-8eeca687ab3f'} 
nov.-02 13:03:28.356 [InputHandler-t3ham5fd3yxi2gm2j3kgzq2que5p46rgjzabixcc3pbxcna67lmfcuad.onion:9999] INFO  b.n.p.n.Connection: Connection shutdown started 
nov.-02 13:03:28.356 [JavaFX Application Thread] INFO  b.n.p.p.PeerManager: onDisconnect called: nodeAddress=Optional[t3ham5fd3yxi2gm2j3kgzq2que5p46rgjzabixcc3pbxcna67lmfcuad.onion:9999], closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=false} SOCKET_TIMEOUT 
nov.-02 13:03:28.357 [JavaFX Application Thread] INFO  b.n.p.p.p.PeerExchangeManager: onDisconnect closeConnectionReason=CloseConnectionReason{sendCloseMessage=false, isIntended=false} SOCKET_TIMEOUT, nodeAddressOpt=Optional[t3ham5fd3yxi2gm2j3kgzq2que5p46rgjzabixcc3pbxcna67lmfcuad.onion:9999] 
nov.-02 13:04:36.932 [JavaFX Application Thread] INFO  b.c.u.Profiler: Total memory: 919 MB; Used memory: 851,54 MB; Free memory: 67,46 MB; Max memory: 2 GB; No. of threads: 75 
nov.-02 13:05:09.047 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerVbyte=23 minFeePerVbyte=2 
nov.-02 13:06:13.961 [JavaFX Application Thread] INFO  b.d.m.s.p.PreferencesView: tx fee = 0.00000003 BTC 
nov.-02 13:06:29.770 [JavaFX Application Thread] INFO  b.d.m.s.p.PreferencesView: tx fee = 0.00000003 BTC

**Comment by ghost** [comment]
Thanks, looks like your wallet is failing its consistency check & needs a resync.  https://bisq.wiki/Resyncing_SPV_file

**Comment by dav1dpgit** [comment]
I received the same issue, but is the solution the same?

Log file attached:
[bisq.log](https://github.com/bisq-network/bisq/files/10169805/bisq.log)
