### ISSUE TITLE
show summary under portfolio history error, log attached

### ISSUE THREAD

**Issue by styleisfoundation** [bisq-network/bisq#6464]

**Comment by ghost** [comment]
@styleisfoundation There's currently no information in your post above.  Could you provide any details, as prompted by the template?  A stack trace from bisq.log would be useful.

**Comment by styleisfoundation** [comment]
@jmacxx here is link to the log file from bisq right after the error I
received.

https://github.com/bisq-network/bisq/files/10242537/bisq.log

Hope this reaches you.

Thanks for your help :)

**Comment by ghost** [comment]
exception from the log:

    Dec.-15 19:50:03.180 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
    Dec.-15 19:50:03.181 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= Expected a finite double, but found NaN 
    Dec.-15 19:50:03.182 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.IllegalArgumentException 
    Dec.-15 19:50:03.192 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
    java.lang.IllegalArgumentException: Expected a finite double, but found NaN
	    at bisq.common.util.MathUtils.roundDouble(MathUtils.java:46)
	    at bisq.common.util.MathUtils.roundDouble(MathUtils.java:38)
	    at bisq.core.util.FormattingUtils.formatToPercent(FormattingUtils.java:231)
	    at bisq.core.util.FormattingUtils.formatToPercent(FormattingUtils.java:227)
	    at bisq.core.util.FormattingUtils.formatToPercentWithSymbol(FormattingUtils.java:211)
	    at bisq.core.trade.ClosedTradableFormatter.getTotalTxFeeAsString(ClosedTradableFormatter.java:103)
	    at bisq.desktop.main.portfolio.closedtrades.ClosedTradesViewModel.getTotalTxFee(ClosedTradesViewModel.java:62)
	    at bisq.desktop.main.overlays.windows.ClosedTradesSummaryWindow.addContent(ClosedTradesSummaryWindow.java:81)
	    at bisq.desktop.main.overlays.windows.ClosedTradesSummaryWindow.show(ClosedTradesSummaryWindow.java:50)
	    at bisq.desktop.main.portfolio.closedtrades.ClosedTradesView.lambda$activate$12(ClosedTradesView.java:335)
	    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)

**Comment by styleisfoundation** [comment]
I'm automatically suspicious of the multiple ports and java strings and
such but my knowledge is limited to the point where I wouldn't know without
researching a bit more. I'm glad your all here to help :) hope it's nothing
major.

**Comment by ghost** [comment]
@styleisfoundation its just a UI display bug -- the reason it has not been noticed before is that it only happens in cases where there is literally zero trade history.  Most user's have at least 1 completed trade before invoking that trades summary button and the bug does not manifest itself then.  Anyway, thanks for bringing it up, PR #6466 is submitted to correct it.
