### ISSUE TITLE
Error comes when i run ./run-bisq.sh on TailsOS

### ISSUE THREAD

**Issue by S108T** [bisq-network/bisq#6470]
./run-bisq.sh

fault: An unexpected error occurred. Please file a report at https://bisq.network/issues
java.io.UncheckedIOException: Directory '/home/amnesia/.local/share/Bisq/btc_mainnet' could not be created
	at bisq.common.config.Config.mkdir(Config.java:915)
	at bisq.common.config.Config.<init>(Config.java:820)
	at bisq.core.app.BisqExecutable.execute(BisqExecutable.java:89)
	at bisq.desktop.app.BisqAppMain.main(BisqAppMain.java:58)
Caused by: java.nio.file.AccessDeniedException: /home/amnesia/.local/share/Bisq/btc_mainnet
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
	at java.base/java.nio.file.Files.createDirectory(Unknown Source)
	at bisq.common.config.Config.mkdir(Config.java:913)
	... 3 more

**Comment by ghost** [comment]
Not familiar with `./run-bisq.sh` -- can you paste the contents of it, or show where it is obtained from?
It looks like Bisq on your system does not have write access to `/home/amnesia/.local/share`

**Comment by S108T** [comment]
I look .local/share location the folder had a write and delete permission as owner rights ...and group permission was "Acess" i change it to create and delete files.
and try to run /run-bisq.sh from Presistent...Attached the Screenshot of the error. 
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Dec 18, 2022, 19:23 by ***@***.***:
