### ISSUE TITLE
Error in saveToFile toProtoMessage - Client App Mac M1 (v1.9.9) 

### ISSUE THREAD

**Issue by andoniabedul** [bisq-network/bisq#6513]
### Description
Error wit

Init the app, it show an error:

```
ene.-09 02:58:28.401 [JavaFX Application Thread] ERROR b.c.p.PersistenceManager: Error in saveToFile toProtoMessage: PreferencesPayload, PreferencesPayload 
ene.-09 02:58:28.402 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
ene.-09 02:58:28.403 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= java.lang.NullPointerException 
ene.-09 02:58:28.403 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.RuntimeException 
ene.-09 02:58:28.404 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.RuntimeException: java.lang.NullPointerException
	at bisq.common.persistence.PersistenceManager.persistNow(PersistenceManager.java:441)
	at bisq.common.persistence.PersistenceManager.persistNow(PersistenceManager.java:419)
	at bisq.common.persistence.PersistenceManager.lambda$maybeStartTimerForPersistence$8(PersistenceManager.java:407)
	at bisq.common.reactfx.FxTimer.lambda$restart$0(FxTimer.java:93)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.animation.Timeline.doPlayTo(Timeline.java:172)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.animation.Animation.doTimePulse(Animation.java:1186)
	at javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:204)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.animation.Animation$1.timePulse(Animation.java:203)
	at com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:343)
	at com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:559)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.NullPointerException
	at protobuf.Region$Builder.setName(Region.java:610)
	at bisq.core.locale.Country.toProtoMessage(Country.java:46)
	at bisq.core.user.PreferencesPayload.toProtoMessage(PreferencesPayload.java:164)
	at bisq.common.proto.persistable.PersistableEnvelope.toPersistableMessage(PersistableEnvelope.java:30)
	at bisq.common.persistence.PersistenceManager.persistNow(PersistenceManager.java:427)
	... 19 more
```

#### Version

1.9.9

### Steps to reproduce
 Init the app. 

#### Device or machine

Mac OS, 12.1 

Chip M1

#### Additional info

If I open the security backup it's throws another error:

```
ene.-09 03:04:06.658 [JavaFX Application Thread] INFO  b.c.p.PersistenceManager: Start flushAllDataToDisk 
ene.-09 03:04:06.664 [JavaFX Application Thread] ERROR b.c.p.PersistenceManager: Error in saveToFile toProtoMessage: PreferencesPayload, PreferencesPayload 
ene.-09 03:04:06.669 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
ene.-09 03:04:06.670 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= java.lang.NullPointerException 
ene.-09 03:04:06.670 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.RuntimeException 
ene.-09 03:04:06.671 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.RuntimeException: java.lang.NullPointerException
	at bisq.common.persistence.PersistenceManager.persistNow(PersistenceManager.java:441)
	at bisq.common.persistence.PersistenceManager.persistNow(PersistenceManager.java:419)
	at bisq.common.persistence.PersistenceManager.lambda$flushAllDataToDisk$3(PersistenceManager.java:152)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at bisq.common.persistence.PersistenceManager.lambda$flushAllDataToDisk$4(PersistenceManager.java:139)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.NullPointerException
	at protobuf.Region$Builder.setName(Region.java:610)
	at bisq.core.locale.Country.toProtoMessage(Country.java:46)
	at bisq.core.user.PreferencesPayload.toProtoMessage(PreferencesPayload.java:164)
	at bisq.common.proto.persistable.PersistableEnvelope.toPersistableMessage(PersistableEnvelope.java:30)
	at bisq.common.persistence.PersistenceManager.persistNow(PersistenceManager.java:427)
	... 8 more
```

**Comment by ghost** [comment]
Please go to "Settings" and in the "Country" option in the top left select your country from the list.

Thanks for reporting, the [issue](https://github.com/bisq-network/bisq/issues/6417) is being looked into.
