### ISSUE TITLE
java.util.ConcurrentModificationException when syncing the blockchain

### ISSUE THREAD

**Issue by Giszmo** [bisq-network/bisq#6622]
### Description

Installed 1.9.9 over 1.7.2 on debian. While waiting for sync, I got invited to leave this issue here.

#### Version

1.9.9

#### Device or machine

Debian 5.10.158-2

#### Additional info

```
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.reduce(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.max(Unknown Source)
	at bisq.core.dao.burningman.accounting.BurningManAccountingService.getLastBlock(BurningManAccountingService.java:163)
	at bisq.core.dao.burningman.accounting.BurningManAccountingService.getBlockHeightOfLastBlock(BurningManAccountingService.java:159)
	at bisq.core.dao.burningman.accounting.node.lite.AccountingLiteNode.processNewAccountingBlock(AccountingLiteNode.java:258)
	at bisq.core.dao.burningman.accounting.node.lite.AccountingLiteNode.onNewBlockReceived(AccountingLiteNode.java:133)
	at bisq.core.dao.burningman.accounting.node.lite.network.AccountingLiteNodeNetworkService.lambda$onMessage$3(AccountingLiteNodeNetworkService.java:232)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at bisq.core.dao.burningman.accounting.node.lite.network.AccountingLiteNodeNetworkService.onMessage(AccountingLiteNodeNetworkService.java:232)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$7(NetworkNode.java:434)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:434)
	at bisq.network.p2p.network.Connection.lambda$onBundleOfEnvelopes$8(Connection.java:425)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(Unknown Source)
	at bisq.network.p2p.network.Connection.lambda$onBundleOfEnvelopes$9(Connection.java:425)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by HenrikJannsen** [comment]
We got that reported multiple times. Any dev available to fix it? There is not concurrent version of LinkedList so it might be not trivial to fix (also not sure if a concurrent collection would be the right fix anyway). @stejbac if you would have time to look into it how to fix that be best way, would be great.

EDIT:
The issue was already fixed with https://github.com/bisq-network/bisq/pull/6551

**Comment by Giszmo** [comment]
Maybe a bug fix release would be in order to avoid more people reporting this? The fix was merged two months ago but no new release was published. Even if the issue is not a blocker for power users, less experienced users have a hard time to tell if their funds are at risk when this happens and might get anxious when seeing these Exceptions.

**Comment by HenrikJannsen** [comment]
Next release will be out soon. If you enable pre-release notifications in settings you will get the notification for the pre-release and can help to test the pre release.
