### ISSUE TITLE
Cannot place an offer when using BSQ for trade fee (error at task CreateMakerFeeTx)

### ISSUE THREAD

**Issue by dario-spagnolo** [bisq-network/bisq#6778]
### Description

I am getting systematic and reproducible errors when placing an offer to buy BTC using BSQ for trade fee. It works fine when using BTC for trade fee.

Right after I click "Confirm: place offer to buy Bitcoin" I get an error message :

"An error occurred at task CreateMakerFeeTx"

#### Version

1.9.12

### Steps to reproduce

 - Go to "Buy" screen
 - Click button "Create new offer to buy BTC"
 - Select trading account : Revolut (also happens with SEPA)
 - Amount of BTC to buy : 0.005
 - Market price : 0%
 - **Select trade fee currency : BSQ** (amount is 0.09 BSQ and wallet has 22.76 BSQ available for spending)
 - Click button "Transfer funds from Bisq wallet"
 - Message appears "Your trading wallet is sufficiently funded"
 - Click button "Review: place offer to buy Bitcoin"
 - On review screen, click button "Confirm: place offer to buy Bitcoin"

### Expected behaviour

After clicking on the button "Confirm: place offer to buy Bitcoin", I should get a confirmation message saying that the order is placed.

### Actual behaviour

After clicking on the button "Confirm: place offer to buy Bitcoin", I get an error message, instantly: "An error occurred at task CreateMakerFeeTx"

### Screenshots

![Sélection_541](https://github.com/bisq-network/bisq/assets/8155871/5cf1555e-3945-49ac-9dbb-25c4e5dfe7f0)

#### Device or machine

ThinkPad P15 Gen 2i
Linux Mint 20.3
Intel(R) Core(TM) i7-11800H @ 2.30GHz

#### Additional info

All addresses, transaction IDs and offer IDs having been replaced with "00000000000000000000" for confidentiality.

```
juil.-21 21:16:07.103 [JavaFX Application Thread] INFO  o.b.w.Wallet: Completing send tx with 2 outputs totalling 0.00100013 BTC and a fee of 0.00 BTC/vkB 
juil.-21 21:16:07.104 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with 0.0046177 BTC change 
juil.-21 21:16:07.106 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with a fee of 0.00008271 BTC/kB, 0.00003325 BTC for 402 bytes 
juil.-21 21:16:07.106 [JavaFX Application Thread] INFO  o.b.w.Wallet:   completed: Transaction{00000000000000000000, wtxid 00000000000000000000
weight: 957 wu, 240 virtual bytes, 402 bytes
purpose: USER_PAYMENT
   in   <empty>  0.00073433 BTC (73433)
        witness:00000000000000000000 00000000000000000000
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   in   <empty>  0.00491675 BTC (491675)
        witness:00000000000000000000 00000000000000000000
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.00000013 BTC (13)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.001 BTC (100000)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.0046177 BTC (461770)
        P2WPKH addr:00000000000000000000
   fee  0.00003474 BTC/wu, 0.00013854 BTC/vkB, 0.00008271 BTC/kB  0.00003325 BTC
} 
juil.-21 21:16:07.106 [JavaFX Application Thread] INFO  o.b.w.Wallet: Completing send tx with 2 outputs totalling 0.00100013 BTC and a fee of 0.00 BTC/vkB 
juil.-21 21:16:07.106 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with 0.00460535 BTC change 
juil.-21 21:16:07.108 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with a fee of 0.00011343 BTC/kB, 0.0000456 BTC for 402 bytes 
juil.-21 21:16:07.108 [JavaFX Application Thread] INFO  o.b.w.Wallet:   completed: Transaction{00000000000000000000, wtxid 00000000000000000000
weight: 957 wu, 240 virtual bytes, 402 bytes
purpose: USER_PAYMENT
   in   <empty>  0.00073433 BTC (73433)
        witness:00000000000000000000 00000000000000000000
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   in   <empty>  0.00491675 BTC (491675)
        witness:00000000000000000000 00000000000000000000
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.00000013 BTC (13)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.001 BTC (100000)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.00460535 BTC (460535)
        P2WPKH addr:00000000000000000000
   fee  0.00004764 BTC/wu, 0.00019 BTC/vkB, 0.00011343 BTC/kB  0.0000456 BTC
} 
juil.-21 21:16:07.108 [JavaFX Application Thread] INFO  b.c.b.TxFeeEstimationService: Fee estimation resulted in a tx vsize of 310 vbytes and a tx fee of 5890 Sat. 
juil.-21 21:16:09.935 [JavaFX Application Thread] INFO  b.c.p.f.FeeService: BTC tx fee: txFeePerVbyte=21 minFeePerVbyte=8 
juil.-21 21:16:17.648 [JavaFX Application Thread] INFO  b.c.o.b.CreateOfferService: create and get offer with offerId=00000000000000000000, 
currencyCode=EUR, 
direction=BUY, 
price=268531127, 
useMarketBasedPrice=true, 
marketPriceMargin=0.0, 
amount=500000, 
minAmount=500000, 
buyerSecurityDeposit=0.19260407637814358 
juil.-21 21:16:17.649 [JavaFX Application Thread] INFO  o.b.w.Wallet: Completing send tx with 2 outputs totalling 0.00100013 BTC and a fee of 0.00 BTC/vkB 
juil.-21 21:16:17.649 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with 0.0046142 BTC change 
juil.-21 21:16:17.651 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with a fee of 0.00009141 BTC/kB, 0.00003675 BTC for 402 bytes 
juil.-21 21:16:17.651 [JavaFX Application Thread] INFO  o.b.w.Wallet:   completed: Transaction{00000000000000000000, wtxid 00000000000000000000
weight: 957 wu, 240 virtual bytes, 402 bytes
purpose: USER_PAYMENT
   in   <empty>  0.00073433 BTC (73433)
        witness:00000000000000000000 00000000000000000000
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   in   <empty>  0.00491675 BTC (491675)
        witness:00000000000000000000 00000000000000000000
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.00000013 BTC (13)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.001 BTC (100000)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.0046142 BTC (461420)
        P2WPKH addr:00000000000000000000
   fee  0.0000384 BTC/wu, 0.00015312 BTC/vkB, 0.00009141 BTC/kB  0.00003675 BTC
} 
juil.-21 21:16:17.652 [JavaFX Application Thread] INFO  o.b.w.Wallet: Completing send tx with 2 outputs totalling 0.00100013 BTC and a fee of 0.00 BTC/vkB 
juil.-21 21:16:17.652 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with 0.00460055 BTC change 
juil.-21 21:16:17.654 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with a fee of 0.00012537 BTC/kB, 0.0000504 BTC for 402 bytes 
juil.-21 21:16:17.654 [JavaFX Application Thread] INFO  o.b.w.Wallet:   completed: Transaction{00000000000000000000, wtxid 00000000000000000000
weight: 957 wu, 240 virtual bytes, 402 bytes
purpose: USER_PAYMENT
   in   <empty>  0.00073433 BTC (73433)
        witness:00000000000000000000 00000000000000000000
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   in   <empty>  0.00491675 BTC (491675)
        witness:00000000000000000000 00000000000000000000
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.00000013 BTC (13)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.001 BTC (100000)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.00460055 BTC (460055)
        P2WPKH addr:00000000000000000000
   fee  0.00005266 BTC/wu, 0.00021 BTC/vkB, 0.00012537 BTC/kB  0.0000504 BTC
} 
juil.-21 21:16:17.654 [JavaFX Application Thread] INFO  b.c.b.TxFeeEstimationService: Fee estimation resulted in a tx vsize of 310 vbytes and a tx fee of 6510 Sat. 
juil.-21 21:16:17.982 [JavaFX Application Thread] INFO  b.c.u.Profiler: Total memory: 1,091 GB; Used memory: 1,001 GB; Free memory: 92,101 MB; Max memory: 2 GB; No. of threads: 105 
juil.-21 21:16:18.423 [JavaFX Application Thread] INFO  b.c.util.GcUtil: GC reduced memory by 0. Total memory before/after: 1,091 GB/1,091 GB. Free memory: 115,475 MB. Took 441 ms. Total GC invocations: 15 / Total GC time 7.088 sec 
juil.-21 21:16:19.043 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: ValidateOffer 
juil.-21 21:16:19.044 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: CheckNumberOfUnconfirmedTransactions 
juil.-21 21:16:19.044 [JavaFX Application Thread] INFO  b.c.t.TaskRunner: Run task: CreateMakerFeeTx 
juil.-21 21:16:19.045 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Saving wallet; last seen block is height 799672, date 2023-07-21T18:48:17Z, hash 000000000000000000034cb43cb906466b03a2b7143697165996567f775d63bb 
juil.-21 21:16:19.058 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Save completed in 12.55 ms 
juil.-21 21:16:19.058 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: getOrCreateAddressEntry: new AddressEntry=AddressEntry{address=00000000000000000000, context=RESERVED_FOR_TRADE, offerId='00000000000000000000', coinLockedInMultiSig=0, segwit=true} 
juil.-21 21:16:19.058 [JavaFX Application Thread] INFO  b.c.b.m.AddressEntryList: addAddressEntry: add new AddressEntry AddressEntry{address=00000000000000000000, context=RESERVED_FOR_TRADE, offerId='00000000000000000000', coinLockedInMultiSig=0, segwit=true} 
juil.-21 21:16:19.059 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Saving wallet; last seen block is height 799672, date 2023-07-21T18:48:17Z, hash 000000000000000000034cb43cb906466b03a2b7143697165996567f775d63bb 
juil.-21 21:16:19.072 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Save completed in 12.74 ms 
juil.-21 21:16:19.072 [JavaFX Application Thread] INFO  b.c.b.w.BtcWalletService: getOrCreateAddressEntry: add new AddressEntry AddressEntry{address=00000000000000000000, context=AVAILABLE, offerId='null', coinLockedInMultiSig=0, segwit=true} 
juil.-21 21:16:19.073 [JavaFX Application Thread] INFO  b.c.b.m.AddressEntryList: addAddressEntry: add new AddressEntry AddressEntry{address=00000000000000000000, context=AVAILABLE, offerId='null', coinLockedInMultiSig=0, segwit=true} 
juil.-21 21:16:19.074 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Saving wallet; last seen block is height 799672, date 2023-07-21T18:48:17Z, hash 000000000000000000034cb43cb906466b03a2b7143697165996567f775d63bb 
juil.-21 21:16:19.085 [JavaFX Application Thread] INFO  o.b.w.WalletFiles: Save completed in 11.03 ms 
juil.-21 21:16:19.086 [JavaFX Application Thread] INFO  o.b.w.Wallet: Completing send tx with 2 outputs totalling 0.00101575 BTC and a fee of 0.00 BTC/vkB 
juil.-21 21:16:19.086 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with 0.00458611 BTC change 
juil.-21 21:16:19.086 [JavaFX Application Thread] INFO  o.b.w.Wallet:   with a fee of 0.00028805 BTC/kB, 0.0000651 BTC for 226 bytes 
juil.-21 21:16:19.086 [JavaFX Application Thread] INFO  o.b.w.Wallet:   completed: Transaction{00000000000000000000
weight: 904 wu, 226 bytes
purpose: USER_PAYMENT
   in   <empty>  0.00001588 BTC (1588)
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:0
   in   <empty>  0.00073433 BTC (73433)
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   in   <empty>  0.00491675 BTC (491675)
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.00001575 BTC (1575)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.001 BTC (100000)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.00458611 BTC (458611)
        P2WPKH addr:00000000000000000000
   fee  0.00007201 BTC/wu, 0.00028805 BTC/kB  0.0000651 BTC
} 
juil.-21 21:16:19.092 [JavaFX Application Thread] INFO  b.c.b.w.WalletService: 
BTC wallet: Signed tx:
Transaction{00000000000000000000, wtxid 00000000000000000000
weight: 1123 wu, 281 virtual bytes, 445 bytes
purpose: USER_PAYMENT
   in   <empty>  0.00001588 BTC (1588)
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:0
   in   <empty>  0.00073433 BTC (73433)
        witness:00000000000000000000 00000000000000000000
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   in   <empty>  0.00491675 BTC (491675)
        witness:00000000000000000000 00000000000000000000
        P2WPKH addr:00000000000000000000  outpoint:00000000000000000000:2
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.00001575 BTC (1575)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.001 BTC (100000)
        P2WPKH addr:00000000000000000000
   out  0[] PUSHDATA(20)[00000000000000000000] (00000000000000000000)  0.00458611 BTC (458611)
        P2WPKH addr:00000000000000000000
   fee  0.00005796 BTC/wu, 0.00023167 BTC/vkB, 0.00014629 BTC/kB  0.0000651 BTC
} 
juil.-21 21:16:19.092 [JavaFX Application Thread] ERROR b.c.t.Task: An error occurred at task: CreateMakerFeeTx org.bitcoinj.crypto.KeyCrypterException$InvalidCipherText: Could not decrypt bytes
	at org.bitcoinj.crypto.KeyCrypterScrypt.decrypt(KeyCrypterScrypt.java:229)
	at org.bitcoinj.crypto.DeterministicKey.findOrDeriveEncryptedPrivateKey(DeterministicKey.java:410)
	at org.bitcoinj.crypto.DeterministicKey.decrypt(DeterministicKey.java:377)
	at org.bitcoinj.crypto.DeterministicKey.decrypt(DeterministicKey.java:44)
	at org.bitcoinj.core.ECKey.decrypt(ECKey.java:1133)
	at org.bitcoinj.crypto.DeterministicKey.decrypt(DeterministicKey.java:388)
	at org.bitcoinj.crypto.DeterministicKey.decrypt(DeterministicKey.java:44)
	at org.bitcoinj.wallet.DecryptingKeyBag.maybeDecrypt(DecryptingKeyBag.java:51)
	at org.bitcoinj.wallet.DecryptingKeyBag.findKeyFromPubKeyHash(DecryptingKeyBag.java:68)
	at org.bitcoinj.core.TransactionOutPoint.getConnectedRedeemData(TransactionOutPoint.java:175)
	at org.bitcoinj.core.TransactionInput.getConnectedRedeemData(TransactionInput.java:333)
	at bisq.core.btc.wallet.WalletService.signTransactionInput(WalletService.java:331)
	at bisq.core.btc.wallet.WalletService.signTx(WalletService.java:303)
	at bisq.core.btc.wallet.BsqWalletService.signTxAndVerifyNoDustOutputs(BsqWalletService.java:498)
	at bisq.core.offer.placeoffer.bisq_v1.tasks.CreateMakerFeeTx.run(CreateMakerFeeTx.java:120)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.handleComplete(TaskRunner.java:85)
	at bisq.common.taskrunner.Task.complete(Task.java:58)
	at bisq.core.offer.placeoffer.bisq_v1.tasks.CheckNumberOfUnconfirmedTransactions.run(CheckNumberOfUnconfirmedTransactions.java:18)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.handleComplete(TaskRunner.java:85)
	at bisq.common.taskrunner.Task.complete(Task.java:58)
	at bisq.core.offer.placeoffer.bisq_v1.tasks.ValidateOffer.run(ValidateOffer.java:96)
	at bisq.common.taskrunner.TaskRunner.next(TaskRunner.java:69)
	at bisq.common.taskrunner.TaskRunner.run(TaskRunner.java:60)
	at bisq.core.offer.placeoffer.bisq_v1.PlaceOfferProtocol.placeOffer(PlaceOfferProtocol.java:95)
	at bisq.core.offer.OpenOfferManager.placeOffer(OpenOfferManager.java:446)
	at bisq.desktop.main.offer.bisq_v1.MutableOfferDataModel.onPlaceOffer(MutableOfferDataModel.java:336)
	at bisq.desktop.main.offer.bisq_v1.MutableOfferViewModel.onPlaceOffer(MutableOfferViewModel.java:655)
	at bisq.desktop.main.offer.bisq_v1.MutableOfferView.lambda$onPlaceOffer$2(MutableOfferView.java:375)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at bisq.desktop.main.overlays.windows.OfferDetailsWindow.lambda$addConfirmAndCancelButtons$3(OfferDetailsWindow.java:444)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8889)
	at javafx.scene.control.Button.fire(Button.java:203)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: pad block corrupted
	at org.bouncycastle.crypto.paddings.PKCS7Padding.padCount(Unknown Source)
	at org.bouncycastle.crypto.paddings.PaddedBufferedBlockCipher.doFinal(Unknown Source)
	at org.bitcoinj.crypto.KeyCrypterScrypt.decrypt(KeyCrypterScrypt.java:225)
	... 76 common frames omitted

juil.-21 21:16:19.093 [JavaFX Application Thread] ERROR b.c.t.TaskRunner: Task failed: CreateMakerFeeTx / errorMessage: An error occurred at task: CreateMakerFeeTx 
juil.-21 21:16:19.093 [JavaFX Application Thread] ERROR b.c.o.p.b.PlaceOfferProtocol: An error occurred at task: CreateMakerFeeTx 
juil.-21 21:16:19.093 [JavaFX Application Thread] ERROR b.d.m.o.b.c.CreateOfferDataModel: An error occurred at task: CreateMakerFeeTx 
```

**Comment by ghost** [comment]
Does it let you send BSQ using your wallet, try a send to self to verify?

It looks like an error decrypting your wallet.  Perhaps it is corrupted.
Suggest restore wallet either from backup (.wallet files under [data directory](https://bisq.wiki/Data_directory)) or recovery phrase.
