### ISSUE TITLE
UI completely broken, uncaught exception “Cannot invoke "javafx.scene.Node.getLayoutBounds()" because "this.textNode" is null”

### ISSUE THREAD

**Issue by pjakma** [bisq-network/bisq#7061]
### Description

I upgraded to 1.9.15. As soon as I switch to the "Offers" tab, the UI completely breaks after an uncaught exception. After that every tab is blank, other than the basic structural framing.

As Bisq does not allow downgrade, this means Bisq is completely unusable to me now, and I can not access/manage the offers I have open.

#### Version

1.9.15

### Steps to reproduce

1. Start bisq
2. The /first/ time I started, I got one of the other tabs ("Buy") correctly painted.
3. I switched to "Portfolio"
4. I got the error message
5. I clicked away the error message
6. Every tab in Bisq is blank

### Expected behaviour

I expect Bisq to work as normal.

### Actual behaviour

Bisq gives an error about an uncaught exception. This stack trace appears in the log:

Mar-20 00:30:57.040 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Mar-20 00:30:57.041 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableMessage= Cannot invoke "javafx.scene.Node.getLayoutBounds()" because "this.textNode" is null 
Mar-20 00:30:57.041 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: throwableClass= class java.lang.NullPointerException 
Mar-20 00:30:57.043 [JavaFX Application Thread] ERROR b.c.s.CommonSetup: Stack trace:
java.lang.NullPointerException: Cannot invoke "javafx.scene.Node.getLayoutBounds()" because "this.textNode" is null
        at bisq.desktop.components.JFXTextFieldSkinBisqStyle.updateTextPos(JFXTextFieldSkinBisqStyle.java:95)
        at bisq.desktop.components.JFXTextFieldSkinBisqStyle.layoutChildren(JFXTextFieldSkinBisqStyle.java:79)
        at javafx.scene.control.Control.layoutChildren(Control.java:601)
        at javafx.scene.Parent.layout(Parent.java:1207)
        at javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.scene.Parent.layout(Parent.java:1214)
        at javafx.scene.Scene.doLayoutPass(Scene.java:576)
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2476)
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:413)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:412)
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:439)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:563)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:840)
 

### Screenshots

![bisq-offer-exception-err](https://github.com/bisq-network/bisq/assets/1454461/ce8136db-2d8d-41ca-b110-ffcaade8196c)

![bisq-portf-bork](https://github.com/bisq-network/bisq/assets/1454461/87716900-bca2-433d-8e74-0a69064e958b)

![bisq-sell-bork](https://github.com/bisq-network/bisq/assets/1454461/379a4e13-30fc-4f49-8e08-09bc8db1f5c5)

#### Device or machine

Server class hardware, Fedora Linux

**Comment by ghost** [comment]
Assuming you built from source.  Try with Java version family 11.

See #6112, #5624

**Comment by pjakma** [comment]
Yes. Bisq was built with JDK 17. Trying 11 now.

**Comment by ghost** [comment]
To users building v1.9.15 from source, please note: https://github.com/bisq-network/bisq/pull/7064

**Comment by pjakma** [comment]
So, built with OpenJDK 11, but running with OpenJDK 17 it still had this issue. Running with JDK 11, then it works again.

Pretty sure I've built and run with OpenJDK 17 for a while now without issues, at least up to 1.9.13. This issue appeared when I tried to upgrade from Bisq .13 to .15.

**Comment by pjakma** [comment]
Working now, though it would be good to fix the OpenJDK >11 issue.

**Comment by HenrikJannsen** [comment]
Current main version should work with JDK 17 (works for me)

**Comment by lordbah** [comment]
I just ran into this. First time building from source. Building and running with OpenJDK 17 on Ubuntu.
`sudo update-alternatives --config java`
and select JDK 11 worked as a workaround.
