### ISSUE TITLE
Bisq 1.9.15 problem on Linux Tails

### ISSUE THREAD

**Issue by 402PaymentReq** [bisq-network/bisq#7087]
I'm using the standard install/run scripts on Linux Tails 6.2
No problem with Bisq 1.9.14, but I get the following error when running Bisq 1.9.15

![tails-error](https://github.com/bisq-network/bisq/assets/124446805/3c7bd033-bdaa-440b-8d71-9828c4040e89)

May-01 05:56:37.632 [StartTor] ERRORbisq.network.p2p.network.RunningTor: Couldn't connect to Tor. net.freehaven.tor.control.TorControlError: Error reply: Command filtered
	at net.freehaven.tor.control.TorControlConnection.sendAndWaitForResponse(TorControlConnection.java:217)
	at net.freehaven.tor.control.TorControlConnection.getInfo(TorControlConnection.java:674)
	at net.freehaven.tor.control.TorControlConnection.getInfo(TorControlConnection.java:699)
	at org.berndpruenster.netlayer.tor.TorController.getBootstrapped(Tor.kt:99)
	at org.berndpruenster.netlayer.tor.Control.waitUntilBootstrapped(Tor.kt:166)
	at bisq.network.p2p.network.RunningTor.getTor(RunningTor.java:87)
	at bisq.network.p2p.network.TorNetworkNode.lambda$createTorAndHiddenService$10(TorNetworkNode.java:170)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

net.freehaven.tor.control.TorControlError: Error reply: Command filtered
	at net.freehaven.tor.control.TorControlConnection.sendAndWaitForResponse(TorControlConnection.java:217)
	at net.freehaven.tor.control.TorControlConnection.getInfo(TorControlConnection.java:674)
	at net.freehaven.tor.control.TorControlConnection.getInfo(TorControlConnection.java:699)
	at org.berndpruenster.netlayer.tor.TorController.getBootstrapped(Tor.kt:99)
	at org.berndpruenster.netlayer.tor.Control.waitUntilBootstrapped(Tor.kt:166)
	at bisq.network.p2p.network.RunningTor.getTor(RunningTor.java:87)
	at bisq.network.p2p.network.TorNetworkNode.lambda$createTorAndHiddenService$10(TorNetworkNode.java:170)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
May-01 05:56:37.634 [StartTor] ERRORbisq.network.p2p.network.TorNetworkNode: Could not connect to running Tor java.io.IOException: No default Tor Instance configured
	at org.berndpruenster.netlayer.tor.TorSocketsKt.getTorInstance(TorSockets.kt:260)
	at org.berndpruenster.netlayer.tor.TorSocketsKt.access$getTorInstance(TorSockets.kt:1)
	at org.berndpruenster.netlayer.tor.HiddenServiceSocket.<init>(TorSockets.kt:187)
	at org.berndpruenster.netlayer.tor.HiddenServiceSocket.<init>(TorSockets.kt:185)
	at org.berndpruenster.netlayer.tor.HiddenServiceSocket.<init>(TorSockets.kt)
	at bisq.network.p2p.network.TorNetworkNode.lambda$createTorAndHiddenService$10(TorNetworkNode.java:172)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

java.io.IOException: No default Tor Instance configured
	at org.berndpruenster.netlayer.tor.TorSocketsKt.getTorInstance(TorSockets.kt:260)
	at org.berndpruenster.netlayer.tor.TorSocketsKt.access$getTorInstance(TorSockets.kt:1)
	at org.berndpruenster.netlayer.tor.HiddenServiceSocket.<init>(TorSockets.kt:187)
	at org.berndpruenster.netlayer.tor.HiddenServiceSocket.<init>(TorSockets.kt:185)
	at org.berndpruenster.netlayer.tor.HiddenServiceSocket.<init>(TorSockets.kt)
	at bisq.network.p2p.network.TorNetworkNode.lambda$createTorAndHiddenService$10(TorNetworkNode.java:172)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
May-01 05:56:37.637 [JavaFX Application Thread] ERRORbisq.core.app.P2PNetworkSetup: onSetupFailed

**Comment by CatsDans** [comment]
Hello,

I can confirm this issue - same situation on Whonix. 1.9.14 worked fine!

**Comment by CatsDans** [comment]
> Hello,
> 
> I can confirm this issue - same situation on Whonix. 1.9.14 worked fine!

Whonix developments fixed this issue

**Comment by dutu** [comment]
You'd need to update `bisq.yml` onion-grater file with `GETINFO` pattern:
```
 GETINFO:
      - pattern: 'status/bootstrap-phase'
        response:
          - pattern: '250-status/bootstrap-phase=*'
            replacement: '250-status/bootstrap-phase=NOTICE BOOTSTRAP PROGRESS=100 TAG=done SUMMARY="Done"'
```
Check this [working bisq.yml file](https://github.com/dutu/run-on-tails/blob/master/bisq/assets/bisq.yml). Or you can even use the [Run-on-Tails guide](https://dutu.github.io/run-on-tails/bisq/bisq.html) to automate Bisq installation,

@suddenwhipvapor, wiki page [Running Bisq on Tails](https://bisq.wiki/Running_Bisq_on_Tails) would require `bisq.yml` updated, since the existing instruction won't work for Bisq v1.9.15.
