### ISSUE TITLE
Can't launch Bisq in Tails

### ISSUE THREAD

**Issue by isaacfender** [bisq-network/bisq#7301]
### Description
Can't launch Bisq in Tails, when i try to launch it using the terminal he shows me errors

#### Version

Bisq 64x 1.9.17.deb

### Steps to reproduce
amnesia@amnesia:~$     /opt/bisq/bin/Bisq --torControlPort 951 --torControlCookieFile=/var/run/tor/control.authcookie --torControlUseSafeCookieAuth
fault: An unexpected error occurred. Please file a report at https://bisq.network/issues
java.io.UncheckedIOException: Application data directory '/home/amnesia/.local/share/Bisq' could not be created
	at bisq.common.config.Config.mkAppDataDir(Config.java:954)
	at bisq.common.config.Config.<init>(Config.java:777)
	at bisq.core.app.BisqExecutable.execute(BisqExecutable.java:89)
	at bisq.desktop.app.BisqAppMain.main(BisqAppMain.java:62)
Caused by: java.nio.file.FileAlreadyExistsException: /home/amnesia/.local/share/Bisq
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
	at java.base/java.nio.file.Files.createDirectories(Files.java:743)
	at bisq.common.config.Config.mkAppDataDir(Config.java:952)
	... 3 more

#### Device or machine
Tails on USB Drive

**Comment by suddenwhipvapor** [comment]
Known issue with bisq and OSes that use their own tor external connection.
Try this tails distribution: https://github.com/DesobedienteTecnologico/dtails

**Comment by dutu** [comment]
Tested with no issues on latest Tails 6.10.
You can use [this guide](https://dutu.github.io/run-on-tails/bisq/bisq.html) to automate Bisq installation on Tails.
