### ISSUE TITLE
Reactivate serverside master seednode

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#92]

**Comment by ManfredKarrer** [comment]
@cbeams: I just tried out the serverside seednode, but I think that is too unstable for using it. I can try to look more into it and try it with the latest TomP2P code base, but I fear we cannot release it with that option. But I added it to the config file as well so as soon we get the serverside seednode stable running we can activate it via the config. I let the server running, so other can try it out as well (maybe its just because I have fallback to relay mode which is the worst case).

**Comment by cbeams** [comment]
Can you describe a bit about what is unstable?

**Comment by ManfredKarrer** [comment]
The problems I have observed are following:
- Error messages on the server (those are reported to Tom Bocek and he said he is working on that)
- The first client can connect but the second client got stuck often in the startup screen
- In the trade process, offer publishing did often not succeed

Error messages on the server:

```
05:44:04.799 [NETTY-TOMP2P - worker-client/server - -1-2] ERROR net.tomp2p.rpc.DispatchHandler - Exception in custom handler java.lang.NullPointerException: null
    at net.tomp2p.message.Encoder.loop(Encoder.java:219) ~[tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.message.Encoder.write(Encoder.java:54) ~[tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.relay.RelayUtils.encodeMessage(RelayUtils.java:30) ~[tomp2p-nat-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.relay.RelayForwarderRPC.handleRelay(RelayForwarderRPC.java:148) ~[tomp2p-nat-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.relay.RelayForwarderRPC.handleResponse(RelayForwarderRPC.java:139) ~[tomp2p-nat-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.rpc.DispatchHandler.forwardMessage(DispatchHandler.java:151) ~[tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.connection.Dispatcher.channelRead0(Dispatcher.java:153) [tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.connection.Dispatcher.channelRead0(Dispatcher.java:54) [tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at net.tomp2p.message.TomP2PCumulationTCP.decoding(TomP2PCumulationTCP.java:69) [tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at net.tomp2p.message.TomP2PCumulationTCP.channelRead(TomP2PCumulationTCP.java:47) [tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at net.tomp2p.connection.IdleStateHandlerTomP2P.channelRead(IdleStateHandlerTomP2P.java:112) [tomp2p-core-5.0-Alpha24-SNAPSHOT.jar:na]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-common-4.0.21.Final.jar:4.0.21.Final]
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.21.Final.jar:4.0.21.Final]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]
```

**Comment by cbeams** [comment]
Alright. Moving this out of 0.1.0, then.

> Error messages on the server (those are reported to Tom Bocek and he said he is working on that)

Is this reported as an issue somewhere? Can you provide a link? Are we basically blocked on this issue until Tom addresses this?

**Comment by ManfredKarrer** [comment]
I added an issue for the TomP2P bug: #161 
I will work on that next week and test with latest TomP2P version. I cannot say yet if it is blocked, need more investigation.

**Comment by cbeams** [comment]
Duplicates #3. Closing.
