### ISSUE TITLE
java.lang.NullPointerException when switching tabs

### ISSUE THREAD

**Issue by viciousvex** [bisq-network/bisq#982]
Hey there,

just realized there is a bug when I am (on v.0.5.3 on MacOS)

(Steps to reproduce)

1) answering a question in the Support tab
2) switch to my Portfolio to lookup some info
3) switch back to Support tab

I am getting a java.lang.NullPointerException when I am in the middle of typing into the reply text field.

Regards

**Comment by ManfredKarrer** [comment]
Could you send me the part of the exception in the log file?

**Comment by viciousvex** [comment]
Oct-22 17:41:43.446 [JavaFX Application Thread] WARN  i.b.c.t.TradeManager: We found an outdated addressEntry for trade nYsRQLvB-33a58711-6929-4557-99ef-f35e85d80458-053 
Oct-22 17:41:43.446 [JavaFX Application Thread] WARN  i.b.c.t.TradeManager: We found an outdated addressEntry for trade tXXU3-4a932aec-5589-4e11-a285-125ad752ac64-053 
Oct-22 17:41:43.446 [JavaFX Application Thread] WARN  i.b.c.t.TradeManager: We found an outdated addressEntry for trade sxPvK-18b1bb23-d79c-4545-b25c-c514c3b434f6-053 
Oct-22 17:41:43.446 [JavaFX Application Thread] INFO  i.b.c.b.w.BtcWalletService: swap addressEntry with address 1JzMJCWJzf7qR8k2UsTLxMJQEpgN3Zu2Ca and offerId sxPvK-18b1bb23-d79c-4545-b25c-c514c3b434f6-053 from context MULTI_SIG to available 
Oct-22 17:41:43.446 [JavaFX Application Thread] WARN  i.b.c.t.TradeManager: We found an outdated addressEntry for trade sxPvK-18b1bb23-d79c-4545-b25c-c514c3b434f6-053 
Oct-22 17:41:43.484 [JavaFX Application Thread] INFO  i.b.g.m.MainViewModel: onRequestingDataCompleted 
Oct-22 19:29:52.371 [JavaFX Application Thread] INFO  i.b.n.p.p.PeerManager: We have been in standby mode for 6479 sec 
Oct-22 19:29:52.372 [JavaFX Application Thread] INFO  i.b.c.o.OpenOfferManager: onAwakeFromStandby 
Oct-22 19:30:20.234 [JavaFX Application Thread] INFO  i.b.n.p.p.g.RequestDataHandler: 
#################################################################
Received 79 instances of storage payload
TradeStatistics: 2
MailboxStoragePayload: 16
Arbitrator: 2
OfferPayload: 59
################################################################# 
Oct-22 19:30:20.469 [JavaFX Application Thread] INFO  i.b.g.m.MainViewModel: onRequestingDataCompleted 
Oct-22 20:08:27.294 [JavaFX Application Thread] INFO  i.b.n.p.p.PeerManager: We have been in standby mode for 2247 sec 
Oct-22 20:08:27.294 [JavaFX Application Thread] INFO  i.b.c.o.OpenOfferManager: onAwakeFromStandby 
Oct-22 20:08:55.984 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Uncaught Exception from thread JavaFX Application Thread 
Oct-22 20:08:55.984 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableMessage= null 
Oct-22 20:08:55.984 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: throwableClass= class java.lang.NullPointerException 
Oct-22 20:08:55.985 [JavaFX Application Thread] ERROR i.b.g.a.BisqApp: Stack trace:
java.lang.NullPointerException
	at io.bisq.gui.main.disputes.trader.TraderDisputeView$19$1.updateItem(TraderDisputeView.java:1233)
	at io.bisq.gui.main.disputes.trader.TraderDisputeView$19$1.updateItem(TraderDisputeView.java:1215)
	at javafx.scene.control.TableCell.updateItem(TableCell.java:663)
	at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.TableViewSkin.resizeColumnToFitContent(TableViewSkin.java:241)
	at com.sun.javafx.scene.control.skin.TableViewSkin.resizeColumnToFitContent(TableViewSkin.java:54)
	at com.sun.javafx.scene.control.skin.TableColumnHeader.doColumnAutoSize(TableColumnHeader.java:531)
	at com.sun.javafx.scene.control.skin.TableColumnHeader.updateScene(TableColumnHeader.java:474)
	at com.sun.javafx.scene.control.skin.TableColumnHeader.handlePropertyChanged(TableColumnHeader.java:314)
	at com.sun.javafx.scene.control.skin.TableColumnHeader.lambda$new$49(TableColumnHeader.java:149)
	at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:831)
	at javafx.scene.Node.invalidatedScenes(Node.java:883)
	at javafx.scene.Node.setScenes(Node.java:921)
	at javafx.scene.Parent.scenesChanged(Parent.java:667)
	at javafx.scene.Node.invalidatedScenes(Node.java:855)
	at javafx.scene.Node.setScenes(Node.java:921)
	at javafx.scene.Parent.scenesChanged(Parent.java:667)
	at javafx.scene.Node.invalidatedScenes(Node.java:855)
	at javafx.scene.Node.setScenes(Node.java:921)
	at javafx.scene.Parent.scenesChanged(Parent.java:667)
	at javafx.scene.Node.invalidatedScenes(Node.java:855)
	at javafx.scene.Node.setScenes(Node.java:921)
	at javafx.scene.Parent.scenesChanged(Parent.java:667)
	at javafx.scene.Node.invalidatedScenes(Node.java:855)
	at javafx.scene.Node.setScenes(Node.java:921)
	at javafx.scene.Parent.scenesChanged(Parent.java:667)
	at javafx.scene.Node.invalidatedScenes(Node.java:855)
	at javafx.scene.Node.setScenes(Node.java:921)
	at javafx.scene.Parent.scenesChanged(Parent.java:667)
	at javafx.scene.Node.invalidatedScenes(Node.java:855)
	at javafx.scene.Node.setScenes(Node.java:921)
	at javafx.scene.Parent$1.onChanged(Parent.java:269)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$19(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at io.bisq.gui.main.MainView.lambda$initialize$8(MainView.java:237)
	at io.bisq.gui.Navigation.lambda$navigateTo$2(Navigation.java:123)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.bisq.gui.Navigation.navigateTo(Navigation.java:123)
	at io.bisq.gui.Navigation.navigateTo(Navigation.java:92)
	at io.bisq.gui.main.MainView$NavButton.lambda$new$1(MainView.java:661)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8413)
	at javafx.scene.control.ToggleButton.fire(ToggleButton.java:256)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
 
Oct-22 20:09:07.790 [BlockingClient network thread for seed.bitcoinstats.com/139.59.116.230:8333] WARN  o.b.c.PeerSocketHandler: [139.59.116.230]:8333 -  org.bitcoinj.core.ProtocolException: Received Ping before version handshake is complete.
	at org.bitcoinj.core.Peer.processMessage(Peer.java:478)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:182)
	at org.bitcoinj.net.BlockingClient.runReadLoop(BlockingClient.java:122)
	at org.bitcoinj.net.BlockingClient$1.run(BlockingClient.java:81)

Oct-22 20:09:31.954 [JavaFX Application Thread] INFO  i.b.g.a.BisqApp: System load: Memory (MB)): 480 / No. of threads: 37

**Comment by ManfredKarrer** [comment]
Thanks. Can you reproduce that after a restart? The line should not cause any exception:

getTableRow().setOpacity(isClosed ? 0.4 : 1);

Seems that getTableRow() is null, but that can only be in case that another error has screwed something up.

**Comment by viciousvex** [comment]
Unfortunately, there are no more open support tickets, so I can not reproduce the exact steps after a restart. Switching between Support and Portfolio works after the restart of the application without any problems.

**Comment by ManfredKarrer** [comment]
i will close it as it am pretty sure it was caused due another issue.
